---
detect_object:
  name: Detect Object
  description: Detect Object Within Zone.
  target:
  fields:
    image_url:
      name: Image URL
      description: Image URL for this object, only required if not provided in the config file.
      required: false
      advanced: false
      example: "http://ip.ad.dr.ess/camera/snapshot.jpg"
      default: ""
