# Created by Danny Tsang <danny@tsang.uk>
automation:
  # region Motion
  - id: "1610234394136"
    alias: "Conservatory: Motion Detected And It's Dark"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.conservatory_area_motion
          - binary_sensor.conservatory_motion_occupancy
          - binary_sensor.conservatory_motion_3_occupancy
        from: "off"
        to: "on"
    conditions:
      - condition: numeric_state
        entity_id: sensor.conservatory_motion_illuminance
        below: input_number.conservatory_light_level_threshold
      - condition: state
        entity_id: input_boolean.enable_conservatory_motion_trigger
        state: "on"
      - or:
          - condition: numeric_state
            entity_id: light.conservatory
            attribute: brightness
            below: 9
          - condition: template
            value_template: "{{ state_attr('light.conservatory', 'brightness') == none }}"
    actions:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: >-
                🐾 Motion detected and
                it's dark ({{ states('sensor.conservatory_motion_illuminance', with_unit=True) }} <
                ({{ states('input_number.conservatory_light_level_threshold', with_unit=True) }}).
                Turning 💡 🔆 light on.
              title: "Conservatory"
              log_level: "Debug"
          - action: scene.turn_on
            target:
              entity_id: scene.conservatory_turn_on_light
            data:
              transition: 2
          - action: timer.cancel
            data: {}
            target:
              entity_id: timer.conservatory_lights_off
    mode: single
  - id: "1610234794461"
    alias: "Conservatory: No Motion Detected"
    description: ""
    triggers:
      - trigger: state
        entity_id: binary_sensor.conservatory_area_motion
        from: "on"
        to: "off"
    conditions:
      - condition: state
        entity_id: light.conservatory
        state: "on"
      - condition: state
        entity_id: input_boolean.enable_conservatory_motion_trigger
        state: "on"
    actions:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: "🚷 No motion. Starting ⏳timer."
              title: "Conservatory"
              log_level: "Debug"
          - action: timer.start
            target:
              entity_id: timer.conservatory_lights_off
            data:
              duration: "00:01:00"
    mode: single
  - id: "1610238960657"
    alias: "Conservatory: No Motion Turning Turn Lights Off"
    description: ""
    triggers:
      - trigger: event
        event_type: timer.finished
        event_data:
          entity_id: timer.conservatory_lights_off
    conditions:
      - condition: state
        entity_id: light.conservatory
        state: "on"
      - condition: state
        entity_id: input_boolean.enable_conservatory_motion_trigger
        state: "on"
    actions:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: "🚷 No motion. Turning lights off."
              title: "Conservatory"
              log_level: "Debug"
          - action: scene.turn_on
            target:
              entity_id: scene.conservatory_turn_off_light
            data: {}
    mode: single
  # region Door
  - id: "1628985027639"
    alias: "Conservatory: Door Open"
    description: ""
    triggers:
      - trigger: state
        entity_id: binary_sensor.conservatory_door
        to: "on"
    conditions: []
    actions:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: "🚪 Door opened."
              title: "Conservatory"
              log_level: "Debug"
          - if:
              - condition: not
                conditions:
                  - condition: state
                    entity_id: climate.hive_receiver_heat
                    state: "off"
            then:
              - action: script.send_to_home_log
                data:
                  message: "Turning off the heating."
                  title: "Conservatory"
                  log_level: "Debug"
              - action: script.set_central_heating_to_off
                data: {}
    mode: single
  - id: "1628985156167"
    alias: "Conservatory: Door Closed"
    description: ""
    triggers:
      - trigger: state
        entity_id: binary_sensor.conservatory_door
        to: "off"
        from: "on"
    conditions: []
    actions:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: "🚪 Conservatory door closed."
              log_level: "Debug"
          - action: script.set_central_heating_to_home_mode
            data: {}
          - choose:
              - conditions:
                  - condition: state
                    entity_id: binary_sensor.shed_door
                    state: "on"
                  - condition: state
                    entity_id: binary_sensor.back_garden_gate_contact
                    state: "on"
                sequence:
                  - action: script.send_direct_notification
                    data:
                      message: "🚪 Door closed. 🛖 shed 🚪 door and gate is still open."
                      title: Conservatory
                      people:
                        entity_id:
                          - person.danny
                          - person.terina
              - conditions:
                  - condition: state
                    entity_id: binary_sensor.shed_door
                    state: "on"
                sequence:
                  - action: script.send_direct_notification
                    data:
                      message: "🚪 Door closed and 🛖 shed 🚪 door is still open."
                      title: Conservatory
                      people:
                        entity_id:
                          - person.danny
                          - person.terina
              - conditions:
                  - condition: state
                    entity_id: binary_sensor.back_garden_gate_contact
                    state: "on"
                sequence:
                  - action: script.send_direct_notification
                    data:
                      message: "🚪 Door closed and gate is still open."
                      title: Conservatory
                      people:
                        entity_id:
                          - person.danny
                          - person.terina
            default: []
    mode: single
  # region Other
  - id: "1733767153966"
    alias: "Conservatory: Turn On Airer"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.conservatory_airer_schedule_1
    conditions:
      - condition: state
        entity_id: input_boolean.enable_conservatory_airer_schedule
        state: "on"
    actions:
      - action: script.check_conservatory_airer
        data: {}
    mode: single
  - id: "1733767153967"
    alias: "Conservatory: Turn Off Airer"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.conservatory_airer_schedule_1
        to: "off"
    conditions:
      - condition: state
        entity_id: input_boolean.enable_conservatory_airer_schedule
        state: "on"
    actions:
      - parallel:
          - action: script.send_to_home_log
            metadata: {}
            data:
              log_level: Normal
              message: Airer schedule 1 is off. Turning airer off.
              title: Conservatory
          - action: switch.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: switch.airer
    mode: single

scene:
  - id: "1610234583738"
    name: "Conservatory: Turn On Light"
    entities:
      light.conservatory:
        min_mireds: 153
        max_mireds: 500
        effect_list:
          - colorloop
          - random
        supported_color_modes:
          - color_temp
          - hs
        color_mode: color_temp
        brightness: 255
        color_temp: 282
        effect: none
        friendly_name: Conservatory
        supported_features: 63
        state: "on"
  - id: "1610238855789"
    name: "Conservatory: Turn Off Light"
    entities:
      light.conservatory:
        min_mireds: 153
        max_mireds: 500
        effect_list:
          - colorloop
          - random
        supported_color_modes:
          - color_temp
          - hs
        friendly_name: Conservatory
        supported_features: 63
        state: "off"

script:
  conservatory_electricity_rate_change:
    alias: Conservatory Electricity Rate change
    description: ""
    fields:
      current_electricity_import_rate:
        description: Pounds per kiloWatt for importing.
        example: "0.1501"
        selector:
          number:
            min: -15
            max: 100
            step: 2
      current_electricity_import_rate_unit:
        description: Unit describing the unit rate.
        example: "GBP/kWh"
        selector:
          text:
    sequence:
      - variables:
          current_import_rate: "{{ current_electricity_import_rate|default(states('sensor.octopus_energy_electricity_current_rate'), true) }}"
          current_import_rate_unit_of_measurement: "{{ current_electricity_import_rate_unit|state_attr('sensor.octopus_energy_electricity_current_rate', 'unit_of_measurement') }}"
      - alias: Conservatory underfloor heating
        choose:
          - conditions:
              - condition: template
                value_template: >-
                  {{ state_attr('climate.conservatory_under_floor_heating', 'temperature')|float(5) >
                  states('input_number.conservatory_default_under_floor_temperature')|float(0) }}
              - alias: "Not in holiday mode"
                not:
                  - condition: state
                    entity_id: input_select.home_mode
                    state: Holiday
              - condition: template
                value_template: "{{ current_import_rate > 0 }}"
            sequence:
              - parallel:
                  - action: script.send_to_home_log
                    data:
                      message: >-
                        Turning off under floor heating by setting target temperature to {{ states('input_number.conservatory_default_under_floor_temperature', with_unit=True) }}.
                      title: Conservatory
                      log_level: "Debug"
                  - action: climate.set_temperature
                    data:
                      temperature: "{{ states('input_number.conservatory_default_under_floor_temperature')|float(5) }}"
                      hvac_mode: heat
                    target:
                      entity_id: climate.conservatory_under_floor_heating
        default: []
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: sensor.conservatory_area_mean_temperature
                below: 25
              - condition: numeric_state
                entity_id: climate.conservatory_under_floor_heating
                attribute: temperature
                below: 20
              - condition: state
                entity_id: input_boolean.conservatory_under_floor_heating_cost_below_nothing
                state: "on"
              - alias: "Not in holiday mode"
                not:
                  - condition: state
                    entity_id: input_select.home_mode
                    state: Holiday
              - condition: template
                value_template: "{{ current_import_rate <= 0 }}"
            sequence:
              - parallel:
                - action: script.send_to_home_log
                  data:
                    message: >-
                      Electricity rate below 0 ({{ current_import_rate~' '~current_import_rate_unit_of_measurement }}).
                      Setting under floor target temperature to 20°C (currently
                      {{ state_attr('climate.conservatory_under_floor_heating', 'temperature') }}°C).
                    title: Conservatory
                    log_level: "Normal"
                - action: climate.set_temperature
                  data:
                    temperature: 20
                    hvac_mode: heat
                  target:
                    entity_id: climate.conservatory_under_floor_heating
          - alias: "Air temperature is hot but floor is cool"
            conditions:
              - condition: numeric_state
                entity_id: sensor.conservatory_area_mean_temperature
                above: 24
              - condition: numeric_state
                entity_id: climate.conservatory_under_floor_heating
                attribute: temperature
                below: 20
            sequence:
              - parallel:
                - action: script.send_to_home_log
                  data:
                    message: "Ambient air temperature is above 24°C ({{ states('sensor.conservatory_area_mean_temperature', with_unit=True) }})
                    but floor is cool {{ state_attr('climate.conservatory_under_floor_heating', 'temperature') }}°C).
                    Skipping Underfloor heating."
                    title: "Conservatory"
                    people:
                      entity_id:
                        - person.danny
        default:
          - action: script.send_direct_notification
            data:
              message: "Ambient air temperature is above 21°C. Skipping Underfloor heating."
              title: "Conservatory"
              people:
                entity_id:
                  - person.danny
  check_conservatory_airer:
    alias: Check Conservatory Airer
    description: "https://www.homesandgardens.com/solved/can-you-dry-laundry-outside-in-winter"
    fields:
      current_electricity_import_rate:
        description: Pounds per kiloWatt for importing.
        example: "0.1501"
        selector:
          number:
            min: -15
            max: 100
            step: 2
      current_electricity_import_rate_unit:
        description: Unit describing the unit rate.
        example: "GBP/kWh"
        selector:
          text:
    sequence:
      - variables:
          current_import_rate: "{{ current_electricity_import_rate|default(states('sensor.octopus_energy_electricity_current_rate'), true) }}"
          current_export_rate: "{{ current_electricity_export_rate|default(states('sensor.octopus_energy_electricity_current_rate'), true) }}"
      - choose:
          - alias: "Check schedule is on"
            conditions:
              - condition: state
                entity_id: input_boolean.enable_conservatory_airer_schedule
                state: "on"
              - condition: state
                entity_id: binary_sensor.conservatory_airer_schedule_1
                state: "on"
              - condition: numeric_state
                entity_id: sensor.conservatory_temperature_over_12_hours
                below: input_number.airer_minimum_temperature
            sequence:
              - parallel:
                  - action: script.send_to_home_log
                    data:
                      message: "Schedule turned on. Turning on airer."
                      title: "Conservatory"
                  - if:
                      - condition: state
                        entity_id: switch.airer
                        state: "off"
                    then:
                      - action: switch.turn_on
                        target:
                          entity_id: switch.airer
          - alias: "Check electricity rates cost nothing"
            conditions:
              - condition: state
                entity_id: input_boolean.enable_conservatory_airer_when_cost_nothing
                state: "off"
              - condition: template
                value_template: "{{ current_import_rate == 0 }}"
            sequence:
              - parallel:
                  - action: script.send_to_home_log
                    data:
                      message: >-
                        Electricity 0p/kw. Turning on airer.
                      title: "Conservatory"
                  - if:
                      - condition: state
                        entity_id: switch.airer
                        state: "on"
                    then:
                      - action: switch.turn_on
                        target:
                          entity_id: switch.airer
          - alias: "Check electricity rates cost below nothing"
            conditions:
              - condition: state
                entity_id: input_boolean.enable_conservatory_airer_when_cost_below_nothing
                state: "on"
              - condition: template
                value_template: "{{ current_import_rate < 0 }}"
            sequence:
              - parallel:
                  - action: script.send_to_home_log
                    data:
                      message: >-
                        Electricity below 0p/kw ({{ current_import_rate }}).Turning on airer.
                      title: "Conservatory"
                  - if:
                      - condition: state
                        entity_id: switch.airer
                        state: "off"
                    then:
                      - action: switch.turn_on
                        target:
                          entity_id: switch.airer
          - alias: "Check electricity rates starts to cost"
            conditions:
              - or:
                  - condition: state
                    entity_id: input_boolean.enable_conservatory_airer_when_cost_below_nothing
                    state: "on"
                  - condition: state
                    entity_id: input_boolean.enable_conservatory_airer_when_cost_nothing
                    state: "on"
              - condition: state
                entity_id: switch.airer
                state: "on"
              - condition: template
                value_template: "{{ current_import_rate > 0 }}"
            sequence:
              - parallel:
                  - action: script.send_to_home_log
                    data:
                      message: >-
                        Electricity above 0p/kw ({{ current_import_rate }}).Turning off airer.
                      title: "Conservatory"
                  - action: switch.turn_off
                    target:
                      entity_id: switch.airer
        default: []

sensor:
  - platform: mold_indicator
    name: Conservatory Mould Indicator
    indoor_temp_sensor: sensor.conservatory_motion_temperature
    indoor_humidity_sensor: sensor.conservatory_motion_humidity
    outdoor_temp_sensor: sensor.gw2000a_outdoor_temperature
    calibration_factor: 1.97
