# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://www.home-assistant.io/integrations/octoprint/
automation:
  - id: "1608655560832"
    alias: "3D Printer: Print Started"
    description: ""
    triggers:
      - trigger: state
        entity_id: binary_sensor.octoprint_printing
        from: "off"
        to: "on"
      - trigger: numeric_state
        entity_id:
          - sensor.octoprint_actual_bed_temp
          - sensor.octoprint_actual_tool0_temp
        above: 50
    conditions:
      - condition: state
        entity_id: input_boolean.enable_3d_printer_automations
        state: "on"
    actions:
      - choose:
          - conditions:
              - condition: sun
                after: sunset
            sequence:
              - action: script.send_to_home_log
                data:
                  message: "🌇 Printing started after sunset. Turning
                    Printer 🔆 💡 light on."
                  title: "🖨️ 🔲 3D printer"
                  log_level: "Normal"
              - action: scene.turn_on
                target:
                  entity_id: scene.3d_printer_light_on
          - conditions:
              - condition: sun
                before: sunrise
            sequence:
              - action: script.send_to_home_log
                data:
                  message: "🌇 Printing started before sunrise. Turning
                    Printer 🔆 💡 light on."
                  title: "🖨️ 🔲 3D printer"
                  log_level: "Normal"
              - action: scene.turn_on
                target:
                  entity_id: scene.3d_printer_light_on
          - conditions:
              - condition: sun
                after: sunrise
                before: sunset
              - condition: state
                entity_id: light.prusa
                state: "on"
            sequence:
              - action: script.send_to_home_log
                data:
                  message: ":sunny: Printing started during the day. Turning
                    Printer light off."
                  title: "🖨️ 🔲 3D printer"
                  log_level: "Normal"
              - action: scene.turn_on
                target:
                  entity_id: scene.3d_printer_light_off
        default:
          - action: script.send_to_home_log
            data:
              message: "🌅 Printing started after sunrise. Not turning
                on printer light."
              title: "🖨️ 🔲 3D printer"
              log_level: "Normal"
          - action: scene.turn_on
            target:
              entity_id: scene.3d_printer_light_off
      - wait_for_trigger:
          - trigger: numeric_state
            entity_id: sensor.octoprint_estimated_finish_time
            above: 0
        timeout: "60"
      - parallel:
          - action: switch.turn_on
            target:
              entity_id: switch.prusa_fan
          - action: script.send_to_home_log
            data:
              message: "Printer priming. Turning on extruder :dash: fan."
              title: "🖨️ 🔲 3D printer"
              log_level: "Normal"
          - wait_for_trigger:
              - trigger: numeric_state
                entity_id: sensor.octoprint_estimated_finish_time
                above: 0
            timeout: "60"
          - action: script.send_to_home_log
            data:
              message: "Printer started. Estimated time to completion:
                {{ states('sensor.octoprint_estimated_finish_time') }}."
              title: "🖨️ 🔲 3D printer"
              log_level: "Normal"
    mode: single
  - id: "1619873649348"
    alias: "3D Printer: 50% Complete"
    description: ""
    triggers:
      - trigger: numeric_state
        entity_id: sensor.octoprint_job_percentage
        above: 50
    conditions:
      - condition: state
        entity_id: input_boolean.enable_3d_printer_automations
        state: "on"
    actions:
      - action: script.send_to_home_log
        data:
          message: "50% complete and due to finish at {{ states('sensor.octoprint_estimated_finish_time') }}."
          title: "🖨️ 🔲 3D printer"
          log_level: "Normal"
    mode: single
  - id: "1623087278802"
    alias: "3D Printer: Check If Printing Light"
    description: ""
    triggers:
      - trigger: time_pattern
        hours: "*"
        seconds: "*"
        minutes: "/30"
      - trigger: sun
        event: sunset
        id: sunset
      - trigger: sun
        event: sunrise
    conditions: []
    actions:
      - if:
          - condition: state
            entity_id: light.prusa
            state: "on"
        then:
          - action: script.3d_printer_check_turn_off_light
        else:
          - action: script.3d_printer_check_turn_on_light
    mode: single
  - id: "1613321560216"
    alias: "3D Printer: Finished Printing"
    description: ""
    triggers:
      - trigger: state
        entity_id: binary_sensor.octoprint_printing
        from: "on"
        to: "off"
    conditions:
      - condition: state
        entity_id: input_boolean.enable_3d_printer_automations
        state: "on"
    actions:
      - action: script.send_to_home_log
        data:
          message: >-
            :white_check_mark: Completed 3D printing which
            started {{states('sensor.octoprint_start_time')}}
          title: "🖨️ 🔲 3D printer"
          log_level: "Normal"
    mode: single
  - id: "1656239435552"
    alias: "3D Printer: Light Turned on"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - light.prusa
        to: "on"
        for:
          hours: 0
          minutes: 5
          seconds: 0
    conditions:
      - condition: state
        entity_id: input_boolean.enable_3d_printer_automations
        state: "on"
    actions:
      - action: script.3d_printer_check_turn_off_light
        data: {}
    mode: single
  - id: "1656239435553"
    alias: "3D Printer: Paused Mid Print"
    description: ""
    triggers:
      - trigger: state
        entity_id: sensor.octoprint_current_state
        to:
          - "Pausing"
          - "Paused"
    conditions:
      - condition: state
        entity_id: input_boolean.enable_3d_printer_automations
        state: "on"
      - condition: state
        entity_id: binary_sensor.octoprint_printing
        state: "on"
    actions:
      - action: script.send_direct_notification
        data:
          message: "🖨️ 3D printer is paused mid print. Please check"
          title: "🖨️ 🔲 3D printer"
          people:
            entity_id:
              - person.danny
          priority: high
          suppress_if_quiet: false
    mode: single

scene:
  - id: "1623014393915"
    name: 3D Printer Light Off
    entities:
      light.prusa:
        min_mireds: 153
        max_mireds: 65535
        effect_list:
          - colorloop
          - random
        supported_color_modes:
          - color_temp
          - hs
        friendly_name: Prusa
        icon: mdi:led-strip-variant
        supported_features: 63
        state: "off"
    icon: mdi:lightbulb
  - id: "1623014429001"
    name: 3D Printer Light On
    entities:
      light.prusa:
        min_mireds: 153
        max_mireds: 65535
        effect_list:
          - colorloop
          - random
        supported_color_modes:
          - color_temp
          - hs
        color_mode: color_temp
        brightness: 251
        color_temp: 153
        hs_color:
          - 54.768
          - 1.6
        rgb_color:
          - 255
          - 254
          - 250
        xy_color:
          - 0.326
          - 0.333
        effect: none
        friendly_name: Prusa
        icon: mdi:led-strip-variant
        supported_features: 63
        state: "on"
    icon: mdi:lightbulb
  - id: "1627724282263"
    name: 3D Printer Temperature Reached
    entities:
      light.prusa:
        min_mireds: 153
        max_mireds: 65535
        effect_list:
          - colorloop
          - random
        supported_color_modes:
          - color_temp
          - hs
        color_mode: hs
        brightness: 251
        hs_color:
          - 120
          - 100
        rgb_color:
          - 0
          - 255
          - 0
        xy_color:
          - 0.172
          - 0.747
        effect: none
        friendly_name: Prusa
        icon: mdi:led-strip-variant
        supported_features: 63
        state: "on"

script:
  3d_printer_left_unattended:
    alias: 3D Printer Left Unattended
    sequence:
      - not:
          - condition: state
            entity_id: sensor.octoprint_estimated_finish_time
            state: "unknown"
      - condition: state
        entity_id: binary_sensor.octoprint_printing
        state: "on"
      - action: script.send_direct_notification
        data:
          message:
            "🖨️ 3D printer is printing and no one is :house_with_garden:
            home."
          title: "🖨️ 🔲 3D printer"
          people:
            entity_id:
              - person.danny
              - person.terina
          priority: high
          suppress_if_quiet: false
    mode: single
    icon: mdi:printer-3d
  3d_printer_check_turn_on_light:
    alias: 3D Printer Check To Turn On Light
    sequence:
      - parallel:
          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: sensor.conservatory_motion_illuminance
                    below: 200
                  - condition: state
                    entity_id: sensor.octoprint_current_state
                    state: "Printing"
                sequence:
                  - action: script.send_to_home_log
                    data:
                      message:
                        "🌇 🖨️ It's getting dark and it's printing.
                        Turning 🔆 💡 lights on."
                      title: "🖨️ 🔲 3D printer"
                      log_level: "Debug"
                  - action: scene.turn_on
                    target:
                      entity_id: scene.3d_printer_light_on
            default: []
    mode: single
    icon: mdi:printer-3d
  3d_printer_check_turn_off_light:
    alias: 3D Printer Check To Turn Off Light
    description: Assume's the light is already on.
    sequence:
      - parallel:
          - choose:
              - conditions:
                  - not:
                      - condition: state
                        entity_id: sensor.octoprint_current_state
                        state: "Printing"
                sequence:
                  - action: script.send_to_home_log
                    data:
                      message: "Printer is not printing. Turning light off."
                      title: "🖨️ 🔲 3D printer"
                      log_level: "Debug"
                  - action: scene.turn_on
                    target:
                      entity_id: scene.3d_printer_light_off
              - conditions:
                  - condition: numeric_state
                    entity_id: sensor.conservatory_motion_illuminance
                    above: 100
                  - condition: state
                    entity_id: sensor.octoprint_current_state
                    state: "Printing"
                sequence:
                  - action: script.send_to_home_log
                    data:
                      message: >-
                        🌇 🖨️ It's getting bright and it's printing.
                        Turning light off.
                      title: "🖨️ 🔲 3D printer"
                      log_level: "Debug"
                  - action: scene.turn_on
                    target:
                      entity_id: scene.3d_printer_light_off
            default: []
    mode: single
    icon: mdi:printer-3d
