# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1628956688014"
    alias: "^Alarm: Disarmed"
    description: ""
    trigger:
      - platform: state
        entity_id: alarm_control_panel.house_alarm
        to: disarmed
    condition: []
    action:
      - parallel:
          - service: script.post_to_home_log
            data:
              message: ":no_bell: Alarmed disarmed."
          - service: script.post_to_home_log
            data:
              message: ":camera: Turning off indoor cameras."
          - service: script.conservatory_turn_off_camera
          - service: script.lounge_turn_off_camera
          - service: script.upstairs_turn_off_camera
          - service: script.set_central_heating_to_home_mode
    mode: single
  - id: "1587680439011"
    alias: "^Alarm: Arm Overnight Home Mode"
    description: ""
    trigger:
      - at: 00:00:00
        platform: time
        id: midnight
      - at: 01:00:00
        platform: time
      - at: 02:00:00
        platform: time
      - at: 05:00:00
        platform: time
    condition:
      - condition: state
        entity_id: group.adult_people
        state: home
      - condition: state
        entity_id: group.alarmed_doors_and_windows
        state: "off"
    action:
      - choose:
          - conditions:
            - not:
              - condition: state
                entity_id: person.danny
                state: home
            - condition: state
              entity_id: person.terina
              state: home
            - condition: trigger
              id: midnight
            sequence:
              - service: script.post_to_home_log
                data:
                  message: ":running: :house_with_garden: Danny is not home. 
                  :no_bell: Alarm not turned on and a check will be performed later."
          - conditions:
            - condition: state
              entity_id: person.danny
              state: home
            - not:
              - condition: state
                entity_id: person.terina
                state: home
            - condition: trigger
              id: midnight
            sequence:
              - service: script.post_to_home_log
                data:
                  message: ":house_with_garden: :woman_dancing: Terina is not 
                  home. :no_bell: Alarm not turned on and a check will be performed later."
          - conditions:
            - condition: state
              entity_id: person.danny
              state: home
            - condition: state
              entity_id: person.terina
              state: home
            sequence:
              - service: script.post_to_home_log
                data:
                  message: "Everyone is home."
              - service: script.set_alarm_to_home_mode
              - parallel:
                  - service: script.post_to_home_log
                    data:
                      message: "Turning on downstairs :camera_with_flash: cameras."
                  - service: script.conservatory_turn_on_camera
                  - service: script.lounge_turn_on_camera
                  - service: script.front_garden_turn_on_camera
          - conditions:
            - not:
              - condition: state
                entity_id: person.danny
                state: home
            - condition: state
              entity_id: person.terina
              state: home
            sequence:
              - service: script.post_to_home_log
                data:
                  message: ":running: :house_with_garden: Danny is not home."
              - service: script.set_alarm_to_home_mode
              - parallel:
                  - service: script.post_to_home_log
                    data:
                      message: "Turning on downstairs :camera_with_flash: cameras."
                  - service: script.conservatory_turn_on_camera
                  - service: script.lounge_turn_on_camera
                  - service: script.front_garden_turn_on_camera
          - conditions:
            - condition: state
              entity_id: person.danny
              state: home
            - not:
              - condition: state
                entity_id: person.terina
                state: home
            sequence:
              - service: script.post_to_home_log
                data:
                  message: ":house_with_garden: :woman_dancing: Terina is not 
                  home."
              - service: script.set_alarm_to_home_mode
              - parallel:
                  - service: script.post_to_home_log
                    data:
                      message: "Turning on downstairs :camera_with_flash: cameras."
                  - service: script.conservatory_turn_on_camera
                  - service: script.lounge_turn_on_camera
                  - service: script.front_garden_turn_on_camera
        default: []
    mode: single
  - id: "1630366065607"
    alias: "^Alarm: Armed"
    description: ""
    trigger:
      - platform: state
        entity_id: alarm_control_panel.house_alarm
        to: armed_away
    condition: []
    action:
      - parallel:
          - service: script.post_to_home_log
            data:
              message:
                ":bell: :camera_with_flash: Alarmed set to away mode (all sensors on).
                Turning on all cameras."
          - service: script.conservatory_turn_on_camera
          - service: script.lounge_turn_on_camera
          - service: script.upstairs_turn_on_camera
          - service: script.front_garden_turn_on_camera
    mode: single
  - id: "1614197981954"
    alias: "^Alarm: Disconnected"
    description: ""
    trigger:
      - platform: state
        entity_id: sensor.house_alarm_info
        to: unavailable
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          title: Alarm Offline
          message: ":warning: :no_bell: Alarm has disconnected from @home_assistant :warning:"
    mode: single
group:
  alarmed_doors_and_windows:
    name: Alarmed Doors and Windows
    entities:
      - binary_sensor.conservatory_door
      - binary_sensor.front_door
      - binary_sensor.lounge_left_window
      - binary_sensor.lounge_middle_window
      - binary_sensor.lounge_right_window
      - binary_sensor.office_window_left
      - binary_sensor.office_window_right
      - binary_sensor.shed_door
script:
  set_alarm_to_away_mode:
    alias: Set Alarm To Away
    sequence:
      - parallel:
          - if:
              - alias: "Alarm is not already in away mode."
                not:
                  - condition: state
                    entity_id: alarm_control_panel.house_alarm
                    state: armed_away
            then:
              - service: script.post_to_home_log
                data:
                  message: "Turning :bell: alarm on in away mode."
              - service: alarm_control_panel.alarm_arm_away
                data: {}
                target:
                  entity_id: alarm_control_panel.house_alarm
    mode: single
    icon: mdi:alarm-light
  set_alarm_to_disarmed_mode:
    alias: Set Alarm To Disarmed
    sequence:
      - parallel:
          - if:
              - alias: "Alarm is not turned off already."
                not:
                  - condition: state
                    entity_id: alarm_control_panel.house_alarm
                    state: disarmed
            then:
              - service: script.post_to_home_log
                data:
                  message: "Turning :no_bell: alarm off."
              - service: alarm_control_panel.alarm_disarm
                data: {}
                target:
                  entity_id: alarm_control_panel.house_alarm
    mode: single
    icon: mdi:alarm-light-off
  set_alarm_to_home_mode:
    alias: Set Alarm To Home
    sequence:
      - parallel:
          - if:
              - alias: "Alarm is not already in away mode."
                not:
                  - condition: state
                    entity_id: alarm_control_panel.house_alarm
                    state: armed_home
            then:
              - service: script.post_to_home_log
                data:
                  message: "Changing :bell: alarm to home mode(door sensors only)."
              - service: alarm_control_panel.alarm_arm_home
                data: {}
                target:
                  entity_id: alarm_control_panel.house_alarm
    mode: single
    icon: mdi:alarm-light
