# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1628956688014"
    alias: "^Alarm: Disarmed"
    description: ""
    trigger:
      - platform: state
        entity_id: alarm_control_panel.stevenage_alarm
        to: disarmed
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":no_bell: Alarmed disarmed."
      - service: script.post_to_home_log
        data:
          message: ":camera: Turning off indoor cameras."
      - service: script.conservatory_turn_off_camera
      - service: script.lounge_turn_off_camera
      - service: script.upstairs_turn_off_camera
      - service: script.set_central_heating_to_home_mode
    mode: single
  - id: "1587680439011"
    alias: "^Alarm: Arm Overnight Home Mode"
    description: ""
    trigger:
      - at: 00:00:00
        platform: time
      - at: 02:00:00
        platform: time
      - at: 05:00:00
        platform: time
    condition:
      - condition: state
        entity_id: group.adult_people
        state: home
      - condition: state
        entity_id: group.alarmed_doors_and_windows
        state: "off"
    action:
      - service: alarm_control_panel.alarm_arm_home
        data: {}
        target:
          entity_id: alarm_control_panel.stevenage_alarm
      - service: script.post_to_home_log
        data:
          message: ":couple: :house: :bell: Turning alarm in home mode (door sensors only) and downstairs :camera_with_flash: cameras."
      - service: script.conservatory_turn_on_camera
      - service: script.lounge_turn_on_camera
      - service: script.front_garden_turn_on_camera
    mode: single
  - id: "1630366065607"
    alias: "^Alarm: Armed"
    description: ""
    trigger:
      - platform: state
        entity_id: alarm_control_panel.stevenage_alarm
        to: armed_away
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":bell: :camera_with_flash: Alarmed set to away mode (all sensors on).
            Turning on all cameras."
      - service: script.conservatory_turn_on_camera
      - service: script.lounge_turn_on_camera
      - service: script.upstairs_turn_on_camera
      - service: script.front_garden_turn_on_camera
    mode: single
  - id: "1614197981954"
    alias: "^Alarm: Disconnected"
    description: ""
    trigger:
      - platform: state
        entity_id: sensor.stevenage_alarm_info
        to: unavailable
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          title: Alarm Offline
          message: ":warning: :no_bell: Alarm has disconnected from @home_assistant :warning:"
    mode: single
group:
  alarmed_doors_and_windows:
    name: Alarmed Doors and Windows
    entities:
      - binary_sensor.conservatory_door
      - binary_sensor.front_door
      - binary_sensor.lounge_left_window
      - binary_sensor.lounge_middle_window
      - binary_sensor.lounge_right_window
      - binary_sensor.office_window_left
      - binary_sensor.office_window_right
      - binary_sensor.shed_door
