# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1654008759007"
    alias: "Calendar: Family"
    description: "https://community.home-assistant.io/t/how-to-calculate-subtract-two-date-time-from-eachother/8197/6"
    trigger:
      - platform: calendar
        event: start
        entity_id: calendar.family
    condition: []
    action:
      - service: script.calendar_event_started
        data:
          entity_id: calendar.family
          name: "{{ trigger.calendar_event.summary|default(none, true) }}"
          event_type: "{{ trigger.event|default(none, true) }}"
          offset: "{{ trigger.offset|default(none, true) }}"
          all_day: "{{ trigger.calendar_event.all_day|default(none, true) }}"
          location: "{{ trigger.calendar_event.location|default(none, true) }}"
          start_time: "{{ trigger.calendar_event.start|default(none, true) }}"
          end_time: "{{ trigger.calendar_event.end|default(none, true) }}"
    mode: queued
  - id: "1654008759008"
    alias: "Calendar: Children"
    description: "https://community.home-assistant.io/t/how-to-calculate-subtract-two-date-time-from-eachother/8197/6"
    trigger:
      - platform: calendar
        event: start
        entity_id: calendar.tsang_children
    condition: []
    action:
      - service: script.calendar_event_started
        data:
          entity_id: calendar.tsang_children
          name: "{{ trigger.calendar_event.summary|default(none, true) }}"
          event_type: "{{ trigger.event|default(none, true) }}"
          offset: "{{ trigger.offset|default(none, true) }}"
          all_day: "{{ trigger.calendar_event.all_day|default(none, true) }}"
          location: "{{ trigger.calendar_event.location|default(none, true) }}"
          start_time: "{{ trigger.calendar_event.start|default(none, true) }}"
          end_time: "{{ trigger.calendar_event.end|default(none, true) }}"
    mode: queued

binary_sensor:
  - platform: workday
    country: GB

script:
  calendar_event_started:
    alias: Calendar event Started
    fields:
      entity_id:
        name: Entity ID
        description: Calendar entity ID.
        required: true
      name:
        name: Event name
        description: name of the event.
        required: true
      event_type:
        name: Event type
        description: denote if the it's the start or end of a calendar event.
      offset:
        name: Offset
        description: Time before or after the event type.
      all_day:
        name: All day
        description: if it's an all day event it will be set to true.
      location:
        name: Location
        description: Location of the event.
      start_time:
        name: Start time
        description: Date and time of the start of the event
      end_time:
        name: End time
        description: Date and time of the end of the event
    variables:
      duration: "{{ (as_timestamp(end_time)-as_timestamp(start_time))|int(0) }}"
      duration_formatted: >-
        {% set new_ts = (as_timestamp(end_time)-as_timestamp(start_time))|int(0) %}
        {{ '{:02d}:{:02d}:{:02d}'.format(new_ts // 3600, (new_ts % 3600) // 60, (new_ts % 3600) % 60) }}
      parsed_start_time: >-
        {% set dt = start_time.split('T') %}
        {{ strptime(dt[0].strip()~' '~dt[1], '%Y-%m-%d %H:%M:%S%z', none) }}
      parsed_end_time: >-
        {% set dt = end_time.split('T') %}
        {{ strptime(dt[0].strip()~' '~dt[1], '%Y-%m-%d %H:%M:%S%z', none) }}
    sequence:
      - choose:
          - alias: "Non all day event"
            conditions:
              - or:
                  - condition: template
                    value_template: "{{ all_day == false }}"
                  - condition: template
                    value_template: "{{ (as_timestamp(parsed_start_time) | timestamp_custom('%Y-%m-%d')) == (as_timestamp(parsed_end_time) | timestamp_custom('%Y-%m-%d')) }}"
              - condition: template
                value_template: "{{ location is not none }}"
            sequence:
              - service: script.send_to_home_log
                data:
                  message: >-
                    Trigger from {{ state_attr(entity_id, 'friendly_name') }} calendar event.

                    Event: {{ name|default('N/A', true) }}

                    Event Type: {{ event_type|default('N/A', true) }}

                    Offset: {{ offset|default('N/A', true) }}

                    All Day: {{ all_day|default('N/A', true) }}

                    Location: {{ location|default('N/A', true) }}

                    Start Time: {{ start_time|default('N/A', true) }}

                    End Time: {{ end_time|default('N/A', true) }}

                    Duration: {{ duration_formatted }}
                  title: ":date: Calendar"
              - service: script.calendar_calculate_travel
                data:
                  location: "{{ location|default('', true) }}"
          - alias: "All/multiple day event"
            conditions:
              - or:
                  - condition: template
                    value_template: "{{ all_day == true }}"
                  - condition: template
                    value_template: "{{ (as_timestamp(parsed_start_time) | timestamp_custom('%Y-%m-%d')) != (as_timestamp(parsed_end_time) | timestamp_custom('%Y-%m-%d')) }}"
              - condition: template
                value_template: "{{ location is not none }}"
            sequence:
              - service: script.send_to_home_log
                data:
                  message: >-
                    Trigger all day event from {{ state_attr(entity_id, 'friendly_name') }} calendar.

                    Calendar: {{ calendar_name|default('N/A', true) }}

                    Event: {{ name|default('N/A', true) }}

                    Event Type: {{ event_type|default('N/A', true) }}

                    Offset: {{ offset|default('N/A', true) }}

                    All Day: {{ all_day|default('N/A', true) }}

                    Location: {{ location|default('N/A', true) }}

                    Start Time: {{ start_time|default('N/A', true) }}

                    End Time: {{ end_time|default('N/A', true) }}

                    Duration: {{ duration_formatted }}
                  title: ":date: Calendar"
              - service: script.calendar_calculate_travel
                data:
                  location: "{{ location|default('', true) }}"
        default:
          - service: script.send_to_home_log
            continue_on_error: true
            data:
              message: >-
                Unknown trigger from {{ state_attr(entity_id, 'friendly_name') }} calendar.

                Calendar: {{ calendar_name|default('N/A', true) }}

                Event: {{ name|default('N/A', true) }}

                Event Type: {{ event_type|default('N/A', true) }}

                Offset: {{ offset|default('N/A', true) }}

                All Day: {{ all_day|default('N/A', true) }}

                Location: {{ location|default('N/A', true) }}

                Start Time: {{ start_time|default('N/A', true) }}

                End Time: {{ end_time|default('N/A', true) }}

                Duration: {{ duration_formatted }}
              title: ":date: Calendar"
  calendar_calculate_travel:
    alias: Calendar Travel Time
    fields:
      location:
        name: Location
        description: Location of the event.
    sequence:
      - if:
          - condition: state
            entity_id: input_boolean.enable_travel_automations
            state: "on"
        then:
          - parallel:
              - service: input_text.set_value
                data:
                  value: zone.home
                target:
                  entity_id: input_text.origin_address
              - service: input_text.set_value
                data:
                  value: "{{ location|default('', true) }}"
                target:
                  entity_id: input_text.destination_address
            alias: Set locations
          - service: homeassistant.update_entity
            data: {}
            target:
              entity_id: sensor.google_travel_time_by_car
          - service: script.send_direct_notification
            data:
              message: |-
                Origin: {{ states('sensor.origin_address') }}
                Destination: {{ states('sensor.destination_address') }}
                Journey Time: {{ state_attr('sensor.google_travel_time_by_car', 'duration') }} ({{ state_attr('sensor.google_travel_time_by_car', 'distance') }})
              title: ":date: Calendar"
              people:
                - person.danny
template:
  - trigger:
      - platform: calendar
        event: start
        entity_id: calendar.family
    sensor:
      - name: "Last Family Calendar Event Name"
        unique_id: 75bbe642-2c23-4e81-8a1b-d02d206e42b6
        state: "{{ trigger.calendar_event.summary|default('unavailable', true) }}"
      - name: "Last Family Calendar Event Type"
        unique_id: f8c9c32f-0d9f-4b5b-9bf0-1943c49e8f10
        state: "{{ trigger.event|default('unavailable', true) }}"
      - name: "Last Family Calendar Event Start Date"
        unique_id: 9a0a526c-8752-4f27-a755-5ec7a78a5281
        state: "{{ trigger.calendar_event.start|default('unavailable', true) }}"
      - name: "Last Family Calendar Event End Date"
        unique_id: 318d4fd8-0ccd-4568-9dfb-1417c8dfb8e3
        state: "{{ trigger.calendar_event.end|default('unavailable', true) }}"
      - name: "Last Family Calendar Event All Day"
        unique_id: 855a2dc9-e8c1-4585-8439-2197ffe96de9
        state: "{{ trigger.calendar_event.all_day|default('unavailable', true) }}"
      - name: "Last Family Calendar Event Location"
        unique_id: e5266e27-a4d4-46f0-8bc7-5f97e54dc758
        state: "{{ trigger.calendar_event.location|default('unavailable', true) }}"
  - trigger:
      - platform: calendar
        event: start
        entity_id: calendar.tsang_children
    sensor:
      - name: "Last Children Calendar Event Name"
        unique_id: e81b5ca4-d1b9-4359-bdfc-126c34fb9918
        state: "{{ trigger.calendar_event.summary|default('unavailable', true) }}"
      - name: "Last Children Calendar Event Type"
        unique_id: 01ea6cda-7f17-48fa-b09e-fffd860964ec
        state: "{{ trigger.event|default('unavailable', true) }}"
      - name: "Last Children Calendar Event Start Date"
        unique_id: 662f671c-a50b-4a5c-898b-01f9b644f115
        state: "{{ trigger.calendar_event.start|default('unavailable', true) }}"
      - name: "Last Children Calendar Event End Date"
        unique_id: 41c1c5de-c920-4d46-97e2-b0ade6eeb2cb
        state: "{{ trigger.calendar_event.end|default('unavailable', true) }}"
      - name: "Last Children Calendar Event All Day"
        unique_id: c621fdc3-9880-4500-9ec8-9792a5220ee8
        state: "{{ trigger.calendar_event.all_day|default('unavailable', true) }}"
      - name: "Last Children Calendar Event Location"
        unique_id: 76bebad8-06ae-444b-87f8-cfb0dad074ad
        state: "{{ trigger.calendar_event.location|default('unavailable', true) }}"
