# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://www.home-assistant.io/integrations/bmw_connected_drive/
#
# #Key
# counter.dannys_car_update_attempts - Number of times called to update the car details.
# counter.dannys_car_location_checked - Number of successful location updates.
# input_boolean.check_dannys_car_location - Turns on or off car location updates.
# timer.update_dannys_car - Delays between each request to update car details.
proximity:
  danny_car_home:
    zone: home
    devices:
      - device_tracker.435i
    tolerance: 100
    unit_of_measurement: mi

sensor:
  - platform: feedparser
    name: Fuelly
    feed_url: !secret fuelly_rss
    date_format: "%a, %b %d %I:%M %p"
    exclusions:
      - authors
      - id
      - guidislink
      - links
      - summary_detail

template:
  - sensor:
      - name: "Danny's Car Longitude"
        unique_id: 7c2e0876-3836-4cdf-bee3-b09865f1344c
        state: "{{ state_attr('device_tracker.435i', 'longitude') }}"
      - name: "Danny's Car Latitude"
        unique_id: 341c92c3-e9bf-40dc-ba4f-94e99ea2d037
        state: "{{ state_attr('device_tracker.435i', 'latitude') }}"
