# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1617795487661"
    alias: "^Office: Chromecast Start Playing"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.office_chromecast
        attribute: media_title
        to: playing
    condition: []
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ state_attr('media_player.office_chromecast', 'media_title') != none }}"
              - condition: template
                value_template: "{{ state_attr('media_player.office_chromecast', 'app_name') != none }}"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":tv: Chromecast office is playing {{ state_attr('media_player.office_chromecast',
                    'media_title') }} on {{ state_attr('media_player.office_chromecast',
                    'app_name') }}."
          - conditions:
              - condition: template
                value_template: "{{ state_attr('media_player.office_chromecast', 'app_name') != none }}"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":tv: Chromecast office is playing {{ state_attr('media_player.office_chromecast',
                    'app_name') }}."
        default:
          - service: script.post_to_home_log
            data:
              message: ":tv: Chromecast office is playing."
    mode: queued
    max: 10
  - id: "1617795505115"
    alias: "^Office: Chromecast Start Paused"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.office_chromecast
        to: paused
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":tv: Chromecast office paused"
    mode: queued
    max: 10
  - id: "1617795302933"
    alias: "^Office: Chromecast Turned On"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.office_chromecast
        to: "on"
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":tv: Chromecast office turned on."
    mode: queued
    max: 10
  - id: "1617795318685"
    alias: "^Office: Chromecast Turned Off"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.office_chromecast
        to: "off"
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":tv: Chromecast office turned off."
    mode: queued
    max: 10
  - id: "1617796469498"
    alias: "^Office: Chromecast Media Changes"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.office_chromecast
        attribute: media_title
    condition: []
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ state_attr('media_player.office_chromecast', 'media_title') != none }}"
              - condition: template
                value_template: "{{ state_attr('media_player.office_chromecast', 'app_name') != none }}"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":tv: Chromecast office is playing {{ state_attr('media_player.office_chromecast',
                    'media_title') }} on {{ state_attr('media_player.office_chromecast',
                    'app_name') }}."
          - conditions:
              - condition: template
                value_template: "{{ state_attr('media_player.office_chromecast', 'app_name') != none }}"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":tv: Chromecast office is playing {{ state_attr('media_player.office_chromecast',
                    'app_name') }}."
        default:
          - service: script.post_to_home_log
            data:
              message: ":tv: Chromecast office is playing."
    mode: queued
    max: 10
