# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://www.home-assistant.io/integrations/cast/
automation:
  # MagicMirror
  - id: "1647307174048"
    alias: "^Stairs: Check Magic Mirror Is Casting Home Assistant"
    description: ""
    trigger:
      - platform: time_pattern
        minutes: "0"
      - platform: homeassistant
        event: start
    condition:
      - or:
          - condition: state
            entity_id: input_select.home_mode
            state: guest
          - condition: state
            entity_id: group.adult_people
            state: home
      - not:
          - condition: state
            entity_id: alarm_control_panel.house_alarm
            state: armed_away
    action:
      parallel:
        - service: script.send_to_home_log
          data:
            message: Casting Home Assistant.
            title: ":mirror: Magic Mirror"
        - service: cast.show_lovelace_view
          data:
            entity_id: media_player.stairs_chromecast
            dashboard_path: lovelace-magicmirror
            view_path: home
    mode: single
