# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://github.com/DeebotUniverse/Deebot-4-Home-Assistant
alert:
  deebot_error:
    name: Vacuum has errored
    entity_id: vacuum.t8
    state: "error"
    repeat: 60
    can_acknowledge: true
    skip_first: true
    notifiers:
      - notify.mobile_app_dannys_phone

automation:
  - id: "1650387098757"
    alias: "^Deebot: Error"
    description: ""
    trigger:
      - platform: state
        entity_id: vacuum.t8
        to: "error"
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: ":warning: :robot_face: :broom: Vacuum has encountered an error :warning:"
          title: ":robot_face: :broom: Vacuum"
    mode: single
  - id: "1650387098756"
    alias: "^Deebot: Fully Charged"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: vacuum.t8
        above: "99"
        attribute: battery_level
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: ":battery: Fully charged"
          title: ":robot_face: :broom: Vacuum"
    mode: single
  - id: "1654865901253"
    alias: "Deebot: Finished Cleaning"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - vacuum.t8
        to: docked
        for:
          hours: 0
          minutes: 1
          seconds: 0
    condition: []
    action:
      - service: camera.snapshot
        data:
          filename: "{{states('input_text.camera_external_folder_path')}}{{states('camera.t8_live_map')}}"
        target:
          entity_id: camera.t8_live_map
      - delay:
          seconds: 2
      - service: script.send_home_log_with_local_attachments
        data:
          message: Cleaning complete
          title: ":robot_face: :broom: Vacuum docked"
          filePath: "{{states('input_text.camera_external_folder_path')}}{{states('camera.t8_live_map')}}"
    mode: single
