# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://github.com/DeebotUniverse/Deebot-4-Home-Assistant
automation:
  - id: "1650387098757"
    alias: "Deebot: Error"
    description: ""
    triggers:
      - trigger: state
        entity_id: vacuum.t8
        to: "error"
    conditions: []
    actions:
      - action: script.send_to_home_log
        data:
          message: ":warning: :robot_face: :broom: Vacuum has encountered an error :warning:"
          title: ":robot_face: :broom: Vacuum"
          log_level: "Normal"
    mode: single
  - id: "1650387098756"
    alias: "Deebot: Fully Charged"
    description: ""
    triggers:
      - trigger: numeric_state
        entity_id: vacuum.t8
        above: "99"
        attribute: battery_level
    conditions: []
    actions:
      - action: script.send_to_home_log
        data:
          message: ":battery: Fully charged"
          title: ":robot_face: :broom: Vacuum"
          log_level: "Debug"
    mode: single
  - id: "1654865901253"
    alias: "Deebot: Finished Cleaning"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - vacuum.t8
        to: "docked"
        for:
          hours: 0
          minutes: 1
          seconds: 0
        not_from: unavailable
    conditions: []
    actions:
      - action: script.send_home_log_with_url
        data:
          message: Cleaning complete
          title: ":robot_face: :broom: Vacuum"
          url: "{{ states('input_text.external_url') }}{{ state_attr('image.t8_map','entity_picture') }}"
    mode: single

rest_command:
  # https://community.home-assistant.io/t/add-service-integration-reload/231940/42
  reload_deebot:
    url: !secret deebot_restcommand_reload_url
    method: POST
    headers:
      authorization: !secret deebot_restcommand_reload_token
      content-type: "application/json"
