# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://github.com/DeebotUniverse/Deebot-4-Home-Assistant
automation:
  - id: "1650387098757"
    alias: "Deebot: Error"
    description: ""
    trigger:
      - platform: state
        entity_id: vacuum.t8
        to: "error"
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: ":warning: :robot_face: :broom: Vacuum has encountered an error :warning:"
          title: ":robot_face: :broom: Vacuum"
          log_level: "Normal"
    mode: single
  - id: "1650387098756"
    alias: "Deebot: Fully Charged"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: vacuum.t8
        above: "99"
        attribute: battery_level
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: ":battery: Fully charged"
          title: ":robot_face: :broom: Vacuum"
          log_level: "Debug"
    mode: single
  - id: "1654865901253"
    alias: "Deebot: Finished Cleaning"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - vacuum.t8
        to: "docked"
        for:
          hours: 0
          minutes: 1
          seconds: 0
        not_from: unavailable
    condition: []
    action:
      - service: camera.snapshot
        data:
          filename: "{{states('input_text.camera_external_folder_path')}}{{states('camera.t8_live_map')}}"
        target:
          entity_id: camera.t8_live_map
      - delay:
          seconds: 2
      - service: script.send_home_log_with_local_attachments
        data:
          message: Cleaning complete
          title: ":robot_face: :broom: Vacuum"
          filePath: "{{states('input_text.camera_external_folder_path')}}{{states('camera.t8_live_map')}}"
    mode: single

rest_command:
  # https://community.home-assistant.io/t/add-service-integration-reload/231940/42
  reload_deebot:
    url: !secret deebot_restcommand_reload_url
    method: POST
    headers:
      authorization: !secret deebot_restcommand_reload_token
      content-type: "application/json"
