# Created by Danny Tsang <danny@tsang.uk>
alert:
  deebot_error:
    name: Vacuum has errored
    entity_id: vacuum.t8
    state: "error"
    repeat: 60
    can_acknowledge: true
    skip_first: true
    notifiers:
      - notify.mobile_app_dannys_phone

automation:
  - id: "1650387098757"
    alias: "^Deebot: Error"
    description: ""
    trigger:
      - platform: state
        entity_id: vacuum.t8
        to: "error"
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: ":warning: :robot_face: :broom: Vacuum has encountered an error :warning:"
          title: ":robot_face: :broom: Vacuum"
    mode: single
  - id: "1650387098756"
    alias: "^Deebot: Fully Charged"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: vacuum.t8
        above: "99"
        attribute: battery_level
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: ":battery: Fully charged"
          title: ":robot_face: :broom: Vacuum"
    mode: single

input_text:
  vacuum_camera_folder:
    initial: !secret camera_vacuum_map_public
    name: Latest Vacuum Map Picture
    icon: mdi:vacuum
