# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1615314042948"
    alias: "^Game: Counter Strike Round Freeze"
    description: ""
    trigger:
      - platform: event
        event_type: csgo_round_freeze
    condition: []
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.counter_strike_round_freeze
    mode: single
  - id: "1615314108603"
    alias: "^Game: Counter Strike Bomb Explodes"
    description: ""
    trigger:
      - platform: event
        event_type: csgo_bomb_exploded
    condition: []
    action:
      - service: script.turn_off
        target:
          entity_id: script.counter_strike_bomb_planted
      - service: scene.turn_on
        target:
          entity_id: scene.counter_strike_bomb_exploded
    mode: single
  - id: "1615314203373"
    alias: "^Game: Counter Strike Bomb Defused"
    description: ""
    trigger:
      - platform: event
        event_type: csgo_bomb_defused
    condition: []
    action:
      - service: script.turn_off
        target:
          entity_id: script.counter_strike_bomb_planted
      - service: scene.turn_on
        target:
          entity_id: scene.counter_strike_bomb_defused
    mode: single
  - id: "1615314310555"
    alias: "^Game: Counter Strike Round Start Or Game Stopped"
    description: ""
    trigger:
      - platform: event
        event_type: csgo_round_started
      - platform: event
        event_type: csgo_game_stopped
    condition: []
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.office_turn_off_light_notification
    mode: single
script:
  counter_strike_bomb_planted:
    alias: Counter Strike Bomb Planted
    sequence:
      - repeat:
          until:
            - condition: or
              conditions:
                - condition: state
                  entity_id: group.jd_computer
                  state: "off"
          sequence:
            - service: light.turn_on
              data:
                color_name: red
                brightness_pct: 100
              target:
                entity_id: light.office_light
            - delay:
                hours: 0
                minutes: 0
                seconds: 1
                milliseconds: 0
            - service: light.turn_off
              target:
                entity_id: light.office_light
    mode: single
