# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1615314042948"
    alias: "^Game: Counter Strike Round Freeze"
    description: ""
    trigger:
      - platform: event
        event_type: csgo_round_freeze
    condition: []
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.counter_strike_round_freeze
    mode: single
  - id: "1615314108603"
    alias: "^Game: Counter Strike Bomb Explodes"
    description: ""
    trigger:
      - platform: event
        event_type: csgo_bomb_exploded
    condition: []
    action:
      - service: script.turn_off
        target:
          entity_id: script.counter_strike_bomb_planted
      - service: scene.turn_on
        target:
          entity_id: scene.counter_strike_bomb_exploded
    mode: single
  - id: "1615314203373"
    alias: "^Game: Counter Strike Bomb Defused"
    description: ""
    trigger:
      - platform: event
        event_type: csgo_bomb_defused
    condition: []
    action:
      - service: script.turn_off
        target:
          entity_id: script.counter_strike_bomb_planted
      - service: scene.turn_on
        target:
          entity_id: scene.counter_strike_bomb_defused
    mode: single
  - id: "1615314310555"
    alias: "^Game: Counter Strike Round Start Or Game Stopped"
    description: ""
    trigger:
      - platform: event
        event_type: csgo_round_started
      - platform: event
        event_type: csgo_game_stopped
    condition: []
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.office_turn_off_light_notification
    mode: queued
scene:
  - id: "1615313628703"
    name: Counter Strike Round Freeze
    entities:
      light.office_light:
        min_mireds: 111
        max_mireds: 400
        effect_list:
          - effect_colorloop
          - effect_pulse
          - effect_stop
        brightness: 255
        hs_color:
          - 59.997
          - 100
        rgb_color:
          - 255
          - 254
          - 0
        xy_color:
          - 0.445
          - 0.516
        friendly_name: Office Light
        supported_features: 55
        state: "on"
  - id: "1615313668376"
    name: Counter Strike Bomb Defused
    entities:
      light.office_light:
        min_mireds: 111
        max_mireds: 400
        effect_list:
          - effect_colorloop
          - effect_pulse
          - effect_stop
        brightness: 255
        hs_color:
          - 134.997
          - 100
        rgb_color:
          - 0
          - 255
          - 63
        xy_color:
          - 0.17
          - 0.703
        friendly_name: Office Light
        supported_features: 55
        state: "on"
  - id: "1615313695663"
    name: Counter Strike Bomb Exploded
    entities:
      light.office_light:
        min_mireds: 111
        max_mireds: 400
        effect_list:
          - effect_colorloop
          - effect_pulse
          - effect_stop
        brightness: 255
        hs_color:
          - 360
          - 100
        rgb_color:
          - 255
          - 0
          - 0
        xy_color:
          - 0.701
          - 0.299
        friendly_name: Office Light
        supported_features: 55
        state: "on"
script:
  counter_strike_bomb_planted:
    alias: Counter Strike Bomb Planted
    sequence:
      - repeat:
          until:
            - condition: or
              conditions:
                - condition: state
                  entity_id: group.jd_computer
                  state: "off"
          sequence:
            - service: light.turn_on
              data:
                color_name: red
                brightness_pct: 100
              target:
                entity_id: light.office_light
            - delay:
                hours: 0
                minutes: 0
                seconds: 1
                milliseconds: 0
            - service: light.turn_off
              target:
                entity_id: light.office_light
    mode: single
