# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://github.com/tolwi/hassio-ecoflow-cloud
automation:
  - id: "1689437015870"
    alias: "EcoFlow: Solar Below House Consumption"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.growatt_input_watt
        below: sensor.smart_meter_electricity_power
        for:
          hours: 0
          minutes: 2
          seconds: 0
    condition:
      - condition: numeric_state
        entity_id: sensor.electricity_current_rate
        above: 0
      - condition: numeric_state
        entity_id: number.ecoflow_kitchen_backup_reserve_level
        above: 10
      - condition: state
        entity_id: switch.ecoflow_kitchen_backup_reserve_enabled
        state: "on"
      - condition: state
        entity_id: input_boolean.enable_ecoflow_automations
        state: "on"
    action:
      - parallel:
          - service: script.send_direct_notification
            data:
              message: Solar production dipped below household consumption. Setting backup to 10%.
              title: Solar
              people:
                - person.danny
          - sequence:
              - service: input_number.set_value
                data:
                  value: 5
                target:
                  entity_id: input_number.target_ecoflow_kitchen_backup_reserve
              - repeat:
                  until:
                    - condition: template
                      value_template: >-
                        {{ repeat.index > 3 }}
                    - condition: template
                      value_template: >-
                        {{ states('number.ecoflow_kitchen_backup_reserve_level')|int(0) ==
                        states('input_number.target_ecoflow_kitchen_backup_reserve')|int(0) }}
                  sequence:
                    - service: number.set_value
                      data:
                        value: >-
                          {{ states('input_number.target_ecoflow_kitchen_backup_reserve')|int(5) }}
                      target:
                        entity_id: number.ecoflow_kitchen_backup_reserve_level
                    - delay:
                        hours: 0
                        minutes: 1
                        seconds: 0
                        milliseconds: 0
              - if:
                  - condition: template
                    value_template: >-
                      {{ states('number.ecoflow_kitchen_backup_reserve_level')|int(0) ==
                      states('input_number.target_ecoflow_kitchen_backup_reserve')|int(0) }}
                then:
                  - service: script.send_direct_notification
                    data:
                      message: Retry failed to set backup to 5%.
                      title: Solar
                      people:
                        - person.danny
    mode: restart
  - id: "1689626117476"
    alias: "Ecoflow: Electricity Rates Costs Nothing"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.electricity_current_rate
        below: 0.01
    condition:
      - condition: state
        entity_id: input_boolean.enable_ecoflow_automations
        state: "on"
    action:
      - parallel:
          - service: script.send_direct_notification
            data:
              message: >-
                Electrictity rate is 0 or below ("{{ states('sensor.electricity_current_rate')}}").
                Setting backup reserve to 100%.
              title: EcoFlow
              people:
                - person.danny
          - sequence:
              - service: input_number.set_value
                data:
                  value: 100
                target:
                  entity_id: input_number.target_ecoflow_kitchen_backup_reserve
              - repeat:
                  until:
                    - condition: template
                      value_template: >-
                        {{ repeat.index > 3 }}
                    - condition: template
                      value_template: >-
                        {{ states('number.ecoflow_kitchen_backup_reserve_level')|int(0) ==
                        states('input_number.target_ecoflow_kitchen_backup_reserve')|int(0) }}
                  sequence:
                    - service: number.set_value
                      data:
                        value: >-
                          {{ states('input_number.target_ecoflow_kitchen_backup_reserve')|int(5) }}
                      target:
                        entity_id: number.ecoflow_kitchen_backup_reserve_level
                    - delay:
                        hours: 0
                        minutes: 1
                        seconds: 0
                        milliseconds: 0
              - if:
                  - condition: template
                    value_template: >-
                      {{ states('number.ecoflow_kitchen_backup_reserve_level')|int(0) ==
                      states('input_number.target_ecoflow_kitchen_backup_reserve')|int(0) }}
                then:
                  - service: script.send_direct_notification
                    data:
                      message: Retry failed to set backup to 100%.
                      title: Solar
                      people:
                        - person.danny
    mode: single

template:
  - trigger:
      - platform: state
        entity_id:
          - sensor.growatt_input_watt
          - sensor.growatt_load_consumption
          - input_number.ecoflow_kitchen_charge_solar_threshold
    sensor:
      - name: "EcoFlow Kitchen Solar Excess"
        unique_id: 947e22f4-5213-4440-8da2-6c3a089f3743
        state: >-
          {{ ((states('sensor.growatt_input_watt')|float(0) - states('sensor.growatt_load_consumption')|float(0) - states('sensor.growatt_battery_1_charge_rate')|float(0))
          *1000 -states('input_number.ecoflow_kitchen_charge_solar_threshold')|int(0))|round(2) }}
        unit_of_measurement: w
  - trigger:
      - platform: state
        entity_id:
          - sensor.ecoflow_kitchen_total_in_power
          - sensor.ecoflow_kitchen_total_out_power
    sensor:
      - name: "EcoFlow Kitchen Charging Rate"
        unique_id: d809c2e4-e50b-499b-ac3a-796cef4806d8
        state: >-
          {{ states('sensor.ecoflow_kitchen_total_in_power')|float(0) - states('sensor.ecoflow_kitchen_total_out_power')|float(0) }}
        unit_of_measurement: w
