# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://www.home-assistant.io/integrations/esphome/
automation:
  - id: "1700645933582"
    alias: "ESPHome: Bed Update"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - group.esphome_device_updates
        not_to: "off"
    conditions:
      - condition: not
        conditions:
          - condition: template
            value_template:
              "{{ state_attr(trigger.entity_id, 'in_progress') == false
              }}"
    actions:
      - parallel:
          - action: script.send_to_home_log
            data:
              log_level: Debug
              message: Updating ESPHome after ESPHome update.
              title: ESPHome
          - action: homeassistant.update_entity
            data: {}
            target:
              entity_id: group.esphome_device_updates
    mode: single
  - id: "1701191210535"
    alias: "ESPHome: Update Firmware"
    description: ""
    triggers:
      - trigger: time_pattern
        hours: "0"
        minutes: "/15"
      - trigger: time_pattern
        hours: "1"
        minutes: "/15"
      - trigger: time_pattern
        hours: "2"
        minutes: "/15"
      - trigger: time_pattern
        hours: "3"
        minutes: "/15"
      - trigger: time_pattern
        hours: "4"
        minutes: "/15"
      - trigger: time_pattern
        hours: "5"
        minutes: "/15"
    conditions:
      - condition: not
        conditions:
          - condition: state
            entity_id: group.esphome_device_updates
            state: "off"
    actions:
      - parallel:
          - action: script.send_to_home_log
            data:
              log_level: Debug
              message: Updating ESPHome On Timer.
              title: ESPHome
          - action: homeassistant.update_entity
            data: {}
            target:
              entity_id: group.esphome_device_updates
    mode: single

group:
  esphome_device_updates:
    name: ESPHome Device Updates
    icon: mdi:update
    entities:
      - update.ashlees_bed_firmware
      - update.bathroom_motion_firmware
      - update.bed_firmware
      - update.boiler_firmware
      - update.kitchen_motion_firmware
      - update.leos_bed_firmware
      - update.lounge_motion_4_firmware
      - update.conservatory_motion_firmware
      - update.water_softener_firmware

script:
  update_esp_home:
    alias: Update ESPHome
    fields:
      entity_id:
        description: Entity ID for the update entity of the ESPHome device.
        required: true
        selector:
          text:
    sequence:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: "{{ state_attr(entity_id, 'friendly_name') }} updated."
              title: "ESPHome"
          - action: update.install
            data: {}
            target:
              entity_id: "{{ entity_id }}"
  restart_esp:
    alias: Restart ESP
    sequence:
      - parallel:
          - sequence:
              - action: switch.turn_off
                metadata: {}
                data: {}
                target:
                  entity_id:
                    - switch.ashlee_s_bedroom_esp_plug
                    - switch.bedroom_esp_plug
                    - switch.conservatory_extension_2
                    - switch.kitchen_esp_plug
                    - switch.leo_s_bedroom_esp_plug
                    - switch.office_extension_l5
              - delay:
                  seconds: 5
              - action: switch.turn_on
                metadata: {}
                data: {}
                target:
                  entity_id:
                    - switch.ashlee_s_bedroom_esp_plug
                    - switch.bedroom_esp_plug
                    - switch.conservatory_extension_2
                    - switch.leo_s_bedroom_esp_plug
                    - switch.office_extension_l5
          - alias: Kitchen Presence Sensor
            action: button.press
            target:
              entity_id: button.kitchen_port_3_power_cycle
            data: {}
    description: ""
    icon: mdi:chip
