# Created by Danny Tsang <danny@tsang.uk>
# https://espresense.com/home_assistant
sensor:
  # One entry for each beacon you want to track
  - platform: mqtt_room
    device_id: !secret ibeacon_id_dannys_phone
    name: "Danny's Phone BLE"
    state_topic: "espresense/rooms"
    timeout: 10
    away_timeout: 30 # number of seconds after which the enitity will get status not_home
  - platform: mqtt_room
    device_id: !secret ibeacon_id_jd_pc
    name: "JD PC"
    state_topic: "espresense/rooms"
    timeout: 30
    away_timeout: 120
  - platform: mqtt_room
    device_id: !secret ibeacon_id_work_headset
    name: "Danny's Work Headset"
    state_topic: "espresense/rooms"
    timeout: 10
    away_timeout: 30
  - platform: mqtt_room
    device_id: !secret ibeacon_id_terinas_phone
    name: "Terina's Phone BLE"
    state_topic: "espresense/rooms"
    timeout: 10
    away_timeout: 30
