# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1613937312554"
    alias: "^Home Assistant CI"
    description: "https://community.home-assistant.io/t/guide-to-setting-up-a-fully-automated-ci-for-hassio/51576"
    trigger:
      - platform: webhook
        webhook_id: git_pull
    condition:
      - condition: state
        entity_id: input_boolean.enable_git_automations
        state: "on"
    action:
      choose:
        - conditions:
            - condition: template
              value_template: "{{ trigger.json.key|string == states('input_text.github_pull_key') }}"
          sequence:
            - service: script.post_to_home_log
              data:
                message: ":construction_worker: :hammer_and_wrench: GitHub
                  build passed :white_check_mark:. Pulling changes."
            - service: hassio.addon_start
              data:
                addon: core_git_pull
      default:
        - service: script.post_to_home_log
          data:
            message: ":warning: :construction_worker: :hammer_and_wrench: GitHub
              build passed :white_check_mark: but incorrect key was sent :warning:"
    mode: single
input_boolean:
  enable_git_automations:
    name: Enable git integration
    icon: mdi:github
input_text:
  github_pull_key:
    name: GitHub Pull Key
    initial: !secret github_pull_key
    icon: mdi:github
    mode: password
sensor:
  # Travis CI build status
  - platform: rest
    resource: !secret travis_ci_url
    headers:
      Accept: application/vnd.travis-ci.2+json
      Authorization: !secret travis_ci_token
      Travis-API-Version: 3
    value_template: "{{ value_json.builds[0].state }}"
    name: "Travis CI Build Status"
