# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1613937312554"
    alias: "^Home Assistant CI"
    description: "https://community.home-assistant.io/t/guide-to-setting-up-a-fully-automated-ci-for-hassio/51576"
    trigger:
      - platform: webhook
        webhook_id: git_pull
    condition:
      - condition: state
        entity_id: input_boolean.enable_github_integration
        state: "on"
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ trigger.json.key|string == states('input_text.github_pull_key') }}"
            sequence:
              - parallel:
                  - service: script.send_to_home_log
                    data:
                      message: "build :white_check_mark: passed. Pulling changes."
                      title: ":construction_worker: :hammer_and_wrench: GitHub"
                  - service: hassio.addon_start
                    data:
                      addon: core_git_pull
        default:
          - service: script.send_to_home_log
            data:
              message: "Build :white_check_mark: passed but ncorrect :key: key was sent."
              title: ":warning: :construction_worker: :hammer_and_wrench: GitHub :warning:"
    mode: single
