# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://www.home-assistant.io/integrations/hive/
automation:
  - id: "1666470473971"
    alias: "HVAC: Heating Mode Changed"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - sensor.thermostat_mode
        to: SCHEDULE
      - platform: state
        entity_id:
          - water_heater.hot_water
        to: eco
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: Central heating mode changed to {{ states('sensor.thermostat_mode') }}
          title: ":hotsprings: :droplet: Boiler"
      - choose:
          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: Holiday
            sequence:
              - service: script.send_direct_notification
                data:
                  message: In holiday mode so heating schould not be on. Turning heating off.
                  title: ":hotsprings: :droplet: Boiler"
                  people:
                    - person.danny
              - service: script.set_central_heating_to_away_mode
                data: {}
    mode: single
  - id: "1666470473972"
    alias: "HVAC: Hot Water Mode Changed"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - water_heater.hot_water
        to: eco
      - platform: state
        entity_id:
          - water_heater.hot_water
        to: "on"
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: Hot water mode changed to {{ states('water_heater.hot_water') }}
          title: ":hotsprings: :droplet: Boiler"
      - choose:
          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: Holiday
            sequence:
              - service: script.send_direct_notification
                data:
                  message: In holiday mode so hot water schould not be on. Turning hot water off.
                  title: ":hotsprings: :droplet: Boiler"
                  people:
                    - person.danny
              - service: script.set_how_water_to_away_mode
                data: {}
    mode: single
  - id: "1662589192400"
    alias: "Central Heating: Turn On Hot Water"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - schedule.hot_water
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.enable_hot_water_automations
        state: "on"
      - not:
          - condition: state
            entity_id: water_heater.hot_water
            state: "on"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: Holiday
            sequence:
              - service: script.send_to_home_log
                data:
                  message: In Holiday mode. Skipping turning on hot water.
                  title: Central Heating
        default:
          - service: script.send_to_home_log
            data:
              message: Turning on hot water from schedule.
              title: Central Heating
          - service: script.set_how_water_to_on
            data: {}
    mode: single
  - id: "1662589333109"
    alias: "Central Heating: Turn Off Hot Water"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - schedule.hot_water
        to: "off"
        for:
          hours: 0
          minutes: 0
          seconds: 30
    condition:
      - condition: state
        entity_id: input_boolean.enable_hot_water_automations
        state: "on"
      - not:
          - condition: state
            entity_id: water_heater.hot_water
            state: "off"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: Holiday
            sequence:
              - service: script.send_to_home_log
                data:
                  message: In Holiday mode. Skipping turning off hot water.
                  title: Central Heating
        default:
          - service: script.send_to_home_log
            data:
              message: Turning off hot water from schedule.
              title: Central Heating
          - service: script.set_how_water_to_home_mode
            data: {}
    mode: single
script:
  set_central_heating_to_away_mode:
    alias: Set Central Heating To Away Mode
    icon: mdi:hvac
    sequence:
      - if:
          - or:
              - not:
                  - condition: state
                    entity_id: climate.thermostat
                    state: "heat"
              - not:
                  - condition: state
                    entity_id: climate.thermostat
                    attribute: temperature
                    state: 7
        then:
          - parallel:
              - service: script.send_to_home_log
                data:
                  message: "Setting heating to :running: away mode."
                  title: ":hotsprings: :droplet: Boiler"
              - service: climate.set_temperature
                target:
                  entity_id: climate.thermostat
                data:
                  temperature: 7
              - service: climate.set_hvac_mode
                data:
                  hvac_mode: heat
                target:
                  entity_id: climate.thermostat
    mode: single
  set_central_heating_to_home_mode:
    alias: Set Central Heating To Home Mode
    icon: mdi:hvac
    sequence:
      - if:
          - not:
              - condition: state
                entity_id: climate.thermostat
                state: "auto"
        then:
          - parallel:
              - service: script.send_to_home_log
                data:
                  message: "Setting heating to :house_with_garden: home mode."
                  title: ":hotsprings: :droplet: Boiler"
              - service: climate.set_hvac_mode
                data:
                  hvac_mode: auto
                target:
                  entity_id: climate.thermostat
    mode: single
  set_central_heating_to_off:
    alias: Set Central Heating Off
    icon: mdi:hvac-off
    sequence:
      - if:
          - not:
              - condition: state
                entity_id: climate.thermostat
                state: "off"
        then:
          - parallel:
              - service: script.send_to_home_log
                data:
                  message: "Setting heating to off."
                  title: ":hotsprings: :droplet: Boiler"
              - service: climate.set_hvac_mode
                data:
                  hvac_mode: "off"
                target:
                  entity_id: climate.thermostat
    mode: single
  set_how_water_to_home_mode:
    alias: Set Hot Water To Home
    icon: mdi:water-boiler-auto
    sequence:
      - if:
          - condition: state
            entity_id: input_boolean.enable_hive_hacs_integration
            state: "on"
        then:
          - if:
              - not:
                  - condition: state
                    entity_id: water_heater.hot_water
                    state: "eco"
            then:
              - parallel:
                  - service: script.send_to_home_log
                    data:
                      message: "Turning on the hot water."
                      title: ":hotsprings: :droplet: Boiler"
                  - service: water_heater.set_operation_mode
                    data:
                      operation_mode: "eco"
                    target:
                      entity_id: water_heater.hot_water
        else:
          - if:
              - not:
                  - condition: state
                    entity_id: water_heater.hot_water
                    state: "auto"
            then:
              - parallel:
                  - service: script.send_to_home_log
                    data:
                      message: "Turning on the hot water."
                      title: ":hotsprings: :droplet: Boiler"
                  - service: water_heater.set_operation_mode
                    data:
                      operation_mode: "auto"
                    target:
                      entity_id: water_heater.hot_water
    mode: single
  set_how_water_to_away_mode:
    alias: Set Hot Water To Off
    icon: mdi:water-boiler-off
    sequence:
      - if:
          - not:
              - condition: state
                entity_id: water_heater.hot_water
                state: "off"
        then:
          - parallel:
              - service: script.send_to_home_log
                data:
                  message: "Turning off the hot water."
                  title: ":hotsprings: :droplet: Boiler"
              - service: water_heater.set_operation_mode
                data:
                  operation_mode: "off"
                target:
                  entity_id: water_heater.hot_water
    mode: single
  set_how_water_to_on:
    alias: Set Hot Water To On
    icon: mdi:water-boiler
    sequence:
      - if:
          - not:
              - condition: state
                entity_id: water_heater.hot_water
                state: "on"
        then:
          - parallel:
              - service: script.send_to_home_log
                data:
                  message: "Turning on the hot water."
                  title: ":hotsprings: :droplet: Boiler"
              - service: water_heater.set_operation_mode
                data:
                  operation_mode: "on"
                target:
                  entity_id: water_heater.hot_water
    mode: single

sensor:
  # historical stats
  - platform: history_stats
    name: Heating On Duration Today
    entity_id: sensor.thermostat_action
    state: "heating"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Heating On Duration Yesterday
    entity_id: sensor.thermostat_action
    state: "heating"
    type: time
    end: "{{ now().replace(hour=0, minute=0, second=0) }}"
    duration:
      hours: 24
  - platform: history_stats
    name: Heating On Duration This Week
    entity_id: sensor.thermostat_action
    state: "heating"
    type: time
    start: "{{ as_timestamp( now().replace(hour=0, minute=0, second=0) ) - now().weekday() * 86400 }}"
    end: "{{ now() }}"
  # Hot Water
  - platform: history_stats
    name: Hot Water TOn Duration Today
    entity_id: sensor.hotwater_state
    state: "ON"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Hot Water On Duration Yesterday
    entity_id: sensor.hotwater_state
    state: "ON"
    type: time
    end: "{{ now().replace(hour=0, minute=0, second=0) }}"
    duration:
      hours: 24
  - platform: history_stats
    name: Hot Water On Duration This Week
    entity_id: sensor.hotwater_state
    state: "ON"
    type: time
    start: "{{ as_timestamp( now().replace(hour=0, minute=0, second=0) ) - now().weekday() * 86400 }}"
    end: "{{ now() }}"
template:
  - sensor:
      - name: "Thermostat Action"
        unique_id: 8dff3606-6aaf-4713-a668-140e71271416
        state: "{{ state_attr('climate.thermostat', 'hvac_action') }}"
