# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://www.home-assistant.io/integrations/webostv/
automation:
  # Office TV
  - id: "1617814309728"
    alias: "Office: TV On"
    description: ""
    triggers:
      - trigger: state
        entity_id: media_player.office_tv
        from: "off"
        to: "on"
    condition: []
    actions:
      - if:
          - condition: template
            value_template: "{{ state_attr('media_player.office_tv', 'source') != none }}"
        then:
          - action: script.send_to_home_log
            data:
              message:
                ":tv: Office TV turned on and playing {{ state_attr('media_player.office_tv',
                'source') }}."
              log_level: "Normal"
        else:
          - action: script.send_to_home_log
            data:
              message: ":tv: Office TV turned on."
              log_level: "Debug"
    mode: queued
    max: 10
  - id: "1617814349289"
    alias: "Office: TV Off"
    description: ""
    triggers:
      - trigger: state
        entity_id: media_player.office_tv
        from: "on"
        to: "off"
    condition: []
    actions:
      - action: script.send_to_home_log
        data:
          message: ":tv: Office TV turned off."
          log_level: "Debug"
    mode: queued
    max: 10
  - id: "1617814753264"
    alias: "Office: TV Source Changes"
    description: ""
    triggers:
      - trigger: state
        entity_id: media_player.office_tv
        attribute: source
    condition: []
    actions:
      - if:
          - condition: template
            value_template: "{{ state_attr('media_player.office_tv', 'source') != none }}"
        then:
          - action: script.send_to_home_log
            data:
              message:
                ":tv: Office TV turned on and playing {{ state_attr('media_player.office_tv',
                'source') }}."
              log_level: "Normal"
        else:
          - action: script.send_to_home_log
            data:
              message: ":tv: Office TV media changed."
              log_level: "Debug"
    mode: queued
    max: 10
