# Created by Danny Tsang <danny@tsang.uk>
automation:
  # Office TV
  - id: "1617814309728"
    alias: "^Office: TV On"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.office_tv
        from: "off"
        to: "on"
    condition: []
    action:
      - if:
          - condition: template
            value_template: "{{ state_attr('media_player.office_tv', 'source') != none }}"
        then:
          - service: script.send_to_home_log
            data:
              message:
                ":tv: Office TV turned on and playing {{ state_attr('media_player.office_tv',
                'source') }}."
        else:
          - service: script.send_to_home_log
            data:
              message: ":tv: Office TV turned on."
    mode: queued
    max: 10
  - id: "1617814349289"
    alias: "^Office: TV Off"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.office_tv
        from: "on"
        to: "off"
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: ":tv: Office TV turned off."
    mode: queued
    max: 10
  - id: "1617814753264"
    alias: "^Office: TV Source Changes"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.office_tv
        attribute: source
    condition: []
    action:
      - if:
          - condition: template
            value_template: "{{ state_attr('media_player.office_tv', 'source') != none }}"
        then:
          - service: script.send_to_home_log
            data:
              message:
                ":tv: Office TV turned on and playing {{ state_attr('media_player.office_tv',
                'source') }}."
        else:
          - service: script.send_to_home_log
            data:
              message: ":tv: Office TV media changed."
    mode: queued
    max: 10
