# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1631138390675"
    alias: "^Enter Normal Mode"
    description: ""
    trigger:
      - platform: state
        entity_id: input_select.home_mode
        to: Normal
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: ":repeat: Entering Normal mode."
    mode: single
  - id: "1631138548505"
    alias: "^Enter Guest Mode"
    description: ""
    trigger:
      - platform: state
        entity_id: input_select.home_mode
        to: Guest
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: ":repeat: Entering Guest mode."
    mode: single

input_boolean:
  enable_direct_notifications:
    name: Enable Direct Notifications
    icon: mdi:cellphone-information
  enable_notifications:
    name: Enable Notifications
    icon: mdi:message-outline

input_select:
  danny_direct_notification_preference:
    name: Danny's Direct Notification Preference
    options:
      - Slack
      - Mobile
      - Telegram
    icon: mdi:cellphone-information
  terina_direct_notification_preference:
    name: Terina's Direct Notification Preference
    options:
      - Slack
      - Mobile
      - Telegram
    icon: mdi:cellphone-information

input_text:
  telegram_danny_chat_id:
    name: Danny's Telegram Chat ID
    icon: mdi:android-messages
    initial: !secret telegram_danny_chat_id

notify:
  - name: slack_notify
    platform: slack
    api_key: !secret slack
    default_channel: "home_log"
  - platform: telegram
    name: telegram
    chat_id: !secret telegram_danny_chat_id

script:
  # Encapsulated scripts
  send_to_home_log:
    alias: Send An Entry To Home Log
    icon: mdi:message-outline
    description: "Post a text message to the home_log channel."
    max: 10
    mode: queued
    # https://github.com/home-assistant/frontend/issues/8591
    fields:
      message:
        description: Message to post.
        required: true
      title:
        description: (optional)Title to the message posted.
    sequence:
      - if:
          - condition: state
            entity_id: input_boolean.enable_notifications
            state: "on"
        then:
          - service: script.post_slack_notification
            data:
              message: "{{ message }}"
              target: "home_log"
  send_direct_notification:
    alias: Send Direct Mesage To a Person
    icon: mdi:message-outline
    description: "Send a direct text message to adults in the house."
    fields:
      message:
        description: Message to post
        required: true
      title:
        description: Title to post
      people:
        description:
          (optional)People to message using people entity e.g. person.danny.
          If no one is specified, it will go to everyone.
    sequence:
      # Check if notifications is turned on.
      - if:
          - condition: state
            entity_id: input_boolean.enable_notifications
            state: "on"
        then:
          # Check if the message is directed at someone.
          - choose:
              # If people parameter is not set
              - conditions:
                  - condition: template
                    value_template: "{% if people is not defined or 
                    people is not match('person.*') %}True{% endif %}"
                sequence:
                  - service: script.post_slack_notification
                    data:
                      message: "{{ message }}"
                      title: "{{ title }}"
                      target: "general"
                      people: "@danny @terina"
              # If both adults mentioned.
              - conditions:
                  - condition: template
                    value_template: "{{ 'person.danny' in people.split(',') }}"
                  - condition: template
                    value_template: "{{ 'person.terina' in people.split(',') }}"
                sequence:
                  # Check if both have the same preferred messaging platform.
                  - choose:
                      - conditions:
                          - condition: state
                            entity_id: input_select.danny_direct_notification_preference
                            state: Slack
                          - condition: state
                            entity_id: input_select.terina_direct_notification_preference
                            state: Slack
                        sequence:
                          - service: script.post_slack_notification
                            data:
                              message: "{{ message }}"
                              title: "{{ title }}"
                              target: "general"
                              people: "@danny @terina"
                    # If not, check each person's preference.
                    default:
                      - service: script.post_direct_notification_by_person
                        data:
                          message: "{{ message }}"
                          title: "{{ title }}"
                          people: "{{ people }}"
              # Check if the person entity has been passed. 
              # The underly script will notify the right people if it does.
              - conditions:
                  - condition: template
                    value_template: "{% if people is defined and people is match('person.*') %}True{% endif %}"
                sequence:
                  # Checked preferred messaging platform.
                  - service: script.post_direct_notification_by_person
                    data:
                      message: "{{ message }}"
                      title: "{{ title }}"
                      people: "{{ people }}"
            # Catch all but modified message.
            default:
              - service: script.post_direct_notification_by_person
                data:
                  message: ":warning: Unknown recipient.\n
                  message: {{ message }}\n
                  people: {{ people }}"
                  title: "{{ title }}"
                  people: "person.danny"
    mode: queued
    max: 10
  send_home_log_with_local_attachments:
    alias: Post To Home Log With Local Attachments
    icon: mdi:message-image-outline
    description: "Post a message with a file attachment to the home_log channel."
    fields:
      message:
        description: Message to post
        required: true
      title:
        description: (optional)Title to the message posted.
      filePath:
        description: File path to attach to post.
        required: true
    sequence:
      - condition: state
        entity_id: input_boolean.enable_notifications
        state: "on"
      - service: script.post_to_slack_home_log_with_local_attachments
        data:
          message: "{{ message }}"
          title: "{{ title }}"
          target: "home_log"
          filePath: "{{ filePath }}"
    mode: queued
    max: 10
  send_home_log_with_url:
    alias: Post To Home Log With URL
    icon: mdi:message-bookmark-outline
    description: "Post a message with a URL to the home_log channel."
    fields:
      message:
        description: Message to post
      title:
        description: (optional)Title to the message posted.
      url:
        description: (optional)Link to file.
    sequence:
      - condition: state
        entity_id: input_boolean.enable_notifications
        state: "on"
      - service: script.post_to_slack_home_log_with_url
        data:
          message: "{{ message }}"
          title: "{{ title }}"
          target: "home_log"
          url: "{{ url }}"
    mode: queued
    max: 10
  send_actionable_notification_with_2_buttons:
    alias: Post Actionable Notification With 2 Buttons
    icon: mdi:message-draw
    fields:
      message:
        description: Message to post
        required: true
      title:
        description: (optional)Title to the message posted.
      people:
        description: People to message e.g. Danny, Terina
        required: true
      action1_title:
        description: First action text.
        required: true
      action1_name:
        description: First vent name if action is selected.
        required: true
      action2_title:
        description: Second action text.
        required: true
      action2_name:
        description: Second event name if action is selected.
        required: true
    sequence:
      - condition: state
        entity_id: input_boolean.enable_direct_notifications
        state: "on"
      - service: script.post_mobile_actionable_notification_with_2_buttons
        data:
          message: "{{ message }}"
          title: "{{ title }}"
          people: "{{ people }}"
          action1_title: "{{ action1_title }}"
          action1_name: "{{ action1_name }}"
          action2_title: "{{ action2_title }}"
          action2_name: "{{ action2_name }}"
    mode: queued
    max: 10
  send_actionable_notification_with_3_buttons:
    alias: Post Actionable Notification With 3 Buttons
    icon: mdi:message-draw
    fields:
      message:
        description: Message to post
        required: true
      title:
        description: (optional)Title to the message posted.
      action1_title:
        description: First action text.
      action1_name:
        description: First vent name if action is selected.
        required: true
      action2_title:
        description: Second action text.
        required: true
      action2_name:
        description: Second event name if action is selected.
        required: true
      action3_title:
        description: Third action text.
        required: true
      action3_name:
        description: Third event name if action is selected.
        required: true
    sequence:
      - condition: state
        entity_id: input_boolean.enable_direct_notifications
        state: "on"
      - service: script.post_mobile_actionable_notification_with_3_buttons
        data:
          message: "{{ message }}"
          title: "{{ title }}"
          data:
            action1_title: "{{ action1_title }}"
            action1_name: "{{ action1_name }}"
            action2_title: "{{ action2_title }}"
            action2_name: "{{ action2_name }}"
            action3_title: "{{ action3_title }}"
            action3_name: "{{ action3_name }}"
    mode: single
  post_direct_notification_by_person:
    alias: Post a direct message based on a persons selected messaging platform.
    icon: mdi:message-outline
    description: "Post a direct text message to adults in the house."
    fields:
      message:
        description: Message to post
        required: true
      title:
        description: Title to post
      people:
        description: People to message using people entity e.g. person.danny.
          If no one is specified, it will go to everyone.
        required: true
    sequence:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ 'person.danny' in people.split(',') }}"
            sequence:
              # Checked preferred messaging platform.
              - choose:
                  - conditions:
                      - condition: state
                        entity_id: input_select.danny_direct_notification_preference
                        state: Telegram
                    sequence:
                      - service: script.post_telegram_direct_notification
                        data:
                          message: "{{ message }}"
                          title: "{{ title }}"
                  - conditions:
                      - condition: state
                        entity_id: input_select.danny_direct_notification_preference
                        state: Slack
                    sequence:
                      - service: script.post_slack_notification
                        data:
                          message: "{{ message }}"
                          title: "{{ title }}"
                          target: "general"
                          people: "@danny"
                default: []
          # Check if Terina was mentioned.
          - conditions:
              - condition: template
                value_template: "{{ 'person.terina' in people.split(',') }}"
            sequence:
              - service: script.post_slack_notification
                data:
                  message: "{{ message }}"
                  title: "{{ title }}"
                  target: "general"
                  people: "@terina"
    mode: queued
    max: 10
  # Slack specific Scripts
  post_slack_notification:
    alias: Post Slack Message
    icon: mdi:slack
    description: "Post a text message to Slack."
    fields:
      message:
        description: Message to post
        required: true
      people:
        description: (optional)People to message e.g. @danny
      target:
        description: Slack channel to post the message to.
        required: true
    sequence:
      - service: notify.slack_notify
        data:
          message: "{{ people }} {{ message }}"
          target: "{{ target }}"
          data:
            blocks: []
    mode: queued
    max: 10
  post_to_slack_home_log_with_local_attachments:
    alias: Post To Slack Home Log With Local Attachments
    icon: mdi:slack
    description: "Post a message with a file attachment to the home_log channel."
    fields:
      message:
        description: Message to post
        required: true
      title:
        description: (optional)Title to the message posted.
      channel:
        description: "Slack channel to post to including the #"
        required: true
      filePath:
        description: File path to attach to post.
        required: true
    sequence:
      - condition: state
        entity_id: input_boolean.enable_notifications
        state: "on"
      - service: notify.slack_notify
        data:
          message: "{{ message }}"
          title: "{{ title|default('', true) }}"
          target: "{{ channel }}"
          data:
            file:
              path: "{{ filePath }}"
    mode: queued
    max: 10
  post_to_slack_home_log_with_url:
    alias: Post To Home Log With URL
    icon: mdi:slack
    description: "Post a message with a URL to the home_log channel."
    fields:
      message:
        description: Message to post
        required: true
      title:
        description: (optional)Title to the message posted.
      target:
        description: "Slack channel to post without the #."
        required: true
      url:
        description: Link to file.
        required: true
    sequence:
      - condition: state
        entity_id: input_boolean.enable_notifications
        state: "on"
      - service: notify.slack_notify
        data:
          message: "{{ message }}"
          title: "{{ title|default('', true) }}"
          target: "home_log"
          data:
            file:
              url: "{{ url }}"
    mode: queued
    max: 10
  # Mobile
  post_mobile_actionable_notification_with_2_buttons:
    alias: Post Actionable Notification With 2 Buttons
    fields:
      message:
        description: Message to post
        required: true
      title:
        description: (optional)Title to the message posted.
      people:
        description: People to message e.g. Danny, Terina
        required: true
      action1_title:
        description: First action text.
        required: true
      action1_name:
        description: First event name if action is selected.
        required: true
      action2_title:
        description: Second action text.
        required: true
      action2_name:
        description: Second event name if action is selected.
        required: true
    sequence:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ state_attr('person.danny','id') == 'danny' }}"
            sequence:
              - service: notify.mobile_app_dannys_phone
                data:
                  message: "{{ message }}"
                  title: "{{ title|default('', true) }}"
                  data:
                    actions:
                      - title: "{{ action1_title }}"
                        action: "{{ action1_name }}"
                      - title: "{{ action2_title }}"
                        action: "{{ action2_name }}"
        default: []
    mode: queued
    max: 10
    icon: mdi:forum
  post_mobile_actionable_notification_with_3_buttons:
    alias: Post Actionable Notification With 3 Buttons
    fields:
      message:
        description: Message to post
        required: true
      title:
        description: (optional)Title to the message posted.
      action1_title:
        description: First action text.
      action1_name:
        description: First vent name if action is selected.
        required: true
      action2_title:
        description: Second action text.
        required: true
      action2_name:
        description: Second event name if action is selected.
        required: true
      action3_title:
        description: Third action text.
        required: true
      action3_name:
        description: Third event name if action is selected.
        required: true
    sequence:
      - condition: state
        entity_id: input_boolean.enable_direct_notifications
        state: "on"
      - service: notify.mobile_app_dannys_phone
        data:
          message: "{{ message }}"
          title: "{{ title|default('', true) }}"
          data:
            actions:
              - title: "{{ action1_title }}"
                action: "{{ action1_name }}"
              - title: "{{ action2_title }}"
                action: "{{ action2_name }}"
              - title: "{{ action3_title }}"
                action: "{{ action3_name }}"
    mode: single
    icon: mdi:forum
  # Telegram specific Scripts
  post_telegram_direct_notification:
    alias: Send Telegram Direct Message
    icon: mdi:android-messages
    description: "Post a direct text message to adults in the house."
    max: 10
    mode: queued
    fields:
      message:
        description: Message to post
        required: true
      title:
        description: Title of post
      people:
        description: Person to send the message to e.g. person.danny.
          If not specified then it goes to everyone.
    sequence:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ 'person.danny' in people.split(',') }}"
            sequence:
              - service: telegram_bot.send_message
                data:
                  message: "{{ message }}"
                  title: "{{ title|default('', true) }}"
                  target: "{{ states('input_text.telegram_danny_chat_id') }}"
        default:
          - service: telegram_bot.send_message
            data:
              message: "{{ message }}"
              title: "{{ title|default('', true) }}"
              target: "{{ states('input_text.telegram_danny_chat_id') }}"
  post_to_telegram_home_log_with_local_attachments:
    alias: Post To Slack Home Log With Local Attachments
    icon: mdi:android-messages
    description: "Post a message with a file attachment to the home_log channel."
    fields:
      message:
        description: Message to post
        required: true
      title:
        description: (optional)Title to the message posted.
      filePath:
        description: File path to attach to post.
        required: true
    sequence:
      - condition: state
        entity_id: input_boolean.enable_notifications
        state: "on"
      - service: notify.slack_notify
        data:
          message: "{{ message }}"
          title: "{{ title|default('', true) }}"
          file: "{{ filePath }}"
    mode: queued
    max: 10
