# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1631138390675"
    alias: "^Enter Normal Mode"
    description: ""
    trigger:
      - platform: state
        entity_id: input_select.home_mode
        to: Normal
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":repeat: Entering Normal mode."
    mode: single
  - id: "1631138548505"
    alias: "^Enter Guest Mode"
    description: ""
    trigger:
      - platform: state
        entity_id: input_select.home_mode
        to: Guest
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":repeat: Entering Guest mode."
    mode: single
input_boolean:
  enable_direct_notifications:
    name: Enable Direct Notifications
    icon: mdi:bell
  enable_mobile_direct_notifications:
    name: Enable Mobile Direct Notifications
    icon: mdi:cellphone-information
  enable_slack_notifications:
    name: Enable Slack notifications
    icon: mdi:slack
input_select:
  danny_direct_notification_preference:
    name: Danny's Direct Notification Preference
    options:
      - Slack
      - Mobile
      - Telegram
    icon: mdi:cellphone-information
  terina_direct_notification_preference:
    name: Danny's Direct Notification Preference
    options:
      - Slack
      - Mobile
      - Telegram
    icon: mdi:cellphone-information

input_text:
  telegram_danny_chat_id:
    name: Danny's Telegram Chat ID
    icon: mdi:android-messages
    initial: !secret telegram_danny_chat_id

notify:
  - name: slack_notify
    platform: slack
    api_key: !secret slack
    default_channel: "#home_log"
  - platform: telegram
    name: telegram_all
    chat_id: !secret telegram_danny_chat_id

script:
  # Encapsulated scripts
  post_to_home_log:
    alias: Post To Home Log
    icon: mdi:message-outline
    description: "Post a text message to the home_log channel."
    max: 10
    mode: queued
    # https://github.com/home-assistant/frontend/issues/8591
    fields:
      message:
        description: Message to post.
        required: true
      title:
        description: (optional)Header to the message posted.
    sequence:
      - condition: state
        entity_id: input_boolean.enable_slack_notifications
        state: "on"
      - data:
          message: "{{ message }}"
          title: "{{ title|default('', true) }}"
          target: "#home_log"
          data:
            blocks: []
        service: notify.slack_notify
  send_direct_notification:
    alias: Post Direct Mesage
    icon: mdi:message-outline
    description: "Post a direct text message to adults in the house."
    max: 10
    mode: queued
    fields:
      message:
        description: Message to post
        required: true
      title:
        description: Title to post
    sequence:
      - condition: state
        entity_id: input_boolean.enable_slack_notifications
        state: "on"
      - choose:
          - conditions:
              - condition: state
                entity_id: input_select.danny_direct_notification_preference
                state: Telegram
            sequence:
              - service: script.post_telegram_direct_notification
                data:
                  message: "{{ message }}"
                  title: "{{ title }}"
          - conditions:
              - condition: state
                entity_id: input_select.danny_direct_notification_preference
                state: Slack
            sequence:
              - service: script.post_slack_direct_notification
                data:
                  message: "{{ message }}"
                  title: "{{ title }}"
                  people: "@danny"
        default: []
      - service: script.post_slack_direct_notification
        data:
          message: "{{ message }}"
          title: "{{ title }}"
          people: "@terina"
  send_home_log_with_local_attachments:
    alias: Post To Home Log With Local Attachments
    icon: mdi:message-image-outline
    description: "Post a message with a file attachment to the home_log channel."
    fields:
      message:
        description: Message to post
        required: true
      title:
        description: (optional)Header to the message posted.
      filePath:
        description: File path to attach to post.
        required: true
    sequence:
      - condition: state
        entity_id: input_boolean.enable_slack_notifications
        state: "on"
      - service: script.post_to_slack_home_log_with_local_attachments
        data:
          message: "{{ message }}"
          title: "{{ title }}"
          target: "#home_log"
          filePath: "{{ filePath }}"
    mode: queued
    max: 10
  send_home_log_with_url:
    alias: Post To Home Log With URL
    icon: mdi:message-bookmark-outline
    description: "Post a message with a URL to the home_log channel."
    fields:
      message:
        description: Message to post
      title:
        description: (optional)Header to the message posted.
      url:
        description: (optional)Link to file.
    sequence:
      - condition: state
        entity_id: input_boolean.enable_slack_notifications
        state: "on"
      - service: script.post_to_slack_home_log_with_url
        data:
          message: "{{ message }}"
          title: "{{ title }}"
          target: "#home_log"
          url: "{{ url }}"
    mode: queued
    max: 10
  send_actionable_notification_with_2_buttons:
    alias: Post Actionable Notification With 2 Buttons
    fields:
      message:
        description: Message to post
        required: true
      title:
        description: (optional)Header to the message posted.
      people:
        description: People to message e.g. Danny, Terina
        required: true
      action1_title:
        description: First action text.
        required: true
      action1_name:
        description: First vent name if action is selected.
        required: true
      action2_title:
        description: Second action text.
        required: true
      action2_name:
        description: Second event name if action is selected.
        required: true
    sequence:
      - condition: state
        entity_id: input_boolean.enable_direct_notifications
        state: "on"
      - service: script.post_mobile_actionable_notification_with_2_buttons
        data:
          message: "{{ message }}"
          title: "{{ title }}"
          people: "{{ people }}"
          action1_title: "{{ action1_title }}"
          action1_name: "{{ action1_name }}"
          action2_title: "{{ action2_title }}"
          action2_name: "{{ action2_name }}"
    mode: queued
    max: 10
    icon: mdi:message-draw
  send_actionable_notification_with_3_buttons:
    alias: Post Actionable Notification With 3 Buttons
    fields:
      message:
        description: Message to post
        required: true
      title:
        description: (optional)Header to the message posted.
      action1_title:
        description: First action text.
      action1_name:
        description: First vent name if action is selected.
        required: true
      action2_title:
        description: Second action text.
        required: true
      action2_name:
        description: Second event name if action is selected.
        required: true
      action3_title:
        description: Third action text.
        required: true
      action3_name:
        description: Third event name if action is selected.
        required: true
    sequence:
      - condition: state
        entity_id: input_boolean.enable_direct_notifications
        state: "on"
      - service: script.post_mobile_actionable_notification_with_3_buttons
        data:
          message: "{{ message }}"
          title: "{{ title }}"
          data:
            action1_title: "{{ action1_title }}"
            action1_name: "{{ action1_name }}"
            action2_title: "{{ action2_title }}"
            action2_name: "{{ action2_name }}"
            action3_title: "{{ action3_title }}"
            action3_name: "{{ action3_name }}"
    mode: single
    icon: mdi:message-draw
  # Slack specific Scripts
  post_slack_direct_notification:
    alias: Send Slack Direct Message
    icon: mdi:slack
    description: "Post a direct text message to adults in the house."
    max: 10
    mode: queued
    fields:
      message:
        description: Message to post
        required: true
      people:
        description: People to message e.g. @danny
        required: true
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.enable_direct_notifications
                state: "on"
            sequence:
              - service: notify.mobile_app_dannys_phone
                data:
                  message: "{{ message }}"
              - service: notify.mobile_app_terina_s_phone
                data:
                  message: "{{ message }}"
        default: []
      - data:
          message: "{{ people }} {{ message }}"
          target: "#general"
          data:
            blocks: []
        service: notify.slack_notify
  post_to_slack_home_log_with_local_attachments:
    alias: Post To Slack Home Log With Local Attachments
    icon: mdi:slack
    description: "Post a message with a file attachment to the home_log channel."
    fields:
      message:
        description: Message to post
        required: true
      title:
        description: (optional)Header to the message posted.
      channel:
        description: "Slack channel to post to including the #"
        required: true
      filePath:
        description: File path to attach to post.
        required: true
    sequence:
      - condition: state
        entity_id: input_boolean.enable_slack_notifications
        state: "on"
      - service: notify.slack_notify
        data:
          message: "{{ message }}"
          title: "{{ title|default('', true) }}"
          target: "{{ channel }}"
          data:
            file:
              path: "{{ filePath }}"
    mode: queued
    max: 10
  post_to_slack_home_log_with_url:
    alias: Post To Home Log With URL
    icon: mdi:slack
    description: "Post a message with a URL to the home_log channel."
    fields:
      message:
        description: Message to post
        required: true
      title:
        description: (optional)Header to the message posted.
      target:
        description: "Slack channel to post to including the #"
        required: true
      url:
        description: Link to file.
        required: true
    sequence:
      - condition: state
        entity_id: input_boolean.enable_slack_notifications
        state: "on"
      - service: notify.slack_notify
        data:
          message: "{{ message }}"
          title: "{{ title|default('', true) }}"
          target: "#home_log"
          data:
            file:
              url: "{{ url }}"
    mode: queued
    max: 10
  # Mobile
  post_mobile_actionable_notification_with_2_buttons:
    alias: Post Actionable Notification With 2 Buttons
    fields:
      message:
        description: Message to post
        required: true
      title:
        description: (optional)Header to the message posted.
      people:
        description: People to message e.g. Danny, Terina
        required: true
      action1_title:
        description: First action text.
        required: true
      action1_name:
        description: First event name if action is selected.
        required: true
      action2_title:
        description: Second action text.
        required: true
      action2_name:
        description: Second event name if action is selected.
        required: true
    sequence:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ state_attr('person.danny','id') == 'danny' }}"
            sequence:
              - service: notify.mobile_app_dannys_phone
                data:
                  message: "{{ message }}"
                  title: "{{ title|default('', true) }}"
                  data:
                    actions:
                      - title: "{{ action1_title }}"
                        action: "{{ action1_name }}"
                      - title: "{{ action2_title }}"
                        action: "{{ action2_name }}"
        default: []
    mode: queued
    max: 10
    icon: mdi:cellphone
  post_mobile_actionable_notification_with_3_buttons:
    alias: Post Actionable Notification With 3 Buttons
    fields:
      message:
        description: Message to post
        required: true
      title:
        description: (optional)Header to the message posted.
      action1_title:
        description: First action text.
      action1_name:
        description: First vent name if action is selected.
        required: true
      action2_title:
        description: Second action text.
        required: true
      action2_name:
        description: Second event name if action is selected.
        required: true
      action3_title:
        description: Third action text.
        required: true
      action3_name:
        description: Third event name if action is selected.
        required: true
    sequence:
      - condition: state
        entity_id: input_boolean.enable_direct_notifications
        state: "on"
      - service: notify.mobile_app_dannys_phone
        data:
          message: "{{ message }}"
          title: "{{ title|default('', true) }}"
          data:
            actions:
              - title: "{{ action1_title }}"
                action: "{{ action1_name }}"
              - title: "{{ action2_title }}"
                action: "{{ action2_name }}"
              - title: "{{ action3_title }}"
                action: "{{ action3_name }}"
    mode: single
    icon: mdi:cellphone
  # Telegram specific Scripts
  post_telegram_direct_notification:
    alias: Send Telegram Direct Message
    icon: mdi:android-messages
    description: "Post a direct text message to adults in the house."
    max: 10
    mode: queued
    fields:
      message:
        description: Message to post
        required: true
      title:
        description: Message to post
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.enable_direct_notifications
                state: "on"
              - condition: state
                entity_id: input_select.danny_direct_notification_preference
                state: "Telegram"
            sequence:
              - service: telegram_bot.send_message
                data:
                  message: "{{ message }}"
                  title: "{{ title|default('', true) }}"
                  target: "{{ states('input_text.telegram_danny_chat_id') }}"
        default: []
  post_to_telegram_home_log_with_local_attachments:
    alias: Post To Slack Home Log With Local Attachments
    icon: mdi:android-messages
    description: "Post a message with a file attachment to the home_log channel."
    fields:
      message:
        description: Message to post
        required: true
      title:
        description: (optional)Header to the message posted.
      filePath:
        description: File path to attach to post.
        required: true
    sequence:
      - condition: state
        entity_id: input_boolean.enable_slack_notifications
        state: "on"
      - service: notify.slack_notify
        data:
          message: "{{ message }}"
          title: "{{ title|default('', true) }}"
          file: "{{ filePath }}"
    mode: queued
    max: 10
