# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1701033189010"
    alias: "Porch: Front Door Lock Status Change"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - lock.nuki_front_door_lock
        not_from:
          - "unlocked"
    conditions:
      - condition: state
        entity_id: binary_sensor.front_door
        state: "off"
      - condition: state
        entity_id: input_boolean.enable_front_door_lock_automations
        state: "on"
    actions:
      - choose:
          - conditions:
              - or:
                  - condition: state
                    entity_id: lock.nuki_front_door_lock
                    state: locking
                  - condition: state
                    entity_id: lock.nuki_front_door_lock
                    state: unlocking
            sequence:
              - parallel:
                  - action: script.front_door_lock_status
                    data: {}
                  - action: script.send_to_home_log
                    data:
                      message: Front door "{{ states('lock.nuki_front_door_lock') }}".
                      title: Porch
                      log_level: Normal
          - conditions:
              - or:
                  - condition: state
                    entity_id: lock.nuki_front_door_lock
                    state: locked
                  - condition: state
                    entity_id: lock.nuki_front_door_lock
                    state: unlocked
            sequence:
              - action: script.send_to_home_log
                data:
                  message: Front door "{{ states('lock.nuki_front_door_lock') }}".
                  title: Porch
                  log_level: Normal
              - action: script.turn_off
                data: {}
                target:
                  entity_id: script.front_door_lock_status
    mode: single

script:
  # Front Door
  lock_front_door:
    alias: Lock Front Door
    sequence:
      - if:
          - condition: state
            entity_id: input_boolean.enable_front_door_lock_automations
            state: "on"
        then:
          - parallel:
              - action: script.send_to_home_log
                data:
                  message: ":lock: Locking."
                  title: ":door: Front Door"
                  log_level: "Normal"
              - action: lock.lock
                data: {}
                target:
                  entity_id: lock.nuki_front_door_lock
    mode: queued
    max: 10
    icon: mdi:lock
  unlock_front_door:
    alias: Unlock Front Door
    sequence:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: ":unlock: Unlocking."
              title: ":door: Front Door"
              log_level: "Normal"
          - action: lock.unlock
            data: {}
            target:
              entity_id: lock.nuki_front_door_lock
    mode: single
    icon: mdi:lock
