# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1701033189010"
    alias: "Porch: Front Door Lock Status Change"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - lock.unified_front_door
        not_from:
          - "unlocked"
    condition:
      - condition: state
        entity_id: binary_sensor.front_door
        state: "off"
      - condition: state
        entity_id: input_boolean.enable_front_door_lock_automations
        state: "on"
    action:
      - choose:
          - conditions:
              - or:
                  - condition: state
                    entity_id: lock.unified_front_door
                    state: locking
                  - condition: state
                    entity_id: lock.unified_front_door
                    state: unlocking
            sequence:
              - parallel:
                  - service: script.front_door_lock_status
                    data: {}
                  - service: script.send_to_home_log
                    data:
                      message: Front door "{{ states('lock.unified_front_door') }}".
                      title: Porch
                      log_level: Normal
          - conditions:
              - or:
                  - condition: state
                    entity_id: lock.unified_front_door
                    state: locked
                  - condition: state
                    entity_id: lock.unified_front_door
                    state: unlocked
            sequence:
              - service: script.send_to_home_log
                data:
                  message: Front door "{{ states('lock.unified_front_door') }}".
                  title: Porch
                  log_level: Normal
              - service: script.turn_off
                data: {}
                target:
                  entity_id: script.front_door_lock_status
    mode: single

script:
  # Front Door
  lock_front_door:
    alias: Lock Front Door
    sequence:
      - if:
          - condition: state
            entity_id: input_boolean.enable_front_door_lock_automations
            state: "on"
        then:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: binary_sensor.front_door
                    state: "on"
                sequence:
                  - service: script.send_direct_notification
                    data:
                      message: ":warning: Open and cannot :lock: Lock. :warning:"
                      title: ":warning: :door: Front Door :warning:"
                      people:
                        entity_id:
                          - person.danny
                          - person.terina
              - conditions:
                  - condition: state
                    entity_id: lock.unified_front_door
                    state: "unlocked"
                sequence:
                  - choose:
                      - alias: Local lock is available
                        conditions:
                          - condition: not
                            conditions:
                              - condition: state
                                entity_id: lock.front_door
                                state: unavailable
                        sequence:
                          - parallel:
                              - service: script.send_to_home_log
                                data:
                                  message: ":lock: Locking."
                                  title: ":door: Front Door"
                                  log_level: "Normal"
                              - service: lock.lock
                                data: {}
                                target:
                                  entity_id: lock.front_door
                      - alias: Web lock is available
                        conditions:
                          - condition: not
                            conditions:
                              - condition: state
                                entity_id: lock.nuki_front_door_lock
                                state: unavailable
                        sequence:
                          - parallel:
                              - service: script.send_to_home_log
                                data:
                                  message: ":lock: Locking."
                                  title: ":door: Front Door"
                                  log_level: "Normal"
                              - service: lock.lock
                                data: {}
                                target:
                                  entity_id: lock.nuki_front_door_lock
                    default:
                      - service: script.send_direct_notification
                        data:
                          message: ":warning: Unable to lock the front door."
                          title: ":door: Front Door"
                          people:
                            entity_id:
                              - person.danny
                              - person.terina
    mode: queued
    max: 10
    icon: mdi:lock
  unlock_front_door:
    alias: Unlock Front Door
    sequence:
      - if:
          - condition: state
            entity_id: input_boolean.enable_front_door_lock_automations
            state: "on"
        then:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: lock.unified_front_door
                    state: "locked"
                sequence:
                  - choose:
                      - alias: Local lock is available
                        conditions:
                          - condition: not
                            conditions:
                              - condition: state
                                entity_id: lock.front_door
                                state: unavailable
                        sequence:
                          - parallel:
                              - service: script.send_to_home_log
                                data:
                                  message: ":unlock: Unlocking."
                                  title: ":door: Front Door"
                                  log_level: "Normal"
                              - service: lock.unlock
                                data: {}
                                target:
                                  entity_id: lock.front_door
                      - alias: Web lock is available
                        conditions:
                          - condition: not
                            conditions:
                              - condition: state
                                entity_id: lock.nuki_front_door_lock
                                state: unavailable
                        sequence:
                          - parallel:
                              - service: script.send_to_home_log
                                data:
                                  message: ":unlock: Unlocking."
                                  title: ":door: Front Door"
                                  log_level: "Normal"
                              - service: lock.unlock
                                data: {}
                                target:
                                  entity_id: lock.nuki_front_door_lock
                    default:
                      - service: script.send_to_home_log
                        data:
                          message: ":unlock: Unlocking."
                          title: ":door: Front Door"
                          log_level: "Normal"
    mode: single
    icon: mdi:lock

lock:
  - platform: template
    name: Unified Front Door Lock
    unique_id: ac45a3d0-cc1c-4b52-adb5-e6147572b210
    value_template: >-
      {{ iif(not(is_state('lock.front_door', 'unavailable')),
      states('lock.front_door'),
      states('lock.nuki_front_door_lock')) }}
    lock:
      service: lock.lock
      target:
        entity_id: >-
          {{ iif(not(is_state('lock.front_door', 'unavailable')),
          'lock.front_door',
          'lock.nuki_front_door_lock') }}
    unlock:
      service: lock.unlock
      target:
        entity_id: >-
          {{ iif(not(is_state('lock.front_door', 'unavailable')),
          'lock.front_door',
          'lock.nuki_front_door_lock') }}
