# Created by Danny Tsang <danny@tsang.uk>
sensor:
  - platform: integration
    source: sensor.office_ups_power
    name: Office UPS Energy
    unit_prefix: k
    round: 2
  - platform: integration
    source: sensor.server_ups_power
    name: Server UPS Energy
    unit_prefix: k
    round: 2
template:
  sensor:
    - name: Office UPS Power
      device_class: "power"
      unit_of_measurement: "W"
      state_class: "measurement"
      state: >
        {% if states('sensor.computer_ups_status_data') in ['OL', 'OL CHRG'] -%}
          {{ (states('sensor.computer_ups_load') | float(0) / 100) * states('sensor.computer_ups_nominal_real_power') | float(0) }}
        {%- else -%}
          0
        {%- endif %}
    - name: Server UPS Power
      device_class: "power"
      unit_of_measurement: "W"
      state_class: "measurement"
      state: >
        {% if states('sensor.server_ups_status_data') in ['OL', 'OL CHRG'] -%}
          {{ (states('sensor.server_ups_load') | float(0) / 100) * states('sensor.server_ups_nominal_real_power') | float(0) }}
        {%- else -%}
          0
        {%- endif %}
