# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://www.home-assistant.io/integrations/octoprint/
automation:
  - id: "1608655560832"
    alias: "^3D Printer: Print Started"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.octoprint_printing
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.enable_3d_printer_automations
        state: "on"
    action:
      - parallel:
          - service: switch.turn_on
            target:
              entity_id: switch.prusa_fan
          - service: script.send_to_home_log
            data:
              message: "Printer priming. Turning on extruder :dash: fan."
              title: ":printer: :black_square_button: 3D printer"
          - wait_for_trigger:
              - platform: numeric_state
                entity_id: sensor.octoprint_estimated_finish_time
                above: "0"
            timeout: "60"
          - service: script.send_to_home_log
            data:
              message: "Printer started. Estimated time to completion:
                {{ states('sensor.octoprint_estimated_finish_time') }}."
              title: ":printer: :black_square_button: 3D printer"
          - choose:
              - conditions:
                  - condition: sun
                    after: sunset
                sequence:
                  - service: script.send_to_home_log
                    data:
                      message:
                        ":city_sunset: Printing started after sunset. Turning
                        Printer :high_brightness: :bulb: light on."
                      title: ":printer: :black_square_button: 3D printer"
                  - service: scene.turn_on
                    target:
                      entity_id: scene.3d_printer_light_on
              - conditions:
                  - condition: sun
                    before: sunrise
                sequence:
                  - service: script.send_to_home_log
                    data:
                      message:
                        ":city_sunset: Printing started before sunrise. Turning
                        Printer :high_brightness: :bulb: light on."
                      title: ":printer: :black_square_button: 3D printer"
                  - service: scene.turn_on
                    target:
                      entity_id: scene.3d_printer_light_on
              - conditions:
                  - condition: sun
                    after: sunrise
                    before: sunset
                  - condition: state
                    entity_id: light.prusa
                    state: "on"
                sequence:
                  - service: script.send_to_home_log
                    data:
                      message: ":sunny: Printing started during the day. Turning
                        Printer light off."
                      title: ":printer: :black_square_button: 3D printer"
                  - service: scene.turn_on
                    target:
                      entity_id: scene.3d_printer_light_off
            default:
              - service: script.send_to_home_log
                data:
                  message:
                    ":sunrise: Printing started after sunrise. Not turning
                    on printer light."
                  title: ":printer: :black_square_button: 3D printer"
              - service: scene.turn_on
                target:
                  entity_id: scene.3d_printer_light_off
    mode: single
  - id: "1619873649348"
    alias: "^3D Printer: 50% Complete"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.octoprint_job_percentage
        above: "50"
    condition:
      - condition: state
        entity_id: input_boolean.enable_3d_printer_automations
        state: "on"
    action:
      - service: script.send_to_home_log
        data:
          message: "50% complete and due to finish at {{ states('sensor.octoprint_estimated_finish_time') }}."
          title: ":printer: :black_square_button: 3D printer"
    mode: single
  - id: "1623087278802"
    alias: "^3D Printer: Check If Printing Light"
    description: ""
    trigger:
      - platform: time_pattern
        hours: "*"
        seconds: "*"
        minutes: "/30"
      - platform: sun
        event: sunset
        id: sunset
      - platform: sun
        event: sunrise
    condition:
      - condition: state
        entity_id: light.prusa
        state: "on"
    action:
      - service: script.3d_printer_check_light
    mode: single
  - id: "1613321560216"
    alias: "^3D Printer: Finished Printing"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.octoprint_printing
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.enable_3d_printer_automations
        state: "on"
    action:
      - service: script.send_to_home_log
        data:
          message: >-
            :white_check_mark: Completed 3D printing which
            started {{states('sensor.octoprint_start_time')}}
          title: ":printer: :black_square_button: 3D printer"
    mode: single
  - id: "1656239435552"
    alias: "^3D Printer: Light Turned on"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - light.prusa
        to: "on"
        for:
          hours: 0
          minutes: 5
          seconds: 0
    condition:
      - condition: state
        entity_id: input_boolean.enable_3d_printer_automations
        state: "on"
    action:
      - service: script.3d_printer_check_light
        data: {}
    mode: single

scene:
  - id: "1623014393915"
    name: 3D Printer Light Off
    entities:
      light.prusa:
        min_mireds: 153
        max_mireds: 65535
        effect_list:
          - colorloop
          - random
        supported_color_modes:
          - color_temp
          - hs
        friendly_name: Prusa
        icon: mdi:led-strip-variant
        supported_features: 63
        state: "off"
    icon: mdi:lightbulb
  - id: "1623014429001"
    name: 3D Printer Light On
    entities:
      light.prusa:
        min_mireds: 153
        max_mireds: 65535
        effect_list:
          - colorloop
          - random
        supported_color_modes:
          - color_temp
          - hs
        color_mode: color_temp
        brightness: 251
        color_temp: 153
        hs_color:
          - 54.768
          - 1.6
        rgb_color:
          - 255
          - 254
          - 250
        xy_color:
          - 0.326
          - 0.333
        effect: none
        friendly_name: Prusa
        icon: mdi:led-strip-variant
        supported_features: 63
        state: "on"
    icon: mdi:lightbulb
  - id: "1627724282263"
    name: 3D Printer Temperature Reached
    entities:
      light.prusa:
        min_mireds: 153
        max_mireds: 65535
        effect_list:
          - colorloop
          - random
        supported_color_modes:
          - color_temp
          - hs
        color_mode: hs
        brightness: 251
        hs_color:
          - 120
          - 100
        rgb_color:
          - 0
          - 255
          - 0
        xy_color:
          - 0.172
          - 0.747
        effect: none
        friendly_name: Prusa
        icon: mdi:led-strip-variant
        supported_features: 63
        state: "on"

script:
  3d_printer_left_unattended:
    alias: 3D Printer Left Unattended
    sequence:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.octoprint_estimated_finish_time
            state: unknown
          - condition: state
            entity_id: binary_sensor.octoprint_printing
            state: "on"
      - service: script.send_direct_notification
        data:
          message:
            ":printer: 3D printer is printing and no one is :house_with_garden:
            home."
          title: ":printer: :black_square_button: 3D printer"
          people:
            - "person.danny"
            - "person.terina"
    mode: single
    icon: mdi:printer-3d
  3d_printer_check_light:
    alias: 3D Printer Check Light
    sequence:
      - parallel:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: light.prusa
                    state: "on"
                  - condition: state
                    entity_id: sensor.octoprint_current_state
                    state: "unavailable"
                sequence:
                  - service: script.send_to_home_log
                    data:
                      message: "Printer is offline. Turning light off."
                      title: ":printer: :black_square_button: 3D printer"
                  - service: scene.turn_on
                    target:
                      entity_id: scene.3d_printer_light_off
              - conditions:
                  - condition: state
                    entity_id: light.prusa
                    state: "off"
                  - condition: numeric_state
                    entity_id: sensor.conservatory_motion_light_level
                    below: "100"
                sequence:
                  - service: script.send_to_home_log
                    data:
                      message:
                        ":city_sunset: :printer: It's getting dark and it's printing.
                        Turning :high_brightness: :bulb: lights on."
                      title: ":printer: :black_square_button: 3D printer"
                  - service: scene.turn_on
                    target:
                      entity_id: scene.3d_printer_light_on
              - conditions:
                  - condition: state
                    entity_id: light.prusa
                    state: "on"
                  - condition: numeric_state
                    entity_id: sensor.conservatory_motion_light_level
                    above: "100"
                sequence:
                  - service: script.send_to_home_log
                    data:
                      message:
                        ":city_sunrise: It's getting bright and it's printing.
                        Turning lights off."
                      title: ":printer: :black_square_button: 3D printer"
                  - service: scene.turn_on
                    target:
                      entity_id: scene.3d_printer_light_off
              - conditions:
                  - condition: state
                    entity_id: light.prusa
                    state: "off"
                  - condition: trigger
                    id: sunset
                sequence:
                  - service: script.send_to_home_log
                    data:
                      message:
                        ":city_sunset: :printer: Sun is setting and it's printing.
                        Turning :high_brightness: :bulb: lights on."
                      title: ":printer: :black_square_button: 3D printer"
                  - service: scene.turn_on
                    target:
                      entity_id: scene.3d_printer_light_on
            default: []
    mode: single
    icon: mdi:printer-3d
