# Created by Danny Tsang <danny@tsang.uk>
camera:
  - platform: mjpeg
    name: OctoPrint
    still_image_url: !secret octoprint_stream_url
    mjpeg_url: !secret octoprint_stream_url
automation:
  - id: "1608655560832"
    alias: "^3D Printer: Print Started"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.octoprint_printing
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.enable_3d_printer_automations
        state: "on"
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.prusa_fan
      - service: script.post_to_home_log
        data:
          message: ":printer: 3D printer is priming. Turning on extruder :dash: fan."
      - wait_for_trigger:
          - platform: numeric_state
            entity_id: sensor.octoprint_estimated_finish_time
            above: "0"
        timeout: "60"
      - service: script.post_to_home_log
        data:
          message:
            ":printer: 3D printer has started. Estimated time to completion:
            {{ states('sensor.octoprint_estimated_finish_time') }}."
      - choose:
          - conditions:
              - condition: sun
                after: sunset
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":printer: :city_sunset: Printing started after sunset. Turning
                    Printer light on."
              - service: scene.turn_on
                target:
                  entity_id: scene.3d_printer_light_on
          - conditions:
              - condition: sun
                before: sunrise
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":printer: :city_sunset: Printing started before sunrise. Turning
                    Printer light on."
              - service: scene.turn_on
                target:
                  entity_id: scene.3d_printer_light_on
          - conditions:
              - condition: sun
                after: sunrise
                before: sunset
              - condition: state
                entity_id: light.prusa
                state: "on"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":printer: :sunny: Printing started during the day. Turning
                    Printer light off."
              - service: scene.turn_on
                target:
                  entity_id: scene.3d_printer_light_off
        default:
          - service: script.post_to_home_log
            data:
              message:
                ":printer: :sunrise: Printing started after sunrise. Not turning
                on printer light."
          - service: scene.turn_on
            target:
              entity_id: scene.3d_printer_light_off
    mode: single
  - id: "1619873649348"
    alias: "^3D Printer: 50% Complete"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.octoprint_job_percentage
        above: "50"
    condition:
      - condition: state
        entity_id: input_boolean.enable_3d_printer_automations
        state: "on"
    action:
      - service: script.post_to_home_log
        data:
          message: "3D printer is 50% complete and due to finish at {{ states('sensor.octoprint_estimated_finish_time') }}."
    mode: single
  - id: "1623087278802"
    alias: "^3D Printer: Check If Printing Light"
    description: ""
    trigger:
      - platform: time_pattern
        hours: "*"
        seconds: "*"
        minutes: "/30"
      - platform: sun
        event: sunset
        id: sunset
      - platform: sun
        event: sunrise
    condition:
      - condition: state
        entity_id: binary_sensor.octoprint_printing
        state: "on"
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.octoprint_current_state
            state: "unavailable"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: light.prusa
                state: "off"
              - condition: numeric_state
                entity_id: sensor.conservatory_motion_light_level
                below: "100"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":city_sunset: :printer: It's getting dark and 3D printer is printing.
                    Turning :bulb: lights on."
              - service: scene.turn_on
                target:
                  entity_id: scene.3d_printer_light_on
          - conditions:
              - condition: state
                entity_id: light.prusa
                state: "on"
              - condition: numeric_state
                entity_id: sensor.conservatory_motion_light_level
                above: "100"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":city_sunrise: :printer: It's getting bright and 3D printer is printing.
                    Turning lights off."
              - service: scene.turn_on
                target:
                  entity_id: scene.3d_printer_light_off
          - conditions:
              - condition: state
                entity_id: light.prusa
                state: "off"
              - condition: trigger
                id: sunset
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":city_sunset: :printer: Sun is setting and 3D printer is printing.
                    Turning :bulb: lights on."
              - service: scene.turn_on
                target:
                  entity_id: scene.3d_printer_light_on
        default: []
    mode: single
  - id: "1613321560216"
    alias: "^3D Printer: Finished Printing"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.octoprint_printing
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.enable_3d_printer_automations
        state: "on"
    action:
      - service: script.post_to_home_log
        data:
          message: ":printer: :white_check_mark: Completed 3D printing which 
          started {{states('sensor.octoprint_start_time')}}"
    mode: single
input_boolean:
  enable_3d_printer_automations:
    name: Enable 3D printer automations
    icon: mdi:printer-3d
  enable_octoprint_automations:
    name: Enable Octoprint automations
    icon: mdi:printer-3d
scene:
  - id: "1623014393915"
    name: 3D Printer Light Off
    entities:
      light.prusa:
        min_mireds: 153
        max_mireds: 65535
        effect_list:
          - colorloop
          - random
        supported_color_modes:
          - color_temp
          - hs
        friendly_name: Prusa
        icon: mdi:led-strip-variant
        supported_features: 63
        state: "off"
    icon: mdi:lightbulb
  - id: "1623014429001"
    name: 3D Printer Light On
    entities:
      light.prusa:
        min_mireds: 153
        max_mireds: 65535
        effect_list:
          - colorloop
          - random
        supported_color_modes:
          - color_temp
          - hs
        color_mode: color_temp
        brightness: 251
        color_temp: 153
        hs_color:
          - 54.768
          - 1.6
        rgb_color:
          - 255
          - 254
          - 250
        xy_color:
          - 0.326
          - 0.333
        effect: none
        friendly_name: Prusa
        icon: mdi:led-strip-variant
        supported_features: 63
        state: "on"
    icon: mdi:lightbulb
  - id: "1627724282263"
    name: 3D Printer Temperature Reached
    entities:
      light.prusa:
        min_mireds: 153
        max_mireds: 65535
        effect_list:
          - colorloop
          - random
        supported_color_modes:
          - color_temp
          - hs
        color_mode: hs
        brightness: 251
        hs_color:
          - 120
          - 100
        rgb_color:
          - 0
          - 255
          - 0
        xy_color:
          - 0.172
          - 0.747
        effect: none
        friendly_name: Prusa
        icon: mdi:led-strip-variant
        supported_features: 63
        state: "on"