# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1744064001680"
    alias: "People: Update Danny's Owntracks"
    description: "https://devblog.yvn.no/posts/replacing-maps-timeline-with-owntracks/"
    triggers:
      - trigger: state
        entity_id:
          - device_tracker.danny_s_phone
    conditions: []
    actions:
      - action: mqtt.publish
        metadata: {}
        data:
          topic: owntracks/danny/iphone
          payload: |
            {
              "_type": "location",
              "t": "p",
              "tid": "ha",
              "lat": {{ state_attr('device_tracker.danny_s_phone', 'latitude') }},
              "lon": {{ state_attr('device_tracker.danny_s_phone', 'longitude') }},
              "alt": {{ state_attr('device_tracker.danny_s_phone', 'altitude') | default(0) }},
              "vac": {{ state_attr('device_tracker.danny_s_phone', 'vertical_accuracy') | default(0) }},
              "acc": {{ state_attr('device_tracker.danny_s_phone', 'gps_accuracy') | default(0) }},
              "vel": {{ state_attr('device_tracker.danny_s_phone', 'speed') | default(0) }},
              "cog": {{ state_attr('device_tracker.danny_s_phone', 'course') | default(0) }},
              "tst": {{ now().timestamp() | int }}
            }
          retain: true
    mode: single
  - id: "1744064001681"
    alias: "People: Update Terina's Owntracks"
    description: "https://devblog.yvn.no/posts/replacing-maps-timeline-with-owntracks/"
    triggers:
      - trigger: state
        entity_id:
          - device_tracker.oneplus_10
    conditions: []
    actions:
      - action: mqtt.publish
        metadata: {}
        data:
          topic: owntracks/terina/oneplus
          payload: |
            {
              "_type": "location",
              "t": "p",
              "tid": "ha",
              "lat": {{ state_attr('device_tracker.oneplus_10', 'latitude') }},
              "lon": {{ state_attr('device_tracker.oneplus_10', 'longitude') }},
              "alt": {{ state_attr('device_tracker.oneplus_10', 'altitude') | default(0) }},
              "vac": {{ state_attr('device_tracker.oneplus_10', 'vertical_accuracy') | default(0) }},
              "acc": {{ state_attr('device_tracker.oneplus_10', 'gps_accuracy') | default(0) }},
              "vel": {{ state_attr('device_tracker.oneplus_10', 'speed') | default(0) }},
              "cog": {{ state_attr('device_tracker.oneplus_10', 'course') | default(0) }},
              "tst": {{ now().timestamp() | int }}
            }
          retain: true
    mode: single
  - id: "1744064001682"
    alias: "People: Update Leo's Owntracks"
    description: "https://devblog.yvn.no/posts/replacing-maps-timeline-with-owntracks/"
    triggers:
      - trigger: state
        entity_id:
          - device_tracker.leos_iphone
    conditions: []
    actions:
      - action: mqtt.publish
        metadata: {}
        data:
          topic: owntracks/leo/iphone
          payload: |
            {
              "_type": "location",
              "t": "p",
              "tid": "ha",
              "lat": {{ state_attr('device_tracker.leos_iphone', 'latitude') }},
              "lon": {{ state_attr('device_tracker.leos_iphone', 'longitude') }},
              "alt": {{ state_attr('device_tracker.leos_iphone', 'altitude') | default(0) }},
              "vac": {{ state_attr('device_tracker.leos_iphone', 'vertical_accuracy') | default(0) }},
              "acc": {{ state_attr('device_tracker.leos_iphone', 'gps_accuracy') | default(0) }},
              "vel": {{ state_attr('device_tracker.leos_iphone', 'speed') | default(0) }},
              "cog": {{ state_attr('device_tracker.leos_iphone', 'course') | default(0) }},
              "tst": {{ now().timestamp() | int }}
            }
          retain: true
    mode: single
