# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1687019771710"
    alias: "Paperless: New Document"
    description: ""
    triggers:
      - trigger: webhook
        allowed_methods:
          - POST
        local_only: false
        webhook_id: 5dc5fc04-365e-4834-97e9-c6967bda3909
    conditions: []
    actions:
      - action: script.send_direct_notification
        data:
          message: >-
            New document ({{trigger.json['id']}}) {{trigger.json['name']}} from
            {{trigger.json['correspondent']}}.

            Download: {{trigger.json['download_url']}}
            Tags: {{trigger.json['tags']}}
          title: ":leaves: Paperless"
          people:
            entity_id:
              - person.danny
    mode: queued
    max: 10

sensor:
  # https://flemmingss.com/monitoring-paperless-ngx-in-home-assistant/
  - platform: rest
    name: Paperless-NGX - Total documents In Inbox
    resource: !secret paperless_inbox_url
    method: GET
    headers:
      Authorization: !secret paperless_inbox_token
    value_template: "{{ value_json.document_count }}"
    scan_interval: 300
