# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://www.home-assistant.io/integrations/pi_hole/
automation:
  - id: "1630082312356"
    alias: "PiHole: Change Status"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - switch.pi_hole
          - switch.pi_hole_2
          - switch.pi_holes
    condition: []
    actions:
      - action: script.send_to_home_log
        data:
          message: "Network filtering on {{ trigger.to_state.name }} has
            been turned {{ trigger.to_state.state }}."
          title: ":pie: :hole: Pi-Hole"
          log_level: "Normal"
    mode: single

template:
  - sensor:
      # Pi Hole totals from different entities
      - name: "Pi-Hole Total Ads Blocked Today"
        unique_id: 201ad303-1412-40c9-a831-4dd7eacce68f
        state: >-
          {{ states('sensor.pi_hole_ads_blocked_today') | default(0) | int +
          states('sensor.pi_hole_2_ads_blocked_today') | default(0) | int }}
        availability: "{{ states('sensor.pi_hole_ads_blocked_today')|is_number and states('sensor.pi_hole_2_ads_blocked_today')|is_number }}"
        unit_of_measurement: "ads"

      - name: "Pi-Hole Total Ads Percentage Blocked Today"
        unique_id: a95ef6dd-ff9e-4ae2-afb9-fd6bf845ad3a
        state: >-
          {{ states('sensor.pi_hole_ads_percentage_blocked_today') | default(0) | int +
          states('sensor.pi_hole_2_ads_percentage_blocked_today') | default(0) | int / 2 | float }}
        availability: "{{ states('sensor.pi_hole_ads_percentage_blocked_today')|is_number and states('sensor.pi_hole_2_ads_percentage_blocked_today')|is_number }}"
        unit_of_measurement: "%"
      - name: "Pi-Hole Total DNS Queries Cached"
        unique_id: d65c0775-15d3-4e49-bd59-10c348c3b255
        state: >-
          {{ states('sensor.pi_hole_dns_queries_cached') | default(0) | int +
          states('sensor.pi_hole_2_dns_queries_cached') | default(0) | int }}
        availability: "{{ states('sensor.pi_hole_dns_queries_cached')|is_number and states('sensor.pi_hole_2_dns_queries_cached')|is_number }}"
        unit_of_measurement: "queries"
      - name: "Pi-Hole Total DNS Queries Forwarded"
        unique_id: 1fb2c8b9-25e2-456b-985b-ea20e9e0a456
        state: >-
          {{ states('sensor.pi_hole_dns_queries_forwarded') | default(0) | int +
          states('sensor.pi_hole_2_dns_queries_forwarded') | default(0) | int }}
        availability: "{{ states('sensor.pi_hole_dns_queries_forwarded')|is_number and states('sensor.pi_hole_2_dns_queries_forwarded')|is_number }}"
        unit_of_measurement: "queries"
      - name: "Pi-Hole Total DNS Queries Today"
        unique_id: caa2b6ce-fbc5-4351-b0e2-55cfcd0b1020
        state: >-
          {{ states('sensor.pi_hole_dns_queries_today') | default(0) | int +
          states('sensor.pi_hole_2_dns_queries_today') | default(0) | int }}
        availability: "{{ states('sensor.pi_hole_dns_queries_today')|is_number and states('sensor.pi_hole_2_dns_queries_today')|is_number }}"
        unit_of_measurement: "queries"
      - name: "Pi-Hole Total DNS Unique Clients"
        unique_id: 7c0a55e3-2f79-4ebf-8d51-76e70ffd053f
        state: >-
          {{ states('sensor.pi_hole_dns_unique_clients') | default(0) | int +
          states('sensor.pi_hole_2_dns_unique_clients') | default(0) | int }}
        availability: "{{ states('sensor.pi_hole_dns_unique_clients')|is_number and states('sensor.pi_hole_2_dns_unique_clients')|is_number }}"
        unit_of_measurement: "clients"
      - name: "Pi-Hole Total DNS Unique Domains"
        unique_id: ebeb498f-0417-4066-8a4f-a725e763118c
        state: >-
          {{ states('sensor.pi_hole_dns_unique_domains') | default(0) | int +
          states('sensor.pi_hole_2_dns_unique_domains') | default(0) | int }}
        availability: "{{ states('sensor.pi_hole_dns_unique_domains')|is_number and states('sensor.pi_hole_2_dns_unique_domains')|is_number }}"
        unit_of_measurement: "domains"
      - name: "Pi-Hole Total Domains Blocked"
        unique_id: f9443abd-23aa-497a-b1ba-c759629cd32e
        state: >-
          {{ states('sensor.pi_hole_domains_blocked') | default(0) | int +
          states('sensor.pi_hole_2_domains_blocked') | default(0) | int }}
        availability: "{{ states('sensor.pi_hole_domains_blocked')|is_number and states('sensor.pi_hole_2_domains_blocked')|is_number }}"
        unit_of_measurement: "domains"
      - name: "Pi-Hole Total Seen Clients"
        unique_id: 5bcfe2e8-1c3d-4fd0-92b5-b0e06ae93546
        state: >-
          {{ states('sensor.pi_hole_seen_clients') | default(0) | int +
          states('sensor.pi_hole_2_seen_clients') | default(0) | int }}
        availability: "{{ states('sensor.pi_hole_seen_clients')|is_number and states('sensor.pi_hole_2_seen_clients')|is_number }}"
        unit_of_measurement: "clients"
