# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1657231864164"
    alias: "Plant: Spider Plant Needs Fertiliser"
    description: ""
    triggers:
      - trigger: numeric_state
        entity_id: sensor.chlorophytum_comosum_soil_conductivity
        below: "201"
    conditions:
      - condition: state
        entity_id: input_boolean.enable_plant_notifications
        state: "on"
    actions:
      - parallel:
          - action: script.send_direct_notification
            data:
              message: ":droplet: :wilted_flower: Needs fertilising."
              title: ":sunflower: Spider plant"
              people:
                entity_id:
                  - person.danny
                  - person.terina
    mode: single
  - id: "1657231864166"
    alias: "Plant: Spider Plant Needs Watering"
    description: ""
    triggers:
      - trigger: numeric_state
        entity_id: sensor.chlorophytum_comosum_moisture
        below: "16"
    conditions:
      - condition: state
        entity_id: input_boolean.enable_plant_notifications
        state: "on"
    actions:
      - parallel:
          - action: script.send_direct_notification
            data:
              message: ":droplet: :wilted_flower: Needs watering."
              title: ":sunflower: Spider plant"
              people:
                entity_id:
                  - person.danny
                  - person.terina
    mode: single
  - id: "1657231864165"
    alias: "Plant: Snake Plant Needs Fertiliser"
    description: ""
    triggers:
      - trigger: numeric_state
        entity_id: sensor.sansevieria_trifasciata_soil_conductivity
        below: "301"
    conditions:
      - condition: state
        entity_id: input_boolean.enable_plant_notifications
        state: "on"
    actions:
      - parallel:
          - action: script.send_direct_notification
            data:
              message: ":droplet: :wilted_flower: Needs fertilising."
              title: ":sunflower: Snake plant"
              people:
                entity_id:
                  - person.danny
                  - person.terina
    mode: single
  - id: "1657231864167"
    alias: "Plant: Snake Plant Needs Watering"
    description: ""
    triggers:
      - trigger: numeric_state
        entity_id: sensor.sansevieria_trifasciata_moisture
        below: "8"
    conditions:
      - condition: state
        entity_id: input_boolean.enable_plant_notifications
        state: "on"
    actions:
      - parallel:
          - action: script.send_direct_notification
            data:
              message: ":droplet: :wilted_flower: Needs watering."
              title: ":sunflower: Snake plant"
              people:
                entity_id:
                  - person.danny
                  - person.terina
    mode: single
