# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1657231864164"
    alias: "Plant: Spider Plant Needs Fertiliser"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.chlorophytum_comosum_soil_conductivity
        below: "201"
    condition:
      - condition: state
        entity_id: input_boolean.enable_plant_notifications
        state: "on"
    action:
      - parallel:
          - service: script.send_direct_notification
            data:
              message: ":droplet: :wilted_flower: Needs fertilising."
              title: ":sunflower: Spider plant"
          - service: script.send_to_home_log
            data:
              message: ":droplet: :wilted_flower: Needs fertilising."
              title: ":sunflower: Spider plant"
    mode: single
  - id: "1657231864166"
    alias: "Plant: Spider Plant Needs Watering"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.chlorophytum_comosum_moisture
        below: "16"
    condition:
      - condition: state
        entity_id: input_boolean.enable_plant_notifications
        state: "on"
    action:
      - parallel:
          - service: script.send_direct_notification
            data:
              message: ":droplet: :wilted_flower: Needs watering."
              title: ":sunflower: Spider plant"
          - service: script.send_to_home_log
            data:
              message: ":droplet: :wilted_flower: Needs watering."
              title: ":sunflower: Spider plant"
    mode: single
  - id: "1657231864165"
    alias: "Plant: Snake Plant Needs Fertiliser"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.sansevieria_trifasciata_soil_conductivity
        below: "301"
    condition:
      - condition: state
        entity_id: input_boolean.enable_plant_notifications
        state: "on"
    action:
      - parallel:
          - service: script.send_direct_notification
            data:
              message: ":droplet: :wilted_flower: Needs fertilising."
              title: ":sunflower: Snake plant"
          - service: script.send_to_home_log
            data:
              message: ":droplet: :wilted_flower: Needs fertilising."
              title: ":sunflower: Snake plant"
    mode: single
  - id: "1657231864167"
    alias: "Plant: Snake Plant Needs Watering"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.sansevieria_trifasciata_moisture
        below: "8"
    condition:
      - condition: state
        entity_id: input_boolean.enable_plant_notifications
        state: "on"
    action:
      - parallel:
          - service: script.send_direct_notification
            data:
              message: ":droplet: :wilted_flower: Needs watering."
              title: ":sunflower: Snake plant"
          - service: script.send_to_home_log
            data:
              message: ":droplet: :wilted_flower: Needs watering."
              title: ":sunflower: Snake plant"
    mode: single
