# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://www.home-assistant.io/integrations/roku/
automation:
  # Roku: Bedroom
  - id: "1612998168527"
    alias: "Bedroom: Roku Stick Playing"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.bedroom_roku_streaming_stick
        to: playing
    condition: []
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: >-
                  {{ state_attr('media_player.bedroom_roku_streaming_stick','media_position') !=
                  none and
                  state_attr('media_player.bedroom_roku_streaming_stick','media_duration') !=
                  none}}
            sequence:
              - service: camera.snapshot
                target:
                  entity_id: camera.bedroom_tv
                data:
                  filename: "{{ states('input_text.camera_external_folder_path') }}{{ states('input_text.latest_hyperion_bedroom_tv_file_path') }}"
              - delay:
                  seconds: 2
              - service: script.send_home_log_with_local_attachments
                data:
                  title: "Bedroom Roku started playing"
                  message: >-
                    :tv: Bedroom Roku playing
                    {{ state_attr('media_player.bedroom_roku_streaming_stick', 'app_name') }} and is at
                    {{ state_attr('media_player.bedroom_roku_streaming_stick', 'media_position') |
                    int | timestamp_custom('%H:%M:%S') }}/{{ state_attr('media_player.bedroom_roku_streaming_stick', 'media_duration') |
                    int | timestamp_custom('%H:%M:%S') }} ({{ ((state_attr('media_player.bedroom_roku_streaming_stick',
                    'media_position') | int / state_attr('media_player.bedroom_roku_streaming_stick',
                    'media_duration') | int) * 100) | round(2, 'common') }}%) way through.
                  filePath: "{{ states('input_text.camera_external_folder_path') }}{{ states('input_text.latest_hyperion_bedroom_tv_file_path') }}"
        default:
          - service: camera.snapshot
            target:
              entity_id: camera.bedroom_tv
            data:
              filename: "{{ states('input_text.camera_external_folder_path') }}{{ states('input_text.latest_hyperion_bedroom_tv_file_path') }}"
          - delay:
              seconds: 2
          - service: script.send_home_log_with_local_attachments
            data:
              title: "Bedroom Roku started playing"
              message: ":tv: Bedroom Roku playing {{ state_attr('media_player.bedroom_roku_streaming_stick', 'app_name') }}"
              filePath: "{{ states('input_text.camera_external_folder_path') }}{{ states('input_text.latest_hyperion_bedroom_tv_file_path') }}"
    mode: queued
    max: 10
  - id: "1612998400191"
    alias: "Bedroom: Roku Stick Turned Off"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.bedroom_roku_streaming_stick
        to: idle
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: ":tv: Bedroom Roku turned off."
    mode: queued
    max: 10
  - id: "1617813522258"
    alias: "Bedroom: Roku Paused"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.bedroom_roku_streaming_stick
        to: paused
    condition: []
    action:
      - service: camera.snapshot
        target:
          entity_id: camera.bedroom_tv
        data:
          filename: "{{ states('input_text.camera_external_folder_path') }}{{ states('input_text.latest_hyperion_bedroom_tv_file_path') }}"
      - service: script.hyperion_notification
        data:
          entity_id: trigger.entity_id
          display_state: "paused"
    mode: queued
    max: 10
  # Roku: Lounge
  - id: "1612998168526"
    alias: "Lounge: Roku Stick Playing"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.lounge_roku_streaming_stick
        to: playing
    condition: []
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: >-
                  {{ state_attr('media_player.lounge_roku_streaming_stick','media_position') !=
                  none and
                  state_attr('media_player.lounge_roku_streaming_stick','media_duration') !=
                  none}}
            sequence:
              - service: camera.snapshot
                target:
                  entity_id: camera.lounge_tv
                data:
                  filename: "{{ states('input_text.camera_external_folder_path') }}{{ states('input_text.latest_hyperion_lounge_tv_file_path') }}"
              - delay:
                  seconds: 2
              - service: script.send_home_log_with_local_attachments
                data:
                  message: >-
                    :tv: Lounge Roku playing {{ state_attr('media_player.lounge_roku_streaming_stick', 'app_name') }}
                    and is at {{ state_attr('media_player.lounge_roku_streaming_stick', 'media_position') |
                    int | timestamp_custom('%H:%M:%S') }}/{{ state_attr('media_player.lounge_roku_streaming_stick', 'media_duration') |
                    int | timestamp_custom('%H:%M:%S') }} ({{ ((state_attr('media_player.lounge_roku_streaming_stick',
                    'media_position') | int / state_attr('media_player.lounge_roku_streaming_stick',
                    'media_duration') | int) * 100) | round(2, 'common') }}%) way through.
                  title: "Lounge Roku started playing"
                  filePath: "{{ states('input_text.camera_external_folder_path') }}{{ states('input_text.latest_hyperion_lounge_tv_file_path') }}"
        default:
          - service: camera.snapshot
            target:
              entity_id: camera.lounge_tv
            data:
              filename: "{{ states('input_text.camera_external_folder_path') }}{{ states('input_text.latest_hyperion_lounge_tv_file_path') }}"
          - delay:
              seconds: 2
          - service: script.send_home_log_with_local_attachments
            data:
              message: ":tv: Lounge Roku playing {{ state_attr('media_player.lounge_roku_streaming_stick', 'app_name') }}"
              title: "Lounge Roku started playing"
              filePath: "{{ states('input_text.camera_external_folder_path') }}{{ states('input_text.latest_hyperion_lounge_tv_file_path') }}"
    mode: queued
    max: 10
  - id: "1612998400190"
    alias: "Lounge: Roku Stick Turned Off"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - media_player.lounge_roku_streaming_stick
          - media_player.bedroom_roku_streaming_stick
        to: idle
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: ":tv: Lounge Roku turned off."
    mode: queued
    max: 10
  - id: "1617813522257"
    alias: "Lounge: Roku Paused"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.lounge_roku_streaming_stick
        to: paused
    condition: []
    action:
      - service: camera.snapshot
        target:
          entity_id: camera.lounge_tv
        data:
          filename: "{{ states('input_text.camera_external_folder_path') }}{{ states('input_text.latest_hyperion_lounge_tv_file_path') }}"
      - service: script.hyperion_notification
        data:
          entity_id: trigger.entity_id
          display_state: "paused"
    mode: queued
    max: 10
  # Common
  - id: "1613051229066"
    alias: "Roku Turned On"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - media_player.lounge_roku_streaming_stick
          - media_player.bedroom_roku_streaming_stick
        to: "on"
    condition: []
    action:
      - service: camera.snapshot
        target:
          entity_id: camera.lounge_tv
        data:
          filename: "{{ states('input_text.camera_external_folder_path') }}{{ states('input_text.latest_hyperion_lounge_tv_file_path') }}"
      - service: script.hyperion_notification
        data:
          entity_id: trigger.entity_id
          display_state: "turned on"
    mode: queued
    max: 10

script:
  roku_turned_basic_notification:
    alias: Roku Turned On Notification
    fields:
      entity_id:
        description: Entity ID of the Roku player.
        required: true
      display_state:
        description: The friendly state in text.
        required: true
        example: "'turned on', 'paused', etc"
    variables:
      title: "{{ ':couch_and_lamp: Lounge' if (entity_id|default('')) == 'media_player.lounge_roku_streaming_stick' else ':bed: Bedroom' }}"
      file_path: "{{ states('input_text.latest_hyperion_lounge_tv_file_path') if entity_id|default('') == 'media_player.lounge_roku_streaming_stick' else states('input_text.latest_hyperion_bedroom_tv_file_path') }}"
    sequence:
      - delay:
          seconds: 2
      - service: script.send_home_log_with_local_attachments
        data:
          message: "Roku {{ display_state }}."
          title: "{{ title }}"
          filePath: "{{ states('input_text.camera_external_folder_path') }}{{ file_path }}"
    mode: queued
    max: 10
