# Created by Danny Tsang <danny@tsang.uk>
# Possible states: https://docs.sleep.urbandroid.org/services/automation.html#events
automation:
  # General
  - id: "1614285576722"
    alias: "^Sleep As Android: Event"
    description: ""
    trigger:
      - platform: webhook
        webhook_id: sleep_as_android
    condition: []
    action:
      - parallel:
          - service: input_text.set_value
            entity_id: input_text.sleep_as_android
            data:
              value: "{{ trigger.json.event }}"
          - choose:
              - conditions:
                  - condition: state
                    entity_id: input_select.sleep_as_android_notification_level
                    state: "Start/Stop"
                  - condition: template
                    value_template: "{{ trigger.json.event in ['sleep_tracking_started', 'sleep_tracking_stopped'] }}"
                sequence:
                  - service: script.send_to_home_log
                    data:
                      message: "Changed to {{ trigger.json.event }}"
                      title: ":zzz: Sleep as :robot_face: Android"
              - conditions:
                  - condition: state
                    entity_id: input_select.sleep_as_android_notification_level
                    state: "All"
                sequence:
                  - service: script.send_to_home_log
                    data:
                      message: "Changed to {{ trigger.json.event }}"
                      title: ":zzz: Sleep as :robot_face: Android"
            default: []
    mode: queued
    max: 10
  # Sleep Timer
  - id: "1658438667856"
    alias: "^Sleep As Android: Started Tracking"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - input_text.sleep_as_android
        to: sleep_tracking_started
    condition: []
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: person.danny
                state: home
            sequence:
              - parallel:
                - service: timer.start
                  data:
                    duration: "{% set new_ts = states('input_number.sleep_timer_duration')|int(60) * 60 %}
                    {{ '{:02d}:{:02d}:{:02d}'.format(new_ts // 3600, (new_ts % 3600) // 60, (new_ts % 3600) % 60) }}"
                  target:
                    entity_id: timer.sleep
                - service: script.send_to_home_log
                  data:
                    message: "Sleep :hourglass_flowing_sand: timer :arrow_forward: started. Time remaining:
                      {{ state_attr('timer.sleep', 'remaining') }}"
                    title: ":zzz: Sleep as :robot_face: Android"
        default: []
    mode: single
  - id: "1658843567854"
    alias: "^Sleep As Android: Awake"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - input_text.sleep_as_android
        to: awake
    condition:
      - condition: state
        entity_id: timer.sleep
        state: active
    action:
      - parallel:
        - service: timer.pause
          data: {}
          target:
            entity_id: timer.sleep
        - service: script.send_to_home_log
          data:
            message: ":pause_button: Pausing sleep :hourglass_flowing_sand: timer. Time remaining:
              {{ state_attr('timer.sleep', 'remaining') }}"
            title: ":zzz: Sleep as :robot_face: Android"
    mode: queued
    max: 10
