# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://github.com/iMicknl/ha-nest-protect
automation:
  - id: "1646778676345"
    alias: "Living Room: Carbon Monoxide Detected"
    description: ""
    triggers:
      - trigger: state
        entity_id: binary_sensor.nest_protect_living_room_co_status
        to: "on"
    conditions: []
    actions:
      - parallel:
          - action: script.send_direct_notification
            data:
              message: ":skull_and_crossbones: Carbon Monoxide detected on the living room."
              title: ":skull_and_crossbones: CO Detected on the living room"
          - action: script.set_central_heating_to_off
            data: {}
          - action: script.set_hot_water_to_home_mode
            data: {}
    mode: single
  - id: "1646778927330"
    alias: "Living Room: Smoked Detected"
    description: ""
    triggers:
      - trigger: state
        entity_id: binary_sensor.nest_protect_living_room_smoke_status
        to: "on"
    conditions: []
    actions:
      - parallel:
          - action: script.send_direct_notification
            data:
              message: ":smoking: Smoke detected on the living room."
              title: ":smoking: Smoke detected on the living room"
          - action: script.set_central_heating_to_off
            data: {}
          - action: script.set_hot_water_to_home_mode
            data: {}
    mode: single
  - id: "1646778627153"
    alias: "Office: Carbon Monoxide Detected"
    description: ""
    triggers:
      - trigger: state
        entity_id: binary_sensor.nest_protect_office_co_status
        to: "on"
    conditions: []
    actions:
      - parallel:
          - action: script.send_direct_notification
            data:
              title: ":skull_and_crossbones: CO Detected in the office"
              message: ":skull_and_crossbones: Carbon Monoxide detected in the :office: office."
          - action: script.set_central_heating_to_off
            data: {}
          - action: script.set_hot_water_to_home_mode
            data: {}
    mode: single
  - id: "1646778909669"
    alias: "Office: Smoked Detected"
    description: ""
    triggers:
      - trigger: state
        entity_id: binary_sensor.nest_protect_office_smoke_status
        to: "on"
    conditions: []
    actions:
      - parallel:
          - action: script.send_direct_notification
            data:
              title: ":smoking: Smoke detected in the office"
              message: ":smoking: Smoke detected in the :office: office."
          - action: script.set_central_heating_to_off
            data: {}
          - action: script.set_hot_water_to_home_mode
            data: {}
    mode: single
  - id: "1646778676344"
    alias: "Stairs: Carbon Monoxide Detected"
    description: ""
    triggers:
      - trigger: state
        entity_id: binary_sensor.nest_protect_upstairs_co_status
        to: "on"
    conditions: []
    actions:
      - parallel:
          - action: script.send_direct_notification
            data:
              title: ":skull_and_crossbones: CO Detected on the stairs"
              message: ":skull_and_crossbones: Carbon Monoxide detected on the stairs."
          - action: script.set_central_heating_to_off
            data: {}
          - action: script.set_hot_water_to_home_mode
            data: {}
    mode: single
  - id: "1646778927329"
    alias: "Stairs: Smoked Detected"
    description: ""
    triggers:
      - trigger: state
        entity_id: binary_sensor.nest_protect_upstairs_smoke_status
        to: "on"
    conditions: []
    actions:
      - parallel:
          - action: script.send_direct_notification
            data:
              title: ":smoking: Smoke detected on the stairs"
              message: ":smoking: Smoke detected on the stairs."
          - action: script.set_central_heating_to_off
            data: {}
          - action: script.set_hot_water_to_home_mode
            data: {}
    mode: single
