# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1612998168529"
    alias: "^Spotify: Playing"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.spotify_danny
        to: playing
    condition: []
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: >-
                  {{ state_attr('media_player.spotify_danny','media_position') !=
                  none and
                  state_attr('media_player.spotify_danny','media_duration') !=
                  none and
                  state_attr('media_player.spotify_danny','media_title') !=
                  none and
                  state_attr('media_player.spotify_danny','media_artist') !=
                  none }}
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":musical_note: Spotify playing *{{ state_attr('media_player.spotify_danny',
                    'media_title') }}* by _{{ state_attr('media_player.spotify_danny',
                    'media_artist') }}_ and is at {{ state_attr('media_player.spotify_danny','media_position') |
                    int | timestamp_custom('%H:%M:%S') }}/{{ state_attr('media_player.spotify_danny','media_duration') |
                    int | timestamp_custom('%H:%M:%S') }} ({{ ((state_attr('media_player.spotify_danny',
                    'media_position') | int / state_attr('media_player.spotify_danny',
                    'media_duration') | int) * 100) | round(2, 'common') }}%) way through."
        default:
          - service: script.post_to_home_log
            data:
              message:
                ":musical_note: Spotify playing *{{ state_attr('media_player.spotify_danny',
                'media_content_type') }}*."
    mode: queued
    max: 10
