# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1641129761539"
    alias: "Stash: Update Library"
    description: "Update Stash library on a regular basis."
    trigger:
      - platform: time_pattern
        minutes: 0
        hours: "/2"
      - platform: time_pattern
        minutes: 0
        hours: "/6"
    condition: []
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: person.danny
                state: "home"
            sequence:
              - parallel:
                  - service: script.send_to_home_log
                    data:
                      message: "Updating."
                      title: ":bearded_person: Stash"
                      log_level: "Debug"
                  - service: rest_command.update_stash
                  - service: rest_command.update_stash2
        default:
          - parallel:
              - service: script.send_to_home_log
                data:
                  message: "Updating."
                  title: ":bearded_person: Stash"
                  log_level: "Debug"
              - service: rest_command.update_stash
              - service: rest_command.update_stash2
    mode: single

rest_command:
  update_stash:
    url: !secret stash_url
    method: POST
    headers:
      ApiKey: !secret stash_key
    payload: "{'query': 'mutation { metadataScan ( input: { useFileMetadata: true } ) metadataGenerate ( input : { sprites: true previews: true imagePreviews: true markers: true transcodes: false } ) } ''}"
    content_type: "application/json"
    verify_ssl: true
  update_stash2:
    url: !secret stash_url2
    method: POST
    headers:
      ApiKey: !secret stash_key2
    payload: "{'query': 'mutation { metadataScan ( input: { useFileMetadata: true } ) metadataGenerate ( input : { sprites: true previews: true imagePreviews: true markers: true transcodes: false } ) } ''}"
    content_type: "application/json"
    verify_ssl: true
