# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://www.home-assistant.io/integrations/hassio/
automation:
  - id: "1674411819883"
    alias: "Add-Ons: File Editor Started"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.file_editor_running
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.enable_stop_add_ons
        state: "on"
    action:
      - service: timer.start
        data:
          duration: 01:00:00
        target:
          entity_id: timer.stop_add_on_file_editor
    mode: single
  - id: "1674411819884"
    alias: "Add-Ons: SSH Started"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.file_editor_running
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.enable_stop_add_ons
        state: "on"
    action:
      - service: timer.start
        data:
          duration: 01:00:00
        target:
          entity_id: timer.stop_add_on_ssh
    mode: single
  - id: "1638101465298"
    alias: "Add-ons: Automatically Disable File Editor"
    description: ""
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.stop_add_on_file_editor
    condition:
      - condition: state
        entity_id: input_boolean.enable_stop_add_ons
        state: "on"
    action:
      - service: script.stop_add_on
        data:
          addonEntityId: core_configurator
          message:
            ":writing_hand: File editor has been on for more than an hour.
            Turning File editor off."
    mode: single
  - id: "1638101748989"
    alias: "Add-ons: Automatically Disable SSH"
    description: ""
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.stop_add_on_ssh
    condition:
      - condition: state
        entity_id: input_boolean.enable_stop_add_ons
        state: "on"
    action:
      - service: script.stop_add_on
        data:
          addonEntityId: core_ssh
          message: SSH has been on for more than an hour. Turning SSH off.
    mode: single

script:
  stop_add_on:
    alias: Stop Add-on
    fields:
      addonEntityId:
        description: Add-on entity ID e.g. core_configurator
        required: true
      message:
        description: Message to post
        required: true
    sequence:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: "{{ message|default(none, true) }}"
              title: ":heavy_plus_sign: Add-on"
          - service: hassio.addon_stop
            data:
              addon: "{{ addonEntityId }}"
