# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1638101465298"
    alias: "Add-ons: Automatically Disable File Editor"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.file_editor_running
        to: "on"
        for:
          hours: 1
          minutes: 0
          seconds: 0
          milliseconds: 0
        from: "off"
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message:
            ":writing_hand: File editor add=on has been on for more than an hour.
            Turning File editor off."
      - service: hassio.addon_stop
        data:
          addon: core_configurator
    mode: single
  - id: "1638101748989"
    alias: "Add-ons: Automatically Disable SSH"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.terminal_ssh_running
        for:
          hours: 1
          minutes: 0
          seconds: 0
          milliseconds: 0
        from: "off"
        to: "on"
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: SSH add-on has been on for more than an hour. Turning SSH off.
      - service: hassio.addon_stop
        data:
          addon: core_ssh
    mode: single
