# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://www.home-assistant.io/integrations/hassio/
automation:
  - id: "1674411819883"
    alias: "Add-Ons: File Editor Started"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.file_editor_running
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.enable_stop_add_ons
        state: "on"
    action:
      - parallel:
          - service: timer.start
            data:
              duration: 01:00:00
            target:
              entity_id: timer.stop_add_on_file_editor
          - service: script.send_to_home_log
            data:
              message: "File Editor started."
              title: ":heavy_plus_sign: Add-on"
              log_level: "Normal"
    mode: single
  - id: "1638101465298"
    alias: "Add-ons: Automatically Disable File Editor"
    description: ""
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.stop_add_on_file_editor
    condition:
      - condition: state
        entity_id: input_boolean.enable_stop_add_ons
        state: "on"
    action:
      - service: script.stop_add_on
        data:
          addonEntityId: core_configurator
          message:
            ":writing_hand: File editor has been on for more than an hour.
            Turning File editor off."
    mode: single
  - id: "1674411819884"
    alias: "Add-Ons: Advanced SSH & Web Terminal"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.advanced_ssh_web_terminal_running
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.enable_stop_add_ons
        state: "on"
    action:
      - parallel:
          - service: timer.start
            data:
              duration: 01:00:00
            target:
              entity_id: timer.stop_add_on_terminal_ssh
          - service: script.send_to_home_log
            data:
              message: "Terminal SSH started."
              title: ":heavy_plus_sign: Add-on"
              log_level: "Normal"
    mode: single
  - id: "1638101748990"
    alias: "Add-ons: Automatically Disable Advanced SSH & Web Terminal"
    description: ""
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.stop_add_on_terminal_ssh
    condition:
      - condition: state
        entity_id: input_boolean.enable_stop_add_ons
        state: "on"
    action:
      - service: script.stop_add_on
        data:
          addonEntityId: a0d7b954_ssh
          message: SSH has been on for more than an hour. Turning SSH off.
    mode: single
  - id: "1638101748992"
    alias: "Add-ons: Zigbee 2 MQTT Proxy Started"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.zigbee2mqtt_proxy_running
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.enable_stop_add_ons
        state: "on"
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: "Zigbee 2 MQTT Proxy started."
              title: ":heavy_plus_sign: Add-on"
              log_level: "Debug"
          - service: timer.start
            metadata: {}
            data:
              duration: "00:30:00"
            target:
              entity_id: timer.stop_add_on_zigbee_2_mqtt_proxy
  - id: "1638101748993"
    alias: "Add-ons: Automatically Disable Zigbee 2 MQTT Proxy"
    description: ""
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.stop_add_on_zigbee_2_mqtt_proxy
    condition:
      - condition: state
        entity_id: input_boolean.enable_stop_add_ons
        state: "on"
    action:
      - service: script.stop_add_on
        data:
          addonEntityId: 45df7312_zigbee2mqtt_proxy
          message: Zigbee2MQTT Proxy has been on for more than an hour. Turning Zigbee2MQTT Proxy off.
    mode: single
  # Update add-ons. Why is this needed when there's an auto update setting??
  - id: "1700062541454"
    alias: "Add-On: Update For File Editor"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - sensor.file_editor_newest_version
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.file_editor_newest_version
            state: sensor.file_editor_version
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: >-
                File Editor updated from {{ states('sensor.file_editor_version') }} to
                {{ states('sensor.file_editor_newest_version')}}.
              title: ":heavy_plus_sign: Add-on"
              log_level: "Normal"
          - service: update.install
            data: {}
            target:
              entity_id: update.file_editor_update
    mode: single
  - id: "1700062541455"
    alias: "Add-On: Update For Terminal & Web"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - sensor.advanced_ssh_web_terminal_newest_version
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.advanced_ssh_web_terminal_newest_version
            state: sensor.advanced_ssh_web_terminal_version
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: >-
                Terminal & SSH updated from {{ states('sensor.advanced_ssh_web_terminal_version') }} to
                {{ states('sensor.advanced_ssh_web_terminal_newest_version')}}.
              title: ":heavy_plus_sign: Add-on"
              log_level: "Normal"
          - service: update.install
            data: {}
            target:
              entity_id: update.advanced_ssh_web_terminal_update
    mode: single
  - id: "1700062541456"
    alias: "Add-On: Update For ESPHome"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - sensor.esphome_newest_version
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.esphome_newest_version
            state: sensor.esphome_version
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: >-
                ESPHome updated from {{ states('sensor.esphome_version') }} to
                {{ states('sensor.esphome_newest_version')}}.
              title: ":heavy_plus_sign: Add-on"
              log_level: "Normal"
          - service: update.install
            data: {}
            target:
              entity_id: update.esphome_update
    mode: single
  - id: "1700062541457"
    alias: "Add-On: Update For Zigbee2MQTT Proxy"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - sensor.zigbee2mqtt_proxy_newest_version
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.zigbee2mqtt_proxy_newest_version
            state: sensor.zigbee2mqtt_proxy_version
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: >-
                Zigbee2MQTT Proxy updated from {{ states('sensor.zigbee2mqtt_proxy_version') }} to
                {{ states('sensor.zigbee2mqtt_proxy_newest_version')}}.
              title: ":heavy_plus_sign: Add-on"
              log_level: "Normal"
          - service: update.install
            data: {}
            target:
              entity_id: update.zigbee2mqtt_proxy_update
    mode: single
  - id: "1700062541458"
    alias: "Add-On: Update For Log Viewer"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - sensor.log_viewer_newest_version
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.log_viewer_newest_version
            state: sensor.log_viewer_version
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: >-
                Log Viewer updated from {{ states('sensor.log_viewer_version') }} to
                {{ states('sensor.log_viewer_newest_version')}}.
              title: ":heavy_plus_sign: Add-on"
              log_level: "Normal"
          - service: update.install
            data: {}
            target:
              entity_id: update.log_viewer_update
    mode: single
  - id: "1700062541459"
    alias: "Add-On: Update For Log Viewer"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - sensor.visual_studio_code_newest_version
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.visual_studio_code_newest_version
            state: sensor.visual_studio_code_version
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: >-
                Log Viewer updated from {{ states('sensor.visual_studio_code_version') }} to
                {{ states('sensor.visual_studio_code_newest_version')}}.
              title: ":heavy_plus_sign: Add-on"
              log_level: "Normal"
          - service: update.install
            data: {}
            target:
              entity_id: update.studio_code_server_update
    mode: single

script:
  stop_add_on:
    alias: Stop Add-on
    fields:
      addonEntityId:
        description: Add-on entity ID e.g. core_configurator
        required: true
        selector:
          addon:
      message:
        description: Message to post
        required: true
        selector:
          text:
    sequence:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: "{{ message|default(none, true) }}"
              title: ":heavy_plus_sign: Add-on"
              log_level: "Normal"
          - service: hassio.addon_stop
            data:
              addon: "{{ addonEntityId }}"
