# Created by Danny Tsang <danny@tsang.uk>
# Source integration from: https://github.com/thejeffreystone/home-assistant-configuration/blob/master/config/packages/switchbot.yaml
# Official documentation: https://github.com/OpenWonderLabs/SwitchBotAPI
# To get the device ID(s), run:
# curl -H "Authorization: API_KEY_HERE" https://api.switch-bot.com/v1.0/devices
rest_command:
  switchbot_device_command:
    url: "https://api.switch-bot.com/v1.0/devices/{{ deviceId }}/commands"
    method: post
    content_type: "application/json"
    headers:
      Authorization: !secret switchbot_api
    payload: '{"command": "{{ command }}","parameter": "{{ parameter }}"}'

sensor:
  - platform: rest
    name: "Office Curtains Left Position"
    resource: !secret switchbot_office_curtain_left_status_url
    method: GET
    scan_interval: 600
    headers:
      Authorization: !secret switchbot_api
      Content-Type: "application/json"
    value_template: "{{ value_json.body.slidePosition }}"
    json_attributes_path: "$.body"
    json_attributes:
      - deviceId
      - deviceType
      - hubDeviceId
      - calibrate
      - group
      - moving
      - slidePosition
  - platform: rest
    name: "Office Curtains Right Position"
    resource: !secret switchbot_office_curtain_right_status_url
    method: GET
    scan_interval: 600
    headers:
      Authorization: !secret switchbot_api
      Content-Type: "application/json"
    value_template: "{{ value_json.body.slidePosition }}"
    json_attributes_path: "$.body"
    json_attributes:
      - deviceId
      - deviceType
      - hubDeviceId
      - calibrate
      - group
      - moving
      - slidePosition

cover:
  - platform: template
    covers:
      office_curtains_left:
        device_class: curtain
        friendly_name: "Office Curtains Left"
        # Position needs to reversed because switchbot report 100(%) as closed where as
        # Home Assistant has 0(%) as closed.
        position_template: "{{ 100 - states('sensor.office_curtains_left_position')|int }}"
        open_cover:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret switchbot_office_curtain_left_device_id
            command: "turnOn"
        close_cover:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret switchbot_office_curtain_left_device_id
            command: "turnOff"
        stop_cover:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret switchbot_office_curtain_left_device_id
            command: "turnOff"
        set_cover_position:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret switchbot_office_curtain_left_device_id
            command: "setPosition"
            parameter: "0,ff,{{position}}"
  - platform: template
    covers:
      office_curtains_right:
        device_class: curtain
        friendly_name: "Office Curtains Right"
        # Position needs to reversed because switchbot report 100(%) as closed where as
        # Home Assistant has 0(%) as closed.
        position_template: "{{ 100 - states('sensor.office_curtains_right_position')|int }}"
        open_cover:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret switchbot_office_curtain_right_device_id
            command: "turnOn"
        close_cover:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret switchbot_office_curtain_right_device_id
            command: "turnOff"
        stop_cover:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret switchbot_office_curtain_right_device_id
            command: "turnOff"
        set_cover_position:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret switchbot_office_curtain_right_device_id
            command: "setPosition"
            parameter: "0,ff,{{position}}"
