# Created by Danny Tsang <danny@tsang.uk>
sensor:
  # Get current timer
  - platform: rest
    name: Toggl Current Timer
    resource: https://api.track.toggl.com/api/v8/time_entries/current
    method: GET
    authentication: basic
    username: !secret toggl
    password: api_token
    # https://community.home-assistant.io/t/help-needed-with-rest-when-empty-null-value-return/87735
    value_template: "{% if value_json.data.description is defined %} {{ value_json.data.description }} {% else %} '' {% endif %}"
    json_attributes_path: "$.data"
    json_attributes:
      - id
      - wid
      - pid
      - billable
      - start
      - duration
      - duronly
      - at
      - uid
  - platform: template
    sensors:
      # Toggl
      toggl_current_timer_start_time:
        value_template: "{{ state_attr('sensor.toggl_current_timer', 'start')['start'] }}"
        device_class: timestamp
