# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://www.home-assistant.io/integrations/unifiprotect/
automation:
  - id: "1757534420170"
    alias: "Unifi Protect: Personal Vehicles"
    description: ""
    triggers:
      - trigger: webhook
        allowed_methods:
          - POST
        local_only: true
        webhook_id: personal-vehicles
    conditions:
      - condition: state
        entity_id: input_boolean.enable_unifi_protect_events_automations
        state: "on"
    actions:
      - action: script.send_to_home_log
        data:
          message: >-
            Personal vehicles detected


            Trigger Value: {{ trigger.json.alarm.triggers[0].value }}

            Event ID: {{ trigger.json.alarm.triggers[0].eventId }}
          title: "Front Garden"
          log_level: "Normal"
    mode: queued
    max: 10
  - id: "1757533154370"
    alias: "Unifi Protect: Known Faces"
    description: ""
    triggers:
      - trigger: webhook
        allowed_methods:
          - POST
        local_only: true
        webhook_id: known-faces
    conditions:
      - condition: state
        entity_id: input_boolean.enable_unifi_protect_events_automations
        state: "on"
    actions:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: "Holiday"
            sequence:
              - action: script.send_direct_notification
                metadata: {}
                data:
                  message: "Unknown person


                    Event ID: {{ trigger.json.alarm.triggers[0].eventId }}

                    Event Path: {{ trigger.json.alarm.eventPath }}

                    Event Local Link: {{ trigger.json.alarm.eventLocalLink }}"
                  people:
                    entity_id:
                      - person.danny
        default: []
    mode: queued
    max: 10
  - id: "1757533154371"
    alias: "Unifi Protect: Unknown Faces"
    description: ""
    triggers:
      - trigger: webhook
        allowed_methods:
          - POST
        local_only: true
        webhook_id: unknown-faces
    conditions:
      - condition: state
        entity_id: input_boolean.enable_unifi_protect_events_automations
        state: "on"
      - condition: template
        value_template: "{{ trigger.json.key_token|string == states('input_text.n8n_webhook_key') }}"
    actions:
      - choose:
          - conditions:
              # testing purposes only
              - not:
                  - condition: state
                    entity_id: input_select.home_mode
                    state: "Holiday"
            sequence:
              - variables:
                  camera_name: "{{ trigger.json.camera_name | default('unknown') }}"
                  source_path: "{{ trigger.json.file_path + '/' +trigger.json.file_name }}"
                  file_path: "{{ states('input_text.camera_external_folder_path') + '/' + camera_name|default(trigger.json.camera_name) + '/' + trigger.json.file_name }}"
                  
              - action: shell_command.download_unifi_image
                data:
                  base_url: "{{ states('input_text.sftpgo_base_url') }}"
                  share_id: "{{ states('input_text.sftpgo_unifi_share_id') }}"
                  password: "{{ states('input_text.sftpgo_unifi_share_password') }}"
                  source_path: "{{ source_path }}"
                  destination_path: "{{ file_path }}"
              - action: script.send_home_log_with_local_attachments
                metadata: {}
                data:
                  message: "Unknown person in {{ camera_name }}."
                  people:
                    entity_id:
                      - person.danny
                  filePath: "{{ file_path }}"
                  priority: normal
                  suppress_if_quiet: false
              # TODO: delete image from SFTPGO
              # - action: shell_command.delete_unifi_image
              #   data:
              #     username:
              #     password:
              #     webhook_url: "{{ states('input_text.n8n_delete_sftpgo_unifi_share_file_webhook_url') }}"
        default: []
    mode: queued
    max: 10
