# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://www.home-assistant.io/integrations/unifiprotect/
automation:
  # region Doorbell
  - id: "1694521590171"
    alias: "Unifi Protect: Doorbell Pressed"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - event.doorbell_doorbell
    conditions:
      - condition: template
        value_template: >-
          {{ trigger.from_state.state != 'unavailable' }}
      - condition: template
        value_template: >-
          {{ trigger.to_state.state != 'unavailable' }}
    actions:
      - parallel:
          - action: script.send_direct_notification
            data:
              message: "Someone pressed the door bell."
              title: "Front Garden"
              people:
                entity_id:
                  - person.danny
                  - person.terina
          - action: script.alexa_announce
            data:
              message: "Ding dong."
              suppress_if_quiet: false
          - alias: Delayed notification
            sequence:
              - action: todo.get_items
                target:
                  entity_id:
                    - todo.shared_notifications
                data:
                  status: needs_action
                response_variable: todo_list
              - if:
                  - condition: state
                    entity_id: group.tracked_people
                    state: "not_home"
                  - alias: Does not already exist
                    condition: template
                    value_template: >-
                      {%- for t in todo_list['todo.shared_notifications']['items'] -%}
                      {%- if t.summary == '🚪 🔔 Someone rung the door bell.' -%}
                      {{ false }}
                      {%- break -%}
                      {%- endif-%}
                      {%- endfor -%}
                then:
                  - action: todo.add_item
                    data:
                      item: "🚪 🔔 Someone rung the door bell."
                    target:
                      entity_id: todo.shared_notifications
          - alias: Take picture
            sequence:
              - action: script.send_direct_notification_with_url
                data:
                  message: Door bell pressed
                  title: Front Door
                  people:
                    entity_id:
                      - person.danny
                  url: "{{ states('input_text.external_url') ~ state_attr('camera.doorbell_high_resolution_channel', 'entity_picture') }}"
                  url_type: image
              - action: script.send_direct_notification_with_url
                data:
                  message: Door bell pressed
                  title: Front Door
                  people:
                    entity_id:
                      - person.danny
                  url: "{{ states('input_text.external_url') ~ state_attr('camera.doorbell_high_resolution_channel', 'video_url') }}"
                  url_type: video
    mode: single
  # region Object detection
  - id: "1757534420170"
    alias: "Unifi Protect: Personal Vehicles"
    description: ""
    triggers:
      - trigger: webhook
        allowed_methods:
          - POST
        local_only: true
        webhook_id: personal-vehicles
    conditions:
      - condition: state
        entity_id: input_boolean.enable_unifi_protect_events_automations
        state: "on"
    actions:
      - action: script.send_to_home_log
        data:
          message: >-
            Personal vehicles detected


            Trigger Value: {{ trigger.json.alarm.triggers[0].value }}

            Event ID: {{ trigger.json.alarm.triggers[0].eventId }}
          title: "Front Garden"
          log_level: "Normal"
    mode: queued
    max: 10
  - id: "1757533154370"
    alias: "Unifi Protect: Known Faces"
    description: ""
    triggers:
      - trigger: webhook
        allowed_methods:
          - POST
        local_only: true
        webhook_id: known-faces
    conditions:
      - condition: state
        entity_id: input_boolean.enable_unifi_protect_events_automations
        state: "on"
    actions:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: "Holiday"
            sequence:
              - action: script.send_direct_notification
                metadata: {}
                data:
                  message: "Unknown person


                    Event ID: {{ trigger.json.alarm.triggers[0].eventId }}

                    Event Path: {{ trigger.json.alarm.eventPath }}

                    Event Local Link: {{ trigger.json.alarm.eventLocalLink }}"
                  people:
                    entity_id:
                      - person.danny
        default: []
    mode: queued
    max: 10
  - id: "1757533154371"
    alias: "Unifi Protect: Unknown Faces"
    description: ""
    triggers:
      - trigger: webhook
        allowed_methods:
          - POST
        local_only: true
        webhook_id: unknown-faces
    conditions:
      - condition: state
        entity_id: input_boolean.enable_unifi_protect_events_automations
        state: "on"
      - condition: template
        value_template: "{{ trigger.json.key_token|string == states('input_text.n8n_webhook_key') }}"
    actions:
      - choose:
          - conditions:
              # testing purposes only
              - not:
                  - condition: state
                    entity_id: input_select.home_mode
                    state: "Holiday"
            sequence:
              - variables:
                  camera_name: "{{ trigger.json.camera_name | default('unknown') }}"
                  source_path: "{{ trigger.json.file_path + '/' +trigger.json.file_name }}"
                  file_path: "{{ states('input_text.camera_external_folder_path') + '/' + camera_name|default(trigger.json.camera_name) + '/' + trigger.json.file_name }}"
                  
              - action: shell_command.download_unifi_image
                data:
                  base_url: "{{ states('input_text.sftpgo_base_url') }}"
                  share_id: "{{ states('input_text.sftpgo_unifi_share_id') }}"
                  password: "{{ states('input_text.sftpgo_unifi_share_password') }}"
                  source_path: "{{ source_path }}"
                  destination_path: "{{ file_path }}"
              - action: script.send_home_log_with_local_attachments
                metadata: {}
                data:
                  message: "Unknown person in {{ camera_name }}."
                  people:
                    entity_id:
                      - person.danny
                  filePath: "{{ file_path }}"
                  priority: normal
                  suppress_if_quiet: false
              # TODO: delete image from SFTPGO
              # - action: shell_command.delete_unifi_image
              #   data:
              #     username:
              #     password:
              #     webhook_url: "{{ states('input_text.n8n_delete_sftpgo_unifi_share_file_webhook_url') }}"
        default: []
    mode: queued
    max: 10
