# Created by Danny Tsang <danny@tsang.uk>
alert:
  server_ups_replace_battery_alarm:
    name: Server UPS Replace Battery Alarm
    entity_id: sensor.server_ups_status_data
    state: "ALARM OL RB"
    repeat: 60
    can_acknowledge: true
    skip_first: true
    notifiers:
      - mobile_app_dannys_phone
automation:
  # Lounge
  - id: "1591553714916"
    alias: "^UPS: Lounge Fully Charged"
    description: ""
    trigger:
      - entity_id: sensor.lounge_ups_status_data
        from: "OL CHRG"
        platform: state
        to: "OL"
    condition: []
    action:
      - data:
          message: ":battery: :thumbsup: Lounge UPS battery is fully charged."
        service: script.post_to_home_log
  - id: "1590564212294"
    alias: "^UPS: Lounge Charging"
    description: ""
    trigger:
      - entity_id: sensor.computer_ups_status_data
        platform: state
        from: "OB DISCHRG"
        to: "OL CHRG"
        id: battery_to_charge
      - entity_id: sensor.lounge_ups_status_data
        platform: state
        to: "OL CHRG"
        id: "charge"
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: charge
            sequence:
              - service: script.post_to_home_log
                data:
                  message: ":electric_plug: :battery: Lounge UPS is charging :electric_plug: :battery:"
        default: []
      - choose:
          - conditions:
              - condition: trigger
                id: battery_to_charge
              - condition: state
                entity_id: input_boolean.enable_slack_direct_messages
                state: "on"
            sequence:
              - service: script.post_to_home_log
                data:
                  message: ":electric_plug: :battery: Lounge UPS went from battery to charging :electric_plug: :battery:"
              - service: script.post_to_direct_notification
                data:
                  message: ":electric_plug: :battery: Lounge UPS went from battery to charging :electric_plug: :battery:"
          - conditions:
              - condition: trigger
                id: battery_to_charge
              - condition: state
                entity_id: input_boolean.enable_slack_direct_messages
                state: "off"
            sequence:
              - service: script.post_to_home_log
                data:
                  message: ":electric_plug: :battery: Lounge UPS went from battery to charging :electric_plug: :battery:"
        default: []
    mode: single
  - id: "1591963855737"
    alias: "^UPS: Lounge Unavailable"
    description: ""
    trigger:
      - entity_id: sensor.lounge_ups_status_data
        platform: state
        to: unavailable
    condition: []
    action:
      - data:
          message:
            ":warning: :battery: Lounge UPS battery is not connected :battery:
            :warning:"
        service: script.post_to_home_log
  - id: "1590564041899"
    alias: "^UPS: Lounge UPS On Battery"
    description: ""
    trigger:
      - entity_id: sensor.lounge_ups_status_data
        platform: state
        to: OB DISCHRG
    condition: []
    action:
      - data:
          message: ":warning: :battery: Lounge UPS is running on battery :battery: :warning:"
        service: script.post_to_home_log
      - data:
          message:
            ":warning: :battery: Lounge UPS is running on battery mins left :battery:
            :warning:"
        service: script.post_to_direct_notification
    mode: single
  - id: "1591705427771"
    alias: "^UPS: Lounge UPS Replace Battery Alarm"
    description: ""
    trigger:
      - entity_id: sensor.lounge_ups_status_data
        platform: state
        to: ALARM OL RB
    condition: []
    action:
      - data:
          message:
            ":warning: :battery: Lounge UPS replace battery alarm. :battery: :warning:"
        service: script.post_to_home_log
      - data:
          message:
            ":warning: :battery: Lounge UPS replace battery alarm.:battery: :warning:"
        service: script.post_to_direct_notification
    mode: single
  # PC
  - id: "1613324300208"
    alias: "^UPS: Computer UPS Unavailable"
    description: ""
    trigger:
      - platform: state
        entity_id: sensor.computer_ups_status
        to: unavailable
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":warning: :battery: PC UPS battery is not connected :battery:
          :warning:"
    mode: single
  - id: "1613246389183"
    alias: "^UPS: Office PC Charging"
    description: ""
    trigger:
      - entity_id: sensor.computer_ups_status_data
        platform: state
        from: "OB DISCHRG"
        to: "OL CHRG"
        id: battery_to_charge
      - entity_id: sensor.computer_ups_status_data
        platform: state
        to: "OL CHRG"
        id: charge
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: charge
            sequence:
              - service: script.post_to_home_log
                data:
                  message: ":electric_plug: :battery: PC UPS is charging :electric_plug: :battery:"
        default: []
      - choose:
          - conditions:
              - condition: trigger
                id: battery_to_charge
              - condition: state
                entity_id: input_boolean.enable_slack_direct_messages
                state: "on"
            sequence:
              - service: script.post_to_home_log
                data:
                  message: ":electric_plug: :battery: PC UPS went from battery to charging :electric_plug: :battery:"
              - service: script.post_to_direct_notification
                data:
                  message: ":electric_plug: :battery: PC UPS went from battery to charging :electric_plug: :battery:"
          - conditions:
              - condition: trigger
                id: battery_to_charge
              - condition: state
                entity_id: input_boolean.enable_slack_direct_messages
                state: "off"
            sequence:
              - service: script.post_to_home_log
                data:
                  message: ":electric_plug: :battery: PC UPS went from battery to charging :electric_plug: :battery:"
        default: []
    mode: single
  - id: "1613246283969"
    alias: "^UPS: Office PC Fully Charged"
    description: ""
    trigger:
      - entity_id: sensor.computer_ups_status_data
        from: "OL CHRG"
        platform: state
        to: "OL"
    condition: []
    action:
      - data:
          message: ":battery: PC UPS battery is fully charged :battery:"
        service: script.post_to_home_log
    mode: single
  - id: "1613246249488"
    alias: "^UPS: Office PC UPS On Battery"
    description: ""
    trigger:
      - entity_id: sensor.computer_ups_status_data
        platform: state
        to: OB DISCHRG
    condition: []
    action:
      - data:
          message:
            ":warning: :battery: PC UPS is running on battery with less than
            5 minutes left :battery: :warning:"
          target: "#general"
        service: notify.slack_notify
      - data:
          message:
            ":warning: :battery: PC UPS is running on battery with less than
            5 minutes left :battery: :warning:"
        service: script.post_to_direct_notification
    mode: single
  - id: "1591705427770"
    alias: "^UPS: Office PC UPS Replace Battery Alarm"
    description: ""
    trigger:
      - entity_id: sensor.computer_ups_status_data
        platform: state
        to: ALARM OL RB
    condition: []
    action:
      - data:
          message:
            ":warning: :battery: PC UPS replace battery alarm. :battery: :warning:"
        service: script.post_to_home_log
      - data:
          message:
            ":warning: :battery: PC UPS replace battery alarm.:battery: :warning:"
        service: script.post_to_direct_notification
    mode: single
  # Server
  - id: "1591729661691"
    alias: "^UPS: Office Fully Charged"
    description: ""
    trigger:
      - entity_id: sensor.server_ups_status_data
        from: "OL CHRG"
        platform: state
        to: "OL"
    condition: []
    action:
      - data:
          message: ":battery: :thumbsup: Server UPS battery is fully charged."
        service: script.post_to_home_log
    mode: single
  - id: "1591705737293"
    alias: "^UPS: Server Charging"
    description: ""
    trigger:
      - entity_id: sensor.server_ups_status_data
        platform: state
        to: "OL CHRG"
    condition: []
    action:
      - data:
          message: ":electric_plug: :battery: Server UPS is charging :electric_plug: :battery:"
        service: script.post_to_home_log
      - data:
          message: ":electric_plug: :battery: Server UPS is charging :electric_plug: :battery:"
        service: script.post_to_direct_notification
    mode: single
  - id: "1591963905748"
    alias: "^Office: UPS Unavailable"
    description: ""
    trigger:
      - entity_id: sensor.server_ups_status_data
        platform: state
        to: unavailable
    condition: []
    action:
      - data:
          message:
            ":warning: :battery: Server UPS battery is not connected :battery:
            :warning:"
        service: script.post_to_home_log
    mode: single
  - id: "1591705427768"
    alias: "^UPS: Server UPS On Battery"
    description: ""
    trigger:
      - entity_id: sensor.server_ups_status_data
        platform: state
        to: OB DISCHRG
    condition: []
    action:
      - data:
          message:
            ":warning: :battery: Server UPS is running on battery with less than
            5 minutes left :battery: :warning:"
          target: "#general"
        service: notify.slack_notify
      - data:
          message:
            ":warning: :battery: Server UPS is running on battery with less than
            5 minutes left :battery: :warning:"
        service: script.post_to_direct_notification
    mode: single
  - id: "1591705427769"
    alias: "^UPS: Server UPS Replace Battery Alarm"
    description: ""
    trigger:
      - entity_id: sensor.server_ups_status_data
        platform: state
        to: ALARM OL RB
    condition: []
    action:
      - data:
          message:
            ":warning: :battery: Server UPS replace battery alarm. :battery: :warning:"
        service: script.post_to_home_log
      - data:
          message:
            ":warning: :battery: Server UPS replace battery alarm.:battery: :warning:"
        service: script.post_to_direct_notification
    mode: single
input_boolean:
  enable_ups_trigger:
    name: Enable UPS events
    icon: mdi:home-account

template:
  - sensor:
      - name: Lounge UPS Power
        device_class: "power"
        unit_of_measurement: "W"
        state_class: "measurement"
        state: >
          {% if states('sensor.lounge_ups_status_data') in ['OL', 'OL CHRG'] -%}
            {{ (states('sensor.lounge_ups_load') | float(0) / 100) * states('sensor.lounge_ups_nominal_real_power') | float(0) }}
          {%- else -%}
            0
          {%- endif %}
      - name: Office UPS Power
        device_class: "power"
        unit_of_measurement: "W"
        state_class: "measurement"
        state: >
          {% if states('sensor.computer_ups_status_data') in ['OL', 'OL CHRG'] -%}
            {{ (states('sensor.computer_ups_load') | float(0) / 100) * states('sensor.computer_ups_nominal_real_power') | float(0) }}
          {%- else -%}
            0
          {%- endif %}
      - name: Server UPS Power
        device_class: "power"
        unit_of_measurement: "W"
        state_class: "measurement"
        state: >
          {% if states('sensor.server_ups_status_data') in ['OL', 'OL CHRG'] -%}
            {{ (states('sensor.server_ups_load') | float(0) / 100) * states('sensor.server_ups_nominal_real_power') | float(0) }}
          {%- else -%}
            0
          {%- endif %}