# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1591553714916"
    alias: "^UPS: Fully Charged"
    description: ""
    trigger:
      - entity_id:
          - sensor.lounge_ups_status_data
          - sensor.computer_ups_status_data
          - sensor.server_ups_status_data
          - sensor.3d_printer_ups_status_data
        from: "OL CHRG"
        platform: state
        to: "OL"
    condition: []
    action:
      - data:
          message: ":battery: Battery is fully charged."
          title: >-
            :battery: UPS: {{ {'sensor.lounge_ups_status_data': ':couch_and_lamp: Lounge',
            'sensor.pc_ups_status_data': ':desktop_computer: PC',
            'sensor.server_ups_status_data': 'Server'}[trigger.entity_id] | default('') }}
        service: script.send_to_home_log
  - id: "1590564212294"
    alias: "^UPS: Charging"
    description: ""
    trigger:
      - entity_id:
          - sensor.computer_ups_status_data
          - sensor.server_ups_status_data
          - sensor.3d_printer_ups_status_data
        platform: state
        from: "OB DISCHRG"
        to: "OL CHRG"
        id: battery_to_charge
      - entity_id:
          - sensor.computer_ups_status_data
          - sensor.lounge_ups_status_data
          - sensor.server_ups_status_data
          - sensor.3d_printer_ups_status_data
        platform: state
        to: "OL CHRG"
        id: "charge"
    condition: []
    action:
      - parallel:
        - choose:
            - conditions:
                - condition: trigger
                  id: charge
              sequence:
                - service: script.send_to_home_log
                  data:
                    message: ":battery: Battery is :electric_plug: charging."
                    title: >-
                      :battery: UPS: {{ {'sensor.lounge_ups_status_data': ':couch_and_lamp: Lounge',
                      'sensor.pc_ups_status_data': ':desktop_computer: PC',
                      'sensor.server_ups_status_data': 'Server',
                      'sensor.3d_printer_ups_status_data': ':printer: 3D Printer'}[trigger.entity_id] | default('') }}
            - conditions:
                - condition: trigger
                  id: battery_to_charge
              sequence:
                - service: script.send_direct_notification
                  data:
                    message: ":battery: UPS went from battery to :electric_plug: charging."
                    title: >-
                      :battery: UPS: {{ {'sensor.lounge_ups_status_data': ':couch_and_lamp: Lounge',
                      'sensor.pc_ups_status_data': ':desktop_computer: PC',
                      'sensor.server_ups_status_data': 'Server'}[trigger.entity_id] | default('') }}
          default: []
    mode: single
  - id: "1591963855737"
    alias: "^UPS: Unavailable"
    description: ""
    trigger:
      - entity_id:
          - sensor.lounge_ups_status_data
          - sensor.computer_ups_status
          - sensor.server_ups_status_data
          - sensor.3d_printer_ups_status_data
        platform: state
        to: unavailable
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message:
            ":battery: Battery is not connected."
          title: >-
            :warning: :battery: UPS: {{ {'sensor.lounge_ups_status_data': ':couch_and_lamp: Lounge',
            'sensor.pc_ups_status_data': ':desktop_computer: PC',
            'sensor.server_ups_status_data': 'Server',
            'sensor.3d_printer_ups_status_data': ':printer: 3D Printer'}[trigger.entity_id] | default('') }}
            :warning:
  - id: "1590564041899"
    alias: "^UPS: UPS On Battery"
    description: ""
    trigger:
      - entity_id:
          - sensor.lounge_ups_status_data
          - sensor.computer_ups_status_data
          - sensor.server_ups_status_data
          - sensor.3d_printer_ups_status_data
        platform: state
        to: OB DISCHRG
    condition: []
    action:
      - service: script.send_direct_notification
        data:
          message: "Running on :battery: battery."
          title: >-
            :warning: :battery: UPS: {{ {'sensor.lounge_ups_status_data': ':couch_and_lamp: Lounge',
            'sensor.pc_ups_status_data': ':desktop_computer: PC',
            'sensor.server_ups_status_data': 'Server',
            'sensor.3d_printer_ups_status_data': ':printer: 3D Printer'}[trigger.entity_id] | default('') }}
            :warning:
    mode: single
  - id: "1591963855738"
    alias: "^UPS: UPS Online Offline"
    description: ""
    trigger:
      - entity_id:
          - sensor.lounge_ups_status_data
          - sensor.computer_ups_status_data
          - sensor.server_ups_status_data
          - sensor.3d_printer_ups_status_data
        platform: state
        to: OL OFF
    condition: []
    action:
      - service: script.send_direct_notification
        data:
          message:
            "Running on :battery: battery because it's 'Online Offline' status."
          title: >-
            :warning: :battery: UPS: {{ {'sensor.lounge_ups_status_data': ':couch_and_lamp: Lounge',
            'sensor.pc_ups_status_data': ':desktop_computer: PC',
            'sensor.server_ups_status_data': 'Server',
            'sensor.3d_printer_ups_status_data': ':printer: 3D Printer'}[trigger.entity_id] | default('') }}
            :warning:
    mode: single
  - id: "1591705427771"
    alias: "^UPS: Replace Battery Alarm"
    description: ""
    trigger:
      - entity_id:
          - sensor.lounge_ups_status_data
          - sensor.computer_ups_status_data
          - sensor.server_ups_status_data
          - sensor.3d_printer_ups_status_data
        platform: state
        to: ALARM OL RB
    condition: []
    action:
      - service: script.send_direct_notification
        data:
          message: "Replace battery alarm."
          title: >-
            :warning: :battery: UPS:
            {{ {'sensor.lounge_ups_status_data': ':couch_and_lamp: Lounge',
            'sensor.pc_ups_status_data': ':desktop_computer: PC',
            'sensor.server_ups_status_data': 'Server',
            'sensor.3d_printer_ups_status_data': ':printer: 3D Printer'}[trigger.entity_id] | default('') }}
            :warning:
    mode: single

template:
  - sensor:
      - name: 3D Printer UPS Power
        unique_id: 31406205-681f-472d-8be1-a7908383de89
        device_class: "power"
        unit_of_measurement: "W"
        state_class: "measurement"
        state: >
          {% if states('sensor.3d_printer_ups_status') in ['OL', 'OL CHRG'] -%}
            {{ (states('sensor.3d_printer_ups_load') | float(0) / 100) * 405 | float(0) }}
          {%- else -%}
            0
          {%- endif %}
      - name: Lounge UPS Power
        unique_id: b34e6d2e-8a46-489a-afcb-551a0e4b9f0a
        device_class: "power"
        unit_of_measurement: "W"
        state_class: "measurement"
        state: >
          {% if states('sensor.lounge_ups_status_data') in ['OL', 'OL CHRG'] -%}
            {{ (states('sensor.lounge_ups_load') | float(0) / 100) * states('sensor.lounge_ups_nominal_real_power') | float(0) }}
          {%- else -%}
            0
          {%- endif %}
      - name: Office UPS Power
        unique_id: 64c705e9-619e-4cfd-9e97-fa722556041e
        device_class: "power"
        unit_of_measurement: "W"
        state_class: "measurement"
        state: >
          {% if states('sensor.computer_ups_status_data') in ['OL', 'OL CHRG'] -%}
            {{ (states('sensor.computer_ups_load') | float(0) / 100) * states('sensor.computer_ups_nominal_real_power') | float(0) }}
          {%- else -%}
            0
          {%- endif %}
      - name: Server UPS Power
        unique_id: 6868a338-192a-4f68-949a-9157b434ec4f
        device_class: "power"
        unit_of_measurement: "W"
        state_class: "measurement"
        state: >
          {% if states('sensor.server_ups_status_data') in ['OL', 'OL CHRG'] -%}
            {{ (states('sensor.server_ups_load') | float(0) / 100) * states('sensor.server_ups_nominal_real_power') | float(0) }}
          {%- else -%}
            0
          {%- endif %}
