# Created by Danny Tsang <danny@tsang.uk>
automation:
  # Lounge
  - id: "1591553714916"
    alias: "^UPS: Lounge Fully Charged"
    description: ""
    trigger:
      - entity_id: sensor.lounge_ups_status_data
        from: "OL CHRG"
        platform: state
        to: "OL"
    condition: []
    action:
      - data:
          message: ":battery: :thumbsup: Lounge UPS battery is fully charged."
        service: script.post_to_home_log
  - id: "1590564212294"
    alias: "^UPS: Lounge Charging"
    description: ""
    trigger:
      - entity_id: sensor.computer_ups_status_data
        platform: state
        from: "OB DISCHRG"
        to: "OL CHRG"
        id: battery_to_charge
      - entity_id: sensor.lounge_ups_status_data
        platform: state
        to: "OL CHRG"
        id: "charge"
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: charge
            sequence:
              - service: script.post_to_home_log
                data:
                  message: ":electric_plug: :battery: Lounge UPS is charging :electric_plug: :battery:"
        default: []
      - choose:
          - conditions:
              - condition: trigger
                id: battery_to_charge
              - condition: state
                entity_id: input_boolean.enable_slack_direct_messages
                state: "on"
            sequence:
              - service: script.post_to_home_log
                data:
                  message: ":electric_plug: :battery: Lounge UPS went from battery to charging :electric_plug: :battery:"
              - service: script.post_to_direct_notification
                data:
                  message: ":electric_plug: :battery: Lounge UPS went from battery to charging :electric_plug: :battery:"
          - conditions:
              - condition: trigger
                id: battery_to_charge
              - condition: state
                entity_id: input_boolean.enable_slack_direct_messages
                state: "off"
            sequence:
              - service: script.post_to_home_log
                data:
                  message: ":electric_plug: :battery: Lounge UPS went from battery to charging :electric_plug: :battery:"
        default: []
    mode: single
  - id: "1591963855737"
    alias: "^Lounge: UPS Unavailable"
    description: ""
    trigger:
      - entity_id: sensor.lounge_ups_status_data
        platform: state
        to: unavailable
    condition: []
    action:
      - data:
          message:
            ":warning: :battery: Lounge UPS battery is not connected :battery:
            :warning:"
        service: script.post_to_home_log
  # PC
  - id: "1613324300208"
    alias: "^UPS: Computer UPS Unavailable"
    description: ""
    trigger:
      - platform: state
        entity_id: sensor.computer_ups_status
        to: unavailable
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":warning: :battery: PC UPS battery is not connected :battery:
          :warning:"
    mode: single
  - id: "1613246389183"
    alias: "^UPS: Office PC Charging"
    description: ""
    trigger:
      - entity_id: sensor.computer_ups_status_data
        platform: state
        from: "OB DISCHRG"
        to: "OL CHRG"
        id: battery_to_charge
      - entity_id: sensor.computer_ups_status_data
        platform: state
        to: "OL CHRG"
        id: charge
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: charge
            sequence:
              - service: script.post_to_home_log
                data:
                  message: ":electric_plug: :battery: PC UPS is charging :electric_plug: :battery:"
        default: []
      - choose:
          - conditions:
              - condition: trigger
                id: battery_to_charge
              - condition: state
                entity_id: input_boolean.enable_slack_direct_messages
                state: "on"
            sequence:
              - service: script.post_to_home_log
                data:
                  message: ":electric_plug: :battery: PC UPS went from battery to charging :electric_plug: :battery:"
              - service: script.post_to_direct_notification
                data:
                  message: ":electric_plug: :battery: PC UPS went from battery to charging :electric_plug: :battery:"
          - conditions:
              - condition: trigger
                id: battery_to_charge
              - condition: state
                entity_id: input_boolean.enable_slack_direct_messages
                state: "off"
            sequence:
              - service: script.post_to_home_log
                data:
                  message: ":electric_plug: :battery: PC UPS went from battery to charging :electric_plug: :battery:"
        default: []
    mode: single
  - id: "1613246283969"
    alias: "^UPS: Office PC Fully Charged"
    description: ""
    trigger:
      - entity_id: sensor.computer_ups_status_data
        from: "OL CHRG"
        platform: state
        to: "OL"
    condition: []
    action:
      - data:
          message: ":battery: PC UPS battery is fully charged :battery:"
        service: script.post_to_home_log
    mode: single
  # Server
  - id: "1591729661691"
    alias: "^UPS: Office Fully Charged"
    description: ""
    trigger:
      - entity_id: sensor.server_ups_status_data
        from: "OL CHRG"
        platform: state
        to: "OL"
    condition: []
    action:
      - data:
          message: ":battery: :thumbsup: Server UPS battery is fully charged."
        service: script.post_to_home_log
    mode: single
  - id: "1591705737293"
    alias: "^UPS: Server Charging"
    description: ""
    trigger:
      - entity_id: sensor.server_ups_status_data
        platform: state
        to: "OL CHRG"
    condition: []
    action:
      - data:
          message: ":electric_plug: :battery: Server UPS is charging :electric_plug: :battery:"
        service: script.post_to_home_log
      - data:
          message: ":electric_plug: :battery: Server UPS is charging :electric_plug: :battery:"
        service: script.post_to_direct_notification
    mode: single
  - id: "1591963905748"
    alias: "^Office: UPS Unavailable"
    description: ""
    trigger:
      - entity_id: sensor.server_ups_status_data
        platform: state
        to: unavailable
    condition: []
    action:
      - data:
          message:
            ":warning: :battery: Server UPS battery is not connected :battery:
            :warning:"
        service: script.post_to_home_log
    mode: single
input_boolean:
  enable_ups_trigger:
    name: Enable UPS events
    icon: mdi:home-account
