# Created by Danny Tsang <danny@tsang.uk>
# See https://www.home-assistant.io/integrations/waqi/
sensor:
  - platform: waqi
    token: !secret aqicn_token
    locations:
      - !secret waqi_location1
