# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1622374233311"
    alias: "^Weather: Forecast To Be Hot"
    description: "Watches weather forecast for hot temperatures"
    trigger:
      - platform: numeric_state
        entity_id: weather.home_weather
        attribute: temperature
        above: "24"
    condition: []
    action:
      - service: script.office_close_curtains_by_weather
        data:
          temperature: "{{ state('weather.weather_home', 'temperature') }}"
          weather_condition: "{{ states('weather.weather_home') }}"
      - service: script.bedroom_close_blinds_by_weather
        data:
          temperature: "{{ state('weather.weather_home', 'temperature') }}"
          weather_condition: "{{ states('weather.weather_home') }}"
      - service: script.leos_bedroom_close_blinds_by_weather
        data:
          temperature: "{{ state('weather.weather_home', 'temperature') }}"
          weather_condition: "{{ states('weather.weather_home') }}"
      - service: script.ashlees_bedroom_close_blinds_by_weather
        data:
          temperature: "{{ state('weather.weather_home', 'temperature') }}"
          weather_condition: "{{ states('weather.weather_home') }}"
      - service: script.bathroom_close_blinds_by_weather
        data:
          temperature: "{{ state('weather.weather_home', 'temperature') }}"
          weather_condition: "{{ states('weather.weather_home') }}"
    mode: single

sensor:
  # https://community.home-assistant.io/t/uk-met-office-severe-weather-warnings/189680/4?u=tuxinator94
  - platform: feedparser
    name: Met Office RSS Weather Warnings
    feed_url: !secret weather_warning_rss
    date_format: "%a, %b %d %I:%M %p"
