# Created by Danny Tsang <danny@tsang.uk>
sensor:
  # https://community.home-assistant.io/t/uk-met-office-severe-weather-warnings/189680/4?u=tuxinator94
  - platform: feedparser
    name: Met Office RSS Weather Warnings
    feed_url: !secret weather_warning_rss
    date_format: "%a, %b %d %I:%M %p"
