# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://www.home-assistant.io/integrations/openweathermap/
automation:
  - id: "1622374233311"
    alias: "Weather: Forecast To Be Hot"
    description: "Watches weather forecast for hot temperatures"
    trigger:
      - platform: numeric_state
        entity_id: weather.home_weather
        attribute: temperature
        above: input_number.forecast_high_temperature
      - platform: numeric_state
        entity_id: weather.home_hourly
        attribute: temperature
        above: input_number.forecast_high_temperature
      - platform: numeric_state
        entity_id:
          - sensor.front_garden_motion_illuminance_lux
          - sensor.back_garden_motion_illuminance_lux
        above: input_number.close_blinds_brightness_threshold
    condition:
      - or:
          - condition: numeric_state
            entity_id: weather.home_weather
            attribute: temperature
            above: input_number.forecast_high_temperature
          - condition: numeric_state
            entity_id: weather.home_hourly
            attribute: temperature
            above: input_number.forecast_high_temperature
      - condition: state
        entity_id: sensor.season
        state: "summer"
    action:
      - parallel:
          - if:
              - condition: numeric_state
                entity_id: sensor.front_garden_motion_illuminance_lux
                above: input_number.close_blinds_brightness_threshold
            then:
              - service: script.bedroom_close_blinds_by_weather
                data:
                  temperature: "{{ state_attr(trigger.entity_id, 'temperature') }}"
                  weather_condition: "{{ states(trigger.entity_id) }}"
              - service: script.ashlees_bedroom_close_blinds_by_weather
                data:
                  temperature: "{{ state_attr(trigger.entity_id, 'temperature') }}"
                  weather_condition: "{{ states(trigger.entity_id) }}"
          - if:
              - condition: numeric_state
                entity_id: sensor.back_garden_motion_illuminance_lux
                above: input_number.close_blinds_brightness_threshold
            then:
              - service: script.leos_bedroom_close_blinds_by_weather
                data:
                  temperature: "{{ state_attr(trigger.entity_id, 'temperature') }}"
                  weather_condition: "{{ states(trigger.entity_id) }}"
              - service: script.bathroom_close_blinds_by_weather
                data:
                  temperature: "{{ state_attr(trigger.entity_id, 'temperature') }}"
                  weather_condition: "{{ states(trigger.entity_id) }}"
    mode: single
  - id: "1645568214221"
    alias: "Weather: Warning Notification"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.met_office_rss_weather_warnings
        above: 0
    condition: []
    action:
      - service: script.send_direct_notification
        data:
          message: >-
            {{ state_attr('sensor.met_office_rss_weather_warnings','entries')[0].title }}

            {{ state_attr('sensor.met_office_rss_weather_warnings','entries')[0].link }}
          title: ":cloud: Weather"
          people:
            - person.danny
            - person.terina
    mode: single

sensor:
  # https://community.home-assistant.io/t/uk-met-office-severe-weather-warnings/189680/4
  - platform: feedparser
    name: Met Office RSS Weather Warnings
    feed_url: !secret weather_warning_rss
    date_format: "%a, %b %d %I:%M %p"
