# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1741294780206"
    alias: Zigbee Coordinator Unavailable
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.zigbee2mqtt_bridge_connection_state
        to: unavailable
        for:
          hours: 0
          minutes: 1
          seconds: 0
    conditions: []
    actions:
      - action: script.send_direct_notification
        metadata: {}
        data:
          message: Zigbee coordinator became unavailable.
          people:
            entity_id:
              - person.danny
    mode: single
