---
#####
# Used to configure yamlling so it skips some checks
# Source: https://github.com/BeardedTinker/Home-Assistant_Config/blob/master/.github/yamllint-config.yml
#####
extends: default

rules:
  line-length: disable
  comments-indentation: disable
  document-start: disable
  indentation: disable

ignore: |
  custom_components/
  .git
  .github/workflows/yaml-lint.yaml
  themes/
