# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://www.home-assistant.io/integrations/ecowitt/

automation:
  - id: "1713094180264"
    alias: "Ecowitt: Offline"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - sensor.gw2000a_dewpoint
        for:
          hours: 1
      - platform: state
        entity_id:
          - sensor.gw2000a_solar_lux
        to: unavailable
        for:
          minutes: 1
    condition: []
    action:
      - parallel:
          - service: script.send_direct_notification
            metadata: {}
            data:
              message: "Ecowitt GW2000A({{ trigger.entity_id }}) has frozen or is unavailable. Rebooting."
              title: Ecowitt
              people:
                entity_id:
                  - person.danny
          - sequence:
              - service: switch.turn_off
                target:
                  entity_id: switch.gw2000a_plug
                data: {}
              - delay:
                  seconds: 2
              - service: switch.turn_on
                target:
                  entity_id: switch.gw2000a_plug
                data: {}
    mode: single
