# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://www.home-assistant.io/integrations/ecowitt/

automation:
  - id: "1713094180264"
    alias: "Ecowitt: Offline"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - sensor.gw2000a_dewpoint
        for:
          minutes: 3
      - trigger: state
        entity_id:
          - sensor.gw2000a_solar_lux
        to: unavailable
        for:
          minutes: 1
    conditions: []
    actions:
      - parallel:
          - action: script.send_to_home_log
            metadata: {}
            data:
              message: "Ecowitt GW2000A({{ trigger.entity_id }}) has frozen or is unavailable. Rebooting."
              title: Ecowitt
              log_level: "Debug"
          - sequence:
              - action: switch.turn_off
                target:
                  entity_id: switch.gw2000a_plug
                data: {}
              - delay:
                  seconds: 2
              - action: switch.turn_on
                target:
                  entity_id: switch.gw2000a_plug
                data: {}
    mode: single
