# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://www.home-assistant.io/integrations/openweathermap/
# Integration: https://www.home-assistant.io/integrations/metoffice/
automation:
  - id: "1622374233311"
    alias: "Weather: Forecast To Be Hot"
    description: "Watches weather forecast for hot temperatures"
    triggers:
      - trigger: numeric_state
        entity_id: weather.home
        attribute: temperature
        above: input_number.forecast_high_temperature
      - trigger: numeric_state
        entity_id: sensor.temperature_forecast_next_hour
        above: input_number.forecast_high_temperature
      - trigger: numeric_state
        entity_id:
          - sensor.front_garden_motion_illuminance
          - sensor.back_garden_motion_illuminance
        above: input_number.close_blinds_brightness_threshold
    conditions:
      - or:
          - condition: numeric_state
            entity_id: weather.home
            attribute: temperature
            above: input_number.forecast_high_temperature
          - condition: numeric_state
            entity_id: sensor.temperature_forecast_next_hour
            above: input_number.forecast_high_temperature
      - condition: state
        entity_id: sensor.season
        state: "summer"
    actions:
      - parallel:
          - if:
              - condition: numeric_state
                entity_id: sensor.front_garden_motion_illuminance
                above: input_number.close_blinds_brightness_threshold
            then:
              - action: script.bedroom_close_blinds_by_weather
                data:
                  temperature: "{{ state_attr(trigger.entity_id, 'temperature') }}"
                  weather_condition: "{{ states(trigger.entity_id) }}"
              - action: script.ashlees_bedroom_close_blinds_by_weather
                data:
                  temperature: "{{ state_attr(trigger.entity_id, 'temperature') }}"
                  weather_condition: "{{ states(trigger.entity_id) }}"
          - if:
              - condition: numeric_state
                entity_id: sensor.back_garden_motion_illuminance
                above: input_number.close_blinds_brightness_threshold
            then:
              - action: script.leos_bedroom_close_blinds_by_weather
                data:
                  temperature: "{{ state_attr(trigger.entity_id, 'temperature') }}"
                  weather_condition: "{{ states(trigger.entity_id) }}"
    mode: single
  - id: "1645568214221"
    alias: "Weather: Warning Notification"
    description: ""
    triggers:
      - trigger: numeric_state
        entity_id: sensor.met_office_rss_weather_warnings
        above: 0
    conditions: []
    actions:
      - action: script.send_direct_notification_with_url
        data:
          message: >-
            {{ state_attr('sensor.met_office_rss_weather_warnings','entries')[0].title }}

            {{ state_attr('sensor.met_office_rss_weather_warnings','entries')[0].link }}
          title: ":cloud: Weather"
          people:
            entity_id:
              - person.danny
              - person.terina
          url: "{{state_attr('sensor.met_office_rss_weather_warnings', 'entries')[0].links[1].href }}"
    mode: single
  - id: "1734968573793"
    alias: "Weather: Storm Warning"
    description: ""
    triggers:
      - trigger: numeric_state
        entity_id:
          - sensor.bedroom_air_pressure_difference
        above: 4
    conditions: []
    actions:
      - action: script.send_direct_notification
        metadata: {}
        data:
          message: ":thunder_cloud_and_rain: Storm Alert"
          title: ":cloud: Weather"
          people:
            entity_id:
              - person.danny
    mode: single

rest:
  - authentication: basic
    resource: !secret weather_warning_n8n_url
    method: GET
    username: !secret n8n_username
    password: !secret n8n_password
    headers:
      User-Agent: Home Assistant
      Content-Type: application/json
    verify_ssl: true
    scan_interval: 60
    sensor:
      - name: "Weather Warning"
        unique_id: 77c4f26c-d940-437f-8693-b7f29debe008
        value_template: "{{ value_json.isWarning }}"
        json_attributes:
          - "title"
          - "content"
          - "url"
          - "image_url"
