language: python
cache: pip
python:
  - "3.8"
install:
  - "pip3 install homeassistant"
script:
  - "mv secrets.yaml.sample secrets.yaml"
  - "mkdir -p /home/travis/build/dannytsang/homeassistant-config/config/camera"
  - "mkdir -p /home/travis/build/dannytsang/homeassistant-config/config/camera/conservatory"
  - "mkdir -p /home/travis/build/dannytsang/homeassistant-config/config/camera/driveway"
  - "mkdir -p /home/travis/build/dannytsang/homeassistant-config/config/camera/front_door"
  - "touch fullchain.pem"
  - "touch privkey.pem"
  - "hass --version"
  - "ls"
  - "hass -c $(pwd) --script check_config | tee check.output"
  - '! less check.output | grep -q "Failed config"'
