language: python
cache: pip
python:
  - "3.8"
before_install:
  - "mv secrets.yaml.sample secrets.yaml"
  - "sed -e '/delete:/d' < configuration.yaml > configuration.yaml"
install:
  - "pip3 install homeassistant"
  - "hass --version"
script:
  - "mkdir -p /home/travis/build/dannytsang/homeassistant-config/config/camera"
# Stub out image_processing because I cannot fix build failures. See https://github.com/dannytsang/homeassistant-config/issues/1
  - "rm image_processing.yaml && touch image_processing.yaml"
  - "touch fullchain.pem"
  - "touch privkey.pem"
  - "hass --version"
  - "ls"
  - "ls custom_components"
  - "hass -c $(pwd) --script check_config | tee check.output"
  - '! less check.output | grep -q "Failed config"'
