# Created by Danny Tsang <danny@tsang.uk>
- platform: workday
  country: GB
- platform: template
  sensors:
    ashlees_blind_state:
      value_template: "{{ is_state('cover.ashlees_blind', 'open') }}"
      friendly_name: "Ashlee's Blind"
      device_class: opening
      icon_template: "mdi:blinds{{ '-open' if is_state('cover.ashlees_blind','open') else '' }}"
    # blind state helpers
    bedroom_blind_state:
      value_template: "{{ is_state('cover.bedroom_blind', 'open') }}"
      friendly_name: "Bedroom Blind"
      device_class: opening
      icon_template: "mdi:blinds{{ '-open' if is_state('cover.bedroom_blind','open') else '' }}"
