# Created by Danny Tsang <danny@tsang.uk>
- platform: workday
  country: UK
- platform: template
  sensors:
    ashlees_blind_state:
      value_template: "{{ is_state('cover.ashlees_blind', 'open') }}"
      friendly_name: "Ashlee's Blind"
      device_class: opening
      icon_template: "mdi:blinds{{ '-open' if is_state('cover.ashlees_blind','open') else '' }}"
    # blind state helpers
    bedroom_blind_state:
      value_template: "{{ is_state('cover.bedroom_blind', 'open') }}"
      friendly_name: "Bedroom Blind"
      device_class: opening
      icon_template: "mdi:blinds{{ '-open' if is_state('cover.bedroom_blind','open') else '' }}"
    bed_occupied:
      icon_template: "mdi:bed-double{{ '-outline' if states('sensor.bed_top_left') | int >= 4000 or states('sensor.bed_top_right') | int >= 10500 or states('sensor.bed_bottom_left') | int >= 1000 or states('sensor.bed_bottom_right') | int >= 8000 else '' }}"
      friendly_name: Bed occupied sensor regardless where on the bed.
      device_class: occupancy
      value_template: >-
        {% if states('sensor.bed_top_left') | int >= 4000 or states('sensor.bed_top_right') | int >= 11000 or states('sensor.bed_bottom_left') | int >= 1000 or states('sensor.bed_bottom_right') | int >= 2000 %}
          on
        {% else %}
          off
        {% endif %}
      attribute_templates:
        number_in_bed: >-
          {% if states('sensor.bed_top_left') | int > 4000 and states('sensor.bed_top_right') | int < 11000 %}
            1
          {% elif states('sensor.bed_top_left') | int > 4000 and states('sensor.bed_top_right') | int > 11000 %}
            2
          {% else %}
            0
          {% endif %}
    leos_bed_occupied:
      icon_template: "mdi:bed-double{{ '-outline' if states('sensor.leos_bed_top_left') | int >= 1000 or states('sensor.leos_bed_top_right') | int >= 1000 or states('leos_sensor.bed_bottom_left') | int >= 1000 or states('sensor.leos_bed_bottom_right') | int >= 1000 else '' }}"
      friendly_name: Leo's bed occupied sensor regardless where on the bed.
      device_class: occupancy
      value_template: >-
        {% if states('sensor.leos_bed_top_left') | int >= 1000 or states('sensor.leos_bed_top_right') | int >= 1000 or states('sensor.leos_bed_bottom_left') | int >= 1000 or states('sensor.leos_bed_bottom_right') | int >= 1000 %}
          on
        {% else %}
          off
        {% endif %}
