- platform: local_file
  file_path: !secret camera_deepstack_conservatory
  name: deepstack_conservatory_latest
- platform: local_file
  file_path: !secret camera_deepstack_driveway
  name: deepstack_driveway_latest
- platform: local_file
  file_path: !secret camera_deepstack_frontdoor
  name: deepstack_dront_door_latest
- platform: local_file
  file_path: !secret camera_deepstack_lounge
  name: deepstack_lounge_latest
- platform: local_file
  file_path: !secret camera_deepstack_upstairs
  name: deepstack_upstairs_latest
