- platform: local_file
  file_path: /config/camera/driveway/deepstack_object_conservatory_latest.jpg
  name: deepstack_conservatory_latest
- platform: local_file
  file_path: /config/camera/driveway/deepstack_object_driveway_latest.jpg
  name: deepstack_driveway_latest
- platform: local_file
  file_path: /config/camera/front_door/deepstack_object_front_door_latest.jpg
  name: deepstack_dront_door_latest
