# Created by Danny Tsang <danny@tsang.uk>
- platform: aruba
  host: !secret aruba_ip
  username: !secret aruba_username
  password: !secret aruba_password
- platform: bluetooth_le_tracker
  track_new_devices: false
  track_battery: true
