# Created by Danny Tsang <danny@tsang.uk>
- platform: deepstack_object
  ip_address: !secret deepstack_host
  port: 5000
  timeout: 120
  api_key: !secret deepstack_api_key
  save_file_folder: /config/camera/driveway
  save_file_format: png
  save_timestamped_file: True
  always_save_latest_file: True
  scale: 0.75
  #roi_x_min: 0.35
  #roi_x_max: 0.8
  #roi_y_min: 0.4
  #roi_y_max: 0.8
  targets:
    - target: person
    - target: vehicle
      confidence: 60
    - target: car
      confidence: 40
  source:
    - entity_id: camera.driveway
- platform: deepstack_object
  ip_address: !secret deepstack_host
  port: 5000
  timeout: 120
  api_key: !secret deepstack_api_key
  save_file_folder: /config/camera/front_door
  save_file_format: jpg
  save_timestamped_file: True
  always_save_latest_file: True
  scale: 0.75
  #roi_x_min: 0.35
  #roi_x_max: 0.8
  #roi_y_min: 0.4
  #roi_y_max: 0.8
  targets:
    - target: person
      confidence: 40
    - target: cat
      confidence: 75
    - target: dog
      confidence: 75
    - target: knife
      confidence: 50
  source:
    - entity_id: camera.front_door
- platform: deepstack_object
  ip_address: !secret deepstack_host
  port: 5000
  timeout: 120
  api_key: !secret deepstack_api_key
  save_file_folder: /config/camera/conservatory
  save_file_format: jpg
  save_timestamped_file: True
  always_save_latest_file: True
  scale: 0.75
  #roi_x_min: 0.35
  #roi_x_max: 0.8
  #roi_y_min: 0.4
  #roi_y_max: 0.8
  targets:
    - target: person
      confidence: 40
    - target: cat
      confidence: 75
    - target: dog
      confidence: 75
    - target: knife
      confidence: 50
  source:
    - entity_id: camera.conservatory
