# Created by Danny Tsang <danny@tsang.uk>
- platform: deepstack_face
  ip_address: !secret deepstack_host
  port: 5000
  api_key: !secret deepstack_api_key
  timeout: 20
  detect_only: False
  save_file_folder: !secret image_processing_conservatory
  save_timestamped_file: True
  save_faces: True
  save_faces_folder: !secret image_processing_conservatory
  show_boxes: True
  source:
    - entity_id: camera.conservatory
