# Created by Danny Tsang <danny@tsang.uk>
- platform: deepstack_face
  ip_address: !secret deepstack_host
  port: 5000
  api_key: !secret deepstack_api_key
  timeout: 20
  save_file_folder: !secret image_processing_conservatory
  save_timestamped_file: true
  save_faces: true
  save_faces_folder: !secret image_processing_faces
  show_boxes: true
  source:
    - entity_id: camera.conservatory
- platform: deepstack_face
  ip_address: !secret deepstack_host
  port: 5000
  api_key: !secret deepstack_api_key
  timeout: 20
  save_file_folder: !secret image_processing_driveway
  save_timestamped_file: true
  save_faces: true
  save_faces_folder: !secret image_processing_faces
  show_boxes: true
  source:
    - entity_id: camera.driveway
- platform: deepstack_face
  ip_address: !secret deepstack_host
  port: 5000
  api_key: !secret deepstack_api_key
  timeout: 20
  save_file_folder: !secret image_processing_front_door
  save_timestamped_file: true
  save_faces: true
  save_faces_folder: !secret image_processing_faces
  show_boxes: true
  source:
    - entity_id: camera.front_door
- platform: deepstack_face
  ip_address: !secret deepstack_host
  port: 5000
  api_key: !secret deepstack_api_key
  timeout: 20
  save_file_folder: !secret image_processing_lounge
  save_timestamped_file: true
  save_faces: true
  save_faces_folder: !secret image_processing_faces
  show_boxes: true
  source:
    - entity_id: camera.lounge
- platform: deepstack_face
  ip_address: !secret deepstack_host
  port: 5000
  api_key: !secret deepstack_api_key
  timeout: 20
  save_file_folder: !secret image_processing_upstairs
  save_timestamped_file: true
  save_faces: true
  save_faces_folder: !secret image_processing_faces
  show_boxes: true
  source:
    - entity_id: camera.upstairs
