# Created by Danny Tsang <danny@tsang.uk>
- name: email_notify
  platform: smtp
  server: smtp.gmail.com
  port: 587
  timeout: 15
  sender: !secret gmail_sender
  encryption: starttls
  username: !secret gmail_username
  password: !secret gmail_password
  recipient:
    - !secret danny_email
    - !secret terina_email
  sender_name: Home Assistant

- platform: telegram
  name: telegram
  chat_id: !secret telegram_chat_id

- name: twitter_notify
  platform: twitter
  consumer_key: !secret twitter_consumer_key
  consumer_secret: !secret twitter_consumer_secret
  access_token: !secret twitter_access_token
  access_token_secret: !secret twitter_access_secret
