# Created by Danny Tsang <danny@tsang.uk>
- platform: smtp
  name: email_notify
  server: smtp.gmail.com
  port: 587
  timeout: 15
  sender: !secret gmail_sender
  encryption: starttls
  username: !secret gmail_username
  password: !secret gmail_password
  recipient:
    - !secret danny_email
    - !secret terina_email
  sender_name: Home Assistant
- platform: telegram
  name: "Danny"
  chat_id: !secret telegram_danny_chat_id
