# Created by Danny Tsang <danny@tsang.uk>
- platform: season

# All sensor configurations
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: last_boot
    - type: load_1m
    - type: load_5m
    - type: load_15m

- platform: steam_online
  api_key: !secret steam_key
  accounts:
    - !secret steam_account

# Date and Time
- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_iso"
    - "time_date"

# DoubleTake MQTT
- platform: mqtt
  name: Leo Driveway
  icon: mdi:account
  state_topic: "double-take/matches/leo-driveway"
  json_attributes_topic: "double-take/matches/leo-driveway"
  value_template: "{{ value_json.camera }}"
  availability_topic: "double-take/available"
- platform: mqtt
  name: Terina Driveway
  icon: mdi:account
  state_topic: "double-take/matches/terina-driveway"
  json_attributes_topic: "double-take/matches/terina-driveway"
  value_template: "{{ value_json.camera }}"
  availability_topic: "double-take/available"
