# Created by Danny Tsang <danny@tsang.uk>
# All sensor configurations
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: last_boot
    - type: load_1m
    - type: load_5m
    - type: load_15m

# Date and Time
- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_iso"
    - "time_date"

# Fridge
- platform: history_stats
  name: Fridge Opened Today
  entity_id: binary_sensor.fridge_door
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"
- platform: history_stats
  name: Fridge Opened Yesterday
  entity_id: binary_sensor.fridge_door
  state: "on"
  type: time
  end: "{{ now().replace(hour=0, minute=0, second=0) }}"
  duration:
    hours: 24

# Pocket Cast Integration
- platform: pocketcasts
  username: !secret pocketcast_username
  password: !secret pocketcast_password
