# Created by Danny Tsang <danny@tsang.uk>
- platform: season

# All sensor configurations
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: last_boot
    - type: load_1m
    - type: load_5m
    - type: load_15m
- platform: bitcoin
  display_options:
    - exchangerate
    - market_price_usd

- platform: steam_online
  api_key: !secret steam_key
  accounts:
    - !secret steam_account

# Date and Time
- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_iso"
    - "time_date"
