# Created by Danny Tsang <danny@tsang.uk>
# All sensor configurations
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: last_boot
    - type: load_1m
    - type: load_5m
    - type: load_15m
- platform: bitcoin
  display_options:
    - exchangerate
    - market_price_usd
# Aggregated sensors
- platform: min_max
  name: Bedroom Area Temperature
  entity_ids:
    - sensor.bedroom_motion_temperature
    - sensor.bedroom_motion_temperature_2
  type: mean
- platform: min_max
  name: Kitchen Area Temperature
  entity_ids:
    - sensor.kitchen_motion_temperature
    - sensor.kitchen_motion_temperature_2
  type: mean
- platform: min_max
  name: Lounge Area Temperature
  entity_ids:
    - sensor.lounge_motion_temperature
    - sensor.lounge_motion_temperature_2
  type: mean
- platform: min_max
  name: Office Area Temperature
  entity_ids:
    - sensor.office_motion_temperature
    - sensor.office_motion_temperature_2
  type: mean
# Total energy usage using energy@home <https://github.com/dannytsang/energyathome>
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Electricity usage
      query: "SELECT id,date_time,channel_id,data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 18 LIMIT 1) LIMIT 1) AND unit = 'W' AND date_time >= NOW() - INTERVAL 30 MINUTE ORDER BY date_time DESC LIMIT 1;"
      column: "data"
      unit_of_measurement: Wh
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Electricity usage day average
      query: "SELECT channel_id, AVG(data) as data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 18 LIMIT 1) AND unit = 'W' AND date_time >= NOW() - INTERVAL 1 DAY GROUP BY channel_id,unit;"
      column: "data"
      unit_of_measurement: Wh
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Electricity usage week average
      query: "SELECT channel_id, AVG(data) as data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 18 LIMIT 1) AND unit = 'W' AND date_time >= NOW() - INTERVAL 1 WEEK GROUP BY channel_id,unit;"
      column: "data"
      unit_of_measurement: Wh
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Electricity usage month average
      query: "SELECT channel_id, AVG(data) as data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 18 LIMIT 1) AND unit = 'W' AND date_time >= NOW() - INTERVAL 1 MONTH GROUP BY channel_id,unit;"
      column: "data"
      unit_of_measurement: Wh
# Computer A
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: JD electricity usage
      query: "SELECT id,date_time,channel_id,data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 19 LIMIT 1) AND date_time >= NOW() - INTERVAL 30 MINUTE ORDER BY date_time DESC LIMIT 1;"
      column: "data"
      unit_of_measurement: Wh
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: JD electricity usage day average
      query: "SELECT channel_id, AVG(data) as data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 19 LIMIT 1) AND date_time >= NOW() - INTERVAL 1 DAY GROUP BY channel_id,unit;"
      column: "data"
      unit_of_measurement: Wh
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: JD electricity usage week average
      query: "SELECT channel_id, AVG(data) as data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 19 LIMIT 1) AND date_time >= NOW() - INTERVAL 1 WEEK GROUP BY channel_id,unit;"
      column: "data"
      unit_of_measurement: Wh
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: JD electricity usage month average
      query: "SELECT channel_id, AVG(data) as data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 19 LIMIT 1) AND date_time >= NOW() - INTERVAL 1 MONTH GROUP BY channel_id,unit;"
      column: "data"
      unit_of_measurement: Wh
# Computer B
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Server electricity usage
      query: "SELECT id,date_time,channel_id,data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 37 LIMIT 1) AND date_time >= NOW() - INTERVAL 30 MINUTE ORDER BY date_time DESC LIMIT 1;"
      column: "data"
      unit_of_measurement: Wh
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Server electricity usage day average
      query: "SELECT channel_id, AVG(data) as data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 37 LIMIT 1) AND date_time >= NOW() - INTERVAL 1 DAY GROUP BY channel_id,unit;"
      column: "data"
      unit_of_measurement: Wh
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Server electricity usage week average
      query: "SELECT channel_id, AVG(data) as data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 37 LIMIT 1) AND date_time >= NOW() - INTERVAL 1 WEEK GROUP BY channel_id,unit;"
      column: "data"
      unit_of_measurement: Wh
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Server electricity usage month average
      query: "SELECT channel_id, AVG(data) as data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 37 LIMIT 1) AND date_time >= NOW() - INTERVAL 1 MONTH GROUP BY channel_id,unit;"
      column: "data"
      unit_of_measurement: Wh
# Telephony
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Telephony electricity usage
      query: "SELECT id,date_time,channel_id,data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 26 LIMIT 1) AND date_time >= NOW() - INTERVAL 30 MINUTE ORDER BY date_time DESC LIMIT 1;"
      column: "data"
      unit_of_measurement: Wh
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Telephony electricity usage day average
      query: "SELECT channel_id, AVG(data) as data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 26 LIMIT 1) AND date_time >= NOW() - INTERVAL 1 DAY GROUP BY channel_id,unit;"
      column: "data"
      unit_of_measurement: Wh
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Telephony electricity usage week average
      query: "SELECT channel_id, AVG(data) as data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 26 LIMIT 1) AND date_time >= NOW() - INTERVAL 1 WEEK GROUP BY channel_id,unit;"
      column: "data"
      unit_of_measurement: Wh
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Telephony electricity usage month average
      query: "SELECT channel_id, AVG(data) as data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 26 LIMIT 1) AND date_time >= NOW() - INTERVAL 1 MONTH GROUP BY channel_id,unit;"
      column: "data"
      unit_of_measurement: Wh
# Fridge Freezer
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Fridge Freezer electricity usage
      query: "SELECT id,date_time,channel_id,data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 20 LIMIT 1) AND date_time >= NOW() - INTERVAL 30 MINUTE ORDER BY date_time DESC LIMIT 1;"
      column: "data"
      unit_of_measurement: Wh
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Fridge Freezer electricity usage day average
      query: "SELECT channel_id, AVG(data) as data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 20 LIMIT 1) AND date_time >= NOW() - INTERVAL 1 DAY GROUP BY channel_id,unit;"
      column: "data"
      unit_of_measurement: Wh
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Fridge Freezer electricity usage week average
      query: "SELECT channel_id, AVG(data) as data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 20 LIMIT 1) AND date_time >= NOW() - INTERVAL 1 WEEK GROUP BY channel_id,unit;"
      column: "data"
      unit_of_measurement: Wh
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Fridge Freezer electricity usage month average
      query: "SELECT channel_id, AVG(data) as data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 20 LIMIT 1) AND date_time >= NOW() - INTERVAL 1 MONTH GROUP BY channel_id,unit;"
      column: "data"
      unit_of_measurement: Wh
# Freezer
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Freezer electricity usage
      query: "SELECT id,date_time,channel_id,data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 28 LIMIT 1) AND date_time >= NOW() - INTERVAL 30 MINUTE ORDER BY date_time DESC LIMIT 1;"
      column: "data"
      unit_of_measurement: Wh
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Freezer electricity usage day average
      query: "SELECT channel_id, AVG(data) as data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 28 LIMIT 1) AND date_time >= NOW() - INTERVAL 1 DAY GROUP BY channel_id,unit;"
      column: "data"
      unit_of_measurement: Wh
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Freezer electricity usage week average
      query: "SELECT channel_id, AVG(data) as data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 28 LIMIT 1) AND date_time >= NOW() - INTERVAL 1 WEEK GROUP BY channel_id,unit;"
      column: "data"
      unit_of_measurement: Wh
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Freezer electricity usage month average
      query: "SELECT channel_id, AVG(data) as data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 28 LIMIT 1) AND date_time >= NOW() - INTERVAL 1 MONTH GROUP BY channel_id,unit;"
      column: "data"
      unit_of_measurement: Wh
# Home Entertainment
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Home Entertainment electricity usage
      query: "SELECT id,date_time,channel_id,data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 21 LIMIT 1) AND date_time >= NOW() - INTERVAL 30 MINUTE ORDER BY date_time DESC LIMIT 1;"
      column: "data"
      unit_of_measurement: Wh
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Home Entertainment electricity usage day average
      query: "SELECT channel_id, AVG(data) as data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 21 LIMIT 1) AND date_time >= NOW() - INTERVAL 1 DAY GROUP BY channel_id,unit;"
      column: "data"
      unit_of_measurement: Wh
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Home Entertainment electricity usage week average
      query: "SELECT channel_id, AVG(data) as data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 21 LIMIT 1) AND date_time >= NOW() - INTERVAL 1 WEEK GROUP BY channel_id,unit;"
      column: "data"
      unit_of_measurement: Wh
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Home Entertainment electricity usage month average
      query: "SELECT channel_id, AVG(data) as data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 21 LIMIT 1) AND date_time >= NOW() - INTERVAL 1 MONTH GROUP BY channel_id,unit;"
      column: "data"
      unit_of_measurement: Wh
# Surround Sound
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Surround Sound electricity usage
      query: "SELECT id,date_time,channel_id,data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 29 LIMIT 1) AND date_time >= NOW() - INTERVAL 30 MINUTE ORDER BY date_time DESC LIMIT 1;"
      column: "data"
      unit_of_measurement: Wh
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Surround Sound electricity usage day average
      query: "SELECT channel_id, AVG(data) as data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 29 LIMIT 1) AND date_time >= NOW() - INTERVAL 1 DAY GROUP BY channel_id,unit;"
      column: "data"
      unit_of_measurement: Wh
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Surround Sound electricity usage week average
      query: "SELECT channel_id, AVG(data) as data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 29 LIMIT 1) AND date_time >= NOW() - INTERVAL 1 WEEK GROUP BY channel_id,unit;"
      column: "data"
      unit_of_measurement: Wh
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Surround Sound electricity usage month average
      query: "SELECT channel_id, AVG(data) as data,unit as unit_of_measurement FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 29 LIMIT 1) AND date_time >= NOW() - INTERVAL 1 MONTH GROUP BY channel_id,unit;"
      column: "data"
      unit_of_measurement: Wh
# Templates
- platform: template
  sensors:
    bedroom_tv_plug_current_w:
      value_template: "{{ state_attr('switch.bedroom_tv_plug','current_power_w') | float }}"
      friendly_name: "Bedroom TV current power"
      unit_of_measurement: "Wh"
      icon_template: mdi:flash
    tv_plug_current_w:
      value_template: "{{ state_attr('switch.tv_plug','current_power_w') | float }}"
      friendly_name: "TV current power"
      unit_of_measurement: "Wh"
      icon_template: mdi:flash
    sky_plug_current_w:
      value_template: "{{ state_attr('switch.sky_plug','current_power_w') | float }}"
      friendly_name: "Sky current power"
      unit_of_measurement: "Wh"
      icon_template: mdi:flash
    # Pi Hole totals from different entities
    pi_hole_total_ads_blocked_today:
      value_template: "{{ states('sensor.pi_hole_ads_blocked_today') | int + states('sensor.pi_hole_secondary_ads_blocked_today') | int }}"
      friendly_name: "Pi-Hole Total Ads Blocked Today"
      unit_of_measurement: "ads"
    pi_hole_total_ads_percentage_blocked_today:
      value_template: "{{ states('sensor.pi_hole_ads_percentage_blocked_today') | int + states('sensor.pi_hole_secondary_ads_percentage_blocked_today') | int / 2 | float }}"
      friendly_name: "Pi-Hole Total Ads Percentage Blocked Today"
      unit_of_measurement: "%"
    pi_hole_total_dns_queries_cached:
      value_template: "{{ states('sensor.pi_hole_dns_queries_cached') | int + states('sensor.pi_hole_secondary_dns_queries_cached') | int }}"
      friendly_name: "Pi-Hole Total DNS Queries Cached"
      unit_of_measurement: "queries"
    pi_hole_total_dns_queries_forwarded:
      value_template: "{{ states('sensor.pi_hole_dns_queries_forwarded') | int + states('sensor.pi_hole_secondary_dns_queries_forwarded') | int }}"
      friendly_name: "Pi-Hole Total DNS Queries Forwarded"
      unit_of_measurement: "queries"
    pi_hole_total_dns_queries_today:
      value_template: "{{ states('sensor.pi_hole_dns_queries_today') | int + states('sensor.pi_hole_secondary_dns_queries_today') | int }}"
      friendly_name: "Pi-Hole Total DNS Queries Today"
      unit_of_measurement: "queries"
    pi_hole_total_dns_unique_clients:
      value_template: "{{ states('sensor.pi_hole_dns_unique_clients') | int + states('sensor.pi_hole_secondary_dns_unique_clients') | int }}"
      friendly_name: "Pi-Hole Total DNS Unique Clients"
      unit_of_measurement: "clients"
    pi_hole_total_dns_unique_domains:
      value_template: "{{ states('sensor.pi_hole_dns_unique_domains') | int + states('sensor.pi_hole_secondary_dns_unique_domains') | int }}"
      friendly_name: "Pi-Hole Total DNS Unique Domains"
      unit_of_measurement: "domains"
    pi_hole_total_domains_blocked:
      value_template: "{{ states('sensor.pi_hole_domains_blocked') | int + states('sensor.pi_hole_secondary_domains_blocked') | int }}"
      friendly_name: "Pi-Hole Total Domains Blocked"
      unit_of_measurement: "domains"
    pi_hole_total_seen_clients:
      value_template: "{{ states('sensor.pi_hole_seen_clients') | int + states('sensor.pi_hole_secondary_seen_clients') | int }}"
      friendly_name: "Pi-Hole Total Seen Clients"
      unit_of_measurement: "clients"
    # TP Link Switches
    my_tp_switch_amps:
      friendly_name_template: "Office Fan Current"
      value_template: '{{ states.switch.office_fan.attributes["current_a"] | float }}'
      unit_of_measurement: "A"
    my_tp_switch_watts:
      friendly_name_template: "Office Fan Current Consumption"
      value_template: '{{ states.switch.office_fan.attributes["current_power_w"] | float }}'
      unit_of_measurement: "W"
    my_tp_switch_total_kwh:
      friendly_name_template: "Office Fan Total Consumption"
      value_template: '{{ states.switch.office_fan.attributes["total_energy_kwh"] | float }}'
      unit_of_measurement: "kWh"
    my_tp_switch_volts:
      friendly_name_template: "Office Fan Voltage"
      value_template: '{{ states.switch.office_fan.attributes["voltage"] | float }}'
      unit_of_measurement: "V"
    my_tp_switch_today_kwh:
      friendly_name_template: "Office Fan Today's Consumption"
      value_template: '{{ states.switch.office_fan.attributes["today_energy_kwh"] | float }}'
      unit_of_measurement: "kWh"
