image_analyzer:
  name: Image Analyzer
  description: Analyze an image with AI
  fields:
    provider:
      name: Provider
      description: 'Configuration to use'
      required: true
      selector:
        config_entry:
          integration: llmvision
    model:
      name: Model
      required: false
      description: 'Model to use. Uncheck for default.'
      example: "gpt-4o-mini"
      selector:
        text:
          multiline: false
    message:
      name: Prompt
      required: true
      description: 'Model prompt'
      example: "Describe the image"
      selector:
        text:
          multiline: true
    image_file:
      name: Image File
      required: false
      description: 'Local path to image'
      example: "/config/www/tmp/front_door.jpg"
      selector:
        text:
          multiline: true
    image_entity:
      name: Image Entity
      required: false
      description: 'Image or camera entity to analyze'
      example: 'image.front_door_person'
      selector:
        entity:
          domain: ["image", "camera"]
          multiple: true
    include_filename:
      name: Include Filename
      required: true
      description: 'Include filename in the request'
      example: false
      default: false
      selector:
        boolean:
    target_width:
      name: Target Width
      required: false
      description: 'Width in pixels to downscale'
      example: 1280
      default: 1280
      selector:
        number:
          min: 512
          max: 1920
    detail:
      name: Detail
      required: false
      description: "Detail parameter. Leave empty for 'auto'"
      default: 'low'
      example: 'low'
      selector:
        select:
          options:
            - 'high'
            - 'low'
    max_tokens:
      name: Maximum Tokens
      description: 'Maximum number of tokens to generate'
      required: true
      example: 100
      default: 100
      selector:
        number:
          min: 1
          max: 300
    temperature:
      name: Temperature
      required: true
      description: 'Randomness. Lower is more accurate, higher is more creative'
      example: 0.2
      default: 0.2
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1

video_analyzer:
  name: Video Analyzer
  description: Analyze video with AI
  fields:
    provider:
      name: Provider
      description: 'Configuration to use'
      required: true
      selector:
        config_entry:
          integration: llmvision
    model:
      name: Model
      required: false
      description: 'Model to use. Uncheck for default.'
      example: "gpt-4o-mini"
      selector:
        text:
          multiline: false
    message:
      name: Prompt
      required: true
      description: 'Model prompt'
      example: "Describe what happens in the video"
      selector:
        text:
          multiline: true
    video_file:
      name: Video File
      required: false
      description: 'Local path to video'
      example: "/config/www/recordings/front_door.mp4"
      selector:
        text:
          multiline: true
    event_id:
      name: Frigate Event ID
      required: false
      description: 'Frigate Event ID'
      example: 1712108310.968815-r28cdt
      selector:
        text:
          multiline: true
    interval:
      name: Interval
      description: "DEPRECATED: Use max_frames. Analyze frames every <interval> seconds."
      required: false
      example: 3
      default: 3
      selector:
        number:
          min: 1
          max: 60
    max_frames:
      name: Max Frames
      description: How many frames to analyze. Picks frames with the most movement.
      required: false
      example: 3
      default: 3
      selector:
        number:
          min: 1
          max: 10
          step: 1
    include_filename:
      name: Include Filename
      required: true
      description: 'Include filename in the request'
      example: false
      default: false
      selector:
        boolean:
    target_width:
      name: Target Width
      required: false
      description: 'Width in pixels to downscale'
      example: 1280
      default: 1280
      selector:
        number:
          min: 512
          max: 1920
    detail:
      name: Detail
      required: false
      description: "Detail parameter, leave empty for 'auto'"
      default: 'low'
      example: 'low'
      selector:
        select:
          options:
            - 'high'
            - 'low'
    max_tokens:
      name: Maximum Tokens
      description: 'Maximum number of tokens to generate'
      required: true
      example: 100
      default: 100
      selector:
        number:
          min: 1
          max: 300
    temperature:
      name: Temperature
      required: true
      description: 'Randomness. Lower is more accurate, higher is more creative'
      example: 0.2
      default: 0.2
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.1

stream_analyzer:
  name: Stream Analyzer
  description: Analyze a live camera stream with AI
  fields:
    provider:
      name: Provider
      description: 'Configuration to use'
      required: true
      selector:
        config_entry:
          integration: llmvision
    model:
      name: Model
      required: false
      description: 'Model to use. Uncheck for default.'
      example: "gpt-4o-mini"
      selector:
        text:
          multiline: false
    message:
      name: Prompt
      required: true
      description: 'Model prompt'
      example: "Describe what happens in the camera feed"
      selector:
        text:
          multiline: true
    image_entity:
      name: Camera Entity
      required: true
      description: 'Camera entity to stream'
      example: 'camera.front_door'
      selector:
        entity:
          domain: ["camera"]
          multiple: true
    interval:
      name: Interval
      description: "DEPRECATED: Use max_frames. Analyze frames every <interval> seconds."
      required: false
      example: 2
      default: 2
      selector:
        number:
          min: 1
          max: 10
    duration:
      name: Recording Duration
      required: true
      description: 'How long to record in seconds'
      example: 5
      default: 5
      selector:
        number:
          min: 1
          max: 60
    max_frames:
      name: Max Frames
      description: How many frames to analyze. Picks frames with the most movement.
      required: false
      example: 3
      default: 3
      selector:
        number:
          min: 1
          max: 10
          step: 1
    include_filename:
      name: Include camera name
      required: true
      description: 'Include camera name in request'
      example: false
      default: false
      selector:
        boolean:
    target_width:
      name: Target Width
      required: false
      description: 'Width in pixels to downscale'
      example: 1280
      default: 1280
      selector:
        number:
          min: 512
          max: 1920
    detail:
      name: Detail
      required: false
      description: "Detail parameter, leave empty for 'auto'"
      default: 'low'
      example: 'low'
      selector:
        select:
          options:
            - 'high'
            - 'low'
    max_tokens:
      name: Maximum Tokens
      description: 'Maximum number of tokens to generate'
      required: true
      example: 100
      default: 100
      selector:
        number:
          min: 1
          max: 300
    temperature:
      name: Temperature
      required: true
      description: 'Randomness. Lower is more accurate, higher is more creative'
      example: 0.2
      default: 0.2
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1