image_analyzer:
  name: LLM Vision Image Analyzer
  description: Analyze an image with AI
  fields:
    provider:
      name: Provider
      description: 'Provider to use'
      required: true
      default: 'OpenAI'
      selector:
        select:
          options:
            - 'OpenAI'
            - 'Anthropic'
            - 'Google'
            - 'Ollama'
            - 'LocalAI'
    model:
      name: Model
      required: false
      description: 'Model to use'
      example: "gpt-4o"
      default: "gpt-4o"
      selector:
        text:
          multiline: false
    message:
      name: Prompt
      required: true
      description: 'Prompt'
      example: "Describe the person present in the photo"
      selector:
        text:
          multiline: true
    image_file:
      name: Image File
      required: false
      description: 'Local path to image'
      example: "/config/www/images/img.jpg"
      selector:
        text:
          multiline: true
    image_entity:
      name: Image Entity
      required: false
      description: 'Image or camera entity to analyze'
      example: 'image.front_door_person'
      selector:
        entity:
          domain: ["image", "camera"]
          multiple: true
    include_filename:
      name: Include Filename
      required: false
      description: 'Include filename in the request'
      default: false
      selector:
        boolean:
    target_width:
      name: Target Width
      required: false
      description: 'Width in pixels to downscale to'
      example: 1280
      default: 1280
      selector:
        number:
          min: 512
          max: 3840
    detail:
      name: Detail
      required: false
      description: "Detail parameter, leave empty for 'auto'"
      default: 'high'
      selector:
        select:
          options:
            - 'high'
            - 'low'
    max_tokens:
      name: Maximum Tokens
      description: 'Maximum number of tokens to generate'
      required: true
      example: 100
      default: 100
      selector:
        number:
          min: 10
          max: 1000
    temperature:
      name: Temperature
      required: true
      description: 'Randomness. Lower is more accurate, higher is more creative'
      example: 0.5
      default: 0.5
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.1