# Created by Danny Tsang <danny@tsang.uk>
automation:
  # region Callback router
  - id: "1625924056779"
    alias: Mobile Notification Action Router
    description: ""
    triggers:
      - trigger: event
        event_type: mobile_app_notification_action
        event_data: {}
    conditions: []
    actions:
      - choose:
          - conditions:
              - condition: template
                value_template:
                  "{{ trigger.event.data.action == 'set_bedroom_blinds_30'
                  }}"
              - condition: numeric_state
                entity_id: cover.bedroom_blinds
                attribute: current_position
                above: 30
            sequence:
              - action: script.send_to_home_log
                data:
                  message: "🪟 Closing bedroom blinds event received."
              - action: cover.set_cover_position
                target:
                  entity_id: cover.bedroom_blinds
                data:
                  position: 30
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.action == 'server_fan_off' }}"
            sequence:
              - action: script.send_to_home_log
                data:
                  message: Turning off server fan event received.
              - action: switch.turn_off
                target:
                  entity_id: switch.server_fan
          - conditions:
              - condition: template
                value_template:
                  "{{ trigger.event.data.action == 'switch_on_office_fan'
                  }}"
            sequence:
              - action: script.send_to_home_log
                data:
                  message: Turning on office fan event received.
              - action: switch.turn_on
                target:
                  entity_id: switch.office_fan
          - conditions:
              - condition: template
                value_template:
                  "{{ trigger.event.data.action == 'switch_on_fridge_freezer'
                  }}"
            sequence:
              - action: script.send_to_home_log
                data:
                  message: Turning on fridge freezer event received.
              - action: switch.turn_on
                target:
                  entity_id: switch.ecoflow_kitchen_plug
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.action == 'switch_on_freezer' }}"
            sequence:
              - action: script.send_to_home_log
                data:
                  message: Turning on freezer event received.
              - action: switch.turn_on
                target:
                  entity_id: switch.freezer
          - conditions:
              - condition: template
                value_template:
                  "{{ trigger.event.data.action == 'guest_mode_arm_alarm_and_turn_off_devices'
                  }}"
            sequence:
              - action: script.send_to_home_log
                data:
                  message: "🔔 Guest mode override. Turning alarm on and devices off."
              - action: script.set_alarm_to_away_mode
              - action: script.lock_front_door
              - action: script.everybody_leave_home
          - conditions:
              - condition: template
                value_template:
                  "{{ trigger.event.data.action == 'guest_mode_arm_alarm_away'
                  }}"
              - condition: state
                entity_id: input_select.home_mode
                state: "Guest"
            sequence:
              - action: script.send_to_home_log
                data:
                  message:
                    "🔔 Guest mode override. Turning alarm in away mode (motion
                    and sensors) on only."
              - action: script.set_alarm_to_away_mode
              - action: script.lock_front_door
          - conditions:
              - condition: template
                value_template:
                  "{{ trigger.event.data.action == 'guest_mode_turn_off_devices'
                  }}"
            sequence:
              - action: script.send_to_home_log
                data:
                  message: Guest mode override. Turning devices off only.
              - action: script.everybody_leave_home
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.action == 'switch_off_alarm' }}"
            sequence:
              - action: script.send_to_home_log
                data:
                  message: Alarm override. Turning Alarm off.
              - action: script.set_alarm_to_disarmed_mode
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.action == 'switch_off_attic_lights' }}"
            sequence:
              - action: script.send_to_home_log
                data:
                  message: Turning attic lights off event.
              - action: light.turn_off
                data: {}
                target:
                  entity_id: light.attic
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.action == 'update_home_assistant' }}"
            sequence:
              - action: script.send_to_home_log
                data:
                  message: Upgrade Home Assistant event.
              - action: update.install
                data:
                  backup: true
                target:
                  entity_id: update.home_assistant_core_update
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.action == 'zappi_stop' }}"
            sequence:
              - action: script.send_to_home_log
                data:
                  message: Stop Zappi event.
              - action: select.select_option
                data:
                  option: Stopped
                target:
                  entity_id: select.myenergi_zappi_charge_mode
        default: []
    mode: queued
    max: 10