# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://www.home-assistant.io/integrations/signal_messenger/
automation:
  - id: "1743359583659"
    alias: "Signal: Message Received"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - sensor.signal_message_received
    conditions: []
    actions:
      - action: script.send_direct_notification
        metadata: {}
        data:
          people:
            entity_id:
              - person.danny
          message: Signal Message Received
          title: Signal
    mode: queued
    max: 10

notify:
  - name: signal_danny
    platform: signal_messenger
    url: !secret signal_api_server
    number: !secret signal_phone_number
    recipients:
      - !secret signal_recipient1

rest:
  - resource: !secret signal_receive_url
    headers:
      Content-Type: application/json
    sensor:
      - name: "Signal message received"
        value_template: ""  # this will fetch the message
        json_attributes_path: $[0].envelope
        json_attributes:
          - source  # sender phone number

script:
  post_signal_notification:
    alias: Post Signal Message
    icon: mdi:message-reply
    description: >-
      Post a text message to Signal. Please use a send script to
      decouple from the messaging platform.
    fields:
      message:
        description: Message to post
        required: true
        selector:
          text:
            multiline: true
      title:
        description: (optional)Title to the message posted.
        selector:
          text:
    sequence:
      - choose:
          # Check a title was set
          - conditions:
              - condition: template
                value_template: "{{ title|default(none, true) is not none }}"
            sequence:
              - action: notify.signal_danny
                data:
                  message: >-
                    **{{ title }}**

                    {{ message }}
                  title: ""
                  data:
                    text_mode: styled
        default:
          - action: notify.signal_danny
            data:
              message: >-
                {{ message }}
              data:
                text_mode: styled
        continue_on_error: true
    mode: queued
    max: 10
  post_to_signal_with_url_attachment:
    alias: "Post To signal With URL"
    icon: mdi:message-image
    description: >-
      Post a message with a URL attachment. Only a URL can be set. Not both or neither. Please use a
      send script to decouple from the messaging platform."
    fields:
      message:
        description: Message to post
        required: true
        selector:
          text:
            multiline: true
      title:
        description: (optional)Title to the message posted.
        selector:
          text:
      url:
        description: Link to file.
        example: "https://picsum.photos/200/300"
        required: true
        selector:
          text:
            type: "url"
    sequence:
      # Check if a title has been set
      - choose:
          # Check at least filePath or url is set.
          - conditions:
              - condition: template
                value_template: "{{ title|default(none, true) is not none }}"
            sequence:
              - action: notify.signal_danny
                data:
                  message: >-
                    {{ message }}
                  title: "{{ title|default('', true) }}"
                  target: "{{ target }}"
                  data:
                    verify_ssl: false
                    urls:
                      - "{{ url }}"
        # No title set
        default:
          - action: notify.signal_danny
            data:
              message: >-
                {{ message }}
              title: "{{ title|default('', true) }}"
              target: "{{ target }}"
              data:
                verify_ssl: false
                urls:
                  - "{{ url }}"
        continue_on_error: true
    mode: queued
    max: 10
  post_to_signal_with_local_attachments:
    alias: "Post To signal With File Attachments"
    icon: mdi:message-image
    description: >-
      Post a message with a file. Only a file can be set. Not both or neither. Please use a
      send script to decouple from the messaging platform.
    fields:
      message:
        description: Message to post
        required: true
        selector:
          text:
            multiline: true
      title:
        description: (optional)Title to the message posted.
        selector:
          text:
      filePath:
        description: File path to attach to post.
        required: true
        selector:
          text:
    sequence:
      - action: notify.signal_danny
        data:
          message: >-
            {{ message }}
          title: "{{ title|default('', true) }}"
          target: "{{ target }}"
          data:
            attachments:
              - "{{ filePath }}"
        continue_on_error: true
    mode: queued
    max: 10
