# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://www.home-assistant.io/integrations/slack/
automation:
  - id: "1689193654844"
    alias: "Slack: Command Received"
    description: "Slack bot command."
    trigger:
      - platform: webhook
        allowed_methods:
          - POST
          - PUT
        local_only: false
        webhook_id: -aPu0u0W8nvlYImwa85lwDMoo
    condition: []
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: |-
                user_id: {{ trigger.data.user_id }}
                user_name: {{ trigger.data.user_name }}
                channel_id: {{ trigger.data.channel_id }}
                channel_name: {{ trigger.data.channel_name }}
                command: {{ trigger.data.command }}
                text: {{ trigger.data.text }}
                response_url: {{ trigger.data.response_url }}
              title: Slack
              log_level: "Debug"
          - if:
              - condition: template
                value_template: "{{ trigger.data.channel_name != 'privategroup' }}"
            then:
              - choose:
                  - alias: "Message from Danny"
                    conditions:
                      - condition: template
                        value_template: "{{ trigger.data.user_id|string|default('', true)  == states('input_text.dannys_slack_id') }}"
                    sequence:
                      - service: conversation.process
                        data:
                          agent_id: "{{ states('input_text.dannys_selected_conversation_agent') }}"
                          text: "{{ trigger.data.text }}"
                        response_variable: assist
                      - if:
                          - condition: template
                            value_template: >-
                              {{ assist.response.response_type|default(none, true)  != none and
                              assist.response.response_type == 'error'}}
                        then:
                          - parallel:
                            - service: script.post_slack_notification
                              data:
                                message: >-
                                  {%- set wait_response = ['hmm...', 'thinking...', '...', 'er...', 'um...', 'well'] -%}
                                  {{ wait_response[range(0, wait_response|length)|random] }}
                                title: "{{ trigger.data.text }}"
                                people: "{{ '<@'~trigger.data.user_name~'>' }}"
                                target: "{{ trigger.data.channel_name }}"
                            - service: conversation.process
                              data:
                                agent_id: "{{ states('input_text.dannys_secondary_selected_conversation_agent') }}"
                                text: "{{ trigger.data.text }}"
                              response_variable: assist
                      - service: script.post_slack_notification
                        data:
                          message: "{{ assist.response.speech.plain.speech }}"
                          title: "{{ trigger.data.text }}"
                          people: "{{ '<@'~trigger.data.user_name~'>' }}"
                          target: "{{ trigger.data.channel_name }}"
            else:
              - service: script.send_to_home_log
                data:
                  message: |-
                    user_id: {{ trigger.data.user_id }}
                    user_name: {{ trigger.data.user_name }}
                    channel_id: {{ trigger.data.channel_id }}
                    channel_name: {{ trigger.data.channel_name }}
                    command: {{ trigger.data.command }}
                    text: {{ trigger.data.text }}
                    response_url: {{ trigger.data.response_url }}
                  title: Slack
                  log_level: "Normal"
    mode: queued
    max: 10

script:
  post_slack_notification:
    alias: Post Slack Message
    icon: mdi:message-reply
    description: "Post a text message to Slack. Please use a send script to
    decouple from the messaging platform."
    fields:
      message:
        description: Message to post
        required: true
        selector:
          text:
            multiline: true
      title:
        description: (optional)Title to the message posted.
        selector:
          text:
      people:
        description: (optional)Slack user ID to message.
        example: "<@ABCDEFG>"
        selector:
          text:
      target:
        description: Slack channel to post the message to without the hash symbol.
        required: true
        example: "general"
        selector:
          text:
    sequence:
      - choose:
        # Check a title was set
        - conditions:
            - condition: template
              value_template: "{{ title|default(none, true) is not none }}"
          sequence:
            - service: notify.danny_tsang
              data:
                message: >-
                  {{ iif(people is not none,people|default('', true)~' ','') }}
                  {%- from 'process_messages.jinja' import process_messages -%}
                  {{ process_messages(message, 'Slack') }}
                target: "{{ target }}"
                data:
                  blocks:
                    - type: header
                      text:
                        type: "plain_text"
                        text: "{{ title }}"
                        emoji: true
                    - type: section
                      text:
                        type: mrkdwn
                        text: >-
                          {{ iif(people is not none,people|default('', true)~' ','') }}
                          {%- from 'process_messages.jinja' import process_messages -%}
                          {{ process_messages(message, 'Slack') }}
        default:
          - service: notify.danny_tsang
            data:
              message: >-
                {{ iif(people is not none,people|default('', true)~' ','') }}
                {{ message }}
              target: "{{ target }}"
              data:
                blocks:
                - type: section
                  text:
                    type: mrkdwn
                    text: >-
                      {{ iif(people is not none,people|default('', true)~' ','') }}
                      {%- from 'process_messages.jinja' import process_messages -%}
                      {{ process_messages(message, 'Slack') }}
        continue_on_error: true
    mode: queued
    max: 10
  post_to_slack_with_url_attachment:
    alias: "Post To Slack Home Log With File Or URL Attachments"
    icon: mdi:message-image
    description: >-
      Post a message with a file or URL attachment to the home_log
      channel. Only a file or URL can be set. Not both or neither. Please use a
      send script to decouple from the messaging platform."
    fields:
      message:
        description: Message to post
        required: true
        selector:
          text:
            multiline: true
      title:
        description: (optional)Title to the message posted.
        selector:
          text:
      target:
        description: Slack channel to post the message to without the hash symbol.
        required: true
        example: "general"
        selector:
          text:
      people:
        description: (optional)Slack user ID to message.
        example: "<@ABCDEFG>"
        selector:
          text:
      url:
        description: Link to file.
        example: "https://picsum.photos/200/300"
        selector:
          text:
            type: "url"
    sequence:
      # Check if a title has been set
      - choose:
          # Check at least filePath or url is set.
          - conditions:
              - condition: template
                value_template: "{{ title|default(none, true) is not none }}"
            sequence:
              - service: notify.danny_tsang
                data:
                  message: >-
                    {% from 'process_messages.jinja' import process_messages %}
                    {{ process_messages(message, 'Slack') }}
                  title: "{{ title|default('', true) }}"
                  target: "{{ target }}"
                  data:
                    blocks:
                      - type: header
                        text:
                          type: "plain_text"
                          text: "{{ title }}"
                          emoji: true
                      - type: section
                        text:
                          type: mrkdwn
                          text: >-
                            {{ iif(people is not none,people|default('', true)~' ','') }}
                            {% from 'process_messages.jinja' import process_messages %}
                            {{ process_messages(message, 'Slack') }}
                        accessory:
                          type: image
                          image_url: "{{ url }}"
                          alt_text: "{{ title|default('Failed to load image', true) }}"
        # No title set
        default:
          - service: notify.danny_tsang
            data:
              message: >-
                {{ iif(people is not none,people|default('', true)~' ','') }}
                {% from 'process_messages.jinja' import process_messages %}
                {{ process_messages(message, 'Slack') }}
              title: "{{ title|default('', true) }}"
              target: "{{ target }}"
              data:
                blocks:
                  - type: section
                    text:
                      type: mrkdwn
                      text: >-
                        {% from 'process_messages.jinja' import process_messages %}
                        {{ process_messages(message, 'Slack') }}
                    accessory:
                      type: image
                      image_url: "{{ url }}"
                      alt_text: "{{ title|default('Failed to load image', true) }}"
        continue_on_error: true
    mode: queued
    max: 10
  post_to_slack_with_local_attachments:
    alias: "Post To Slack Home Log With File Or URL Attachments"
    icon: mdi:message-image
    description: >-
      Post a message with a file or URL attachment to the home_log
      channel. Only a file or URL can be set. Not both or neither. Please use a
      send script to decouple from the messaging platform.
    fields:
      message:
        description: Message to post
        required: true
        selector:
          text:
            multiline: true
      title:
        description: (optional)Title to the message posted.
        selector:
          text:
      target:
        description: Slack channel to post the message to without the hash symbol.
        required: true
        example: "general"
        selector:
          text:
      people:
        description: (optional)Slack user ID to message.
        example: "<@ABCDEFG>"
        selector:
          text:
      filePath:
        description: File path to attach to post.
        required: true
        selector:
          text:
    sequence:
      - service: notify.danny_tsang
        data:
          message: >-
            {{ iif(people is not none,people|default('', true)~' ','') }}
            {% from 'process_messages.jinja' import process_messages %}
            {{ process_messages(message, 'Slack') }}
          title: "{{ title|default('', true) }}"
          target: "{{ target }}"
          data:
            file:
              path: "{{ filePath }}"
        continue_on_error: true
    mode: queued
    max: 10
