esphome:
  name: living-room-motion-2
  friendly_name: living-room-motion-2

substitutions:
  name: "living-room-motion-2"
  friendly_name: "living-room-motion-2"
  illuminance_update_interval: "2s"
  hidden_ssid: "false"
  log_level: DEBUG

update:
  - platform: http_request
    id: update_http_request
    name: Everything Presence Lite Firmware
    source: https://everythingsmarthome.github.io/everything-presence-lite/everything-presence-lite-ha-co2-manifest.json
    disabled_by_default: true

dashboard_import:
  package_import_url: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha-co2.yaml@main
  import_full_config: false # or true

packages:
  device_base: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha-co2.yaml@main

esp32_ble_tracker:
  scan_parameters:
    active: true  # Whether to send scan-request packets to devices to gather more info (like devicename)
    interval: 320ms  # suggested 211ms # default 320ms
    window: 300ms  # suggested 120ms # default 30ms

bluetooth_proxy:
  active: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
