start:
  description: Start the presence simulation
  fields:
    entity_id:
      description: The list of entities to use by the presence simulation to override the list configured in the component
      example: >
            - group.outside_lights
    delta:
      description: Override the default number of days used by the simulation
      example: 7
    restore_states:
      description: Override the default restore switch. If set, the states will be restored after the simulation
      example: True
    random:
      description: Add a random factor (in seconds) to the historic events
      example: 300
stop:
  description: Stop the presence simulation
toggle:
  description: Toggle the presence simulation
