start:
  name: Presence simulation start
  description: Start the presence simulation
  fields:
    entity_id:
      name: Entities list
      description: The list of entities to use by the presence simulation to override the list configured in the component
      example: >
            - group.outside_lights
    delta:
      name: Delta
      description: Override the default number of days used by the simulation
      example: 7
    restore_states:
      name: Should presence simulation status be restored after restart
      description: Override the default restore switch. If set, the states will be restored after the simulation
      example: True
    random:
      name: Activate random
      description: Add a random factor (in seconds) to the historic events
      example: 300
stop:
  description: Stop the presence simulation
  name: Presence simulation stop
toggle:
  description: Toggle the presence simulation
  name: Presence simulation toggle
