# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://github.com/CJNE/ha-myenergi
automation:
  # myEnergi
  - id: "1677762423485"
    alias: "Energy: Eddi Diverting Energy"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - sensor.myenergi_eddi_status
        to: "Diverting"
    conditions:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.myenergi_eddi_energy_consumed_session_daily
            state: "unknown"
      - condition: state
        entity_id: input_boolean.enable_hot_water_automations
        state: "on"
    actions:
      - action: script.send_to_home_log
        data:
          message: >-
            :fuelpump: Eddi diverting energy.

            It has diverted {{ states('sensor.myenergi_eddi_energy_consumed_session_daily',
            with_unit=True) }} so far.
          title: myEnergi
          log_level: "Debug"
    mode: queued
    max: 10
  - id: "1685005214749"
    alias: "HVAC: Eddi Turn On"
    description: ""
    triggers:
      - trigger: time
        at: "00:00:00"
      - trigger: time
        at: "13:00:00"
    conditions:
      - condition: state
        entity_id: select.myenergi_eddi_operating_mode
        state: "Stopped"
      - not:
          - condition: state
            entity_id: input_select.home_mode
            state: "Holiday"
      - condition: state
        entity_id: input_boolean.enable_hot_water_automations
        state: "on"
      - condition: state
        entity_id: input_boolean.enable_eddi_automatic_reset
        state: "on"
    actions:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: >-
                :clock{{ now().strftime('%I') | int }}{% if now().minute | int >
                25 and now().minute | int < 35 %}30{% else %}{% endif %}: Turning :fuelpump:
                Eddi back on.
              title: myEnergi
              log_level: "Debug"
          - action: timer.cancel
            target:
              entity_id: timer.eddi_max_temperature_reached
            data: {}
          - action: select.select_option
            data:
              option: Normal
            target:
              entity_id: select.myenergi_eddi_operating_mode
    mode: single
  - id: "1678578286486"
    alias: "HVAC: Eddi Generated Hot Water And Hot Water Is On"
    description: ""
    triggers:
      - trigger: numeric_state
        entity_id: sensor.myenergi_eddi_energy_consumed_per_heating_cycle
        above: input_number.hot_water_solar_diverter_boiler_cut_off
    conditions:
      - condition: state
        entity_id: input_boolean.enable_hot_water_automations
        state: "on"
      - condition: state
        entity_id: water_heater.thermostat
        state: "on"
    actions:
      - action: script.send_to_home_log
        data:
          message: >-
            Eddi has heated enough hot water
            {{ states('sensor.myenergi_eddi_energy_consumed_per_heating_cycle') }}
            in the last 6 hours
            (> {{ states('input_number.hot_water_solar_diverter_boiler_cut_off')|float(0) }})
            {{ state_attr('sensor.myenergi_eddi_energy_consumed_session', 'unit_of_measurement') }}
            and the hot water is on.

            Turning off hot water.
          title: ":hotsprings: Central Heating"
          log_level: "Normal"
      - action: script.set_hot_water_to_home_mode
        data: {}
    mode: single
  - id: "1712238362391"
    alias: "Eddi: Max Temperature Reached"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - sensor.myenergi_eddi_status
        to: Max temp reached
    conditions:
      - condition: state
        entity_id: input_boolean.enable_hot_water_automations
        state: "on"
    actions:
      - parallel:
          - action: script.send_to_home_log
            metadata: {}
            data:
              message: Hot water tank reached max temperature.
              title: Eddi
              log_level: Debug
          - action: timer.start
            target:
              entity_id: timer.eddi_max_temperature_reached
            data:
              duration: "04:00:00"
          - action: script.hvac_check_eddi_boost_hot_water
            data:
              current_electricity_import_rate: "{{ states('sensor.electricity_current_rate') }}"
    mode: single

script:
  hvac_set_solar_diverter_to_holiday_mode:
    alias: HVAC Set Solar Diverter To Holiday Mode
    sequence:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: >-
                Turning :fuelpump: Eddi back on.
              title: myEnergi
              log_level: "Normal"
          - action: select.select_option
            data:
              option: Stopped
            target:
              entity_id: select.myenergi_eddi_operating_mode
    mode: single
    icon: mdi:gas-station
  hvac_set_solar_diverter_to_normal_mode:
    alias: HVAC Set Solar Diverter To normal Mode
    sequence:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: >-
                Turning :fuelpump: Eddi back on.
              title: myEnergi
              log_level: "Normal"
          - action: select.select_option
            data:
              option: Normal
            target:
              entity_id: select.myenergi_eddi_operating_mode
    mode: single
    icon: mdi:gas-station
  hvac_set_solar_diverter_to_boost_mode:
    alias: HVAC Set Solar Diverter To boost Mode
    fields:
      minutes:
        description: Number of minutes to boost by.
        required: true
        selector:
          number:
            min: 1
            max: 240
            unit_of_measurement: "min"
    sequence:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: >-
                Turning :fuelpump: Eddi to boost for
                {{ minutes|float(0) }} mins.
              title: myEnergi
              log_level: "Normal"
          - action: myenergi.myenergi_eddi_boost
            data:
              target: Heater 1
              time: "{{ minutes|float(0) }}"
            target:
              device_id: 69fa95cf807591fa318b0e7da75e2762
    mode: single
    icon: mdi:gas-station
  hvac_check_eddi_boost_hot_water:
    alias: HVAC Check Eddi Boost Hot Water
    trace:
      stored_traces: 40
    fields:
      current_electricity_import_rate:
        description: Pounds per kiloWatt for importing.
        example: "0.1501"
        selector:
          number:
            min: -15
            max: 100
            step: 2
      current_electricity_import_rate_unit:
        description: Unit describing the unit rate.
        example: "GBP/kWh"
        selector:
          text:
      event:
        description: The trigger for running an electricity rate check.
        example: time
        required: true
        selector:
          select:
            options:
              - event
              - time
    sequence:
      - variables:
          current_import_rate: "{{ current_electricity_import_rate|default(states('sensor.electricity_current_rate'), true) }}"
          current_import_rate_unit_of_measurement: "{{ current_electricity_import_rate_unit|state_attr('sensor.electricity_current_rate', 'unit_of_measurement') }}"
      - choose:
          - alias: "Unit rate is below 0p/kw"
            conditions:
              - condition: template
                value_template: "{{ current_import_rate < 0}}"
              - condition: state
                entity_id: input_boolean.eddi_heat_water_cost_below_nothing
                state: "on"
            sequence:
              - parallel:
                  - action: script.send_to_home_log
                    data:
                      message: >-
                        Electricity rate is below 0p/kW ({{ current_import_rate~' '~current_import_rate_unit_of_measurement }}).
                        Boosting hot water with eddi.
                      title: Eddi
                  - action: script.hvac_set_solar_diverter_to_boost_mode
                    data:
                      minutes: 20
          - alias: "Unit rate is on 0p/kw"
            conditions:
              - condition: template
                value_template: "{{ current_import_rate == 0}}"
              - condition: state
                entity_id: input_boolean.eddi_heat_water_cost_nothing
                state: "on"
            sequence:
              - parallel:
                  - action: script.send_to_home_log
                    data:
                      message: >-
                        Electricity rate is 0p/kW ({{ current_import_rate~' '~current_import_rate_unit_of_measurement }}).
                        Boosting hot water with eddi.
                      title: Eddi
                  - action: script.hvac_set_solar_diverter_to_boost_mode
                    data:
                      minutes: 20
          - alias: "Charging schedule is enabled"
            conditions:
              - or:
                  - condition: state
                    entity_id: input_boolean.enable_permanent_hot_water_below_export
                    state: "on"
                  - and:
                      - condition: state
                        entity_id: input_boolean.enable_boost_hot_water_schedule_1
                        state: "on"
                      - condition: state
                        entity_id: binary_sensor.boost_hot_water_schedule_1
                        state: "on"
            sequence:
              - parallel:
                  - action: script.send_direct_notification
                    data:
                      message: >-
                        Scheduled boosting of hot water by Electricity. Boosting hot water with eddi.
                      title: Eddi
                      people:
                        entity_id:
                          - person.danny
                  - action: script.hvac_set_solar_diverter_to_boost_mode
                    data:
                      minutes: 20
          - alias: "Exceed Cut Off Threshold"
            conditions:
              - condition: state
                entity_id: timer.eddi_max_temperature_reached
                state: "active"
              - condition: state
                entity_id: input_boolean.enable_hot_water_automations
                state: "on"
              - condition: time
                before: "12:00:00"
            sequence:
              - if:
                  - not:
                      - condition: state
                        entity_id: select.myenergi_eddi_operating_mode
                        state: "Stopped"
                then:
                  - parallel:
                      - action: script.send_to_home_log
                        data:
                          message: >-
                            Stopping :fuelpump: Eddi. Divered {{ states('sensor.myenergi_eddi_energy_consumed_per_heating_cycle') }}
                            in the last 4 hours
                            ({{ states('sensor.myenergi_eddi_energy_consumed_session_daily') }})
                            {{ state_attr('sensor.myenergi_eddi_energy_consumed_session', 'unit_of_measurement') }}.
                          title: myEnergi
                          log_level: "Debug"
                      - action: select.select_option
                        data:
                          option: "Stopped"
                        target:
                          entity_id: select.myenergi_eddi_operating_mode
          - alias: "Unit rate is above 0p/kWh"
            conditions:
              - condition: template
                value_template: "{{ current_import_rate > 0}}"
              - condition: state
                entity_id: sensor.myenergi_eddi_status
                state: "Boosting"
            sequence:
              - parallel:
                  - action: script.send_to_home_log
                    data:
                      message: >-
                        Currently {{ states('sensor.myenergi_eddi_status') }}. Cancelling boost.
                      title: Eddi
                      log_level: "Debug"
                  - action: myenergi.myenergi_stop_boost
                    target:
                      entity_id: select.myenergi_eddi_operating_mode
                    data: {}
          - alias: "Default mode"
            conditions:
              - not:
                  - condition: state
                    entity_id: select.myenergi_eddi_operating_mode
                    state: "Normal"
            sequence:
              - parallel:
                  - action: script.send_to_home_log
                    data:
                      message: >-
                        Scheduled boosting of hot water by Electricity. Boosting hot water with eddi.
                      title: Eddi
                      log_level: "Debug"
                  - action: script.hvac_set_solar_diverter_to_normal_mode
                    data: {}
        default: []

utility_meter:
  # Electricity used every 6 hours =
  # heating cycle before needing to reheat hot water again.
  myenergi_eddi_energy_consumed_6_hours:
    source: sensor.myenergi_eddi_energy_used_today
    name: MyEnergi Eddi Energy Consumed Per Heating Cycle
    unique_id: 2e83399e-89e8-4941-99ee-4c2741d23026
    cron: "0 */4 * * *"
    periodically_resetting: true
