# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://www.home-assistant.io/integrations/hive/
automation:
  # Central Heating
  - id: "1666470473971"
    alias: "HVAC: Heating Mode Changed"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - sensor.thermostat_mode
        to: "SCHEDULE"
      - platform: state
        entity_id:
          - water_heater.thermostat
        to: "eco"
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: Central heating mode changed to {{ states('sensor.thermostat_mode') }}
          title: ":hotsprings: :droplet: Boiler"
      - choose:
          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: "Holiday"
            sequence:
              - service: script.send_direct_notification
                data:
                  message: In holiday mode so heating schould not be on. Turning heating off.
                  title: ":hotsprings: :droplet: Boiler"
                  people:
                    entity_id:
                      - person.danny
              - service: script.set_central_heating_to_away_mode
                data: {}
    mode: single
  - id: "1666470473973"
    alias: "HVAC: Heating Mode Changed To Automatic"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - climate.thermostat
        to: "auto"
    condition: []
    action:
      - service: script.send_direct_notification
        data:
          message: Thermostat switched to auto mode (again).
          title: ":hotsprings: :droplet: Boiler"
          people:
            entity_id:
              - person.danny
    mode: single
  # Hot Water
  - id: "1666470473972"
    alias: "HVAC: Hot Water Mode Changed"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - water_heater.thermostat
        to: "eco"
      - platform: state
        entity_id:
          - water_heater.thermostat
        to: "on"
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: Hot water mode changed to {{ states('water_heater.thermostat') }}
          title: ":hotsprings: :droplet: Boiler"
      - choose:
          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: "Holiday"
            sequence:
              - service: script.send_direct_notification
                data:
                  message: In holiday mode so hot water schould not be on. Turning hot water off.
                  title: ":hotsprings: :droplet: Boiler"
                  people:
                    entity_id:
                      - person.danny
              - service: script.set_how_water_to_away_mode
                data: {}
    mode: single
  - id: "1662589192400"
    alias: "Central Heating: Turn On Hot Water"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - schedule.hot_water
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.enable_hot_water_automations
        state: "on"
      - not:
          - condition: state
            entity_id: water_heater.thermostat
            state: "on"
    action:
      - choose:
          - alias: "In Holiday Mode"
            conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: "Holiday"
            sequence:
              - service: script.send_to_home_log
                data:
                  message: In Holiday mode. Skipping turning on hot water.
                  title: ":hotsprings: Central Heating"
                  log_level: "Debug"
          - alias: "Already Heated Hot water"
            conditions:
              - condition: template
                value_template: >
                  {{ (states('sensor.myenergi_eddi_energy_consumed_per_heating_cycle')|float(0)) >
                  (states('input_number.hot_water_solar_diverter_boiler_cut_off')|float(0)) }}
            sequence:
              - service: script.send_to_home_log
                data:
                  message: >-
                    Eddi has heated the hot water {{ states('sensor.myenergi_eddi_energy_consumed_per_heating_cycle') }}
                    (> {{ states('input_number.hot_water_solar_diverter_boiler_cut_off')|float(0) }}).
                    {{ state_attr('sensor.myenergi_eddi_energy_consumed_session', 'unit_of_measurement') }}
                    was heated totday.


                    Skipping scheduled turning on hot water.
                  title: ":hotsprings: Central Heating"
                  log_level: "Normal"
        default:
          - service: script.send_to_home_log
            data:
              message: Turning on hot water from schedule.
              title: ":hotsprings: Central Heating"
              log_level: "Normal"
          - service: script.set_how_water_to_on
            data: {}
    mode: single
  - id: "1662589333109"
    alias: "Central Heating: Turn Off Hot Water"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - schedule.hot_water
        to: "off"
        for:
          hours: 0
          minutes: 0
          seconds: 30
    condition:
      - condition: state
        entity_id: input_boolean.enable_hot_water_automations
        state: "on"
      - not:
          - condition: state
            entity_id: water_heater.thermostat
            state: "off"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: "Holiday"
            sequence:
              - service: script.send_to_home_log
                data:
                  message: In Holiday mode. Skipping turning off hot water.
                  title: ":hotsprings: Central Heating"
                  log_level: "Normal"
        default:
          - service: script.send_to_home_log
            data:
              message: Turning off hot water from schedule.
              title: ":hotsprings: Central Heating"
              log_level: "Normal"
          - service: script.set_hot_water_to_home_mode
            data: {}
    mode: single

script:
  set_central_heating_to_away_mode:
    alias: Set Central Heating To Away Mode
    icon: mdi:hvac
    sequence:
      - if:
          - or:
              - not:
                  - condition: state
                    entity_id: climate.thermostat
                    state: "heat"
              - not:
                  - condition: state
                    entity_id: climate.thermostat
                    attribute: temperature
                    state: 7
        then:
          - service: script.hvac_turn_off_heater_schedule
            data: {}
          - parallel:
              - service: script.send_to_home_log
                data:
                  message: "Setting heating to :running: away mode."
                  title: ":hotsprings: :droplet: Boiler"
                  log_level: "Normal"
              - service: climate.set_temperature
                target:
                  entity_id: climate.thermostat
                data:
                  temperature: 7
              - service: climate.set_hvac_mode
                data:
                  hvac_mode: heat
                target:
                  entity_id: climate.thermostat
    mode: single
  set_central_heating_to_home_mode:
    alias: Set Central Heating To Home Mode
    icon: mdi:hvac
    sequence:
      - if:
          - not:
              - condition: state
                entity_id: climate.thermostat
                state: "heat"
        then:
          - parallel:
              - service: script.send_to_home_log
                data:
                  message: "Setting heating to :house_with_garden: home mode."
                  title: ":hotsprings: :droplet: Boiler"
                  log_level: "Normal"
              - sequence:
                  - service: script.hvac_turn_on_heater_schedule
                    data: {}
                  - service: script.check_and_run_central_heating
                    data: {}
    mode: single
  set_central_heating_to_off:
    alias: Set Central Heating Off
    icon: mdi:hvac-off
    sequence:
      - if:
          - not:
              - condition: state
                entity_id: climate.thermostat
                state: "off"
        then:
          - parallel:
              - service: script.send_to_home_log
                data:
                  message: "Setting heating to off."
                  title: ":hotsprings: :droplet: Boiler"
                  log_level: "Normal"
              - service: climate.set_hvac_mode
                data:
                  hvac_mode: "off"
                target:
                  entity_id: climate.thermostat
    mode: single
  check_and_run_central_heating:
    alias: Check And Run Central Heating Schedule
    icon: mdi:hvac
    variables:
      current_schedule: "{{ 'switch.schedule_heating_for_' ~ now().timestamp() | timestamp_custom('%A') | lower }}"
    sequence:
      - if:
          - condition: template
            value_template: "{{ states(current_schedule) == 'off' }}"
        then:
          - service: switch.turn_on
            data: {}
            target:
              entity_id: "{{ current_schedule }}"
      - service: scheduler.run_action
        data:
          entity_id: "{{ current_schedule }}"
  hvac_turn_off_heater_schedule:
    alias: "HVAC: Turn Off Heater Schedule"
    sequence:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: Turning off schedule.
              title: ":hotsprings: :droplet: Boiler"
              log_level: "Normal"
          - service: switch.turn_off
            data: {}
            target:
              entity_id:
                - switch.schedule_heating_for_monday
                - switch.schedule_heating_for_tuesday
                - switch.schedule_heating_for_wednesday
                - switch.schedule_heating_for_thursday
                - switch.schedule_heating_for_friday
                - switch.schedule_heating_for_saturday
                - switch.schedule_heating_for_sunday
    mode: single
  hvac_turn_on_heater_schedule:
    alias: "HVAC: Turn On Heater Schedule"
    sequence:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: Turning on schedule.
              title: ":hotsprings: :droplet: Boiler"
              log_level: "Normal"
          - service: switch.turn_on
            data: {}
            target:
              entity_id:
                - switch.schedule_heating_for_monday
                - switch.schedule_heating_for_tuesday
                - switch.schedule_heating_for_wednesday
                - switch.schedule_heating_for_thursday
                - switch.schedule_heating_for_friday
                - switch.schedule_heating_for_saturday
                - switch.schedule_heating_for_sunday
    mode: single
  set_hot_water_to_home_mode:
    alias: Set Hot Water To Home
    icon: mdi:water-boiler-auto
    sequence:
      - if:
          - condition: state
            entity_id: input_boolean.enable_hive_hacs_integration
            state: "on"
        then:
          - if:
              - not:
                  - condition: state
                    entity_id: water_heater.thermostat
                    state: "eco"
            then:
              - parallel:
                  - service: script.send_to_home_log
                    data:
                      message: "Turning on the hot water."
                      title: ":hotsprings: :droplet: Boiler"
                      log_level: "Normal"
                  - service: water_heater.set_operation_mode
                    data:
                      operation_mode: "eco"
                    target:
                      entity_id: water_heater.thermostat
        else:
          - if:
              - not:
                  - condition: state
                    entity_id: water_heater.thermostat
                    state: "auto"
            then:
              - parallel:
                  - service: script.send_to_home_log
                    data:
                      message: "Turning on the hot water."
                      title: ":hotsprings: :droplet: Boiler"
                      log_level: "Normal"
                  - service: water_heater.set_operation_mode
                    data:
                      operation_mode: "auto"
                    target:
                      entity_id: water_heater.thermostat
    mode: single
  set_how_water_to_away_mode:
    alias: Set Hot Water To Off
    icon: mdi:water-boiler-off
    sequence:
      - if:
          - not:
              - condition: state
                entity_id: water_heater.thermostat
                state: "off"
        then:
          - parallel:
              - service: script.send_to_home_log
                data:
                  message: "Turning off the hot water."
                  title: ":hotsprings: :droplet: Boiler"
                  log_level: "Debug"
              - service: water_heater.set_operation_mode
                data:
                  operation_mode: "off"
                target:
                  entity_id: water_heater.thermostat
    mode: single
  set_how_water_to_on:
    alias: Set Hot Water To On
    icon: mdi:water-boiler
    sequence:
      - if:
          - not:
              - condition: state
                entity_id: water_heater.thermostat
                state: "on"
        then:
          - parallel:
              - service: script.send_to_home_log
                data:
                  message: "Turning on the hot water."
                  title: ":hotsprings: :droplet: Boiler"
                  log_level: "Debug"
              - service: water_heater.set_operation_mode
                data:
                  operation_mode: "on"
                target:
                  entity_id: water_heater.thermostat
    mode: single

sensor:
  # historical stats
  - platform: history_stats
    name: Heating On Duration Today
    unique_id: 77fbd1e1-d7c6-4b01-9eb6-e48059be7a2c
    entity_id: sensor.thermostat_action
    state: "heating"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Heating On Duration Last 24 Hours
    unique_id: 75ac50fc-a9d0-48d6-be63-e425f17416d5
    entity_id: sensor.thermostat_action
    state: "heating"
    type: time
    end: "{{ now() }}"
    duration:
      hours: 24
  - platform: history_stats
    name: Heating On Duration Yesterday
    unique_id: a244b3a7-4f2c-435c-92c7-e9970e908190
    entity_id: sensor.thermostat_action
    state: "heating"
    type: time
    end: "{{ now().replace(hour=0, minute=0, second=0) }}"
    duration:
      hours: 24
  - platform: history_stats
    name: Heating On Duration This Week
    unique_id: fd7761b0-6609-40ef-aabb-fb650e4be282
    entity_id: sensor.thermostat_action
    state: "heating"
    type: time
    start: "{{ as_timestamp( now().replace(hour=0, minute=0, second=0) ) - now().weekday() * 86400 }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Heating On Duration Last Week
    unique_id: e50f7544-9ff5-4417-b9f1-228006fba2d5
    entity_id: sensor.thermostat_action
    state: "heating"
    type: time
    end: "{{ as_timestamp( now().replace(hour=0, minute=0, second=0) ) - now().weekday() * 86400 }}"
    duration:
      days: 7
  - platform: history_stats
    name: Heating On Duration This Month
    unique_id: 76c20069-4c27-45f3-ba30-b773d76af677
    entity_id: sensor.thermostat_action
    state: "heating"
    type: time
    start: "{{ now().replace(day=1, hour=0, minute=0, second=0, microsecond=0 ) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Heating On Duration Last Month
    unique_id: 8c326aba-7016-4656-a8d3-27cc89a9ca24
    entity_id: sensor.thermostat_action
    state: "heating"
    type: time
    start: "{{ now().replace(day=1, month=now().month, hour=0, minute=0, second=0, microsecond=0) }}"
    end: "{{ now().replace(day=1, hour=0, minute=0, second=0, microsecond=0) }}"
  # Hot Water
  - platform: history_stats
    name: Hot Water On Duration Today
    unique_id: 61030bc1-1dda-4045-9ff3-1c4f60fae30c
    entity_id: sensor.hotwater_state
    state: "ON"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Hot Water On Duration Last 24 Hours
    unique_id: 31172d13-cd84-41a7-8523-40317c8d523b
    entity_id: sensor.hotwater_state
    state: "ON"
    type: time
    end: "{{ now() }}"
    duration:
      hours: 24
  - platform: history_stats
    name: Hot Water On Duration Yesterday
    unique_id: a0acaa28-60a3-406a-a2d4-1bc5b6c0889e
    entity_id: sensor.hotwater_state
    state: "ON"
    type: time
    end: "{{ now().replace(hour=0, minute=0, second=0) }}"
    duration:
      hours: 24
  - platform: history_stats
    name: Hot Water On Duration This Week
    unique_id: 896e9be3-2c7d-47b5-8a8e-0a2b356b7e89
    entity_id: sensor.hotwater_state
    state: "ON"
    type: time
    start: "{{ as_timestamp( now().replace(hour=0, minute=0, second=0) ) - now().weekday() * 86400 }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Hot Water On Duration This Month
    unique_id: 83c344e5-e053-4439-8156-1ab93150c438
    entity_id: sensor.hotwater_state
    state: "ON"
    type: time
    start: "{{ now().replace(day=1, hour=0, minute=0, second=0, microsecond=0 ) }}"
    end: "{{ now() }}"
