# Created by Danny Tsang <danny@tsang.uk>
automation:
  # Radiators
  - id: "1678125037184"
    alias: "HVAC: House Target Temperature Changed"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - sensor.thermostat_target_temperature
    conditions: []
    actions:
      - action: script.send_to_home_log
        data:
          message: >-
            Home thermostat target temperature changed.

            Updating TRV from {{ state_attr('climate.living_room_radiator', 'temperature')|float(22) }}
            to {{ state_attr('climate.thermostat', 'temperature')|float(22) }}c.
          title: ":hotsprings: :droplet: Boiler"
          log_level: "Debug"
      - action: climate.set_temperature
        data:
          temperature: "{{ states('sensor.thermostat_target_temperature')|float(22) }}"
        target:
          entity_id:
            - climate.ashlees_bedroom_radiator
            - climate.bedroom_radiator
            - climate.kitchen_radiator
            - climate.leos_bedroom_radiator
            - climate.living_room_radiator
            - climate.office_radiator
    mode: single
  - id: "1678271646645"
    alias: "HVAC: Radiators Below Target Temperature"
    description: "Monitor rooms below temperature with TRVs"
    triggers:
      - trigger: numeric_state
        entity_id: sensor.bedroom_radiator_temperature
        for:
          hours: 0
          minutes: 30
          seconds: 0
        below: sensor.bedroom_radiator_minimum_target_temperature
      - trigger: numeric_state
        entity_id: sensor.leos_radiator_temperature
        for:
          hours: 0
          minutes: 30
          seconds: 0
        below: sensor.leos_radiator_minimum_target_temperature
      - trigger: numeric_state
        entity_id: sensor.living_room_radiator_temperature
        for:
          hours: 0
          minutes: 30
          seconds: 0
        below: sensor.living_room_radiator_minimum_target_temperature
      - trigger: numeric_state
        entity_id: sensor.office_radiator_temperature
        for:
          hours: 0
          minutes: 30
          seconds: 0
        below: sensor.office_radiator_minimum_target_temperature
        id: office
    conditions:
      - not:
          - condition: state
            entity_id: climate.thermostat
            attribute: hvac_action
            state: "heating"
    actions:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - office
              - condition: state
                entity_id: binary_sensor.office_windows
                state: "off"
              - condition: state
                entity_id: binary_sensor.conservatory_door
                state: "off"
            sequence:
              - action: script.send_direct_notification
                data:
                  message: Radiator to call for heat.
                  title: ":office: Office"
                  people:
                    entity_id:
                      - person.danny
        default:
          - action: script.send_direct_notification
            data:
              message: Radiator call for heat in.
              title: >-
                {%- if trigger.entity_id == 'sensor.bedroom_radiator_temperature' -%}
                :bed: bedroom
                {%- elif trigger.entity_id == 'sensor.leos_radiator_temperature' -%}
                Leo's :bed: bedroom
                {%- elif trigger.entity_id == 'sensor.living_room_radiator_temperature' -%}
                :couch_and_lamp: Lounge
                {%- elif trigger.entity_id == 'sensor.office_radiator_temperature' -%}
                :office: Office
                {%- else -%}
                Unknown location
                {%- endif -%}
              people:
                entity_id:
                  - person.danny
    mode: single

sensor:
  # Boiler Flow
  - platform: statistics
    name: "Flow Temperature Delta Last 24 Hours"
    unique_id: 96bc7959-a867-4d5b-b733-188bcc25c92c
    entity_id: sensor.boiler_delta_temperature
    state_characteristic: mean
    max_age:
      hours: 24
  - platform: statistics
    name: "Flow Temperature Highest Delta"
    unique_id: aaac8076-2bfa-4f8d-825f-2603051f7eb9
    entity_id: sensor.boiler_delta_temperature
    state_characteristic: value_max
    sampling_size: 43200
    max_age:
      days: 30
  - platform: statistics
    name: "Flow Temperature Lowest Delta"
    unique_id: e4febfc7-2d8b-443d-8aae-b9d5d86e6449
    entity_id: sensor.boiler_delta_temperature
    state_characteristic: value_min
    sampling_size: 43200
    max_age:
      days: 30
  - platform: statistics
    name: "Flow Temperature Delta Difference"
    unique_id: 99a1f9d4-b8bb-456d-840a-e3ad0c997215
    entity_id: sensor.boiler_delta_temperature
    state_characteristic: distance_absolute
    sampling_size: 43200
    max_age:
      days: 30

template:
  - sensor:
      - name: "Ashlee's Bedroom Radiator Temperature"
        unique_id: 8a80cae1-99f3-4298-9428-23589a0b80f9
        state: "{{ state_attr('climate.ashlees_bedroom_radiator', 'current_temperature') }}"
        icon: mdi:thermometer
        device_class: "temperature"
        unit_of_measurement: "°C"
      - name: "Ashlee's Bedroom Radiator Target Temperature"
        unique_id: 730e948a-d66f-4dd6-a84f-6bbdd9715868
        state: "{{ state_attr('climate.ashlees_bedroom_radiator', 'temperature') }}"
        icon: mdi:thermometer
        device_class: "temperature"
        unit_of_measurement: "°C"
      - name: "Bedroom Radiator Temperature"
        unique_id: 2c40b45d-9f2c-4ce1-9707-25dbf2c2f757
        state: "{{ state_attr('climate.bedroom_radiator', 'current_temperature') }}"
        icon: mdi:thermometer
        device_class: "temperature"
        unit_of_measurement: "°C"
      - name: "Bedroom Radiator Target Temperature"
        unique_id: afab67b2-1a06-400a-bbfa-61cbd2bb4b15
        state: "{{ state_attr('climate.bedroom_radiator', 'temperature') }}"
        icon: mdi:thermometer
        device_class: "temperature"
        unit_of_measurement: "°C"
      - name: "Conservatory Radiator Temperature"
        unique_id: 08d957b2-197e-4087-8dff-2d6e41c7edb1
        state: "{{ state_attr('climate.Conservatory_radiator', 'current_temperature') }}"
        icon: mdi:thermometer
        device_class: "temperature"
        unit_of_measurement: "°C"
      - name: "Conservatory Radiator Target Temperature"
        unique_id: 79882d5e-8b5b-4ca5-9085-4f3d1bf0ab20
        state: "{{ state_attr('climate.Conservatory_radiator', 'temperature') }}"
        icon: mdi:thermometer
        device_class: "temperature"
        unit_of_measurement: "°C"
      - name: "Conservatory Radiator 2 Temperature"
        unique_id: cb239761-e2db-4c83-a072-35c2cc4fe310
        state: "{{ state_attr('climate.Conservatory_radiator_2', 'current_temperature') }}"
        icon: mdi:thermometer
        device_class: "temperature"
        unit_of_measurement: "°C"
      - name: "Conservatory Radiator 2 Target Temperature"
        unique_id: 83f42450-8707-4928-aef7-829ae38572dd
        state: "{{ state_attr('climate.Conservatory_radiator_2', 'temperature') }}"
        icon: mdi:thermometer
        device_class: "temperature"
        unit_of_measurement: "°C"
      - name: "Kitchen Radiator Temperature"
        unique_id: 98bd623b-771b-4c11-b43d-83f432308b97
        state: "{{ state_attr('climate.kitchen_radiator', 'current_temperature') }}"
        icon: mdi:thermometer
        device_class: "temperature"
        unit_of_measurement: "°C"
      - name: "Kitchen Radiator Target Temperature"
        unique_id: 4a0fae76-8de5-4a8d-a6e0-30e0acb0301e
        state: "{{ state_attr('climate.kitchen_radiator', 'temperature') }}"
        icon: mdi:thermometer
        device_class: "temperature"
        unit_of_measurement: "°C"
      - name: "Leo's Radiator Temperature"
        unique_id: 59115996-9365-4350-ab2f-b800d4ac1a06
        state: "{{ state_attr('climate.leos_bedroom_radiator', 'current_temperature') }}"
        icon: mdi:thermometer
        device_class: "temperature"
        unit_of_measurement: "°C"
      - name: "Leo's Radiator Target Temperature"
        unique_id: c83578d4-90b0-4e7f-945c-691d0b453432
        state: "{{ state_attr('climate.leos_bedroom_radiator', 'temperature') }}"
        icon: mdi:thermometer
        device_class: "temperature"
        unit_of_measurement: "°C"
      - name: "Lounge Radiator Temperature"
        unique_id: b13e42a5-3cd0-4d2a-8ab6-3c2669730c77
        state: "{{ state_attr('climate.living_room_radiator', 'current_temperature') }}"
        icon: mdi:thermometer
        device_class: "temperature"
        unit_of_measurement: "°C"
      - name: "Lounge Radiator Target Temperature"
        unique_id: 4c2f2439-f6bc-40e6-88c0-10eb2eae8f79
        state: "{{ state_attr('climate.living_room_radiator', 'temperature') }}"
        icon: mdi:thermometer
        device_class: "temperature"
        unit_of_measurement: "°C"
      - name: "Office Radiator Temperature"
        unique_id: b3aee9df-eb93-4880-b1f7-0096fc448526
        state: "{{ state_attr('climate.office_radiator', 'current_temperature') }}"
        icon: mdi:thermometer
        device_class: "temperature"
        unit_of_measurement: "°C"
      - name: "Office Radiator Target Temperature"
        unique_id: 009b2414-5db7-4b9b-8ecc-71982e878b2f
        state: "{{ state_attr('climate.office_radiator', 'temperature') }}"
        icon: mdi:thermometer
        device_class: "temperature"
        unit_of_measurement: "°C"
      - name: "Porch Radiator Temperature"
        unique_id: 74ba0d76-5a64-4a81-a5dd-cfbfc566a052
        state: "{{ state_attr('climate.porch_radiator', 'current_temperature') }}"
        icon: mdi:thermometer
        device_class: "temperature"
        unit_of_measurement: "°C"
      - name: "Porch Radiator Target Temperature"
        unique_id: b9e808cf-84c1-4dbc-8192-30f035f70948
        state: "{{ state_attr('climate.porch_radiator', 'temperature') }}"
        icon: mdi:thermometer
        device_class: "temperature"
        unit_of_measurement: "°C"
      - name: "Thermostat Action"
        unique_id: 8dff3606-6aaf-4713-a668-140e71271416
        state: "{{ state_attr('climate.thermostat', 'hvac_action') }}"
      - name: Thermostat Target Temperature
        unique_id: e4890bce-7126-416b-8a5f-1bd6a7bd9ac0
        device_class: "temperature"
        unit_of_measurement: "°C"
        state: "{{ state_attr('climate.thermostat', 'temperature') | float(0) }}"
  - trigger:
      - trigger: state
        entity_id:
          - climate.ashlees_bedroom_radiator
        attribute: temperature
      - trigger: state
        entity_id:
          - input_number.ashlees_bedroom_radiator_heating_threshold
    sensor:
      - name: "Ashlee's Bedroom Radiator Minimum Target Temperature"
        unique_id: c9cf6c97-e67e-46bd-9fed-80b5eec71ed2
        state: "{{ state_attr('climate.ashlees_bedroom_radiator', 'temperature')|float(10) - states('input_number.ashlees_bedroom_radiator_heating_threshold')|float(0) }}"
        unit_of_measurement: "°C"
  - trigger:
      - trigger: state
        entity_id:
          - climate.bedroom_radiator
        attribute: temperature
      - trigger: state
        entity_id:
          - input_number.bedroom_radiator_heating_threshold
    sensor:
      - name: "Bedroom Radiator Minimum Target Temperature"
        unique_id: 82b0142c-0c10-4049-b271-4f28c8f81534
        state: "{{ state_attr('climate.bedroom_radiator', 'temperature')|float(10) - states('input_number.bedroom_radiator_heating_threshold')|float(0) }}"
        unit_of_measurement: "°C"
  - trigger:
      - trigger: state
        entity_id:
          - climate.kitchen_radiator
        attribute: temperature
      - trigger: state
        entity_id:
          - input_number.kitchen_radiator_heating_threshold
    sensor:
      - name: "Kitchen Radiator Minimum Target Temperature"
        unique_id: b57d8a81-0b4a-443c-9831-221db5b476e2
        state: "{{ state_attr('climate.kitchen_radiator', 'temperature')|float(10) - states('input_number.kitchen_radiator_heating_threshold')|float(0) }}"
        unit_of_measurement: "°C"
  - trigger:
      - trigger: state
        entity_id:
          - climate.leos_bedroom_radiator
        attribute: temperature
      - trigger: state
        entity_id:
          - input_number.leos_bedroom_radiator_heating_threshold
    sensor:
      - name: "Leo's Radiator Minimum Target Temperature"
        unique_id: 355c5e71-d16c-4bdd-b89a-1298652a0bb5
        state: "{{ state_attr('climate.leos_bedroom_radiator', 'temperature')|float(10) - states('input_number.leos_bedroom_radiator_heating_threshold')|float(0) }}"
        unit_of_measurement: "°C"
  - trigger:
      - trigger: state
        entity_id:
          - climate.living_room_radiator
        attribute: temperature
      - trigger: state
        entity_id:
          - input_number.living_room_radiator_heating_threshold
    sensor:
      - name: "Lounge Radiator Minimum Target Temperature"
        unique_id: 37c5a84f-6d5e-47c5-bfa0-df5a2cb4c2bc
        state: "{{ state_attr('climate.living_room_radiator', 'temperature')|float(10) - states('input_number.living_room_radiator_heating_threshold')|float(0) }}"
        unit_of_measurement: "°C"
  - trigger:
      - trigger: state
        entity_id:
          - climate.office_radiator
        attribute: temperature
      - trigger: state
        entity_id:
          - input_number.office_radiator_heating_threshold
    sensor:
      - name: "Office Radiator Minimum Target Temperature"
        unique_id: 921ff09b-0936-4106-b5f6-6e677305fe4d
        state: "{{ state_attr('climate.office_radiator', 'temperature')|float(10) - states('input_number.office_radiator_heating_threshold')|float(0) }}"
        unit_of_measurement: "°C"
