# Created by Danny Tsang <danny@tsang.uk>
# Aggregated sensors
- platform: min_max
  name: Bedroom Area Light Level
  entity_ids:
    - sensor.bedroom_motion_light_level
    - sensor.bedroom_motion_2_light_level
  type: mean
- platform: min_max
  name: Bedroom Area Temperature
  entity_ids:
    - sensor.bedroom_motion_temperature
    - sensor.bedroom_motion_2_temperature
  type: mean
- platform: min_max
  name: Kitchen Area Light Level
  entity_ids:
    - sensor.kitchen_motion_light_level
    - sensor.kitchen_motion_2_light_level
  type: mean
- platform: min_max
  name: Kitchen Area Temperature
  entity_ids:
    - sensor.kitchen_motion_temperature
    - sensor.kitchen_motion_2_temperature
  type: mean
- platform: min_max
  name: Lounge Area Light Level
  entity_ids:
    - sensor.lounge_motion_light_level
    - sensor.lounge_motion_2_light_level
  type: mean
- platform: min_max
  name: Lounge Area Temperature
  entity_ids:
    - sensor.lounge_motion_temperature
    - sensor.lounge_motion_2_temperature
  type: mean
- platform: min_max
  name: Office Area Light Level
  entity_ids:
    - sensor.office_motion_light_level
    - sensor.office_motion_2_light_level
  type: mean
- platform: min_max
  name: Office Area Temperature
  entity_ids:
    - sensor.office_motion_temperature
    - sensor.office_motion_2_temperature
  type: mean
# Statistics
- platform: statistics
  entity_id: sensor.bed_sensor
  name: Bed Sensor Stat
