# Created by Danny Tsang <danny@tsang.uk>
# Aggregated sensors
# Motion sensor paired with Hue reports lux where as smarthing is lx. This causes errors when aggregating
#- platform: min_max
#  name: Bedroom Area Light Level
#  entity_ids:
#    - sensor.bedroom_motion_light_level
#    - sensor.bedroom_motion_2_light_level
#  type: mean
# Statistics
- platform: statistics
  entity_id: sensor.leos_bed_top_left
  name: Leo's Bed Top Left Stat
  sampling_size: 2000
- platform: statistics
  entity_id: sensor.leos_bed_top_right
  name: Leo's Bed Top Right Stat
  sampling_size: 2000
- platform: statistics
  entity_id: sensor.leos_bed_bottom_left
  name: Leo's Bed Bottom Left Stat
  sampling_size: 2000
- platform: statistics
  entity_id: sensor.leos_bed_bottom_right
  name: Leo's Bed Bottom Right Stat
  sampling_size: 2000
