# Created by Danny Tsang <danny@tsang.uk>
# Aggregated sensors
- platform: min_max
  name: Bedroom Area Temperature
  entity_ids:
    - sensor.bedroom_motion_temperature
    - sensor.bedroom_motion_temperature_2
  type: mean
- platform: min_max
  name: Kitchen Area Temperature
  entity_ids:
    - sensor.kitchen_motion_temperature
    - sensor.kitchen_motion_temperature_2
  type: mean
- platform: min_max
  name: Lounge Area Temperature
  entity_ids:
    - sensor.lounge_motion_temperature
    - sensor.lounge_motion_temperature_2
  type: mean
- platform: min_max
  name: Office Area Temperature
  entity_ids:
    - sensor.office_motion_temperature
    - sensor.office_motion_temperature_2
  type: mean
