# Created by Danny Tsang <danny@tsang.uk>
# Total energy usage using energy@home <https://github.com/dannytsang/energyathome>
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Electricity usage
      query: "SELECT id,date_time,channel_id,data/1000 as data FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 18 LIMIT 1) LIMIT 1) AND unit = 'W' AND date_time >= NOW() - INTERVAL 30 MINUTE ORDER BY date_time DESC LIMIT 1;"
      column: "data"
      unit_of_measurement: kWh
# Computer A
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: JD electricity usage
      query: "SELECT id,date_time,channel_id,data/1000 as data FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 19 LIMIT 1) AND date_time >= NOW() - INTERVAL 30 MINUTE ORDER BY date_time DESC LIMIT 1;"
      column: "data"
      unit_of_measurement: kWh
# Computer B
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Server electricity usage
      query: "SELECT id,date_time,channel_id,data/1000 as data FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 37 LIMIT 1) AND date_time >= NOW() - INTERVAL 30 MINUTE ORDER BY date_time DESC LIMIT 1;"
      column: "data"
      unit_of_measurement: kWh
# Telephony
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Telephony electricity usage
      query: "SELECT id,date_time,channel_id,data/1000 as data FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 26 LIMIT 1) AND date_time >= NOW() - INTERVAL 30 MINUTE ORDER BY date_time DESC LIMIT 1;"
      column: "data"
      unit_of_measurement: kWh
# Fridge Freezer
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Fridge Freezer electricity usage
      query: "SELECT id,date_time,channel_id,data/1000 as data FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 20 LIMIT 1) AND date_time >= NOW() - INTERVAL 30 MINUTE ORDER BY date_time DESC LIMIT 1;"
      column: "data"
      unit_of_measurement: kWh
# Freezer
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Freezer electricity usage
      query: "SELECT id,date_time,channel_id,data/1000 as data FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 28 LIMIT 1) AND date_time >= NOW() - INTERVAL 30 MINUTE ORDER BY date_time DESC LIMIT 1;"
      column: "data"
      unit_of_measurement: kWh
# Home Entertainment
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Home Entertainment electricity usage
      query: "SELECT id,date_time,channel_id,data/1000 as data FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 21 LIMIT 1) AND date_time >= NOW() - INTERVAL 30 MINUTE ORDER BY date_time DESC LIMIT 1;"
      column: "data"
      unit_of_measurement: kWh
# Surround Sound
- platform: sql
  db_url: !secret energyathome
  queries:
    - name: Surround Sound electricity usage
      query: "SELECT id,date_time,channel_id,data/1000 as data FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 29 LIMIT 1) AND date_time >= NOW() - INTERVAL 30 MINUTE ORDER BY date_time DESC LIMIT 1;"
      column: "data"
      unit_of_measurement: kWh
