# Created by Danny Tsang <danny@tsang.uk>
- platform: london_underground
  line:
    - Bakerloo
    - Central
    - Circle
    - District
    - DLR
    - Hammersmith & City
    - Jubilee
    - London Overground
    - Metropolitan
    - Northern
    - Piccadilly
    - TfL Rail
    - Victoria
    - Waterloo & City
- platform: uk_transport
  app_id: !secret uktransport_id
  app_key: !secret uktransport
  queries:
    - mode: train
      origin: SVG
      destination: ZFD
