service_send_message:
  name: Send a message
  description: Send a text message to be shown on your keyboard symbol by symbol
  target:
    device:
      integration: chroma
  fields:
    message:
      name: Message
      description: Message to be shown on the keyboard
      required: true
      example: Hello, Chroma!
      selector:
        text:
    spacing:
      name: Spacing
      description: Time spacing between symbols (in seconds) - how fast one symbol will be changed to another
      required: false
      example: 0.5
      selector:
        number:
          min: 0.05
          max: 10
          step: 0.05
          mode: box
          unit_of_measurement: seconds
    color:
      name: Color
      description: Color (RGB) of the effect
      required: true
      example: "[255, 127, 63]"
      selector:
        color_rgb:
    background:
      name: Background
      description: Color (RGB) of the background
      required: false
      example: "[0, 0, 0]"
      selector:
        color_rgb:
    brightness:
      name: Brightness
      description: Brightness of effect
      required: false
      example: 255
      selector:
        number:
          min: 1
          max: 255
    tail:
      name: Tail length
      description: Length of the tail in the animation
      required: false
      example: 0
      selector:
        number:
          min: 0
          max: 33
    repeats:
      name: Repeats
      description: How many times should the message repeat
      required: true
      example: 1
      selector:
        number:
          min: 1
          max: 33
    sleep:
      name: Sleep time
      description: Time to sleep between repeats
      required: false
      example: 0.5
      selector:
        number:
          min: 0
          max: 10
          step: 0.05
          mode: box
