# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://github.com/alandtse/tesla
# Integration: https://github.com/teslamate-org/teslamate
automation:
  - id: "1726077652711"
    alias: "Tesla: USB Archive"
    description: ""
    triggers:
      - trigger: webhook
        allowed_methods:
          - POST
        local_only: true
        webhook_id: teslausb
    conditions: []
    actions:
      - action: script.send_to_home_log
        data:
          message: >-
            {{ trigger.json.value2 }}
          title: "Tesla"
          log_level: "Normal"
    mode: queued
    max: 10
  - id: "1750161174574"
    alias: "Tesla: Windows Open At Night"
    description: ""
    triggers:
      - trigger: time
        at: "23:00:00"
    conditions:
      - condition: state
        entity_id: binary_sensor.model_3_windows
        state: "on"
    actions:
      - action: script.send_direct_notification
        metadata: {}
        data:
          title: "Car :car:"
          message: "Model 3 windows 🪟 are open."
          people:
            entity_id:
              - person.danny
    mode: single

script:
  tesla_notify_low_electricity_rates:
    alias: Tesla Notify Low Electricity Rates
    description: ""
    fields:
      current_electricity_import_rate:
        description: Pounds per kiloWatt for importing.
        example: "0.15"
        selector:
          number:
            min: -15
            max: 100
            step: 2
    sequence:
      - variables:
          current_import_rate: "{{ current_electricity_import_rate|default(states('sensor.octopus_energy_electricity_current_rate'), true) }}"
      - choose:
          - alias: Rates Below 0p/kW
            conditions:
              - condition: template
                value_template: "{{ current_import_rate < 0}}"
              - condition: state
                entity_id: device_tracker.tesla_2
                state: "home"
            sequence:
              - action: script.send_direct_notification
                data:
                  message: >-
                    Car is not plugged in and electricity rates are below 0p/kWh ({{ states('sensor.octopus_energy_electricity_current_rate') }}).

                    Your car is {{ states('sensor.model_y_battery', with_unit=True) }} charged.
                  title: "Tesla"
                  people:
                    entity_id:
                      - person.terina
          - alias: Rates Cost Nothing
            conditions:
              - condition: template
                value_template: "{{ current_import_rate == 0}}"
              - condition: state
                entity_id: device_tracker.tesla_2
                state: "home"
            sequence:
              - action: script.send_direct_notification
                data:
                  message: >-
                    Car is not plugged in and electricity rates is {{ states('sensor.octopus_energy_electricity_current_rate', with_unit=True) }}.

                    Your car is {{ states('sensor.model_y_battery', with_unit=True) }} charged.
                  title: "Tesla"
                  people:
                    entity_id:
                      - person.terina
          - alias: Cheap Rates And Near Home
            conditions:
              - condition: template
                value_template: "{{ current_import_rate <= 0}}"
              - condition: state
                entity_id: device_tracker.tesla_2
                state: "not_home"
              - condition: numeric_state
                entity_id: sensor.tesla_model_y_home_location_tracker_distance
                below: 5000
            sequence:
              - action: script.send_direct_notification
                data:
                  message: >-
                    Electricity rates is or below 0p/kWh ({{ states('sensor.octopus_energy_electricity_current_rate', with_unit=True) }}).

                    You're close to home ({{ states('sensor.tesla_model_y_home_location_tracker_distance') }}
                    < 5000m) so this is a FYI.

                    Your car is {{ states('sensor.model_y_battery', with_unit=True) }} charged.
                  title: "Tesla"
                  people:
                    entity_id:
                      - person.terina
        default: []
    mode: single

template:
  - trigger:
      - trigger: state
        entity_id:
          - sensor.tesla_charger_power
          - switch.model_y_charger
    binary_sensor:
      - name: "Tesla Charging"
        unique_id: 38c00574-6feb-4712-8089-24f84291ad69
        state: >-
          {{ states('sensor.tesla_charger_power')|float(0) > 0 or states('switch.model_y_charger') == 'off' }}
        availability: >-
          {{ states('sensor.tesla_charger_power')|is_number and states('switch.model_y_charger') != 'unavailable' }}
  # Car 2
  - trigger:
      - trigger: state
        entity_id:
          - sensor.tesla_charger_power_2
          - switch.model_3_charger
    binary_sensor:
      - name: "Tesla Charging"
        unique_id: 6389f66e-f7ce-4b3e-9b41-e006c4f713ea
        state: >-
          {{ states('sensor.tesla_charger_power_2')|float(0) > 0 or states('switch.model_3_charger') == 'off' }}
        availability: >-
          {{ states('sensor.tesla_charger_power_2')|is_number and states('switch.model_3_charger') != 'unavailable' }}
