# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy
automation:
  - id: "168962611780"
    alias: "Octopus Energy: Electricity Rates Changed"
    description: ""
    trace:
      stored_traces: 40
    triggers:
      - trigger: state
        entity_id: sensor.electricity_current_rate
    conditions: []
    actions:
      - parallel:
          - alias: Check Solar Assistant
            if:
              - condition: state
                entity_id: input_boolean.enable_solar_assistant_automations
                state: "on"
              - not:
                  - condition: state
                    entity_id: select.growatt_sph_work_mode_priority
                    state: "unavailable"
            then:
              - action: script.solar_assistant_check_charging_mode
                data:
                  event: "event"
                  current_electricity_import_rate: "{{ states('sensor.electricity_current_rate') }}"
                  current_electricity_import_rate_unit: "{{ state_attr('sensor.electricity_current_rate', 'unit_of_measurement') }}"
                  current_electricity_export_rate: "{{ states('sensor.electricity_export_current_rate') }}"
                  current_electricity_export_rate_unit: "{{ state_attr('sensor.electricity_export_current_rate', 'unit_of_measurement') }}"
          - alias: Check Zappi
            choose:
              - conditions:
                  - condition: state
                    entity_id: input_boolean.enable_zappi_automations
                    state: "on"
                  - not:
                      - condition: state
                        entity_id: sensor.myenergi_zappi_plug_status
                        state: "EV Disconnected"
                sequence:
                  - alias: Check Zappi
                    action: script.zappi_check_ev_charge
                    data:
                      current_electricity_import_rate: "{{ states('sensor.electricity_current_rate') }}"
                      current_electricity_import_rate_unit: "{{ state_attr('sensor.electricity_current_rate', 'unit_of_measurement') }}"
                      current_electricity_export_rate: "{{ states('sensor.electricity_export_current_rate') }}"
            default: []
          - alias: Check Eddi
            choose:
              - conditions:
                  - not:
                      - condition: state
                        entity_id: select.myenergi_eddi_operating_mode
                        state: "Stopped"
                  - not:
                      - condition: state
                        entity_id: input_select.home_mode
                        state: "Holiday"
                  - condition: state
                    entity_id: input_boolean.enable_hot_water_automations
                    state: "on"
                sequence:
                  - action: script.hvac_check_eddi_boost_hot_water
                    data:
                      current_electricity_import_rate: "{{ states('sensor.electricity_current_rate') }}"
                      current_electricity_import_rate_unit: "{{ state_attr('sensor.electricity_current_rate', 'unit_of_measurement') }}"
            default: []
          - alias: Check Ecoflow
            choose:
              - conditions:
                  - condition: state
                    entity_id: input_boolean.enable_ecoflow_automations
                    state: "on"
                sequence:
                  - action: script.ecoflow_check_charging_mode
                    data:
                      current_electricity_import_rate: "{{ states('sensor.electricity_current_rate') }}"
                      current_electricity_import_rate_unit: "{{ state_attr('sensor.electricity_current_rate', 'unit_of_measurement') }}"
                      current_electricity_export_rate: "{{ states('sensor.electricity_export_current_rate') }}"
            default: []
          - alias: Check office air conditioner
            choose:
              - conditions:
                  - condition: state
                    entity_id: input_boolean.office_air_conditioner_on_when_electricity_cost_nothing
                    state: "on"
                  - condition: state
                    entity_id: input_boolean.enable_office_air_conditioner_automations
                    state: "on"
                sequence:
                  - action: script.check_office_air_conditioner
                    data:
                      current_electricity_import_rate: "{{ states('sensor.electricity_current_rate') }}"
                      current_electricity_export_rate: "{{ states('sensor.electricity_export_current_rate') }}"
            default: []
          - alias: Conservatory underfloor heating
            choose:
              - conditions:
                  - condition: state
                    entity_id: input_boolean.enable_conservatory_under_floor_heating_automations
                    state: "on"
                sequence:
                  - action: script.conservatory_electricity_rate_change
                    data:
                      current_electricity_import_rate: "{{ states('sensor.electricity_current_rate') }}"
                      current_electricity_import_rate_unit: "{{ state_attr('sensor.electricity_current_rate', 'unit_of_measurement') }}"
            default: []
          - alias: Tesla not connected and home
            choose:
              - conditions:
                  - condition: state
                    entity_id: binary_sensor.model_y_charger
                    state: "Unplugged"
                  - condition: state
                    entity_id: sensor.myenergi_zappi_plug_status
                    state: "EV Disconnected"
                  - condition: state
                    entity_id: input_boolean.enable_tesla_automations
                    state: "on"
                sequence:
                  - action: script.tesla_notify_low_electricity_rates
                    data: {}
            default: []
          - alias: Check Airer
            choose:
              - conditions:
                  - or:
                      - condition: state
                        entity_id: input_boolean.enable_conservatory_airer_when_cost_below_nothing
                        state: "on"
                      - condition: state
                        entity_id: input_boolean.enable_conservatory_airer_when_cost_nothing
                        state: "on"
                sequence:
                  - action: script.check_conservatory_airer
                    data:
                      current_electricity_import_rate: "{{ states('sensor.electricity_current_rate') }}"
                      current_electricity_import_rate_unit: "{{ state_attr('sensor.electricity_current_rate', 'unit_of_measurement') }}"
            default: []
  - id: "168962611781"
    alias: Refresh intelligent dispatches
    description: "Example from: https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/services/#octopus_energyrefresh_intelligent_dispatches"
    triggers:
      - trigger: state
        entity_id: sensor.myenergi_zappi_plug_status
        not_to: "EV Disconnected"
      # Refresh every 3 minutes in case the schedule has changed
      - trigger: time_pattern
        minutes: /3
    conditions:
      - not:
          - condition: state
            entity_id: sensor.myenergi_zappi_plug_status
            state: "EV Disconnected"
    actions:
      - action: octopus_energy.refresh_intelligent_dispatches
        target:
          entity_id: binary_sensor.octopus_energy_intelligent_dispatching
    mode: single
