# Created by Danny Tsang <danny@tsang.uk>
automation:
  # Unit rate related automations
  - id: "1691009694611"
    alias: "Solar Assistant: Electricity Rate Below Export Rate"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.electricity_current_rate
        below: sensor.electricity_export_current_rate
      - platform: state
        entity_id: sensor.electricity_current_rate
        to: sensor.electricity_export_current_rate
    condition:
      - condition: state
        entity_id: input_boolean.enable_solar_assistant_automations
        state: "on"
      - condition: state
        entity_id: input_boolean.solar_assistant_charge_below_export
        state: "on"
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: >-
                Electricity unit rate is the same or below export rate
                ({{ states('sensor.electricity_current_rate') ~'<=' ~
                states('sensor.electricity_export_current_rate') }}). Charging house battery.
              title: Solar Assistant
              log_level: "Debug"
          - service: select.select_option
            target:
              entity_id:
                - select.growatt_sph_work_mode_priority
            data:
              option: Battery first
    mode: single
  - id: "1689626117481"
    alias: "Solar Assistant: Electricity Rates Starts To Cost"
    description: >-
      Disable battery first schedule which is automatically 
      set when changing work mode to battery first.
    trigger:
      - platform: numeric_state
        entity_id: sensor.electricity_current_rate
        above: 0
      - platform: numeric_state
        entity_id: sensor.electricity_current_rate
        above: sensor.electricity_export_current_rate
    condition:
      - condition: state
        entity_id: input_boolean.enable_solar_assistant_automations
        state: "on"
    action:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: sensor.electricity_current_rate
                below: sensor.electricity_export_current_rate
            sequence:
              - service: script.send_to_home_log
                data:
                  message: >-
                    Electrictity rate has gove above 0
                    ({{ states('sensor.electricity_current_rate', with_unit=True) }})p/kw
                    but below export
                    ({{ states('sensor.electricity_export_current_rate', with_unit=True) }}).
                    Keeping house battery charged.
                  title: Solar Assistant
                  log_level: "Debug"
        default:
          - parallel:
              - service: script.send_to_home_log
                data:
                  message: >-
                    {%- from 'calculate_ecoflow_delta2_charge_rate.jinja' import calculate_ecoflow_delta2_charge_rate -%}
                    Electrictity rate has gove above 0
                    ({{ states('sensor.electricity_current_rate', with_unit=True) }})p/kw
                  title: Solar Assistant
                  log_level: "Debug"
              - service: select.select_option
                target:
                  entity_id:
                    - select.growatt_sph_work_mode_priority
                data:
                  option: Load first
              - service: switch.turn_off
                target:
                  entity_id:
                    - switch.growatt_sph_battery_first_slot_1_enabled
                data: {}
    mode: single
