# Created by Danny Tsang <danny@tsang.uk>
automation:
  # Unit rate related automations
  - id: "1691009694611"
    alias: "Solar Assistant: Electricity Rate Below Export Rate"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.electricity_current_rate
        below: sensor.electricity_export_current_rate
      - platform: state
        entity_id: sensor.electricity_current_rate
        to: sensor.electricity_export_current_rate
    condition:
      - condition: state
        entity_id: input_boolean.enable_solar_assistant_automations
        state: "on"
      - condition: state
        entity_id: input_boolean.solar_assistant_charge_below_export
        state: "on"
    action:
      - choose:
        - conditions:
            - or:
              - condition: state
                entity_id: sensor.electricity_current_rate
                state: "0"
              - condition: numeric_state
                entity_id: sensor.electricity_current_rate
                below: 0
            - not:
                - condition: state
                  entity_id: select.growatt_sph_work_mode_priority
                  state: Battery first
            - condition: state
              entity_id: input_boolean.solar_assistant_charge_electricity_cost_nothing
              state: "on"
          sequence:
            - parallel:
                - service: script.send_direct_notification
                  data:
                    message: >-
                      Electrictity rate
                      ({{ states('sensor.electricity_current_rate', with_unit=True) }}) has fallen
                      below £0.00 ({{ states('sensor.electricity_export_current_rate', with_unit=True) }}).
                      Charging house battery.
                    title: Solar Assistant
                    people:
                      entity_id:
                        - person.danny
                - service: script.battery_first_priority_mode
                  data: {}
        - conditions:
            - condition: numeric_state
              entity_id: sensor.electricity_current_rate
              below: sensor.electricity_export_current_rate
            - not:
                - condition: state
                  entity_id: select.growatt_sph_work_mode_priority
                  state: Battery first
            - condition: state
              entity_id: input_boolean.solar_assistant_charge_below_export
              state: "on"
          sequence:
            - parallel:
                - service: script.send_direct_notification
                  data:
                    message: >-
                      Electricity unit rate is the same or below export rate
                      ({{ states('sensor.electricity_current_rate') ~'<=' ~
                      states('sensor.electricity_export_current_rate') }}). Charging house battery.
                    title: Solar Assistant
                    people:
                      entity_id:
                        - person.danny
                - service: script.battery_first_priority_mode
                  data: {}
    mode: single
  - id: "1689626117481"
    alias: "Solar Assistant: Electricity Rates Starts To Cost"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.electricity_current_rate
        above: 0
      - platform: numeric_state
        entity_id: sensor.electricity_current_rate
        above: sensor.electricity_export_current_rate
    condition:
      - condition: state
        entity_id: input_boolean.enable_solar_assistant_automations
        state: "on"
    action:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: sensor.electricity_current_rate
                below: sensor.electricity_export_current_rate
            sequence:
              - service: script.send_to_home_log
                data:
                  message: >-
                    Electrictity rate has gove above 0
                    ({{ states('sensor.electricity_current_rate', with_unit=True) }})p/kw
                    but below export
                    ({{ states('sensor.electricity_export_current_rate', with_unit=True) }}).
                    Keeping house battery charged.
                  title: Solar Assistant
                  log_level: "Debug"
        default:
          - parallel:
              - service: script.send_to_home_log
                data:
                  message: >-
                    Electrictity rate has gove above 0
                    ({{ states('sensor.electricity_current_rate', with_unit=True) }})p/kw.
                  title: Solar Assistant
                  log_level: "Debug"
              - service: script.load_first_priority_mode
                data: {}
    mode: single
  - id: "1702820645690"
    alias: "Solar Assistant: Check Agile Rates"
    description: ""
    trigger:
      - platform: time_pattern
        minutes: "5"
      - platform: time_pattern
        minutes: "35"
    condition:
      - condition: state
        entity_id: input_boolean.enable_solar_assistant_automations
        state: "on"
    action:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: sensor.electricity_current_rate
                above: sensor.electricity_export_current_rate
              - not:
                  - condition: state
                    entity_id: select.growatt_sph_work_mode_priority
                    state: Load first
            sequence:
              - parallel:
                  - service: script.send_direct_notification
                    data:
                      message: >-
                        Electrictity rate has gove above 0
                        ({{ states('sensor.electricity_current_rate', with_unit=True) }})p/kw
                        and inverter has not switched from
                        {{ states('select.growatt_sph_work_mode_priority') }} to load first mode.
                      title: Solar Assistant
                      people:
                        entity_id:
                          - person.danny
                  - service: script.load_first_priority_mode
                    data: {}
          - conditions:
              - or:
                - condition: state
                  entity_id: sensor.electricity_current_rate
                  state: "0"
                - condition: numeric_state
                  entity_id: sensor.electricity_current_rate
                  below: 0
              - not:
                  - condition: state
                    entity_id: select.growatt_sph_work_mode_priority
                    state: Battery first
              - condition: state
                entity_id: input_boolean.solar_assistant_charge_electricity_cost_nothing
                state: "on"
            sequence:
              - parallel:
                  - service: script.send_direct_notification
                    data:
                      message: >-
                        Electrictity rate
                        ({{ states('sensor.electricity_current_rate', with_unit=True) }}) has fallen
                        below £0.00 ({{ states('sensor.electricity_export_current_rate', with_unit=True) }})
                        and inverter has not switched to battery first mode.
                      title: Solar Assistant
                      people:
                        entity_id:
                          - person.danny
                  - service: script.battery_first_priority_mode
                    data: {}
          - conditions:
              - condition: numeric_state
                entity_id: sensor.electricity_current_rate
                below: sensor.electricity_export_current_rate
              - not:
                  - condition: state
                    entity_id: select.growatt_sph_work_mode_priority
                    state: Battery first
              - condition: state
                entity_id: input_boolean.solar_assistant_charge_below_export
                state: "on"
            sequence:
              - parallel:
                  - service: script.send_direct_notification
                    data:
                      message: >-
                        Electrictity rate
                        ({{ states('sensor.electricity_current_rate', with_unit=True) }}) has fallen
                        below export rate ({{ states('sensor.electricity_export_current_rate', with_unit=True) }})
                        and inverter has not switched to battery first mode.
                      title: Solar Assistant
                      people:
                        entity_id:
                          - person.danny
                  - service: script.battery_first_priority_mode
                    data: {}
    mode: single

script:
  battery_first_priority_mode:
    alias: Solar Assistant Battery First Priority Mode
    description: ""
    sequence:
      - if:
          - condition: state
            entity_id: select.growatt_sph_work_mode_priority
            state: Battery first
        then:
          - service: script.send_to_home_log
            data:
              message: >-
                Priority is already set to battery first. Skipping.
              title: Solar Assistant
              log_level: "Normal"
        else:
          - service: script.send_to_home_log
            data:
              message: >-
                Setting priority from {{ states('select.growatt_sph_work_mode_priority') }}
                to battery first.
              title: Solar Assistant
              log_level: "Debug"
          - service: script.turn_off_mode_schedules
            data: {}
          - service: select.select_option
            target:
              entity_id:
                - select.growatt_sph_work_mode_priority
            data:
              option: Battery first
  grid_first_priority_mode:
    alias: Solar Assistant Gird First Priority Mode
    description: ""
    sequence:
      - if:
          - condition: state
            entity_id: select.growatt_sph_work_mode_priority
            state: Grid first
        then:
          - service: script.send_to_home_log
            data:
              message: >-
                Priority is already set to grid first. Skipping.
              title: Solar Assistant
              log_level: "Normal"
        else:
          - if:
              - not:
                  - condition: state
                    entity_id: select.myenergi_eddi_operating_mode
                    state: "Stopped"
            then:
              - service: script.send_direct_notification
                data:
                  message: >-
                    Setting priority from {{ states('select.growatt_sph_work_mode_priority') }}
                    to grid first. FYI eddi is still on.
                  title: Solar Assistant
                  people:
                    entity_id:
                      - person.danny
            else:
              - service: script.send_to_home_log
                data:
                  message: >-
                    Setting priority from {{ states('select.growatt_sph_work_mode_priority') }}
                    to grid first.
                  title: Solar Assistant
                  log_level: "Debug"
          - service: script.turn_off_mode_schedules
            data: {}
          - service: select.select_option
            target:
              entity_id:
                - select.growatt_sph_work_mode_priority
            data:
              option: Gird first
  load_first_priority_mode:
    alias: Solar Assistant Load First Priority Mode
    description: >-
      Disable battery first schedule which is automatically 
      set when changing work mode to battery first.
    sequence:
      - if:
          - condition: state
            entity_id: select.growatt_sph_work_mode_priority
            state: Load first
        then:
          - service: script.send_to_home_log
            data:
              message: >-
                Priority is already set to load first. Skipping.
              title: Solar Assistant
              log_level: "Normal"
        else:
          - service: script.send_to_home_log
            data:
              message: >-
                Setting priority from {{ states('select.growatt_sph_work_mode_priority') }}
                to load first.
              title: Solar Assistant
              log_level: "Debug"
          - service: script.turn_off_mode_schedules
            data: {}
          - service: select.select_option
            target:
              entity_id:
                - select.growatt_sph_work_mode_priority
            data:
              option: Load first
  turn_off_mode_schedules:
    alias: Solar Assistant Turn Off Mode Schedules
    description: >-
      Disable battery first schedule which is automatically 
      set when changing work mode to battery first.
    sequence:
      - parallel:
          - repeat:
            sequence:
              - service: switch.turn_off
                target:
                  entity_id:
                    - switch.growatt_sph_battery_first_slot_1_enabled
                data: {}
              - alias: Delay before checking to see if the setting has taken hold
                delay:
                seconds: 5
            until:
              - condition: state
                entity_id: switch.growatt_sph_battery_first_slot_1_enabled
                state: "off"
                for:
                  hours: 0
                  minutes: 0
                  seconds: 30
          - repeat:
            sequence:
              - service: switch.turn_off
                target:
                  entity_id:
                    - switch.growatt_sph_grid_first_slot_1_enabled
                data: {}
              - alias: Delay before checking to see if the setting has taken hold
                delay:
                seconds: 5
            until:
              - condition: state
                entity_id: switch.growatt_sph_grid_first_slot_1_enabled
                state: "off"
                for:
                  hours: 0
                  minutes: 0
                  seconds: 30

template:
  # Solar Assistant
  - trigger:
      - platform: state
        entity_id:
          - sensor.growatt_sph_battery_power
    sensor:
      - name: "Growatt Battery Discharge Power"
        unique_id: 251bd989-90a2-4e1b-81d0-b6d87f934eeb
        state: "{{ iif(states('sensor.growatt_sph_battery_power')|float < 0, states('sensor.growatt_sph_battery_power')|int|abs, 0) }}"
        device_class: "power"
        unit_of_measurement: "W"
        state_class: "measurement"
  - trigger:
      - platform: state
        entity_id:
          - sensor.growatt_sph_battery_power
    sensor:
      - name: "Growatt Battery Charge Power"
        unique_id: fe4f9f9c-4a61-4b27-9122-9c17ce5da164
        state: >-
          {%- if states('sensor.growatt_sph_battery_power') == 'unknown' -%}
            {{ states('sensor.growatt_sph_battery_power') }}
          {% elif states('sensor.growatt_sph_battery_power')|int(0) > 0 -%}
            {{ states('sensor.growatt_sph_battery_power')|int(0) }}
          {%- else -%}
            0
          {%- endif -%}
        device_class: "power"
        unit_of_measurement: "W"
        state_class: "measurement"
  - trigger:
      - platform: state
        entity_id:
          - sensor.growatt_sph_grid_power
    sensor:
      - name: "Growatt Grid Import Power"
        unique_id: 09f48f73-ea68-421f-868c-ffd20cd8eab8
        state: >-
          {%- if states('sensor.growatt_sph_grid_power') == 'unknown' -%}
            {{ states('sensor.growatt_sph_grid_power') }}
          {% elif states('sensor.growatt_sph_grid_power')|int(0) > 0 -%}
            {{ states('sensor.growatt_sph_grid_power')|int(0) }}
          {%- else -%}
            0
          {%- endif -%}
        device_class: "power"
        unit_of_measurement: "W"
        state_class: "measurement"
  - trigger:
      - platform: state
        entity_id:
          - sensor.growatt_sph_grid_power
    sensor:
      - name: "Growatt Grid Export Power"
        unique_id: ed52b9f5-fddd-4797-85a1-b4fb6df8cd0e
        state: >-
          {%- if states('sensor.growatt_sph_grid_power') == 'unknown' -%}
            {{ states('sensor.growatt_sph_grid_power') }}
          {% elif states('sensor.growatt_sph_grid_power')|int(0) > 0 -%}
            {{ states('sensor.growatt_sph_grid_power')|int(0) }}
          {%- else -%}
            0
          {%- endif -%}
        device_class: "power"
        unit_of_measurement: "W"
        state_class: "measurement"
