# Created by Danny Tsang <danny@tsang.uk>
# Integration: https://github.com/CJNE/ha-myenergi
automation:
  - id: "1712086876964"
    alias: "Zappi: Charging Schedule Started"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.ev_charger_schedule_1
          - binary_sensor.ev_charger_schedule_2
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.enable_zappi_automations
        state: "on"
      - condition: state
        entity_id: sensor.myenergi_zappi_plug_status
        state: "EV Connected"
      - or:
          - and:
              - condition: state
                entity_id: input_boolean.enable_ev_charger_schedule_1
                state: "on"
              - condition: state
                entity_id: input_boolean.enable_ev_charger_schedule_1
                state: "on"
          - and:
              - condition: state
                entity_id: input_boolean.enable_ev_charger_schedule_2
                state: "on"
              - condition: state
                entity_id: input_boolean.enable_ev_charger_schedule_2
                state: "on"
    action:
      - service: script.zappi_check_ev_charge
        data: {}
    mode: single
  - id: "1712086876965"
    alias: "Zappi: Charging Schedule Stopped"
    description: ""
    trace:
      stored_traces: 10
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.ev_charger_schedule_1
          - binary_sensor.ev_charger_schedule_2
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.enable_zappi_automations
        state: "on"
      - not:
          - condition: state
            entity_id: sensor.myenergi_zappi_plug_status
            state: "EV Disconnected"
      - not:
          - condition: state
            entity_id: sensor.myenergi_zappi_status
            state: "Paused"
      - or:
          - condition: state
            entity_id: input_boolean.enable_ev_charger_schedule_1
            state: "on"
          - condition: state
            entity_id: input_boolean.enable_ev_charger_schedule_2
            state: "on"
    action:
      - service: script.send_direct_notification
        metadata: {}
        data:
          message: Charging schedule stopped from {{ state_attr(trigger.entity_id, 'friendly_name') }}
          title: "Zappi: Charging Scheduled Stop"
          people:
            entity_id:
              - person.terina
      - service: myenergi.myenergi_boost
        target:
          entity_id:
            - select.myenergi_zappi_charge_mode
        data:
          amount: 1
      - service: select.select_option
        target:
          entity_id:
            - select.myenergi_zappi_charge_mode
        data:
          option: Eco+
    mode: single
  - id: "1712435997060"
    alias: "Zappi: Connected"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - sensor.myenergi_zappi_plug_status
        from: EV Disconnected
        to: EV Connected
    condition:
      - condition: state
        entity_id: input_boolean.enable_zappi_automations
        state: "on"
    action:
      - service: script.zappi_check_ev_charge
        data: {}
    mode: single
  - id: "1712435997062"
    alias: "Zappi: Check Charging Conditions"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.electricity_current_rate
        below: 0
      - platform: state
        entity_id: sensor.electricity_current_rate
        to: "0.0"
      - platform: homeassistant
        event: start
    condition:
      - condition: state
        entity_id: input_boolean.enable_zappi_automations
        state: "on"
      - condition: state
        entity_id: sensor.myenergi_zappi_plug_status
        state: "EV Connected"
    action:
      - service: script.zappi_check_ev_charge
        data: {}
    mode: single
  - id: "1715345710884"
    alias: "Zappi: Unidentified Vehicle Connected"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - sensor.myenergi_zappi_plug_status
        from: EV Disconnected
        not_to: "unavailable"
        for:
          minutes: 15
    condition:
      - condition: state
        entity_id: input_boolean.enable_zappi_automations
        state: "on"
      - condition: state
        entity_id: binary_sensor.model_y_charger
        state: "off"
      - condition: state
        entity_id: input_boolean.guest_ev
        state: "off"
    action:
      - service: script.send_direct_notification
        metadata: {}
        data:
          message: Vehicle connected and it's not Terina's car.
          title: Zappi
          people:
            entity_id:
              - person.danny
    mode: single
  - id: "1715345710885"
    alias: "Zappi: Vehicle Disconnected"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - sensor.myenergi_zappi_plug_status
        to: EV Disconnected
    condition:
      - condition: state
        entity_id: input_boolean.enable_zappi_automations
        state: "on"
      - condition: state
        entity_id: input_boolean.guest_ev
        state: "on"
    action:
      - parallel:
          - service: script.send_to_home_log
            metadata: {}
            data:
              message: Vehicle disconnected.
              title: Zappi
              debug: "Debug"
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.guest_ev
            data: {}
    mode: single

script:
  zappi_check_ev_charge:
    alias: Zappi Check EV Charge
    sequence:
      - parallel:
          - choose:
              - alias: "Scheduled Charge"
                conditions:
                  - or:
                      - and:
                          - condition: state
                            entity_id: input_boolean.enable_ev_charger_schedule_1
                            state: "on"
                          - condition: state
                            entity_id: binary_sensor.ev_charger_schedule_1
                            state: "on"
                      - and:
                          - condition: state
                            entity_id: input_boolean.enable_ev_charger_schedule_2
                            state: "on"
                          - condition: state
                            entity_id: binary_sensor.ev_charger_schedule_2
                            state: "on"
                sequence:
                  - if:
                      - condition: state
                        entity_id: sensor.myenergi_zappi_plug_status
                        state: EV Connected
                    then:
                      - parallel:
                          - service: script.send_direct_notification
                            metadata: {}
                            data:
                              message: Charging started.
                              title: "Zappi"
                              people:
                                entity_id:
                                  - person.terina
                          - service: myenergi.myenergi_boost
                            target:
                              entity_id: select.myenergi_zappi_charge_mode
                            data:
                              amount: 70
              - alias: "Electricity Rates Below 0p/kWh"
                conditions:
                  - condition: numeric_state
                    entity_id: sensor.electricity_current_rate
                    below: "0"
                  - condition: state
                    entity_id: input_boolean.zappi_charge_when_electricity_cost_below_nothing
                    state: "on"
                sequence:
                  - if:
                      - condition: state
                        entity_id: sensor.myenergi_zappi_plug_status
                        state: EV Connected
                    then:
                      - parallel:
                          - service: script.send_direct_notification
                            metadata: {}
                            data:
                              message: >-
                                Electricity rate is below 0p/kWh (
                                {{ states('sensor.electricity_current_rate')|round(2) ~ ' ' ~ state_attr('sensor.electricity_current_rate', 'unit_of_measurement') }}
                                ).

                                Charging started.
                              title: "Zappi"
                              people:
                                entity_id:
                                  - person.terina
                          - service: myenergi.myenergi_boost
                            target:
                              entity_id: select.myenergi_zappi_charge_mode
                            data:
                              amount: 70
              - alias: "Electricity Rates is 0p/kWh"
                conditions:
                  - condition: state
                    entity_id: sensor.electricity_current_rate
                    state: "0.0"
                  - condition: state
                    entity_id: input_boolean.zappi_charge_when_electricity_cost_nothing
                    state: "on"
                sequence:
                  - if:
                      - condition: state
                        entity_id: sensor.myenergi_zappi_plug_status
                        state: EV Connected
                    then:
                      - parallel:
                          - service: script.send_direct_notification
                            metadata: {}
                            data:
                              message: >-
                                Electricity rate is 0p/kWh. Charging started.
                              title: "Zappi"
                              people:
                                entity_id:
                                  - person.terina
                          - service: myenergi.myenergi_boost
                            target:
                              entity_id: select.myenergi_zappi_charge_mode
                            data:
                              amount: 70
              - alias: "Electricity Rates Starts To Cost"
                conditions:
                  - not:
                      - condition: state
                        entity_id: sensor.myenergi_zappi_plug_status
                        state: EV Connected
                      - condition: state
                        entity_id: sensor.myenergi_zappi_plug_status
                        state: EV Disconnected
                  - condition: numeric_state
                    entity_id: sensor.electricity_current_rate
                    above: "0"
                  - or:
                      - condition: state
                        entity_id: input_boolean.zappi_charge_when_electricity_cost_nothing
                        state: "on"
                      - condition: state
                        entity_id: input_boolean.zappi_charge_when_electricity_cost_below_nothing
                        state: "on"
                sequence:
                  - parallel:
                      - service: script.send_direct_notification
                        metadata: {}
                        data:
                          message: >-
                            Electricity rate is above 0p/kWh (
                            {{ states('sensor.electricity_current_rate')|round(2) ~ ' ' ~ state_attr('sensor.electricity_current_rate', 'unit_of_measurement') }}
                            ).

                            Stopping charge.
                          title: "Zappi"
                          people:
                            entity_id:
                              - person.terina
                      - service: myenergi.myenergi_boost
                        target:
                          entity_id: select.myenergi_zappi_charge_mode
                        data:
                          amount: 1
              - alias: "Default"
                conditions:
                  - not:
                      - condition: state
                        entity_id: sensor.myenergi_zappi_plug_status
                        state: EV Disconnected
                sequence:
                  - service: select.select_option
                    target:
                      entity_id:
                        - select.myenergi_zappi_charge_mode
                    data:
                      option: Eco+
            default: []
          - if:
              - condition: state
                entity_id: sensor.growatt_sph_inverter_mode
                state: Grid first
            then:
              - service: script.send_actionable_notification_with_2_buttons
                data:
                  message:
                    Solar is in {{ states('sensor.growatt_sph_inverter_mode') }}.
                    This may start charging the car rather than exporting back to the grid.
                    Turn off EV charging?
                  title: Zappi
                  people:
                    - person.danny
                    - person.terina
                  action1_title: "Yes"
                  action1_name: zappi_stop
                  action2_title: "No"
                  action2_name: ignore
