esp32_ble_tracker:
  scan_parameters:
    active: true
    interval: 211ms  # suggested 211ms # default 320ms
    window: 120ms  # suggested 120ms # default 30ms

bluetooth_proxy:
  active: true

esp32_improv:
  authorizer: none
