button:
  - platform: restart
    id: restart_internal
    entity_category: config
    internal: true

ota:
  - platform: esphome

switch:
  - platform: restart
    name: "ESP32 Reboot"
    icon: mdi:power-cycle

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
