# Created by Danny Tsang <danny@tsang.uk>
sensor:
  # Computer
  - platform: history_stats
    name: PC Uptime Today
    unique_id: 0991cb72-ffe8-408a-826d-48b0230353c8
    entity_id: group.jd_computer
    state: "home"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: PC Uptime Last 24 Hours
    unique_id: 472320b6-4109-4e07-b914-c8ea54491362
    entity_id: group.jd_computer
    state: "home"
    type: time
    end: "{{ now() }}"
    duration:
      hours: 24
  - platform: history_stats
    name: PC Uptime Yesterday
    unique_id: 8f999940-08bd-49be-85f7-495dfcbe4309
    entity_id: group.jd_computer
    state: "home"
    type: time
    end: "{{ now().replace(hour=0, minute=0, second=0) }}"
    duration:
      hours: 24
  - platform: history_stats
    name: PC Uptime This Week
    unique_id: 837d727a-2290-4527-ab68-3cd78344321c
    entity_id: group.jd_computer
    state: "home"
    type: time
    start: "{{ as_timestamp( now().replace(hour=0, minute=0, second=0) ) - now().weekday() * 86400 }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: PC Uptime Last 30 Days
    unique_id: 9ec48946-234a-4093-844c-800ba67ab340
    entity_id: group.jd_computer
    state: "home"
    type: time
    end: "{{ now().replace(hour=0, minute=0, second=0) }}"
    duration:
      days: 30
  - platform: history_stats
    name: Work Computer Uptime Today
    unique_id: cb2cfc1a-39b5-4225-86b4-5b34d287c0b6
    entity_id: group.dannys_work_computer
    state: "home"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Work Computer Uptime Yesterday
    unique_id: 2fd1cec2-a453-4347-8e7f-14f25e08144c
    entity_id: group.dannys_work_computer
    state: "home"
    type: time
    end: "{{ now().replace(hour=0, minute=0, second=0) }}"
    duration:
      hours: 24
  - platform: history_stats
    name: Work Computer Uptime This Week
    unique_id: dc0e517b-2308-4c6f-8ad8-38665f312ce3
    entity_id: group.dannys_work_computer
    state: "home"
    type: time
    start: "{{ as_timestamp( now().replace(hour=0, minute=0, second=0) ) - now().weekday() * 86400 }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Work Computer Uptime Last 30 Days
    unique_id: 3695a5ba-ebfe-43c2-a7b3-2e04704ae4c4
    entity_id: group.dannys_work_computer
    state: "home"
    type: time
    end: "{{ now().replace(hour=0, minute=0, second=0) }}"
    duration:
      days: 30
