# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1640970081113"
    alias: "^Attic: Water Tank Below 50%"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.attic_water_tank_percent
        below: "50"
        for:
          hours: 0
          minutes: 2
          seconds: 0
    condition:
      - not:
          - condition: state
            entity_id: sensor.attic_water_tank_percent
            state: unavailable
    action:
      - service: script.send_to_home_log
        data:
          message: ":potable_water: Water tank is below 50% full."
    mode: single
  - id: "1640970248794"
    alias: "^Attic: Water Tank Below 25%"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.attic_water_tank_percent
        below: "25"
        for:
          hours: 0
          minutes: 2
          seconds: 0
    condition:
      - not:
          - condition: state
            entity_id: sensor.attic_water_tank_percent
            state: unavailable

    action:
      - service: script.send_direct_notification
        data:
          title: ":potable_water: Water tank is low"
          message: Check water tank in the attic because it's below 25%.
      - service: script.send_to_home_log
        data:
          message:
            ":potable_water: Check water tank in the attic because it's below
            25%."
    mode: single
group:
  attic_area_temperature:
    name: Attic Temperature
    icon: mdi:thermometer
    entities:
      - sensor.attic_temperature
      - sensor.attic_temperature_2
template:
  - sensor:
    - name: Attic Water Tank Percent
      unit_of_measurement: "%"
      # Dry resistance value (max) = 0.54
      # Fully submerged in tank (min) = 0.36/0.37
      # Formula for calculating the percent for the above range: ((input - min) * 100) / (max - min)
      # The above would result in the inverse i.e full tank = 0% and empty = 100%.
      # Inverse formula: max / (1 + current %).
      # Full formala: max / (1 + ((input - min) * 100) / (max - min))
      # References:
      #  https://stackoverflow.com/questions/25835591/how-to-calculate-percentage-between-the-range-of-two-values-a-third-value-is/25835683
      #  https://www.quora.com/How-do-you-calculate-a-reverse-percentage-What-is-the-formula
      state: >-
        {% if states('sensor.water_tank_level') == 'unavailable' %}unavailable
        {% else %}{{ (0.54/(1+((states('sensor.water_tank_level') | float - 0.37) / (0.54 - 0.37)))/0.54)*100 }}
        {% endif %}
      icon: "{% if (0.54/(1+((states('sensor.water_tank_level') | float - 0.37) / (0.54 - 0.37)))/0.54)*100 | int > 50 %}
      mdi:water-percent {% elif (0.54/(1+((states('sensor.water_tank_level') | float - 0.37) / (0.54 - 0.37)))/0.54)*100 | int > 25 %}
      mdi:water-percent-alert{% else %}
      mdi:water-remove{% endif %}"
