# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1676493888411"
    alias: "Attic: Hatch Opened"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.attic_hatch_contact
        from: "off"
        to: "on"
    conditions: []
    actions:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: Attic hatch opened. Turning lights on.
              title: "Attic"
              log_level: "Debug"
          - action: light.turn_on
            data: {}
            target:
              entity_id: light.attic
    mode: single
  - id: "1676493961946"
    alias: "Attic: Hatch Closed"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.attic_hatch_contact
        from: "on"
        to: "off"
    conditions: []
    actions:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: Attic hatch opened. Turning lights off.
              title: "Attic"
              log_level: "Debug"
          - action: light.turn_off
            data: {}
            target:
              entity_id: light.attic
    mode: single
  - id: "1664827040573"
    alias: "Attic: Lights On"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - light.attic
        to: "on"
        for:
          hours: 0
          minutes: 30
          seconds: 0
    conditions: []
    actions:
      - action: script.send_actionable_notification_with_2_buttons
        data:
          message: Lights have been on for 15 minutes. Turn off?
          title: Attic
          people:
            entity_id:
              - person.danny
              - person.terina
          action1_title: "Yes"
          action1_name: switch_off_attic_lights
          action2_title: "No"
          action2_name: ignore
    mode: single
