# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1622309854294"
    alias: "^Back Garden: Door Open And Motion Detected"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.back_garden_motion
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: group.back_doors
        state: "on"
    action:
      - service: script.post_to_home_log
        data:
          message: ":paw_prints: :door: {% set count = namespace(value=0) %}{% for door in state_attr('group.back_doors','entity_id') %}{% if states(door) == 'on' %}{%if count.value > 1 %}and {%endif%}{{ state_attr(door,'friendly_name') }}{% set count.value = count.value + 1 %}{% endif %}{% endfor %}{% if count.value >= 2 %} are {%else%} is {% endif %}open and motion detected in the back garden. 
          :camera: Capturing image for processing."
      - service: script.conservatory_camera_process_image
        data:
          title: Snapshot
          message: Motion Detected In Back Garden And Shed/Conservatory Door Open
    mode: queued
    max: 10

group:
  back_doors:
    name: Back Doors
    icon: mdi:door
    entities:
      - binary_sensor.conservatory_door
      - binary_sensor.shed_door
