# Created by Danny Tsang <danny@tsang.uk>
automation:
  # Shed
  - id: "1618158789152"
    alias: "Shed: Door Closed"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.shed_door
        from: "on"
        to: "off"
    condition: []
    action:
      - choose:
          - conditions:
              - not:
                  - condition: state
                    entity_id: alarm_control_panel.house_alarm
                    state: disarmed
              - condition: state
                entity_id: binary_sensor.conservatory_door
                state: "on"
            sequence:
              - service: script.send_to_home_log
                data:
                  message: ":door: Door closed. Keeping conservatory
                  :camera: camera on because :bell: alarm is armed and conservatory door is open."
                  title: ":hut: Shed"
          - conditions:
            - not:
                - condition: state
                  entity_id: alarm_control_panel.house_alarm
                  state: disarmed
            - condition: state
              entity_id: binary_sensor.conservatory_door
              state: "off"
            sequence:
              - service: script.send_to_home_log
                data:
                  message: ":door: Door closed. Keeping conservatory
                  camera on because :bell: alarm is armed."
                  title: ":hut: Shed"
          - conditions:
            - condition: state
              entity_id: binary_sensor.conservatory_door
              state: "on"
            sequence:
              - service: script.send_to_home_log
                data:
                  message: ":door: Door closed. Keeping conservatory
                  :camera: camera on because conservatory :door: door is open."
                  title: ":hut: Shed"
          - conditions:
              - condition: state
                entity_id: alarm_control_panel.house_alarm
                state: "disarmed"
            sequence:
              - parallel:
                  - service: script.send_to_home_log
                    data:
                      message: ":door: Door closed. Turning conservatory
                      :camera: camera off."
                      title: ":hut: Shed"
                  - service: script.conservatory_turn_off_camera
          - conditions:
              - not:
                  - condition: state
                    entity_id: alarm_control_panel.house_alarm
                    state: "disarmed"
            sequence:
              - service: script.send_to_home_log
                data:
                  message: ":door: Door closed. Keeping conservatory
                  camera on because :bell: alarm is armed."
                  title: ":hut: Shed"
        default: []
    mode: single
  - id: "1618158730212"
    alias: "Shed: Door Opened"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.shed_door
        from: "off"
        to: "on"
    condition: []
    action:
      - parallel:
        - service: script.send_to_home_log
          data:
            message:
              ":door: :hut: :camera_with_flash: Shed door opened. Turning conservatory
              camera on."
            title: ":hut: Shed"
        - service: script.conservatory_turn_on_camera
    mode: single
  - id: "1618158998129"
    alias: "Shed: Motion Detected When Door Is Closed"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.shed_motion
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: binary_sensor.shed_door
        state: "off"
    action:
      - service: script.send_direct_notification
        data:
          message: ":paw_prints: Motion detected in the shed and the door is shut."
          title: ":hut: Shed"
    mode: single
