# Created by Danny Tsang <danny@tsang.uk>
automation:
  # Shed
  - id: "1618158789152"
    alias: "Shed: Door Closed"
    description: ""
    triggers:
      - trigger: state
        entity_id: binary_sensor.shed_door
        from: "on"
        to: "off"
    condition: []
    actions:
      - choose:
          - conditions:
              - not:
                  - condition: state
                    entity_id: alarm_control_panel.house_alarm
                    state: "disarmed"
              - condition: state
                entity_id: binary_sensor.conservatory_door
                state: "on"
            sequence:
              - action: script.send_to_home_log
                data:
                  message: ":door: Door closed. Keeping conservatory
                  :camera: camera on because :bell: alarm is armed and conservatory door is open."
                  title: ":hut: Shed"
                  log_level: "Debug"
          - conditions:
            - not:
                - condition: state
                  entity_id: alarm_control_panel.house_alarm
                  state: "disarmed"
            - condition: state
              entity_id: binary_sensor.conservatory_door
              state: "off"
            sequence:
              - action: script.send_to_home_log
                data:
                  message: ":door: Door closed. Keeping conservatory
                  camera on because :bell: alarm is armed."
                  title: ":hut: Shed"
                  log_level: "Debug"
          - conditions:
            - condition: state
              entity_id: binary_sensor.conservatory_door
              state: "on"
            sequence:
              - action: script.send_to_home_log
                data:
                  message: ":door: Door closed. Keeping conservatory
                  :camera: camera on because conservatory :door: door is open."
                  title: ":hut: Shed"
                  log_level: "Debug"
          - conditions:
              - condition: state
                entity_id: alarm_control_panel.house_alarm
                state: "disarmed"
            sequence:
              - parallel:
                  - action: script.send_to_home_log
                    data:
                      message: ":door: Door closed. Turning conservatory
                      :camera: camera off."
                      title: ":hut: Shed"
                      log_level: "Debug"
          - conditions:
              - not:
                  - condition: state
                    entity_id: alarm_control_panel.house_alarm
                    state: "disarmed"
            sequence:
              - action: script.send_to_home_log
                data:
                  message: ":door: Door closed. Keeping conservatory
                  camera on because :bell: alarm is armed."
                  title: ":hut: Shed"
                  log_level: "Debug"
        default: []
    mode: single
  - id: "1618158998129"
    alias: "Shed: Motion Detected When Door Is Closed"
    description: ""
    triggers:
      - trigger: state
        entity_id: binary_sensor.shed_motion
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: binary_sensor.shed_door
        state: "off"
    actions:
      - action: script.send_direct_notification
        data:
          message: ":paw_prints: Motion detected in the shed and the door is shut."
          title: ":hut: Shed"
          log_level: "Debug"
    mode: single
  # Light Level
  - id: "1660894232445"
    alias: "Back Garden: Below Direct Sun Light"
    description: ""
    triggers:
      - trigger: numeric_state
        entity_id: sensor.back_garden_motion_illuminance_lux
        for:
          hours: 0
          minutes: 10
          seconds: 0
        below: input_number.close_blinds_brightness_threshold
    condition: []
    actions:
      - action: script.send_to_home_log
        data:
          message:
            Sun light has fallen below {{ states('input_number.close_blinds_brightness_threshold')
            }} ({{ states('sensor.back_garden_motion_illuminance_lux') }}){{ state_attr('sensor.back_garden_motion_illuminance_lux',
            'unit_of_measurement') }}. Opening blinds/curtains.
          title: Back Garden
          log_level: "Debug"
      - if:
          - condition: numeric_state
            entity_id: cover.bedroom_blinds
            attribute: current_position
            below: input_number.blind_closed_position_threshold
          - condition: time
            before: input_datetime.childrens_bed_time
        then:
          - action: cover.open_cover
            target:
              entity_id: cover.leos_bedroom_blinds
    mode: single
