# Created by Danny Tsang <danny@tsang.uk>
automation:
  # Shed
  - id: "1622309854294"
    alias: "Back Garden: Door Open And Motion Detected"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.back_garden_motion
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: binary_sensor.back_doors
        state: "on"
    action:
      - parallel:
        - service: script.send_to_home_log
          data:
            message: >-
              :paw_prints: Motion detected and :door: Shed/Conservatory door open
              {% set count = namespace(value=0) %}
              {% for door in state_attr('binary_sensor.back_doors','entity_id') %}
              {% if states(door) == 'on' %}{%if count.value > 1 %}and {%endif%}
              {{ state_attr(door,'friendly_name') }}
              {% set count.value = count.value + 1 %}{% endif %}{% endfor %}
              {% if count.value >= 2 %}are{%else%}is{% endif %}
              open. :camera_with_flash: Capturing image for processing.
            title: ":deciduous_tree: Back Garden"
        - service: script.conservatory_camera_process_image
          data:
            message: "Sending image for processing."
            title: ":deciduous_tree: Back Garden"
    mode: queued
    max: 10
  - id: "1618158789152"
    alias: "Shed: Door Closed"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.shed_door
        from: "on"
        to: "off"
    condition: []
    action:
      - choose:
          - conditions:
              - not:
                  - condition: state
                    entity_id: alarm_control_panel.house_alarm
                    state: disarmed
              - condition: state
                entity_id: binary_sensor.conservatory_door
                state: "on"
            sequence:
              - service: script.send_to_home_log
                data:
                  message: ":door: Door closed. Keeping conservatory
                  :camera: camera on because :bell: alarm is armed and conservatory door is open."
                  title: ":hut: Shed"
          - conditions:
            - not:
                - condition: state
                  entity_id: alarm_control_panel.house_alarm
                  state: disarmed
            - condition: state
              entity_id: binary_sensor.conservatory_door
              state: "off"
            sequence:
              - service: script.send_to_home_log
                data:
                  message: ":door: Door closed. Keeping conservatory
                  camera on because :bell: alarm is armed."
                  title: ":hut: Shed"
          - conditions:
            - condition: state
              entity_id: binary_sensor.conservatory_door
              state: "on"
            sequence:
              - service: script.send_to_home_log
                data:
                  message: ":door: Door closed. Keeping conservatory
                  :camera: camera on because conservatory :door: door is open."
                  title: ":hut: Shed"
          - conditions:
              - condition: state
                entity_id: alarm_control_panel.house_alarm
                state: "disarmed"
            sequence:
              - parallel:
                  - service: script.send_to_home_log
                    data:
                      message: ":door: Door closed. Turning conservatory
                      :camera: camera off."
                      title: ":hut: Shed"
                  - service: script.conservatory_turn_off_camera
          - conditions:
              - not:
                  - condition: state
                    entity_id: alarm_control_panel.house_alarm
                    state: "disarmed"
            sequence:
              - service: script.send_to_home_log
                data:
                  message: ":door: Door closed. Keeping conservatory
                  camera on because :bell: alarm is armed."
                  title: ":hut: Shed"
        default: []
    mode: single
  - id: "1618158730212"
    alias: "Shed: Door Opened"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.shed_door
        from: "off"
        to: "on"
    condition: []
    action:
      - parallel:
        - service: script.send_to_home_log
          data:
            message:
              ":door: :hut: :camera_with_flash: Shed door opened. Turning conservatory
              camera on."
            title: ":hut: Shed"
        - service: script.conservatory_turn_on_camera
    mode: single
