# Created by Danny Tsang <danny@tsang.uk>
automation:
  # Shed
  - id: "1622309854294"
    alias: "^Back Garden: Door Open And Motion Detected"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.back_garden_motion
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: group.back_doors
        state: "on"
    action:
      - service: script.post_to_home_log
        data:
          message: ":paw_prints: :door: {% set count = namespace(value=0) %}{% for door in state_attr('group.back_doors','entity_id') %}{% if states(door) == 'on' %}{%if count.value > 1 %}and {%endif%}{{ state_attr(door,'friendly_name') }}{% set count.value = count.value + 1 %}{% endif %}{% endfor %}{% if count.value >= 2 %} are {%else%} is {% endif %}open and motion detected in the back garden. :camera_with_flash: Capturing image for processing."
      - service: script.conservatory_camera_process_image
        data:
          title: Back Garden Snapshot
          message: Motion Detected In Back Garden And Shed/Conservatory Door Open
    mode: queued
    max: 10
  - id: "1618158789152"
    alias: "^Shed: Door Closed"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.shed_door
        from: "on"
        to: "off"
    condition: []
    action:
      - choose:
          - conditions:
              - condition: not
                conditions:
                  - condition: state
                    entity_id: alarm_control_panel.house_alarm
                    state: disarmed
              - condition: state
                entity_id: binary_sensor.conservatory_door
                state: "on"
            sequence:
              - choose:
                - conditions:
                    - condition: state
                      state: "on"
                      entity_id: input_boolean.enable_slack_notifications
                  sequence:
                    - service: script.post_to_home_log
                      data:
                        message: ":door: :hut: :bell: Shed door closed. Keeping conservatory
                        camera on because alarm is armed and conservatory door is open."
                default: []
          - conditions:
            - condition: not
              conditions:
                - condition: state
                  entity_id: alarm_control_panel.house_alarm
                  state: disarmed
            - condition: state
              entity_id: binary_sensor.conservatory_door
              state: "off"
            sequence:
              - choose:
                - conditions:
                    - condition: state
                      state: "on"
                      entity_id: input_boolean.enable_slack_notifications
                  sequence:
                    - service: script.post_to_home_log
                      data:
                        message: ":door: :hut: :bell: Shed door closed. Keeping conservatory
                        camera on because alarm is armed."
                default: []
          - conditions:
            - condition: state
              entity_id: binary_sensor.conservatory_door
              state: "on"
            sequence:
              - choose:
                - conditions:
                    - condition: state
                      state: "on"
                      entity_id: input_boolean.enable_slack_notifications
                  sequence:
                    - service: script.post_to_home_log
                      data:
                        message: ":door: :hut: :bell: Shed door closed. Keeping conservatory
                        camera on because conservatory door is open."
                default: []
          - conditions:
              - condition: state
                entity_id: alarm_control_panel.house_alarm
                state: "disarmed"
            sequence:
              - choose:
                - conditions:
                    - condition: state
                      state: "on"
                      entity_id: input_boolean.enable_slack_notifications
                  sequence:
                    - service: script.post_to_home_log
                      data:
                        message: ":door: :hut: :camera: Shed door closed. Turning conservatory
                        camera off."
                default: []
              - service: script.conservatory_turn_off_camera
          - conditions:
              - condition: not
                conditions:
                  - condition: state
                    entity_id: alarm_control_panel.house_alarm
                    state: "disarmed"
            sequence:
              - choose:
                - conditions:
                    - condition: state
                      state: "on"
                      entity_id: input_boolean.enable_slack_notifications
                  sequence:
                    - service: script.post_to_home_log
                      data:
                        message: ":door: :hut: :bell: Shed door closed. Keeping conservatory
                        camera on because alarm is armed."
                default: []
        default: []
    mode: single
input_boolean:
  enable_back_garden_motion_trigger:
    name: Enable motion trigger for back garden
    icon: mdi:motion-sensor
group:
  back_doors:
    name: Back Doors
    icon: mdi:door
    entities:
      - binary_sensor.conservatory_door
      - binary_sensor.shed_door
