# Created by Danny Tsang <danny@tsang.uk>
automation:
  # region Motion
  - id: "1754227355547"
    alias: "Bathroom: Motion Detected"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.bathroom_motion_pir
        to: "on"
    conditions: []
    actions:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: light.bathroom_lights
                    state: "off"
                  - condition: numeric_state
                    entity_id: sensor.bathroom_area_mean_light_level
                    above: input_number.bathroom_light_level_threshold
                sequence:
                  - action: script.send_to_home_log
                    data:
                      message: >-
                        :paw_prints: Motion detected. but it's too bright (
                        {{ states('sensor.bathroom_area_mean_light_level') }} > {{ states('input_number.bathroom_light_level_threshold') }}).
                        Skipping turning on lights.
                      title: ":bathtub: Bathroom"
                      debug: "Debug"
              - conditions:
                  - condition: state
                    entity_id: light.bathroom_lights
                    state: "off"
                sequence:
                  - parallel:
                      - action: script.send_to_home_log
                        data:
                          message: ":paw_prints: Motion detected. Turning :bulb: light on."
                          title: ":bathtub: Bathroom"
                          debug: "Debug"
                      - action: light.turn_on
                        metadata: {}
                        data: {}
                        target:
                          entity_id: light.bathroom_lights
            default:
              - action: script.send_to_home_log
                data:
                  message: ":paw_prints: Motion detected and :bulb: light is already on."
                  title: ":bathtub: Bathroom"
                  debug: "Debug"
          - action: timer.cancel
            target:
              entity_id: timer.bathroom_light
            data: {}
    mode: single
  - id: "1754227694151"
    alias: "Bathroom: No Motion Detected"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.bathroom_motion_pir
        to: "off"
        for:
          hours: 0
          minutes: 5
          seconds: 0
    conditions: []
    actions:
      - choose:
          - alias: Door closed
            conditions:
              - condition: state
                entity_id: binary_sensor.bathroom_door_contact
                state: "off"
            sequence:
              - action: script.send_to_home_log
                data:
                  message: ":no_pedestrians: No motion detected and door closed. Skipping turning :bulb: light off."
                  title: ":bathtub: Bathroom"
                  debug: "Debug"
          - alias: Door open
            conditions:
              - condition: state
                entity_id: binary_sensor.bathroom_door_contact
                state: "on"
            sequence:
              - parallel:
                  - action: script.send_to_home_log
                    data:
                      message: ":no_pedestrians: No motion detected. Starting :hourglass_flowing_sand: timer."
                      title: ":bathtub: Bathroom"
                      debug: "Debug"
                  - action: timer.start
                    target:
                      entity_id: timer.bathroom_light
                    data:
                      duration: 00:05:00
        default: []
    mode: single
  # region Lights
  - id: "1754254675071"
    alias: "Bathroom: Light Turned Off"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - light.bathroom_lights
        to: "off"
    conditions: []
    actions:

      - parallel:
          - action: script.send_to_home_log
            data:
              message: ":bulb: Lights turned off. Cancelling light timer."
              title: ":bathtub: Bathroom"
              debug: "Debug"
          - action: timer.cancel
            target:
              entity_id: timer.bathroom_light
            data: {}
    mode: single
  - id: "1754254675073"
    alias: "Bathroom: Light Switch Toggled"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.bathroom_light_input_0
    conditions: []
    actions:
      - delay:
          seconds: 1
      - choose:
          - conditions:
              - condition: state
                entity_id: light.bathroom_lights
                state: "on"
            sequence:
              - parallel:
                  - action: script.send_to_home_log
                    data:
                      message: "Light switch used"
                      title: ":bathtub: Bathroom"
                      debug: "Debug"
                  - action: timer.cancel
                    target:
                      entity_id: timer.bathroom_light
                    data: {}
        default: []
    mode: single
  - id: "1754254675072"
    alias: "Bathroom: Light Timer Finished"
    description: ""
    triggers:
      - trigger: event
        event_type: timer.finished
        event_data:
          entity_id: timer.bathroom_light
    conditions: []
    actions:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: ":bulb: Light timer finished. Turning off lights."
              title: ":bathtub: Bathroom"
              debug: "Debug"
          - action: light.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: light.bathroom_lights
    mode: single
    
  # region Door
  - id: "1680461746985"
    alias: "Bathroom: High Humidity"
    description: ""
    triggers:
      - trigger: numeric_state
        entity_id: sensor.bathroom_motion_humidity
        for:
          hours: 0
          minutes: 30
          seconds: 0
        above: 59.9
    conditions:
      - condition: state
        entity_id: binary_sensor.bathroom_window_contact
        state: "off"
    actions:
      - action: script.send_direct_notification
        data:
          message: "High Humidity ({{ states('sensor.bathroom_motion_humidity') }} > 59.9%) and window is closed."
          title: ":bathtub: Bathroom"
          log_level: "Debug"
          people:
            entity_id:
              - person.danny
              - person.terina
    mode: single

scene:
  - id: "1610310643539"
    name: "Bathroom: Light On"
    entities:
      light.bathroom:
        min_mireds: 111
        max_mireds: 400
        effect_list:
          - effect_colorloop
          - effect_pulse
          - effect_stop
        brightness: 255
        color_temp: 285
        friendly_name: Bathroom Light
        supported_features: 55
        state: "on"
  - id: "1610310671262"
    name: "Bathroom: Turn Off Light"
    entities:
      light.bathroom:
        min_mireds: 111
        max_mireds: 400
        effect_list:
          - effect_colorloop
          - effect_pulse
          - effect_stop
        friendly_name: Bathroom Light
        supported_features: 55
        state: "off"
  - id: "1610310719574"
    name: "Bathroom: Dim Lights"
    entities:
      light.bathroom:
        min_mireds: 111
        max_mireds: 400
        effect_list:
          - effect_colorloop
          - effect_pulse
          - effect_stop
        brightness: 26
        color_temp: 285
        friendly_name: Bathroom Light
        supported_features: 55
        state: "on"
  - id: "1632078596492"
    name: Bathroom Night Light
    entities:
      light.bathroom:
        min_mireds: 153
        max_mireds: 454
        effect_list:
          - effect_pulse
          - effect_stop
        supported_color_modes:
          - color_temp
        color_mode: color_temp
        brightness: 102
        color_temp: 454
        hs_color:
          - 29.79
          - 84.553
        rgb_color:
          - 255
          - 146
          - 39
        xy_color:
          - 0.579
          - 0.388
        friendly_name: Bathroom Light
        supported_features: 39
        state: "on"
    icon: mdi:lightbulb

script:
  bathroom_flash_light:
    alias: Bathroom Flash Light
    sequence:
      - repeat:
          count: "2"
          sequence:
            - action: light.turn_on
              data:
                brightness_pct: 100
              entity_id: light.bathroom
            - action: light.turn_off
              data: {}
              entity_id: light.bathroom
    mode: single

sensor:
  - platform: mold_indicator
    name: Bathroom Mould Indicator
    indoor_temp_sensor: sensor.bathroom_door_temperature
    indoor_humidity_sensor: sensor.bathroom_motion_humidity
    outdoor_temp_sensor: sensor.gw2000a_outdoor_temperature
    calibration_factor: 1.32
