# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1610307951215"
    alias: "^Bathroom: Motion Detected And It's Dark"
    description: ""
    trigger:
      - platform: state
        entity_id: group.bathroom_motion
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.enable_bathroom_motion_trigger
        state: "on"
      - condition: state
        entity_id: input_boolean.bathroom_light_override
        state: "off"
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: light.bathroom_light
            attribute: brightness
            below: "200"
          - condition: template
            value_template:
              '{{ state_attr("light.bathroom_light", "brightness") ==
              none }}'
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: Guest
              - condition: numeric_state
                entity_id: sensor.bathroom_motion_2_light_level
                below: "40"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":paw_prints: :bathtub: Motion detected in the bathroom and it's dark in :busts_in_silhouette: 
                      guest mode ({{ states('sensor.bathroom_motion_light_level') }} < 40 lux). Turning lights on."
              - scene: scene.bathroom_light_on
          - conditions:
              - condition: not
                conditions:
                  - condition: state
                    entity_id: input_select.home_mode
                    state: Guest
              - condition: numeric_state
                entity_id: sensor.bathroom_motion_2_light_level
                below: "30"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":paw_prints: :bathtub: Motion detected in the bathroom and it's dark ({{ states('sensor.bathroom_motion_light_level') }}
                    < 40 lux). Turning lights on."
              - scene: scene.bathroom_light_on
        default: []
    mode: single
  - id: "1610314735644"
    alias: "^Bathroom: No Motion Detected"
    description: ""
    trigger:
      - platform: state
        to: "off"
        for: 00:03:30
        entity_id: group.bathroom_motion
        id: door_open
      - platform: state
        to: "off"
        for: 00:12:00
        entity_id: group.bathroom_motion
        id: door_closed
    condition:
      - condition: state
        entity_id: light.bathroom_light
        state: "on"
      - condition: state
        entity_id: input_boolean.enable_bathroom_motion_trigger
        state: "on"
    action:
      - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.bathroom_door
              state: "on"
            - condition: state
              entity_id: input_boolean.bathroom_light_override
              state: "off"
            - condition: trigger
              id: door_open
          sequence:
            - service: script.post_to_home_log
              data:
                message:
                  ":no_pedestrians: No motion again and door is open. Turning bathroom
                  light off."
            - service: scene.turn_on
              target:
                entity_id: scene.bathroom_turn_off_light
        - conditions:
            - condition: state
              entity_id: binary_sensor.bathroom_door
              state: "off"
            - condition: trigger
              id: door_closed
          sequence:
            - service: script.post_to_home_log
              data:
                message:
                  ":no_pedestrians: No motion again and door is closed. Turning bathroom
                  light off."
            - service: scene.turn_on
              target:
                entity_id: scene.bathroom_turn_off_light
        default: []
    mode: single
  - id: "1611164800136"
    alias: "^Bathroom: No Motion Detected Dimming Lights"
    description: ""
    trigger:
      - platform: state
        entity_id: group.bathroom_motion
        to: "off"
        for: 00:03:00
        id: short
      - platform: state
        entity_id: group.bathroom_motion
        to: "off"
        for: 00:10:00
        id: long
    condition:
      - condition: state
        entity_id: light.bathroom_light
        state: "on"
      - condition: state
        entity_id: input_boolean.enable_bathroom_motion_trigger
        state: "on"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.bathroom_door
                state: "on"
              - condition: state
                entity_id: input_boolean.bathroom_light_override
                state: "off"
              - condition: trigger
                id: short
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":no_pedestrians: :bulb: :low_brightness: No motion and door is open.
                    Dimming bathroom light."
              - service: scene.turn_on
                target:
                  entity_id: scene.bathroom_dim_lights
          - conditions:
              - condition: state
                entity_id: binary_sensor.bathroom_door
                state: "off"
              - condition: trigger
                id: long
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":no_pedestrians: :bathtub: :bulb: :low_brightness: No motion and door
                    is closed. Dimming bathroom light."
              - service: scene.turn_on
                target:
                  entity_id: scene.bathroom_dim_lights
        default: []
    mode: single
  - id: "1613684184857"
    alias: "^Bathroom: Door Opened"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_door
        to: "on"
        from: "off"
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":bathtub: :door: Bathroom door opened. Incrementing counter :abacus:
            from {{ states('counter.bathroom_door') }} to {{ states('counter.bathroom_door')
            | int + state_attr('counter.bathroom_door', 'step') | int }}."
      - service: counter.increment
        data: {}
        entity_id: counter.bathroom_door
    mode: single
  - id: "1611164672680"
    alias: "^Bathroom: Door Closed And It's Dark"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_door
        to: "off"
        from: "on"
    condition:
      - condition: state
        entity_id: input_boolean.enable_bathroom_motion_trigger
        state: "on"
      - condition: numeric_state
        entity_id: sensor.bathroom_motion_light_level
        below: "30"
    action:
      - service: script.post_to_home_log
        data:
          message: ":bathtub: :door: Bathroom door closed and it's dark
          ({{ states('sensor.bathroom_motion_light_level') }} lux < 30 lux). 
          Turning lights on."
      - scene: scene.bathroom_light_on
    mode: single
  - id: "1613684645058"
    alias: "Bathroom: Door Opened Once For More than 20 seconds"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_door
        to: "on"
        from: "off"
        for: 00:00:20
    condition:
      - condition: numeric_state
        entity_id: counter.bathroom_door
        below: "2"
    action:
      - service: script.post_to_home_log
        data:
          message:
            ':bathtub: :door: :abacus: Bathroom  door has been opened for more
            than 20 secs. Resetting counter  from {{ states("counter.bathroom_door")
            }} to 0'
      - service: counter.reset
        data: {}
        entity_id: counter.bathroom_door
    mode: single
  - id: "1613697803282"
    alias: "^Bathroom: Door Closed And Opened In Succession"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: counter.bathroom_door
        above: "1"
    condition:
      - condition: state
        entity_id: input_boolean.enable_bathroom_light_override
        state: "on"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.bathroom_light_override
                state: "off"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":bathtub: :door: Closed and opened {{ states('counter.bathroom_door')
                    }}x in 30 seconds, keeping lights on for 10 minutes."
              - service: script.bathroom_flash_light
                data: {}
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 2
                  milliseconds: 0
              - scene: scene.bathroom_light_on
              - service: counter.reset
                data: {}
                entity_id: counter.bathroom_door
              - service: input_boolean.turn_on
                data: {}
                entity_id: input_boolean.bathroom_light_override
          - conditions:
              - condition: state
                entity_id: input_boolean.bathroom_light_override
                state: "on"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":bathtub: :door: Closed and opened {{ states('counter.bathroom_door')
                    }} in 30 seconds, resetting lights to :paw_prints: motion detection."
              - service: script.bathroom_flash_light
                data: {}
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 2
                  milliseconds: 0
              - scene: scene.bathroom_turn_off_light
              - service: counter.reset
                data: {}
                entity_id: counter.bathroom_door
              - service: input_boolean.turn_off
                data: {}
                entity_id: input_boolean.bathroom_light_override
        default: []
    mode: single
  # Blinds
  - id: "1621203193434"
    alias: "^Bathroom: Open Blinds In The Morning"
    description: ""
    trigger:
      - platform: time
        at: 06:30:00
    condition:
      - condition: state
        entity_id: input_boolean.enable_bathroom_blind_automations
        state: "on"
    action:
      - service: script.post_to_home_log
        data:
          message: opening bathroom blinds
      - service: cover.open_cover
        target:
          entity_id: cover.bathroom_blinds
    mode: single
  - id: "1621203351544"
    alias: "^Bathroom: Close Blinds At Night"
    description: ""
    trigger:
      - platform: time
        at: 00:00:00
    condition:
      - condition: state
        entity_id: input_boolean.enable_bathroom_blind_automations
        state: "on"
    action:
      - service: script.post_to_home_log
        data:
          message: ":city_sunset: :window: It's getting dark, closing bathroom's blinds."
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.bathroom_window
                state: "on"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":warning: :window: Bathroom window is still open. Waiting until
                    it's closed before closing blinds. :warning:"
        default:
          - service: cover.set_cover_position
            target:
              entity_id: cover.bathroom_blinds
            data:
              position: 40
    mode: single
  - id: "1622667464880"
    alias: "^Bedroom: Window Closed At Night"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.bedroom_window
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.enable_bedroom_blind_automations
        state: "on"
      - condition: sun
        after: sunset
      - condition: sun
        before: sunrise
      - condition: not
        conditions:
          - condition: state
            entity_id: cover.bedroom_blind
            state: "closed"
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":window: :city_sunset: Bedroom window closed and it's dark. Closing
            blinds."
      - service: cover.set_cover_position
        data:
          position: 40
    mode: single
  - id: "1622934382699"
    alias: "^Bathroom: Window Closed At Night 2"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_window
        from: "on"
        to: "off"
    condition:
      - condition: time
        after: 00:00:00
        before: 06:30:00
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":window: :city_sunset: Bathroom window closed and it's dark. Closing
            blinds."
      - service: cover.close_cover
        target:
          entity_id: cover.bathroom_blinds
    mode: single
counter:
  bathroom_door:
    name: Bathroom Door Open Close
    restore: false
    initial: 0
    minimum: 0
    step: 1
group:
  bathroom_motion:
    name: Bathroom Motion
    icon: mdi:walk
    entities:
      - binary_sensor.bathroom_motion
      - binary_sensor.bathroom_motion_2
input_boolean:
  enable_bathroom_blind_automations:
    name: Enable bathroom blind automations
    icon: mdi:window-open
  enable_bathroom_light_override:
    name: Enable Bathroom Override Feature
    icon: mdi:lightbulb
  bathroom_light_override:
    name: Bathroom Light Override
    icon: mdi:lightbulb
    initial: false
  enable_bathroom_motion_trigger:
    name: Enable motion trigger for bathroom
    icon: mdi:motion-sensor
sensor:
  # Aggregated sensors
  - platform: min_max
    name: Bathroom Area Light Level
    entity_ids:
      - sensor.bathroom_motion_light_level
      - sensor.bathroom_motion_2_light_level
    type: mean
  - platform: min_max
    name: Bathroom Area Temperature
    entity_ids:
      - sensor.bathroom_motion_temperature
      - sensor.bathroom_motion_2_temperature
    type: mean
