# Created by Danny Tsang <danny@tsang.uk>
automation:
  # region Blinds
  - id: "1605925028960"
    alias: "Ashlee's Bedroom: Timed Close Blinds"
    description: ""
    triggers:
      - trigger: time
        at: input_datetime.childrens_bed_time
      - trigger: time
        at: "22:00:00"
        id: no_children
    conditions:
      - condition: numeric_state
        entity_id: cover.ashlees_bedroom_blinds
        attribute: current_position
        above: input_number.blind_closed_position_threshold
      - condition: state
        entity_id: input_boolean.enable_ashlees_blind_automations
        state: "on"
    actions:
      - choose:
          - alias: Window is still open
            conditions:
              - condition: state
                entity_id: binary_sensor.ashlees_bedroom_window_contact
                state: "on"
            sequence:
              - action: script.send_to_home_log
                data:
                  message:
                    "⚠️ :clock{{ now().strftime('%I') | int }}{% if now().minute | int
                    > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: 🪟 Ashlee's window is still open. Waiting until
                    it's closed before closing blinds. ⚠️"
                  title: "Ashlee's 🛏️ bedroom"
                  log_level: "Debug"
          - alias: No children mode
            conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: "No Children"
              - condition: trigger
                id: no_children
              - condition: state
                entity_id: binary_sensor.ashlees_bedroom_window_contact
                state: "off"
            sequence:
              - action: script.send_to_home_log
                data:
                  message: "🌇 🪟 It's getting dark, closing Ashlee's blinds."
                  title: "Ashlee's 🛏️ bedroom"
                  log_level: "Debug"
              - action: cover.close_cover
                target:
                  entity_id: cover.ashlees_bedroom_blinds
          - alias: Bed sensor enabled
            conditions:
              - condition: state
                entity_id: input_boolean.enable_ashlees_bed_sensor
                state: "on"
              - condition: state
                entity_id: binary_sensor.ashlees_bedroom_window_contact
                state: "off"
              - condition: trigger
                id: sunset
            sequence:
              - action: script.send_to_home_log
                data:
                  message:
                    ":clock{{ now().strftime('%I') | int }}{% if now().minute | int
                    > 25 and now().minute | int < 35 %}30{% else %}{% endif %}:
                    🌇 🪟 It's getting dark and no one is in Ashlee's 🛏️ bed,
                    closing Ashlee's blinds."
                  title: "Ashlee's 🛏️ bedroom"
                  log_level: "Debug"
              - action: cover.close_cover
                target:
                  entity_id: cover.ashlees_bedroom_blinds
          - alias: Bed sensor is off
            conditions:
              - condition: state
                entity_id: binary_sensor.ashlees_bedroom_window_contact
                state: "off"
              - condition: state
                entity_id: input_boolean.enable_ashlees_bed_sensor
                state: "off"
            sequence:
              - action: script.send_to_home_log
                data:
                  message:
                    ":clock{{ now().strftime('%I') | int }}{% if now().minute | int
                    > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: 🌇 🪟 It's getting dark, closing Ashlee's blinds."
                  title: "Ashlee's 🛏️ bedroom"
                  log_level: "Debug"
              - action: cover.close_cover
                target:
                  entity_id: cover.ashlees_bedroom_blinds
        default: []
    mode: single
  - id: "1622891806607"
    alias: "Ashlee's Bedroom: Window Closed After Dark"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.ashlees_bedroom_window_contact
        from: "on"
        to: "off"
        for:
          hours: 0
          minutes: 1
          seconds: 0
    conditions:
      - condition: numeric_state
        entity_id: cover.ashlees_bedroom_blinds
        attribute: current_position
        above: input_number.bedroom_blind_closed_threshold
      - condition: state
        entity_id: input_boolean.enable_ashlees_blind_automations
        state: "on"
      - condition: time
        after: input_datetime.childrens_bed_time
    actions:
      - action: script.send_to_home_log
        data:
          message: "🪟 Window closed and it's dark. Closing blinds."
          title: "Ashlee's 🛏️ bedroom"
          log_level: "Debug"
      - action: cover.close_cover
        target:
          entity_id: cover.ashlees_bedroom_blinds
        data: {}
    mode: single
  - id: "1599994669457"
    alias: "Ashlee's Bedroom: Open Blinds In The Morning"
    description: ""
    triggers:
      - trigger: time
        at: "08:00:00"
        id: early
      - trigger: time
        at: "09:00:00"
        id: late
    conditions:
      - condition: numeric_state
        entity_id: cover.ashlees_bedroom_blinds
        attribute: current_position
        below: input_number.blind_closed_position_threshold
      - condition: state
        entity_id: input_boolean.enable_ashlees_blind_automations
        state: "on"
      - not:
          - condition: state
            entity_id: input_select.home_mode
            state: "Guest"
          - condition: state
            entity_id: input_select.home_mode
            state: "No Children"
    actions:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.workday_sensor
                state: "off"
              - condition: trigger
                id: late
            sequence:
              - parallel:
                  - action: script.send_to_home_log
                    data:
                      message:
                        ":clock{{ now().strftime('%I') | int }}{% if now().minute | int
                        > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: 🌅 🪟 School day. Opening Ashlee's blinds"
                      title: "Ashlee's 🛏️ bedroom"
                      log_level: "Debug"

                  - action: cover.open_cover
                    target:
                      entity_id: cover.ashlees_bedroom_blinds
          - conditions:
              - condition: state
                entity_id: binary_sensor.workday_sensor
                state: "on"
              - condition: trigger
                id: early
            sequence:
              - parallel:
                  - action: script.send_to_home_log
                    data:
                      message:
                        ":clock{{ now().strftime('%I') | int }}{% if now().minute | int
                        > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: 🌅 🪟 Non school day. Opening Ashlee's blinds"
                      title: "Ashlee's 🛏️ bedroom"
                      log_level: "Debug"
                  - action: cover.open_cover
                    target:
                      entity_id: cover.ashlees_bedroom_blinds
        default: []
    mode: single
  - id: "1599994669458"
    alias: "Ashlee's Bedroom: Open Blinds In The Morning No Children Mode"
    description: ""
    triggers:
      - trigger: time
        at: "08:00:00"
        id: workday
      - trigger: time
        at: "09:00:00"
        id: non_workday
    conditions:
      - condition: state
        entity_id: input_select.home_mode
        state: "No Children"
    actions:
      - choose:
          - conditions:
              - condition: state
                state: "off"
                entity_id: binary_sensor.workday_sensor
              - condition: trigger
                id: workday
            sequence:
              - action: script.send_to_home_log
                data:
                  message:
                    ":clock{{ now().strftime('%I') | int }}{% if now().minute | int
                    > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: 🪟 Opening blinds
                    with {{ states('input_select.home_mode') }} on a non working day."
                  title: "Ashlee's 🛏️ bedroom"
                  log_level: "Debug"
              - action: cover.open_cover
                target:
                  entity_id: cover.ashlees_bedroom_blinds
          - conditions:
              - condition: state
                state: "on"
                entity_id: binary_sensor.workday_sensor
              - condition: trigger
                id: non_workday
            sequence:
              - action: script.send_to_home_log
                data:
                  message:
                    ":clock{{ now().strftime('%I') | int }}{% if now().minute | int
                    > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: 🪟 Opening blinds
                    with {{ states('input_select.home_mode') }} on a working day."
                  title: "Ashlee's 🛏️ bedroom"
                  log_level: "Debug"
              - action: cover.open_cover
                target:
                  entity_id: cover.ashlees_bedroom_blinds
        default: []
    mode: single
  - id: "1655237597647"
    alias: "Ashlee's Bedroom: Someone Is In Bed"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.ashlees_bed_occupied
        from: "off"
        to: "on"
        for:
          hours: 0
          minutes: 0
          seconds: 30
    conditions: []
    actions:
      - parallel:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: input_boolean.enable_ashlees_bed_sensor
                    state: "on"
                  - condition: state
                    entity_id: input_boolean.enable_ashlees_blind_automations
                    state: "on"
                  - condition: numeric_state
                    entity_id: cover.ashlees_bedroom_blinds
                    attribute: current_position
                    below: input_number.blind_closed_position_threshold
                  - or:
                      - condition: time
                        after: input_datetime.childrens_bed_time
                      - condition: time
                        before: 05:00:00
                  - condition: state
                    entity_id: binary_sensor.ashlees_bedroom_window_contact
                    state: "off"
                sequence:
                  - action: script.send_to_home_log
                    data:
                      message: "Someone is in Ashlee's 🛏️ bed after 🕢. Closing
                        blinds."
                      title: "Ashlee's 🛏️ bedroom"
                      log_level: "Debug"
                  - action: cover.close_cover
                    data: {}
                    target:
                      entity_id: cover.ashlees_bedroom_blinds
            default: []
    mode: single
  # region Switches
  - id: "1655235874989"
    alias: "Ashlee's Bedroom: Turn Off Fan After 1 Hour"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - switch.ashlees_bedroom_fan
        to: "on"
        for:
          hours: 1
          minutes: 0
          seconds: 0
    conditions: []
    actions:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: "🪭 Fan has been on for an hour. Turning fan off."
              title: "🛏️ Ashlee's bedroom"
              log_level: "Debug"
          - action: switch.turn_off
            data: {}
            target:
              entity_id: switch.ashlees_bedroom_fan
    mode: single
  # region Hue Remote
  - id: "1656355431188"
    alias: "Ashlee's Bedroom: Hue Remote On Button"
    description: ""
    triggers:
      - trigger: device
        domain: mqtt
        device_id: 43598aa0e01c65b2bfc26491940f3353
        type: action
        subtype: on_press_release
    conditions: []
    actions:
      - action: script.send_to_home_log
        data:
          message: "Power button pressed. 💡 Toggling light."
          title: "🛏️ Ashlee's Bedroom"
          log_level: "Debug"
      - action: light.toggle
        data: {}
        target:
          entity_id: light.ashlees_bedroom_main_light
    mode: queued
    max: 10
  - id: "1656355431189"
    alias: "Ashlee's Bedroom: Hue Remote Up Button"
    description: ""
    triggers:
      - trigger: device
        domain: mqtt
        device_id: 43598aa0e01c65b2bfc26491940f3353
        type: action
        subtype: up_press_release
    conditions: []
    actions:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: "Bright button on remote pressed. Opening 🪟 Ashlee's blinds."
              title: "🛏️ Ashlee's Bedroom"
              log_level: "Debug"
          - action: cover.open_cover
            data: {}
            target:
              entity_id: cover.ashlees_bedroom_blinds
    mode: queued
    max: 10
  - id: "1656355431190"
    alias: "Ashlee's Bedroom: Hue Remote Down Button"
    description: ""
    triggers:
      - trigger: device
        domain: mqtt
        device_id: 43598aa0e01c65b2bfc26491940f3353
        type: action
        subtype: down_press_release
    conditions: []
    actions:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: "Dim button on remote pressed. Closing 🪟 Ashlee's blinds."
              title: "🛏️ Ashlee's Bedroom"
              log_level: "Debug"
          - action: cover.close_cover
            data: {}
            target:
              entity_id: cover.ashlees_bedroom_blinds
    mode: queued
    max: 10
  - id: "1656355431191"
    alias: "Ashlee's Bedroom: Hue Remote Off Button"
    description: ""
    triggers:
      - trigger: device
        domain: mqtt
        device_id: 43598aa0e01c65b2bfc26491940f3353
        type: action
        subtype: off_press_release
    conditions: []
    actions:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: "Hue button on remote pressed. Toggle Ashlee's main 💡 light."
              title: "🛏️ Ashlee's Bedroom"
              log_level: "Debug"
          - action: light.toggle
            data: {}
            target:
              entity_id: light.ashlees_bedroom_main_light
    mode: queued
    max: 10

script:
  ashlees_bedroom_close_blinds_by_weather:
    alias: Ashlee's Bedroom Close Blinds Based Weather
    description: "Close Leo's bedroom blinds depending on the weather."
    fields:
      temperature:
        description: Temperature in celsius.
        required: true
        selector:
          number:
            min: -20
            max: 50
            step: 0.1
            unit_of_measurement: "°c"
            mode: "box"
      weather_condition:
        description: Text weather condition e.g. lightning-rainy
        required: true
        selector:
          text:
    sequence:
      # Only run the weather check if it's during the day otherwise it might be closed for evening.
      - if:
          - condition: sun
            before: sunset
          - condition: state
            entity_id: input_boolean.enable_ashlees_blind_automations
            state: "on"
          - condition: numeric_state
            entity_id: cover.ashlees_bedroom_blinds
            attribute: current_position
            above: input_number.blind_open_position_threshold
        then:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ weather_condition in ['sunny','partlycloudy'] }}"
                sequence:
                  - choose:
                      - alias: Check if window is open.
                        conditions:
                          - condition: state
                            entity_id: binary_sensor.leos_bedroom_window_contact
                            state: "on"
                        sequence:
                          # TODO: replace with actionable notification
                          - action: script.send_to_home_log
                            data:
                              message:
                                "It's going to be hot ({{ temperature }} {{ weather_condition }}) and
                                the 🪟 window is open preventing the blinds from closing."
                              title: "Ashlee's 🛏️ bedroom"
                              log_level: "Debug"
                    default:
                      - action: script.send_to_home_log
                        data:
                          message: "It's going to be hot ({{ temperature }} {{ weather_condition }}). Closing blinds."
                          title: "Ashlee's 🛏️ bedroom"
                          log_level: "Debug"
                      - action: cover.close_cover
                        target:
                          entity_id: cover.ashlees_bedroom_blinds
            default: []
    mode: single
    icon: mdi:roller-shade-closed

sensor:
  - platform: mold_indicator
    name: Ashlee's Bedroom Mould Indicator
    indoor_temp_sensor: sensor.ashlees_bedroom_door_temperature
    indoor_humidity_sensor: sensor.ashlees_bed_humidity
    outdoor_temp_sensor: sensor.gw2000a_outdoor_temperature
    calibration_factor: 1.55

template:
  - binary_sensor:
      - name: Ashlees Bed Occupied
        unique_id: f884af3a-2eb7-42ee-9d23-4e3dc41e575d
        icon: >-
          mdi:bed-single{{ '-outline' if (states('sensor.ashlees_bed_top') | float(0) >= 0.1) or
          (states('sensor.ashlees_bed_middle_top') | float(0)) >= 0.1 or
          (states('sensor.ashlees_bed_middle_bottom') | float(0)) >= 0.1 or
          (states('sensor.ashlees_bed_bottom') | float(0)) >= 0.1 else '' }}
        device_class: occupancy
        state: >-
          {% if (states('sensor.ashlees_bed_top') | float(0)) >= 0.1 or
              (states('sensor.ashlees_bed_middle_top') | float(0)) >= 0.1 or
              (states('sensor.ashlees_bed_middle_bottom') | float(0)) >= 0.1 or
              (states('sensor.ashlees_bed_bottom') | float(0)) >= 0.1 %}
            on
          {% else %}
            off
          {% endif %}
        attributes:
          top: "{{ states('sensor.ashlees_bed_top') }}"
          top_middle: "{{ states('sensor.ashlees_bed_middle_top') }}"
          bottom_middle: "{{ states('sensor.ashlees_bed_middle_bottom') }}"
          bottom: "{{ states('sensor.ashlees_bed_bottom') }}"
