# Created by Danny Tsang <danny@tsang.uk>
automation:
  # Blinds
  - id: "1605925028960"
    alias: "^Ashlee's Room: Timed Close Blinds"
    description: ""
    trigger:
      - platform: time
        at: "19:30:00"
      - platform: sun
        event: sunset
        id: sunset
    condition:
      - not:
          - condition: state
            entity_id: cover.ashlees_blinds
            state: closed
      - condition: state
        entity_id: input_boolean.enable_ashlees_blind_automations
        state: "on"
    action:
      - choose:
          # Window is still open
          - conditions:
              - condition: state
                entity_id: binary_sensor.ashlees_window
                state: "on"
            sequence:
              - service: script.send_to_home_log
                data:
                  message:
                    ":warning: :clock{{ now().strftime('%I') | int }}{% if now().minute | int
                    > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :window: Ashlee's window is still open. Waiting until
                    it's closed before closing blinds. :warning:"
                  title: "Ashlee's :bed: bedroom"
          # No children mode
          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: No Children
              - condition: trigger
                id: sunset
              - condition: state
                entity_id: binary_sensor.ashlees_window
                state: "off"
            sequence:
              - service: script.send_to_home_log
                data:
                  message: ":city_sunset: :window: It's getting dark, closing Ashlee's blinds."
                  title: "Ashlee's :bed: bedroom"
              - service: cover.close_cover
                target:
                  entity_id: cover.ashlees_blinds
          # Bed sensor enabled
          - conditions:
              - condition: state
                entity_id: input_boolean.enable_ashlees_bed_sensor
                state: "on"
              - condition: trigger
                id: sunset
            sequence:
              - service: script.send_to_home_log
                data:
                  message:
                    ":clock{{ now().strftime('%I') | int }}{% if now().minute | int
                    > 25 and now().minute | int < 35 %}30{% else %}{% endif %}:
                    :city_sunset: :window: It's getting dark and no one is in Ashlee's :bed: bed,
                    closing Ashlee's blinds."
                  title: "Ashlee's :bed: bedroom"
              - service: cover.close_cover
                target:
                  entity_id: cover.ashlees_blinds
          # Window closed
          - conditions:
              - condition: state
                entity_id: binary_sensor.ashlees_window
                state: "off"
            sequence:
              - service: script.send_to_home_log
                data:
                  message:
                    ":clock{{ now().strftime('%I') | int }}{% if now().minute | int
                    > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :city_sunset: :window: It's getting dark, closing Ashlee's blinds."
                  title: "Ashlee's :bed: bedroom"
              - service: cover.close_cover
                target:
                  entity_id: cover.ashlees_blinds
        default: []
    mode: single
  - id: "1622891806607"
    alias: "^Ashlee's Room: Window Closed After Dark"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.ashlees_window
        from: "on"
        to: "off"
        for:
          hours: 0
          minutes: 1
          seconds: 0
    condition:
      - condition: state
        entity_id: cover.ashlees_blinds
        state: open
      - condition: state
        entity_id: input_boolean.enable_ashlees_blind_automations
        state: "on"
      - condition: time
        after: "19:30:00"
    action:
      - service: script.send_to_home_log
        data:
          message: ":window: Window closed and it's dark. Closing blinds."
          title: "Ashlee's :bed: bedroom"
      - service: cover.close_cover
        target:
          entity_id: cover.ashlees_blinds
        data: {}
    mode: single
  - id: "1605775729191"
    alias: "^Ashlee's Room: Turn Off Lamp After An Hour"
    description: ""
    trigger:
      - platform: state
        entity_id: switch.ashlees_lamp
        to: "on"
        for: 01:00:00
    condition: []
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.ashlees_lamp
      - service: script.send_to_home_log
        data:
          message: "Lamp has been on for 1 hour. Turning lamp off."
          title: "Ashlee's :bed: bedroom"
    mode: single
  - id: "1599994669457"
    alias: "^Ashlee's Room: Open Blinds In The Morning"
    description: ""
    trigger:
      - at: 08:00:00
        platform: time
    condition:
      - condition: state
        entity_id: cover.ashlees_blinds
        state: closed
      - condition: state
        entity_id: input_boolean.enable_ashlees_blind_automations
        state: "on"
    action:
      - choose:
          - conditions:
              - not:
                  - condition: state
                    entity_id: input_select.home_mode
                    state: Guest
            sequence:
              - data:
                  message:
                    ":clock{{ now().strftime('%I') | int }}{% if now().minute | int
                    > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :sunrise: :window: Opening Ashlee's blinds"
                  title: "Ashlee's :bed: bedroom"
                service: script.send_to_home_log
              - service: cover.open_cover
                target:
                  entity_id: cover.ashlees_blinds
          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: Guest
            sequence:
              - service: script.send_to_home_log
                data:
                  message:
                    ":stop_sign: :sunrise: :window: Guest mode is enabled. Skipping
                    opening Ashlee's bedroom blinds."
                  title: "Ashlee's :bed: bedroom"
        default: []
    mode: single

template:
  - binary_sensor:
      - name: Ashlees Bed Occupied
        icon: >-
          mdi:bed-single{{ '-outline' if states('sensor.ashlees_bed_top') | float >= 0.1 or
          states('sensor.ashlees_bed_middle_top') | float >= 0.1 or
          states('sensor.ashlees_bed_middle_bottom') | float >= 0.1 or
          states('sensor.ashlees_bed_bottom') | float >= 0.1 else '' }}
        device_class: occupancy
        state: >-
          {% if states('sensor.ashlees_bed_top') | float >= 0.1 or 
              states('sensor.ashlees_bed_middle_top') | float >= 0.1 or 
              states('sensor.ashlees_bed_middle_bottom') | float >= 0.1 or
              states('sensor.ashlees_bed_bottom') | float >= 0.1 %}
            on
          {% else %}
            off
          {% endif %}
        attributes:
          top: "{{ states('sensor.ashlees_bed_top') }}"
          top_middle: "{{ states('sensor.ashlees_bed_middle_top') }}"
          bottom_middle: "{{ states('sensor.ashlees_bed_middle_bottom') }}"
          bottom: "{{ states('sensor.ashlees_bed_bottom') }}"
