# Created by Danny Tsang <danny@tsang.uk>
automation:
  # Blinds
  - id: "1627285063813"
    alias: "^Leo's Bedroom: Timed Open Blinds"
    description: ""
    trigger:
      - platform: time
        at: 08:00:00
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: cover.leos_blinds
            state: closed
          - condition: state
            entity_id: cover.leos_blinds
            state: closing
      - condition: not
        conditions:
          - condition: state
            state: Guest
            entity_id: input_select.home_mode
    action:
      - service: script.post_to_home_log
        data:
          message: Opening Leo's bedroom blinds
      - service: cover.open_cover
        target:
          entity_id: cover.leos_blinds
    mode: single
  - id: "1629844319596"
    alias: "^Leo's Bedroom: Timed Close Blinds"
    description: ""
    trigger:
      - platform: time
        at: "19:30:00"
      - platform: sun
        event: sunset
        id: sunset
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: cover.leos_blinds
            state: closed
      - condition: state
        entity_id: input_boolean.enable_leos_blind_automations
        state: "on"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.leos_window
                state: "on"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":warning: :clock{{ now().strftime('%I') | int }}{% if now().minute | int
                    > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :city_sunset: :window: Leo's
                    window is open. Skipping closing blinds. :warning:"
          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: No Children
              - condition: trigger
                id: sunset
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":clock{{ now().strftime('%I') | int }}{% if now().minute | int
                    > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :window: Closing
                    Leo's blinds"
              - service: cover.close_cover
                target:
                  entity_id: cover.leos_blinds
          - conditions:
              - condition: state
                entity_id: binary_sensor.leos_window
                state: "off"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":clock{{ now().strftime('%I') | int }}{% if now().minute | int
                    > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :window: Closing
                    Leo's blinds"
              - service: cover.close_cover
                target:
                  entity_id: cover.leos_blinds
        default: []
    mode: single
  - id: "1617376203344"
    alias: "^Leo's Room: Close Blinds Before Sun Rise"
    description: ""
    trigger:
      - platform: sun
        event: sunrise
        offset: -02:00:00
    condition:
      - condition: state
        entity_id: cover.leos_blinds
        state: open
      - condition: state
        entity_id: binary_sensor.leos_window
        state: "off"
    action:
      - service: cover.close_cover
        target:
          entity_id: cover.leos_blinds
      - service: script.post_to_home_log
        data:
          message: ":city_sunset: :window: closing Leo's blinds."
    mode: single
  - id: "1617376413056"
    alias: "^Leo's Room: Open Blinds In The Morning"
    description: ""
    trigger:
      - at: 09:30:00
        platform: time
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: cover.leos_blinds
            state: closed
          - condition: state
            entity_id: cover.leos_blinds
            state: closing
      - condition: state
        entity_id: input_boolean.enable_leos_blind_automations
        state: "on"
    action:
      - data:
          message: ":sunrise: :window: Opening Leo's blinds"
        service: script.post_to_home_log
      - service: cover.open_cover
        target:
          entity_id: cover.leos_blinds
    mode: single
  - id: "1617458869658"
    alias: "^Leo's Room: Open Blinds In The Morning When No One Is In Bed"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.leos_bed_occupied
        from: "on"
        to: "off"
    condition:
      - condition: time
        after: 07:00:00
        before: "12:00:00"
      - condition: or
        conditions:
          - condition: state
            entity_id: cover.leos_blinds
            state: closed
          - condition: state
            entity_id: cover.leos_blinds
            state: closing
      - condition: state
        entity_id: input_boolean.enable_leos_blind_automations
        state: "on"
      - condition: state
        entity_id: input_boolean.enable_leos_bed_presence
        state: "on"
      - condition: not
        conditions:
          - condition: state
            entity_id: input_select.home_mode
            state: Guest
    action:
      - service: script.post_to_home_log
        data:
          message: ":window: :bed: Someone is in Leo's bed. Closing blinds."
      - service: cover.open_cover
        target:
          entity_id: cover.leos_blinds
    mode: single
input_boolean:
  enable_leos_bed_presence:
    name: Enable Leo's Bed Sensor
    icon: mdi:bed-single
  enable_leos_blind_automations:
    name: Enable Leos Blind Automation
    icon: mdi:window-open
  enable_leos_door_automations:
    name: Enable Leo's Door Automation
    icon: mdi:door
sensor:
  # Aggregated sensors
  - platform: min_max
    name: Leo's Bedroom Area Temperature
    entity_ids:
      - sensor.leos_bed_temperature
      - sensor.leos_door_temperature
      - sensor.leos_window_temperature
template:
  - binary_sensor:
      - name: Leos Bed Occupied
        icon: >-
          mdi:bed-double{{ '-outline' if states('sensor.leos_bed_top_left') | float >= 0.06 or
          states('sensor.leos_bed_top_right') | float >= 0.06 or
          states('sensor.leos_bed_bottom_left') | float >= 0.07 or
          states('sensor.leos_bed_bottom_right') | float >= 0.06
          else '' }}
        device_class: occupancy
        state: >-
          {% if states('sensor.leos_bed_top_left') | float >= 0.06 
            or states('sensor.leos_bed_top_right') | float >= 0.06 
            or states('sensor.leos_bed_bottom_left') | float >= 0.07 
            or states('sensor.leos_bed_bottom_right') | float >= 0.06 %}
            on
          {% else %}
            off
          {% endif %}
        attributes:
          top_left: "{{ states('sensor.leos_bed_top_left') }}"
          top_right: "{{ states('sensor.leos_bed_top_right') }}"
          bottom_left: "{{ states('sensor.leos_bed_bottom_left') }}"
          bottom_right: "{{ states('sensor.leos_bed_bottom_right') }}"
