# Created by Danny Tsang <danny@tsang.uk>
automation:
  # Motion triggers
  - id: "1621713217274"
    alias: "^Bedroom: Motion Detected (Day)"
    description: ""
    trigger:
      - platform: state
        entity_id: group.bedroom_motion
        from: "off"
        to: "on"
      - platform: state
        entity_id: input_boolean.enable_bedroom_motion_trigger
        to: "on"
    condition:
      - condition: sun
        before: sunset
        after: sunrise
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ state_attr('light.under_bed_light_left','brightness') == none }}"
          - condition: template
            value_template: "{{ state_attr('light.under_bed_light_right','brightness') == none }}"
          - condition: numeric_state
            entity_id: light.under_bed_light_left
            below: "100"
            attribute: brightness
          - condition: numeric_state
            entity_id: light.under_bed_light_right
            below: "100"
            attribute: brightness
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":bed: :paw_prints: :high_brightness: Motioned detected in the bedroom
            before sunset. Turning lights on full brightness."
      - scene: scene.bedroom_turn_on_light
    mode: single
  - id: "1621713735692"
    alias: "^Bedroom: Motion Detected (Night)"
    description: ""
    trigger:
      - platform: state
        entity_id: group.bedroom_motion
        from: "off"
        to: "on"
    condition:
      - condition: sun
        after: sunset
      - condition: state
        entity_id: input_boolean.enable_bedroom_motion_trigger
        state: "on"
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ state_attr('light.under_bed_light_left','brightness') == none }}"
          - condition: template
            value_template: "{{ state_attr('light.under_bed_light_right','brightness') == none }}"
          - condition: numeric_state
            entity_id: light.under_bed_light_left
            below: "9"
            attribute: brightness
          - condition: numeric_state
            entity_id: light.under_bed_light_right
            below: "9"
            attribute: brightness
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":bed: :paw_prints: :low_brightness: Motioned detected in the bedroom
            before sunset. Turning lights on low brightness."
      - scene: scene.bedroom_dim_light
    mode: single
  - id: "1621713867762"
    alias: "^Bedroom: No Motion"
    description: ""
    trigger:
      - platform: state
        entity_id: group.bedroom_motion
        from: "on"
        to: "off"
        for: 00:02:00
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: light.under_bed_light_left
            state: "on"
          - condition: state
            entity_id: light.under_bed_light_right
            state: "on"
    action:
      - service: script.post_to_home_log
        data:
          message: ":bed: No motion detected for 1 minute. Turning lights off."
      - scene: scene.bedroom_turn_off_light
    mode: single
  # Bed
  - id: "1601641236163"
    alias: "^Bedroom: Close Blinds When Someone Is In Bed After Sunset"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.bed_occupied
        from: "off"
        to: "on"
        for: 00:00:30
    condition:
      - condition: state
        entity_id: cover.bedroom_blind
        state: open
      - condition: state
        entity_id: input_boolean.enable_bedroom_blind_automations
        state: "on"
      - condition: sun
        after: sunset
      - condition: state
        entity_id: binary_sensor.bedroom_window
        state: "off"
      - condition: state
        entity_id: input_boolean.enable_bed_presence
        state: "on"
    action:
      - data:
          title: Close bedroom blinds
          message:
            ":sleeping_accommodation: :window: Someone is in bed ({{states('sensor.bed_sensor')}}),
            bedroom window is closed and it's getting late. Closing blinds."
        service: script.post_to_home_log
      - service: cover.close_cover
        target:
          entity_id: cover.bedroom_blind
    mode: single
  - id: "1600127180656"
    alias: "^Bedroom: Close Blinds Before Sunrise"
    description: ""
    trigger:
      - event: sunrise
        offset: -02:00:00
        platform: sun
    condition:
      - condition: state
        entity_id: cover.bedroom_blind
        state: open
      - condition: state
        entity_id: input_boolean.enable_bedroom_blind_automations
        state: "on"
      - condition: state
        entity_id: binary_sensor.bedroom_window
        state: "off"
    action:
      - data:
          message:
            ":sunrise: Bedroom blind is open and it's nearly sunrise. Closing
            blinds"
        service: script.post_to_home_log
      - service: cover.close_cover
        target:
          entity_id: cover.bedroom_blind
    mode: single
  - id: "1615689096351"
    alias: "^Bedroom: Window Closed And Someone Is In Bed At Night"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.bedroom_window
        from: "on"
        to: "off"
        for: 00:00:30
    condition:
      - condition: state
        entity_id: cover.bedroom_blind
        state: open
      - condition: state
        entity_id: input_boolean.enable_bedroom_blind_automations
        state: "on"
      - condition: sun
        after: sunset
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.enable_bed_presence
                state: "on"
              - condition: state
                entity_id: binary_sensor.bed_occupied
                state: "on"
            sequence:
              - service: script.post_to_home_log
                data:
                  title: Close bedroom blinds
                  message:
                    ":sleeping_accommodation: :window: Bedroom window shut, someone is
                    in bed ({{states('sensor.bed_sensor')}}) and it's getting late. Closing
                    blinds."
              - service: cover.close_cover
                target:
                  entity_id: cover.bedroom_blind
          - conditions:
              - condition: state
                entity_id: input_boolean.enable_bed_presence
                state: "off"
            sequence:
              - service: script.post_to_home_log
                data:
                  title: Close bedroom blinds
                  message:
                    ":sleeping_accommodation: :window: Bedroom window shut, someone is
                    in bed ({{states('sensor.bed_sensor')}}) and it's getting late. Closing
                    blinds."
              - service: cover.close_cover
                target:
                  entity_id: cover.bedroom_blind
        default: []
    mode: single
  - id: "1601641292576"
    alias: "^Bedroom: Open Blind When No One Is In Bed"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.bed_occupied
        from: "on"
        to: "off"
        for: 00:00:30
    condition:
      - condition: state
        entity_id: cover.bedroom_blind
        state: closed
      - condition: sun
        after: sunrise
        after_offset: -01:00:00
        before: sunset
      - condition: state
        entity_id: input_boolean.enable_bedroom_blind_automations
        state: "on"
      - condition: state
        entity_id: input_boolean.enable_bed_presence
        state: "on"
    action:
      - delay: 00:01:00
      - data:
          title: Open Blinds
          message:
            ":bed: :window: No one is in bed ({{states('sensor.bed_sensor')}}).
            Opening the blinds."
        service: script.post_to_home_log
      - service: cover.open_cover
        target:
          entity_id: cover.bedroom_blind
    mode: single
  # Time
  - id: "1621875409014"
    alias: "^Bedroom: Morning Timed Open Blinds"
    description: ""
    trigger:
      - platform: time
        at: "09:30:00"
        id: "093000"
      - platform: time
        at: "10:30:00"
        id: "103000"
    condition:
      - condition: state
        entity_id: cover.bedroom_blind
        state: closed
      - condition: state
        entity_id: input_boolean.enable_bedroom_blind_automations
        state: "on"
      - condition: state
        entity_id: binary_sensor.bedroom_tv_powered_on
        state: "off"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.workday_sensor
                state: "on"
            sequence:
              - service: cover.open_cover
                target:
                  entity_id: cover.bedroom_blind
              - condition: trigger
                id: "093000"
              - service: script.post_to_home_log
                data:
                  message: ":clock{{ now().strftime('%I') | int }}{% if now().minute | int > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :window: Opening blinds because it's closed and its 09:30 on a weekday!"
          - conditions:
              - condition: state
                entity_id: binary_sensor.workday_sensor
                state: "off"
              - condition: not
                conditions:
                  - condition: state
                    entity_id: input_select.home_mode
                    state: No Children
              - condition: trigger
                id: "093000"
            sequence:
              - service: cover.open_cover
                target:
                  entity_id: cover.bedroom_blind
              - service: script.post_to_home_log
                data:
                  message: ":clock{{ now().strftime('%I') | int }}{% if now().minute | int > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :window: Opening blinds because it's closed and its 09:30 on a weekend!"
          - conditions:
              - condition: trigger
                id: "103000"
            sequence:
              - service: cover.open_cover
                target:
                  entity_id: cover.bedroom_blind
              - service: script.post_to_home_log
                data:
                  message: ":clock{{ now().strftime('%I') | int }}{% if now().minute | int > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :window: Opening blinds because it's closed and its 10:30!"
        default: []
    mode: single
  - id: "1621875567853"
    alias: "^Bedroom: Evening Timed Blinds"
    description: ""
    trigger:
      - platform: time
        at: "22:30:00"
    condition:
      - condition: state
        entity_id: input_boolean.enable_bedroom_blind_automations
        state: "on"
      - condition: state
        entity_id: cover.bedroom_blind
        state: open
    action:
      - service: script.post_to_home_log
        data:
          message: ":city_sunset: :window: It's getting dark, closing bedroom's blinds."
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.bedroom_window
                state: "on"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":warning: :window: Bedroom window is still open. Waiting until
                    it's closed before closing blinds. :warning:"
        default:
          - service: cover.close_cover
            target:
              entity_id: cover.bedroom_blind
    mode: single
  # Plugs / switches
  - id: "1581800266867"
    alias: "^Turn off Electric Blanket After 1 hour"
    description: ""
    trigger:
      - entity_id: switch.blanket
        for: 01:00:00
        platform: state
        to: "'on'"
    condition: []
    action:
      - data: {}
        entity_id: switch.blanket
        service: switch.turn_off
      - data:
          message: Electric blanket has been on for 1 hour. Turning electric blanket off.
        service: script.post_to_home_log
  - id: "1624194131454"
    alias: "^Bedroom: TV Turned On During Bright Day"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.bedroom_tv_powered_on
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.enable_bedroom_blind_automations
        state: "on"
      - condition: sun
        before: sunset
        after: sunrise
      - condition: not
        conditions:
          - condition: state
            entity_id: cover.bedroom_blind
            state: closed
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.enable_mobile_direct_notifications
                state: "on"
              - condition: state
                entity_id: binary_sensor.bedroom_window
                state: "on"
              - condition: numeric_state
                entity_id: weather.home
                attribute: wind_speed
                above: "10"
            sequence:
              - service: notify.mobile_app_dannys_phone
                data:
                  message: Do you want to close the blinds?
                  data:
                    actions:
                      - title: "Yes"
                        action: set_bedroom_blinds_20
                      - title: "No"
                        action: ignore
                  title: 📺🛌TV On & Window Is Open
          - conditions:
              - condition: state
                entity_id: input_boolean.enable_mobile_direct_notifications
                state: "on"
              - condition: state
                entity_id: binary_sensor.bedroom_window
                state: "on"
              - condition: numeric_state
                entity_id: weather.home
                attribute: wind_speed
                below: "10"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":tv: :bed: Bedroom TV turned on and it's bright. The window is open however it is below 10km/h. Lowering bedroom
                    blinds."
              - service: cover.set_cover_position
                target:
                  entity_id: cover.bedroom_blind
                data:
                  position: 20
          - conditions:
              - condition: state
                entity_id: binary_sensor.bedroom_window
                state: "off"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":tv: :bed: Bedroom TV turned on and it's bright. Lowering bedroom
                    blinds."
              - service: cover.set_cover_position
                target:
                  entity_id: cover.bedroom_blind
                data:
                  position: 20
        default: []
    mode: single
  - id: "1624194439043"
    alias: "^Bedroom: TV Turned Off"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.bedroom_tv_powered_on
        from: "on"
        to: "off"
        for: 00:01:00
    condition:
      - condition: numeric_state
        entity_id: cover.bedroom_blind
        attribute: current_position
        below: "100"
      - condition: state
        entity_id: input_boolean.enable_bedroom_blind_automations
        state: "on"
      - condition: sun
        before: sunset
      - condition: sun
        after: sunrise
    action:
      - service: script.post_to_home_log
        data:
          message: ":tv: :bed: Bedroom TV turned off. Opening Blinds."
      - service: cover.open_cover
        target:
          entity_id: cover.bedroom_blind
    mode: single
binary_sensor:
  - platform: template
    sensors:
      bedroom_tv_powered_on:
        value_template: "{{ states('sensor.bedroom_tv_power_meter') | float > 40 }}"
        friendly_name: "Bedroom TV Powered On"
        device_class: "power"
        icon_template: "mdi:television-classic{{ '' if states('sensor.bedroom_tv_power_meter') | float > 40 else '-off' }}"
      bed_occupied:
        icon_template: "mdi:bed-double{{ '-outline' if states('sensor.bed_top_left') | int >= 4000 or states('sensor.bed_bottom_left') | int >= 1000 or states('sensor.bed_bottom_right') | int >= 8000 else '' }}"
        friendly_name: Bed occupied sensor regardless where on the bed.
        device_class: occupancy
        value_template: >-
          {% if states('sensor.bed_top_left') | int >= 11000 or states('sensor.bed_bottom_left') | int >= 1000 or states('sensor.bed_bottom_right') | int >= 2000 %}
            on
          {% else %}
            off
          {% endif %}
        attribute_templates:
          number_in_bed: >-
            {% if states('sensor.bed_top_left') | int > 4000 and states('sensor.bed_bottom_right') | int < 1000 %}
              1
            {% elif states('sensor.bed_top_left') | int < 4000 and states('sensor.bed_bottom_right') | int > 1000 %}
              1
            {% elif states('sensor.bed_top_left') | int > 4000 and states('sensor.bed_bottom_right') | int > 1000 %}
              2
            {% else %}
              0
            {% endif %}
input_boolean:
  enable_bed_presence:
    name: Enable Bed Sensor
    icon: mdi:bed-double-outline
  enable_bedroom_blind_automations:
    name: Enable bedroom blind automations
    icon: mdi:window-open
  enable_bedroom_motion_trigger:
    name: Enable motion trigger for bedroom
    icon: mdi:motion-sensor
group:
  bedroom_desk_lights:
    name: Bedroom Lights
    icon: mdi:lightbulb
    entities:
      - light.bedroom_left_lamp
      - light.bedroom_right_lamp
  bedroom_lights:
    name: Bedroom Lights
    icon: mdi:lightbulb
    entities:
      - light.bedroom_left_lamp
      - light.bedroom_right_lamp
      - light.under_bed_light_left
      - light.under_bed_light_right
  bedroom_motion:
    name: Bedroom Motion
    icon: mdi:walk
    entities:
      - binary_sensor.bedroom_motion
      - binary_sensor.bedroom_motion_2
sensor:
  # Aggregated sensors
  - platform: min_max
    name: Bedroom Area Light Level
    entity_ids:
      - sensor.bedroom_motion_light_level
      - sensor.bedroom_motion_2_light_level
    type: mean
  - platform: min_max
    name: Bedroom Area Temperature
    entity_ids:
      - sensor.bedroom_motion_temperature
      - sensor.bedroom_motion_2_temperature
    type: mean
  # Statistics
  - platform: statistics
    entity_id: sensor.bed_top_left
    name: Bed Top Left Stat
    sampling_size: 2000
  - platform: statistics
    entity_id: sensor.bed_top_right
    name: Bed Top Right Stat
    sampling_size: 2000
  - platform: statistics
    entity_id: sensor.bed_bottom_left
    name: Bed Bottom Left Stat
    sampling_size: 2000
  - platform: statistics
    entity_id: sensor.bed_bottom_right
    name: Bed Bottom Right Stat
    sampling_size: 2000
