# Created by Danny Tsang <danny@tsang.uk>
automation:
  # Blinds
  - id: "1605925028960"
    alias: "^Ashlee's Room: Timed Close Blinds"
    description: ""
    trigger:
      - platform: time
        at: input_datetime.childrens_bed_time
      - platform: sun
        event: sunset
        id: sunset
    condition:
      - not:
          - condition: state
            entity_id: cover.ashlees_blinds
            state: closed
      - condition: state
        entity_id: input_boolean.enable_ashlees_blind_automations
        state: "on"
    action:
      - choose:
          # Window is still open
          - conditions:
              - condition: state
                entity_id: binary_sensor.ashlees_window
                state: "on"
            sequence:
              - service: script.send_to_home_log
                data:
                  message:
                    ":warning: :clock{{ now().strftime('%I') | int }}{% if now().minute | int
                    > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :window: Ashlee's window is still open. Waiting until
                    it's closed before closing blinds. :warning:"
                  title: "Ashlee's :bed: bedroom"
          # No children mode
          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: No Children
              - condition: trigger
                id: sunset
              - condition: state
                entity_id: binary_sensor.ashlees_window
                state: "off"
            sequence:
              - service: script.send_to_home_log
                data:
                  message: ":city_sunset: :window: It's getting dark, closing Ashlee's blinds."
                  title: "Ashlee's :bed: bedroom"
              - service: cover.close_cover
                target:
                  entity_id: cover.ashlees_blinds
          # Bed sensor enabled
          - conditions:
              - condition: state
                entity_id: input_boolean.enable_ashlees_bed_sensor
                state: "on"
              - condition: state
                entity_id: binary_sensor.ashlees_window
                state: "off"
              - condition: trigger
                id: sunset
            sequence:
              - service: script.send_to_home_log
                data:
                  message:
                    ":clock{{ now().strftime('%I') | int }}{% if now().minute | int
                    > 25 and now().minute | int < 35 %}30{% else %}{% endif %}:
                    :city_sunset: :window: It's getting dark and no one is in Ashlee's :bed: bed,
                    closing Ashlee's blinds."
                  title: "Ashlee's :bed: bedroom"
              - service: cover.close_cover
                target:
                  entity_id: cover.ashlees_blinds
          # Bed sensor is off
          - conditions:
              - condition: state
                entity_id: binary_sensor.ashlees_window
                state: "off"
              - condition: state
                entity_id: input_boolean.enable_ashlees_bed_sensor
                state: "off"
            sequence:
              - service: script.send_to_home_log
                data:
                  message:
                    ":clock{{ now().strftime('%I') | int }}{% if now().minute | int
                    > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :city_sunset: :window: It's getting dark, closing Ashlee's blinds."
                  title: "Ashlee's :bed: bedroom"
              - service: cover.close_cover
                target:
                  entity_id: cover.ashlees_blinds
        default: []
    mode: single
  - id: "1622891806607"
    alias: "^Ashlee's Room: Window Closed After Dark"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.ashlees_window
        from: "on"
        to: "off"
        for:
          hours: 0
          minutes: 1
          seconds: 0
    condition:
      - condition: state
        entity_id: cover.ashlees_blinds
        state: open
      - condition: state
        entity_id: input_boolean.enable_ashlees_blind_automations
        state: "on"
      - condition: time
        after: input_datetime.childrens_bed_time
    action:
      - service: script.send_to_home_log
        data:
          message: ":window: Window closed and it's dark. Closing blinds."
          title: "Ashlee's :bed: bedroom"
      - service: cover.close_cover
        target:
          entity_id: cover.ashlees_blinds
        data: {}
    mode: single
  - id: "1605775729191"
    alias: "^Ashlee's Room: Turn Off Lamp After An Hour"
    description: ""
    trigger:
      - platform: state
        entity_id: switch.ashlees_lamp
        to: "on"
        for: 01:00:00
    condition: []
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.ashlees_lamp
      - service: script.send_to_home_log
        data:
          message: "Lamp has been on for 1 hour. Turning lamp off."
          title: "Ashlee's :bed: bedroom"
    mode: single
  - id: "1599994669457"
    alias: "^Ashlee's Room: Open Blinds In The Morning"
    description: ""
    trigger:
      - at: 08:00:00
        platform: time
        id: default
      - at: 07:30:00
        platform: time
        id: school_day
    condition:
      - condition: state
        entity_id: cover.ashlees_blinds
        state: closed
      - condition: state
        entity_id: input_boolean.enable_ashlees_blind_automations
        state: "on"
    action:
      - choose:
          - conditions:
              - not:
                  - condition: state
                    entity_id: input_select.home_mode
                    state: Guest
              - condition: trigger
                id: school_day
              - condition: state
                entity_id: binary_sensor.workday_sensor
                state: "on"
            sequence:
              - data:
                  message:
                    ":clock{{ now().strftime('%I') | int }}{% if now().minute | int
                    > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :sunrise: :window: School day. Opening Ashlee's blinds"
                  title: "Ashlee's :bed: bedroom"
                service: script.send_to_home_log
              - service: cover.open_cover
                target:
                  entity_id: cover.ashlees_blinds
          - conditions:
              - not:
                  - condition: state
                    entity_id: input_select.home_mode
                    state: Guest
              - condition: trigger
                id: default
            sequence:
              - data:
                  message:
                    ":clock{{ now().strftime('%I') | int }}{% if now().minute | int
                    > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :sunrise: :window: Opening Ashlee's blinds"
                  title: "Ashlee's :bed: bedroom"
                service: script.send_to_home_log
              - service: cover.open_cover
                target:
                  entity_id: cover.ashlees_blinds
          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: Guest
            sequence:
              - service: script.send_to_home_log
                data:
                  message:
                    ":stop_sign: :sunrise: :window: Guest mode is enabled. Skipping
                    opening Ashlee's bedroom blinds."
                  title: "Ashlee's :bed: bedroom"
        default: []
    mode: single
  - id: "1655237597647"
    alias: "^Ashlee's Bedroom: Someone Is In Bed"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.ashlees_bed_occupied
        from: "off"
        to: "on"
        for:
          hours: 0
          minutes: 0
          seconds: 30
    condition: []
    action:
      - parallel:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: input_boolean.enable_ashlees_bed_sensor
                    state: "on"
                  - condition: state
                    entity_id: input_boolean.enable_ashlees_blind_automations
                    state: "on"
                  - condition: state
                    entity_id: cover.ashlees_blinds
                    state: open
                  - or:
                      - condition: time
                        after: input_datetime.childrens_bed_time
                      - condition: time
                        before: 05:00:00
                  - condition: state
                    entity_id: binary_sensor.ashlees_window
                    state: "off"
                sequence:
                  - service: script.send_to_home_log
                    data:
                      message:
                        "Someone is in Ashlee's :bed: bed after :clock730:. Closing
                        blinds."
                      title: "Ashlee's :bed: bedroom"
                  - service: cover.close_cover
                    data: {}
                    target:
                      entity_id: cover.ashlees_blinds
            default: []
    mode: single
  # Switches
  - id: "1655235874989"
    alias: "^Ashlee's Bedroom: Turn Off Fan After 1 Hour"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - switch.ashlees_fan
        to: "on"
        for:
          hours: 1
          minutes: 0
          seconds: 0
    condition: []
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: ":fan: Fan has been on for an hour. Turning fan off."
              title: ":bed: Ashlee's bedroom"
          - service: switch.turn_off
            data: {}
            target:
              entity_id: switch.ashlees_fan
    mode: single
  # Hue Remote
  - id: "1656355431188"
    alias: "^Ashlee's Bedroom: Hue Remote Short Presses"
    description: ""
    trigger:
      - platform: event
        event_type: hue_event
        event_data:
          id: ashlee_s_switch_button
          type: short_release
    condition: []
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.unique_id == '1096f89c-ec38-4b07-afc0-67a6294443af'}}"
            sequence:
              - service: script.send_to_home_log
                data:
                  message: "Power button pressed. :bulb: Toggling light."
                  title: ":bed: Ashlee's Bedroom"
              - service: light.toggle
                data: {}
                target:
                  entity_id: light.ashlees_main_light
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.unique_id == '0c3030ec-fe67-4f11-9682-01a6ff9b10d1'}}"
            sequence:
              - parallel:
                  - service: script.send_to_home_log
                    data:
                      message: "Hue buttom on remote pressed. Toggle Ahlee's :bulb: lamp."
                      title: ":bed: Ashlee's Bedroom"
                  - service: switch.toggle
                    data: {}
                    target:
                      entity_id: switch.ashlees_lamp
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.unique_id == 'a4594566-7671-449a-b348-2d9822d62f38'}}"
            sequence:
              - parallel:
                  - service: script.send_to_home_log
                    data:
                      message: "Bright buttom on remote pressed. Opening :window: Ashlee's blinds."
                      title: ":bed: Ashlee's Bedroom"
                  - service: cover.open_cover
                    data: {}
                    target:
                      entity_id: cover.ashlees_blinds
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.unique_id == '0c27554e-9338-4bd2-8cff-6255654fca42'}}"
            sequence:
              - parallel:
                  - service: script.send_to_home_log
                    data:
                      message: "Dim buttom on remote pressed. Closing :window: Ashlee's blinds."
                      title: ":bed: Ashlee's Bedroom"
                  - service: cover.close_cover
                    data: {}
                    target:
                      entity_id: cover.ashlees_blinds
        default: []
    mode: queued
    max: 10

template:
  - binary_sensor:
      - name: Ashlees Bed Occupied
        icon: >-
          mdi:bed-single{{ '-outline' if states('sensor.ashlees_bed_top') | float >= 0.1 or
          states('sensor.ashlees_bed_middle_top') | float >= 0.1 or
          states('sensor.ashlees_bed_middle_bottom') | float >= 0.1 or
          states('sensor.ashlees_bed_bottom') | float >= 0.1 else '' }}
        device_class: occupancy
        state: >-
          {% if states('sensor.ashlees_bed_top') | float >= 0.1 or 
              states('sensor.ashlees_bed_middle_top') | float >= 0.1 or 
              states('sensor.ashlees_bed_middle_bottom') | float >= 0.1 or
              states('sensor.ashlees_bed_bottom') | float >= 0.1 %}
            on
          {% else %}
            off
          {% endif %}
        attributes:
          top: "{{ states('sensor.ashlees_bed_top') }}"
          top_middle: "{{ states('sensor.ashlees_bed_middle_top') }}"
          bottom_middle: "{{ states('sensor.ashlees_bed_middle_bottom') }}"
          bottom: "{{ states('sensor.ashlees_bed_bottom') }}"
