# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1605925028960"
    alias: "^Ashlee's Room: Timed Close Blinds"
    description: ""
    trigger:
      - platform: time
        at: "19:30:00"
      - platform: sun
        event: sunset
        id: sunset
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: cover.ashlees_blinds
            state: closed
      - condition: state
        entity_id: input_boolean.enable_ashlees_blind_automations
        state: "on"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.ashlees_window
                state: "on"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":warning: :clock{{ now().strftime('%I') | int }}{% if now().minute | int
                    > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :window: Ashlee's window is still open. Waiting until
                    it's closed before closing blinds. :warning:"
          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: No Children
              - condition: trigger
                id: sunset
              - condition: state
                entity_id: binary_sensor.ashlees_window
                state: "off"
            sequence:
              - service: script.post_to_home_log
                data:
                  message: ":city_sunset: :window: It's getting dark, closing Ashlee's blinds."
              - service: cover.close_cover
                target:
                  entity_id: cover.ashlees_blinds
          - conditions:
              - condition: state
                entity_id: binary_sensor.ashlees_window
                state: "off"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":clock{{ now().strftime('%I') | int }}{% if now().minute | int
                    > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :city_sunset: :window: It's getting dark, closing Ashlee's blinds."
              - service: cover.close_cover
                target:
                  entity_id: cover.ashlees_blinds
        default: []
    mode: single
  - id: "1605775729191"
    alias: "^Ashlee's Room: Turn Off Lamp After An Hour"
    description: ""
    trigger:
      - platform: state
        entity_id: switch.ashlees_lamp
        to: "on"
        for: 01:00:00
    condition: []
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.ashlees_lamp
      - service: script.post_to_home_log
        data:
          message: "Ashlee's lamp has been on for 1 hour. Turning lamp off."
    mode: single
  - id: "1599994669457"
    alias: "^Ashlee's Room: Open Blinds In The Morning"
    description: ""
    trigger:
      - at: 08:00:00
        platform: time
    condition:
      - condition: state
        entity_id: cover.ashlees_blinds
        state: closed
      - condition: state
        entity_id: input_boolean.enable_ashlees_blind_automations
        state: "on"
    action:
      - choose:
          - conditions:
              - condition: not
                conditions:
                  - condition: state
                    entity_id: input_select.home_mode
                    state: Guest
            sequence:
              - data:
                  message:
                    ":clock{{ now().strftime('%I') | int }}{% if now().minute | int
                    > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :sunrise: :window: Opening Ashlee's blinds"
                service: script.post_to_home_log
              - service: cover.open_cover
                target:
                  entity_id: cover.ashlees_blinds
          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: Guest
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":stop_sign: :sunrise: :window: Guest mode is enabled. Skipping
                    opening Ashlee's bedroom blinds."
        default: []
    mode: single
group:
  ashlees_bedroom_area_temperature:
    name: Ashlee's Bedroom Area Temperature
    icon: mdi:thermometer
    entities:
      - sensor.ashlees_bed_temperature
      # Radiator
      - sensor.ashlees_bedroom_temperature
      - sensor.ashlees_door_temperature
      - sensor.ashlees_window_temperature
  ashlees_bedroom_area_humidity:
    name: Ashlee's Bedroom Area Humidity
    icon: mdi:water-percent
    entities:
      - sensor.ashlees_bed_humidity
      # Radiator
      - sensor.ashlees_bedroom_humidity
input_boolean:
  enable_ashlees_bed_presence:
    name: Enable Ashlee's Bed Sensor
    icon: mdi:bed-single-outline
  enable_ashlees_blind_automations:
    name: Enable Ashlees Blind Automation
    icon: mdi:window-open
  enable_ashlees_door_automations:
    name: Enable Ashlee's Door Automation
    icon: mdi:door
template:
  - binary_sensor:
      - name: Ashlees Bed Occupied
        icon: >-
          mdi:bed-single{{ '-outline' if states('sensor.ashlees_bed_top') | float >= 0.1 or
          states('sensor.ashlees_bed_middle_top') | float >= 0.1 or
          states('sensor.ashlees_bed_middle_bottom') | float >= 0.1 or
          states('sensor.ashlees_bed_bottom') | float >= 0.1 else '' }}
        device_class: occupancy
        state: >-
          {% if states('sensor.ashlees_bed_top') | float >= 0.1 or 
              states('sensor.ashlees_bed_middle_top') | float >= 0.1 or 
              states('sensor.ashlees_bed_middle_bottom') | float >= 0.1 or
              states('sensor.ashlees_bed_bottom') | float >= 0.1 %}
            on
          {% else %}
            off
          {% endif %}
        attributes:
          top: "{{ states('sensor.ashlees_bed_top') }}"
          top_middle: "{{ states('sensor.ashlees_bed_middle_top') }}"
          bottom_middle: "{{ states('sensor.ashlees_bed_middle_bottom') }}"
          bottom: "{{ states('sensor.ashlees_bed_bottom') }}"
