# Created by Danny Tsang <danny@tsang.uk>
automation:
  # Blinds
  - id: "1627285063813"
    alias: "^Leo's Bedroom: Timed Open Blinds"
    description: ""
    trigger:
      - platform: time
        at: 08:00:00
    condition:
      - or:
          - condition: state
            entity_id: cover.leos_blinds
            state: closed
          - condition: state
            entity_id: cover.leos_blinds
            state: closing
      - not:
          - condition: state
            state: Guest
            entity_id: input_select.home_mode
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: Opening Leo's bedroom blinds
          - service: cover.open_cover
            target:
              entity_id: cover.leos_blinds
    mode: single
  - id: "1629844319596"
    alias: "^Leo's Bedroom: Timed Close Blinds"
    description: ""
    trigger:
      - platform: time
        at: "19:30:00"
      - platform: sun
        event: sunset
        id: sunset
    condition:
      - not:
          - condition: state
            entity_id: cover.leos_blinds
            state: closed
      - condition: state
        entity_id: input_boolean.enable_leos_blind_automations
        state: "on"
    action:
      - parallel:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: binary_sensor.leos_window
                    state: "on"
                sequence:
                  - service: script.send_to_home_log
                    data:
                      message:
                        ":warning: :clock{{ now().strftime('%I') | int }}{% if now().minute | int
                        > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :city_sunset: :window: Leo's
                        window is open. Skipping closing blinds. :warning:"
                      title: "Leo's :bed: bedroom"
              - conditions:
                  - condition: state
                    entity_id: input_select.home_mode
                    state: No Children
                  - condition: trigger
                    id: sunset
                sequence:
                  - service: script.send_to_home_log
                    data:
                      message:
                        ":clock{{ now().strftime('%I') | int }}{% if now().minute | int
                        > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :window: Closing
                        Leo's blinds"
                      title: "Leo's :bed: bedroom"
                  - service: cover.close_cover
                    target:
                      entity_id: cover.leos_blinds
              - conditions:
                  - condition: state
                    entity_id: binary_sensor.leos_window
                    state: "off"
                sequence:
                  - service: script.send_to_home_log
                    data:
                      message:
                        ":clock{{ now().strftime('%I') | int }}{% if now().minute | int
                        > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :window: Closing
                        Leo's blinds"
                      title: "Leo's :bed: bedroom"
                  - service: cover.close_cover
                    target:
                      entity_id: cover.leos_blinds
            default: []
    mode: single
  - id: "1617376203344"
    alias: "^Leo's Room: Close Blinds Before Sun Rise"
    description: ""
    trigger:
      - platform: sun
        event: sunrise
        offset: -02:00:00
    condition:
      - condition: state
        entity_id: cover.leos_blinds
        state: open
      - condition: state
        entity_id: binary_sensor.leos_window
        state: "off"
    action:
      - parallel:
          - service: cover.close_cover
            target:
              entity_id: cover.leos_blinds
          - service: script.send_to_home_log
            data:
              message: ":city_sunset: :window: closing Leo's blinds."
              title: "Leo's :bed: bedroom"
    mode: single
  - id: "1617376413056"
    alias: "^Leo's Room: Open Blinds In The Morning"
    description: ""
    trigger:
      - at: 09:30:00
        platform: time
    condition:
      - or:
          - condition: state
            entity_id: cover.leos_blinds
            state: closed
          - condition: state
            entity_id: cover.leos_blinds
            state: closing
      - condition: state
        entity_id: input_boolean.enable_leos_blind_automations
        state: "on"
    action:
      - parallel:
          - data:
              message: ":sunrise: :window: Opening Leo's blinds"
              title: "Leo's :bed: bedroom"
            service: script.send_to_home_log
          - service: cover.open_cover
            target:
              entity_id: cover.leos_blinds
    mode: single
  - id: "1617458869658"
    alias: "^Leo's Room: Open Blinds In The Morning When No One Is In Bed"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.leos_bed_occupied
        from: "on"
        to: "off"
    condition:
      - condition: time
        after: 07:00:00
        before: "12:00:00"
      - or:
          - condition: state
            entity_id: cover.leos_blinds
            state: closed
          - condition: state
            entity_id: cover.leos_blinds
            state: closing
      - condition: state
        entity_id: input_boolean.enable_leos_blind_automations
        state: "on"
      - condition: state
        entity_id: input_boolean.enable_leos_bed_sensor
        state: "on"
      - not:
          - condition: state
            entity_id: input_select.home_mode
            state: Guest
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: ":window: :bed: Someone is in Leo's bed. Closing blinds."
              title: "Leo's :bed: bedroom"
          - service: cover.open_cover
            target:
              entity_id: cover.leos_blinds
    mode: single
  - id: "1619254173098"
    alias: "Leo's Room: Window Closed At Night"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.leos_window
        to: "off"
        from: "on"
    condition:
      - condition: state
        entity_id: cover.leos_blinds
        state: open
      - condition: time
        after: "18:30:00"
      - condition: state
        entity_id: input_boolean.enable_leos_blind_automations
        state: "on"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.enable_leos_bed_sensor
                state: "on"
              - condition: state
                entity_id: binary_sensor.leos_bed_occupied
                state: "on"
            sequence:
              - service: script.send_to_home_log
                data:
                  message:
                    ":window: :bed: Leo's window closed and someone is in bed. Closing
                    blinds."
                  title: "Leo's :bed: bedroom"
              - service: cover.close_cover
                target:
                  entity_id: cover.leos_blinds
          - conditions:
              - condition: state
                entity_id: input_boolean.enable_leos_bed_sensor
                state: "off"
            sequence:
              - service: script.send_to_home_log
                data:
                  message:
                    ":window: :bed: Leo's window closed and someone is in bed. Closing
                    blinds."
                  title: "Leo's :bed: bedroom"
              - service: cover.close_cover
                target:
                  entity_id: cover.leos_blinds
        default: []
    mode: single
  # Music
  - id: "1650915676886"
    alias: "^Leo's Bedroom: Turn Off Spotify At Night"
    description: ""
    trigger:
      - platform: time
        at: "22:00:00"
    condition:
      - condition: state
        entity_id: media_player.spotify_danny
        attribute: source
        state: Leo's Bedroom
      - condition: state
        entity_id: media_player.spotify_danny
        state: playing
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message:
                ":clock{{ now().strftime('%I') | int }}{% if now().minute | int >
                25 and now().minute | int < 35 %}30{% else %}{% endif %}: Turning off :musical_note:
                music in Leo's Bedroom :radio: Echo."
              title: "Leo's :bed: bedroom"
          - service: media_player.media_pause
            data: {}
            target:
              entity_id: media_player.spotify_danny
    mode: single

template:
  - binary_sensor:
      - name: Leos Bed Occupied
        icon: >-
          mdi:bed-double{{ '-outline' if states('sensor.leos_bed_top_left') | float >= 0.06 or
          states('sensor.leos_bed_top_right') | float >= 0.06 or
          states('sensor.leos_bed_bottom_left') | float >= 0.07 or
          states('sensor.leos_bed_bottom_right') | float >= 0.06
          else '' }}
        device_class: occupancy
        state: >-
          {% if states('sensor.leos_bed_top_left') | float >= 0.06 
            or states('sensor.leos_bed_top_right') | float >= 0.06 
            or states('sensor.leos_bed_bottom_left') | float >= 0.07 
            or states('sensor.leos_bed_bottom_right') | float >= 0.06 %}
            on
          {% else %}
            off
          {% endif %}
        attributes:
          top_left: "{{ states('sensor.leos_bed_top_left') }}"
          top_right: "{{ states('sensor.leos_bed_top_right') }}"
          bottom_left: "{{ states('sensor.leos_bed_bottom_left') }}"
          bottom_right: "{{ states('sensor.leos_bed_bottom_right') }}"
