# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1617395256574"
    alias: "^Leo's Room: Bed Occupied At Night"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.leos_bed_occupied
        to: "on"
    condition:
      - condition: state
        entity_id: cover.leos_blinds
        state: open
      - condition: state
        entity_id: binary_sensor.leos_window
        state: "off"
      - condition: time
        after: "18:30:00"
      - condition: state
        entity_id: input_boolean.enable_leos_blind_automations
        state: "on"
      - condition: state
        entity_id: input_boolean.enable_leos_bed_presence
        state: "on"
    action:
      - service: cover.close_cover
        target:
          entity_id: cover.leos_blinds
    mode: single
  - id: "1617376203344"
    alias: "^Leo's Room: Close Blinds Before Sun Rise"
    description: ""
    trigger:
      - platform: sun
        event: sunrise
        offset: -02:00:00
    condition:
      - condition: state
        entity_id: cover.leos_blinds
        state: open
      - condition: state
        entity_id: binary_sensor.leos_window
        state: "off"
    action:
      - service: cover.close_cover
        target:
          entity_id: cover.leos_blinds
      - service: script.post_to_home_log
        data:
          message: ":city_sunset: :window: closing Leo's blinds."
    mode: single
  - id: "1617376413056"
    alias: "^Leo's Room: Open Blinds In The Morning"
    description: ""
    trigger:
      - at: 09:30:00
        platform: time
    condition:
      - condition: state
        entity_id: cover.leos_blinds
        state: closed
      - condition: state
        entity_id: input_boolean.enable_leos_blind_automations
        state: "on"
    action:
      - data:
          message: ":sunrise: :window: Opening Leo's blinds"
        service: script.post_to_home_log
      - service: cover.open_cover
        target:
          entity_id: cover.leos_blinds
    mode: single
  - id: "1617458869658"
    alias: "^Leo's Room: Open Blinds In The Morning When No One Is In Bed"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.leos_bed_occupied
        from: "on"
        to: "off"
    condition:
      - condition: time
        after: 07:00:00
        before: "12:00:00"
      - condition: state
        entity_id: cover.leos_blinds
        state: closed
      - condition: state
        entity_id: input_boolean.enable_leos_blind_automations
        state: "on"
      - condition: state
        entity_id: input_boolean.enable_leos_bed_presence
        state: "on"
    action:
      - service: script.post_to_home_log
        data:
          message: ":window: :bed: Someone is in Leo's bed. Closing blinds."
      - service: cover.open_cover
        target:
          entity_id: cover.leos_blinds
    mode: single
sensor:
  # Statistics
  - platform: statistics
    entity_id: sensor.leos_bed_top_left
    name: Leo's Bed Top Left Stat
    sampling_size: 2000
  - platform: statistics
    entity_id: sensor.leos_bed_top_right
    name: Leo's Bed Top Right Stat
    sampling_size: 2000
  - platform: statistics
    entity_id: sensor.leos_bed_bottom_left
    name: Leo's Bed Bottom Left Stat
    sampling_size: 2000
  - platform: statistics
    entity_id: sensor.leos_bed_bottom_right
    name: Leo's Bed Bottom Right Stat
    sampling_size: 2000
