# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1605775729191"
    alias: "^Ashlee's Room: Turn Off Lamp After An Hour"
    description: ""
    trigger:
      - platform: state
        entity_id: switch.ashlees_lamp
        to: "on"
        for: 01:00:00
    condition: []
    action:
      - type: turn_off
        device_id: f7c05239afa74c2380c5fd0e36c9f849
        entity_id: switch.ashlees_lamp
        domain: switch
      - service: script.post_to_home_log
        data:
          message: Ashlee's lamp has been on for 1 hour. Turning lamp off.
    mode: single
  - id: "1599994669457"
    alias: "^Ashlee's Room: Open Blinds In The Morning"
    description: ""
    trigger:
      - at: 08:30:00
        platform: time
    condition:
      - condition: state
        entity_id: cover.ashlees_blinds
        state: closed
      - condition: state
        entity_id: input_boolean.enable_ashlees_blind_automations
        state: "on"
    action:
      - data:
          message: ":sunrise: :window: Opening Ashlee's blinds"
        service: script.post_to_home_log
      - service: cover.open_cover
        target:
          entity_id: cover.ashlees_blinds
    mode: single
input_boolean:
  enable_ashlees_blind_automations:
  name: Enable Ashlees Blind Automation
  icon: mdi:window-open
