# Created by Danny Tsang <danny@tsang.uk>
automation:
  # Motion
  - id: "1610234394136"
    alias: "Conservatory: Motion Detected And It's Dark"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.conservatory_area_motion
          - binary_sensor.conservatory_motion_occupancy
        from: "off"
        to: "on"
    condition:
      - condition: numeric_state
        entity_id: sensor.conservatory_motion_illuminance
        below: input_number.conservatory_light_level_threshold
      - condition: state
        entity_id: input_boolean.enable_conservatory_motion_trigger
        state: "on"
      - or:
          - condition: numeric_state
            entity_id: light.conservatory
            attribute: brightness
            below: "9"
          - condition: template
            value_template: "{{ state_attr('light.conservatory', 'brightness') == none }}"
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: >-
                :paw_prints: Motion detected and
                it's dark ({{ states('sensor.conservatory_motion_illuminance', with_unit=True) }} <
                ({{ states('input_number.conservatory_light_level_threshold', with_unit=True) }}).
                Turning :bulb: :high_brightness: light on.
              title: "Conservatory"
              log_level: "Debug"
          - service: scene.turn_on
            target:
              entity_id: scene.conservatory_turn_on_light
            data:
              transition: 2
    mode: single
  - id: "1610234794461"
    alias: "Conservatory: No Motion Detected Dim Lights"
    description: ""
    trigger:
      - platform: state
        to: "off"
        for: 00:01:00
        entity_id: binary_sensor.conservatory_area_motion
        from: "on"
    condition:
      - condition: state
        entity_id: light.conservatory
        state: "on"
      - condition: state
        entity_id: input_boolean.enable_conservatory_motion_trigger
        state: "on"
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: ":no_pedestrians: No motion. :bulb: :low_brightness: Dimming lights."
              title: "Conservatory"
              log_level: "Debug"
          - service: scene.turn_on
            target:
              entity_id: scene.conservatory_dim_light
            data:
              transition: 2
    mode: single
  - id: "1610238960657"
    alias: "Conservatory: No Motion Turning Turn Lights Off"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.conservatory_area_motion
        to: "off"
        for: 00:01:30
    condition:
      - condition: state
        entity_id: light.conservatory
        state: "on"
      - condition: state
        entity_id: input_boolean.enable_conservatory_motion_trigger
        state: "on"
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: ":no_pedestrians: No motion. Turning lights off."
              title: "Conservatory"
              log_level: "Debug"
          - service: scene.turn_on
            target:
              entity_id: scene.conservatory_turn_off_light
            data:
              transition: 2
    mode: single
  # Camera
  - id: "1629146628067"
    alias: "Conservatory: Person Detected"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.conservatory_person_detected
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: alarm_control_panel.house_alarm
        state: "armed_away"
    action:
      - service: camera.snapshot
        data_template:
          filename:
            "{{ states('input_text.latest_frigate_conservatory_person_file_path')
            }}"
        target:
          entity_id: camera.conservatory_high_resolution_channel
      - service: script.send_home_log_with_local_attachments
        data_template:
          message: Frigate detected a person in the conservatory.
          title: Person detected in conservatory
          log_level: "Normal"
          filePath: "{{ states('input_text.latest_frigate_conservatory_person_file_path') }}"
    mode: queued
    max: 10
  # Door
  - id: "1628985027639"
    alias: "Conservatory: Door Open"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.conservatory_door
        to: "on"
    condition: []
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: ":door: Door opened."
              title: "Conservatory"
              log_level: "Debug"
          - if:
              - condition: not
                conditions:
                  - condition: state
                    entity_id: climate.thermostat
                    state: "off"
            then:
              - service: script.send_to_home_log
                data:
                  message: "Turning off the heating."
                  title: "Conservatory"
                  log_level: "Debug"
              - service: script.set_central_heating_to_off
                data: {}
    mode: single
  - id: "1628985156167"
    alias: "Conservatory: Door Closed"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.conservatory_door
        to: "off"
        from: "on"
    condition: []
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: ":door: Conservatory door closed."
              log_level: "Debug"
          - if:
              - condition: state
                entity_id: climate.thermostat
                state: "off"
            then:
              - service: script.send_to_home_log
                data:
                  message: "Turning heating on."
                  title: "Conservatory"
                  log_level: "Debug"
              - service: script.set_central_heating_to_home_mode
                data: {}
          - choose:
              - conditions:
                  - condition: state
                    entity_id: binary_sensor.shed_door
                    state: "on"
                  - condition: state
                    entity_id: binary_sensor.back_garden_gate_contact
                    state: "on"
                sequence:
                  - service: script.send_direct_notification
                    data:
                      message: ":door: Door closed. :hut: shed :door: door and gate is still open."
                      title: Conservatory
                      people:
                        entity_id:
                          - person.danny
                          - person.terina
              - conditions:
                  - condition: state
                    entity_id: binary_sensor.shed_door
                    state: "on"
                sequence:
                  - service: script.send_direct_notification
                    data:
                      message: ":door: Door closed and :hut: shed :door: door is still open."
                      title: Conservatory
                      people:
                        entity_id:
                          - person.danny
                          - person.terina
              - conditions:
                  - condition: state
                    entity_id: binary_sensor.back_garden_gate_contact
                    state: "on"
                sequence:
                  - service: script.send_direct_notification
                    data:
                      message: ":door: Door closed and gate is still open."
                      title: Conservatory
                      people:
                        entity_id:
                          - person.danny
                          - person.terina
            default: []
    mode: single
  # Unit rate related automations
  - id: "1689626117479"
    alias: "Conservatory: Electricity Rates Pays For Usage"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.electricity_current_rate
        below: 0
    condition:
      - condition: state
        entity_id: input_boolean.enable_conservatory_under_floor_heating_automations
        state: "on"
      - condition: state
        entity_id: input_boolean.conservatory_under_floor_heating_cost_below_nothing
        state: "on"
      - alias: "Not in holiday mode"
        not:
          - condition: state
            entity_id: input_select.home_mode
            state: Holiday
    action:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: sensor.conservatory_area_mean_temperature
                below: "25"
              - condition: numeric_state
                entity_id: climate.conservatory_under_floor_heating
                attribute: temperature
                below: "20"
            sequence:
              - parallel:
                - service: script.send_to_home_log
                  data:
                    message: >-
                      Electrictity rate below 0 ({{ states('sensor.electricity_current_rate', with_unit=True) }}).
                      Setting under floor target temperature to 20°C (currently
                      {{ state_attr('climate.conservatory_under_floor_heating', 'temperature') }}°C).
                    title: Conservatory
                    log_level: "Normal"
                - service: climate.set_temperature
                  data:
                    temperature: 20
                    hvac_mode: heat
                  target:
                    entity_id: climate.conservatory_under_floor_heating
          - alias: "Air temperature is hot but floor is cool"
            conditions:
              - condition: numeric_state
                entity_id: sensor.conservatory_area_mean_temperature
                above: "24"
              - condition: numeric_state
                entity_id: climate.conservatory_under_floor_heating
                attribute: temperature
                below: "20"
            sequence:
              - parallel:
                - service: script.send_to_home_log
                  data:
                    message: "Ambient air temperature is above 24°C ({{ states('sensor.conservatory_area_mean_temperature', with_unit=True) }})
                    but floor is cool {{ state_attr('climate.conservatory_under_floor_heating', 'temperature') }}°C).
                    Skipping Underfloor heating."
                    title: "Conservatory"
                    people:
                      - person.danny
        default:
          - service: script.send_direct_notification
            data:
              message: "Ambient air temperature is above 21°C. Skipping Underfloor heating."
              title: "Conservatory"
              people:
                entity_id:
                  - person.danny
    mode: single
  - id: "1689626117480"
    alias: "Conservatory: Electricity Rates Starts To Cost"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.electricity_current_rate
        above: "0"
    condition:
      - condition: template
        value_template: >-
          {{ state_attr('climate.conservatory_under_floor_heating', 'temperature')|float >
          states('input_number.conservatory_default_under_floor_temperature')|float }}
      - alias: "Not in holiday mode"
        not:
          - condition: state
            entity_id: input_select.home_mode
            state: Holiday
      - condition: state
        entity_id: input_boolean.enable_conservatory_under_floor_heating_automations
        state: "on"
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: >-
                Turning off under floor heating by setting target temperature to {{ states('input_number.conservatory_default_under_floor_temperature', with_unit=True) }}.
              title: Conservatory
              log_level: "Debug"
          - service: climate.set_temperature
            data:
              temperature: "{{ states('input_number.conservatory_default_under_floor_temperature')|float }}"
              hvac_mode: heat
            target:
              entity_id: climate.conservatory_under_floor_heating
    mode: single

scene:
  - id: "1610234583738"
    name: "Conservatory: Turn On Light"
    entities:
      light.conservatory:
        min_mireds: 153
        max_mireds: 500
        effect_list:
          - colorloop
          - random
        supported_color_modes:
          - color_temp
          - hs
        color_mode: color_temp
        brightness: 255
        color_temp: 282
        effect: none
        friendly_name: Conservatory
        supported_features: 63
        state: "on"
  - id: "1610238837322"
    name: "Conservatory: Dim Light"
    entities:
      light.conservatory:
        min_mireds: 153
        max_mireds: 500
        effect_list:
          - colorloop
          - random
        supported_color_modes:
          - color_temp
          - hs
        color_mode: color_temp
        brightness: 128
        color_temp: 282
        effect: none
        friendly_name: Conservatory
        supported_features: 63
        state: "on"
  - id: "1610238855789"
    name: "Conservatory: Turn Off Light"
    entities:
      light.conservatory:
        min_mireds: 153
        max_mireds: 500
        effect_list:
          - colorloop
          - random
        supported_color_modes:
          - color_temp
          - hs
        friendly_name: Conservatory
        supported_features: 63
        state: "off"

sensor:
  - platform: mold_indicator
    name: Conservatory Mould Indicator
    indoor_temp_sensor: sensor.conservatory_motion_temperature
    indoor_humidity_sensor: sensor.conservatory_motion_humidity
    outdoor_temp_sensor: sensor.gw2000a_outdoor_temperature
    calibration_factor: 1.97
