# Created by Danny Tsang <danny@tsang.uk>
automation:
  # Motion
  - id: "1610234394136"
    alias: "Conservatory: Motion Detected And It's Dark"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.conservatory_area_motion
          - binary_sensor.conservatory_motion_occupancy
        from: "off"
        to: "on"
    conditions:
      - condition: numeric_state
        entity_id: sensor.conservatory_motion_illuminance
        below: input_number.conservatory_light_level_threshold
      - condition: state
        entity_id: input_boolean.enable_conservatory_motion_trigger
        state: "on"
      - or:
          - condition: numeric_state
            entity_id: light.conservatory
            attribute: brightness
            below: "9"
          - condition: template
            value_template: "{{ state_attr('light.conservatory', 'brightness') == none }}"
    actions:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: >-
                :paw_prints: Motion detected and
                it's dark ({{ states('sensor.conservatory_motion_illuminance', with_unit=True) }} <
                ({{ states('input_number.conservatory_light_level_threshold', with_unit=True) }}).
                Turning :bulb: :high_brightness: light on.
              title: "Conservatory"
              log_level: "Debug"
          - action: scene.turn_on
            target:
              entity_id: scene.conservatory_turn_on_light
            data:
              transition: 2
    mode: single
  - id: "1610234794461"
    alias: "Conservatory: No Motion Detected Dim Lights"
    description: ""
    triggers:
      - trigger: state
        to: "off"
        for: 00:01:00
        entity_id: binary_sensor.conservatory_area_motion
        from: "on"
    conditions:
      - condition: state
        entity_id: light.conservatory
        state: "on"
      - condition: state
        entity_id: input_boolean.enable_conservatory_motion_trigger
        state: "on"
    actions:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: ":no_pedestrians: No motion. :bulb: :low_brightness: Dimming lights."
              title: "Conservatory"
              log_level: "Debug"
          - action: scene.turn_on
            target:
              entity_id: scene.conservatory_dim_light
            data:
              transition: 2
    mode: single
  - id: "1610238960657"
    alias: "Conservatory: No Motion Turning Turn Lights Off"
    description: ""
    triggers:
      - trigger: state
        entity_id: binary_sensor.conservatory_area_motion
        to: "off"
        for: 00:01:30
    conditions:
      - condition: state
        entity_id: light.conservatory
        state: "on"
      - condition: state
        entity_id: input_boolean.enable_conservatory_motion_trigger
        state: "on"
    actions:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: ":no_pedestrians: No motion. Turning lights off."
              title: "Conservatory"
              log_level: "Debug"
          - action: scene.turn_on
            target:
              entity_id: scene.conservatory_turn_off_light
            data:
              transition: 2
    mode: single
  # Camera
  - id: "1629146628067"
    alias: "Conservatory: Person Detected"
    description: ""
    triggers:
      - trigger: state
        entity_id: binary_sensor.conservatory_person_detected
        from: "off"
        to: "on"
    conditions:
      - condition: state
        entity_id: alarm_control_panel.house_alarm
        state: "armed_away"
    actions:
      - action: camera.snapshot
        data_template:
          filename:
            "{{ states('input_text.latest_frigate_conservatory_person_file_path')
            }}"
        target:
          entity_id: camera.conservatory_high_resolution_channel
      - action: script.send_home_log_with_local_attachments
        data_template:
          message: Frigate detected a person in the conservatory.
          title: Person detected in conservatory
          log_level: "Normal"
          filePath: "{{ states('input_text.latest_frigate_conservatory_person_file_path') }}"
    mode: queued
    max: 10
  # Door
  - id: "1628985027639"
    alias: "Conservatory: Door Open"
    description: ""
    triggers:
      - trigger: state
        entity_id: binary_sensor.conservatory_door
        to: "on"
    conditions: []
    actions:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: ":door: Door opened."
              title: "Conservatory"
              log_level: "Debug"
          - if:
              - condition: not
                conditions:
                  - condition: state
                    entity_id: climate.thermostat
                    state: "off"
            then:
              - action: script.send_to_home_log
                data:
                  message: "Turning off the heating."
                  title: "Conservatory"
                  log_level: "Debug"
              - action: script.set_central_heating_to_off
                data: {}
    mode: single
  - id: "1628985156167"
    alias: "Conservatory: Door Closed"
    description: ""
    triggers:
      - trigger: state
        entity_id: binary_sensor.conservatory_door
        to: "off"
        from: "on"
    conditions: []
    actions:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: ":door: Conservatory door closed."
              log_level: "Debug"
          - if:
              - condition: state
                entity_id: climate.thermostat
                state: "off"
            then:
              - action: script.send_to_home_log
                data:
                  message: "Turning heating on."
                  title: "Conservatory"
                  log_level: "Debug"
              - action: script.set_central_heating_to_home_mode
                data: {}
          - choose:
              - conditions:
                  - condition: state
                    entity_id: binary_sensor.shed_door
                    state: "on"
                  - condition: state
                    entity_id: binary_sensor.back_garden_gate_contact
                    state: "on"
                sequence:
                  - action: script.send_direct_notification
                    data:
                      message: ":door: Door closed. :hut: shed :door: door and gate is still open."
                      title: Conservatory
                      people:
                        entity_id:
                          - person.danny
                          - person.terina
              - conditions:
                  - condition: state
                    entity_id: binary_sensor.shed_door
                    state: "on"
                sequence:
                  - action: script.send_direct_notification
                    data:
                      message: ":door: Door closed and :hut: shed :door: door is still open."
                      title: Conservatory
                      people:
                        entity_id:
                          - person.danny
                          - person.terina
              - conditions:
                  - condition: state
                    entity_id: binary_sensor.back_garden_gate_contact
                    state: "on"
                sequence:
                  - action: script.send_direct_notification
                    data:
                      message: ":door: Door closed and gate is still open."
                      title: Conservatory
                      people:
                        entity_id:
                          - person.danny
                          - person.terina
            default: []
    mode: single

scene:
  - id: "1610234583738"
    name: "Conservatory: Turn On Light"
    entities:
      light.conservatory:
        min_mireds: 153
        max_mireds: 500
        effect_list:
          - colorloop
          - random
        supported_color_modes:
          - color_temp
          - hs
        color_mode: color_temp
        brightness: 255
        color_temp: 282
        effect: none
        friendly_name: Conservatory
        supported_features: 63
        state: "on"
  - id: "1610238837322"
    name: "Conservatory: Dim Light"
    entities:
      light.conservatory:
        min_mireds: 153
        max_mireds: 500
        effect_list:
          - colorloop
          - random
        supported_color_modes:
          - color_temp
          - hs
        color_mode: color_temp
        brightness: 128
        color_temp: 282
        effect: none
        friendly_name: Conservatory
        supported_features: 63
        state: "on"
  - id: "1610238855789"
    name: "Conservatory: Turn Off Light"
    entities:
      light.conservatory:
        min_mireds: 153
        max_mireds: 500
        effect_list:
          - colorloop
          - random
        supported_color_modes:
          - color_temp
          - hs
        friendly_name: Conservatory
        supported_features: 63
        state: "off"

sensor:
  - platform: mold_indicator
    name: Conservatory Mould Indicator
    indoor_temp_sensor: sensor.conservatory_motion_temperature
    indoor_humidity_sensor: sensor.conservatory_motion_humidity
    outdoor_temp_sensor: sensor.gw2000a_outdoor_temperature
    calibration_factor: 1.97
