# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1617735040678"
    alias: "^Conservatory: Motion Detected And Alarm Armed"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.conservatory_area_motion
        from: "off"
        to: "on"
    condition:
      - or:
          - condition: state
            entity_id: group.adult_people
            state: not_home
          - not:
              - condition: state
                entity_id: alarm_control_panel.house_alarm
                state: disarmed
      - condition: state
        entity_id: input_boolean.enable_home_presence_detection
        state: "on"
    action:
      - service: script.conservatory_camera_process_image
        data:
          message: ":paw_prints: Motion detected in theconservatory and :bell: Alarm armed."
          title: "Conservatory"
    mode: single
  - id: "1610234394136"
    alias: "^Conservatory: Motion Detected And It's Dark"
    description: ""
    trigger:
      - platform: state
        to: "on"
        entity_id: binary_sensor.conservatory_area_motion
        from: "off"
    condition:
      - condition: numeric_state
        entity_id: sensor.conservatory_motion_light_level
        below: input_number.conservatory_light_level_threshold
      - condition: state
        entity_id: input_boolean.enable_conservatory_motion_trigger
        state: "on"
      - or:
          - condition: numeric_state
            entity_id: light.conservatory
            attribute: brightness
            below: "9"
          - condition: template
            value_template: "{{ state_attr('light.conservatory', 'brightness') == none }}"
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: >-
                :paw_prints: Motion detected and
                it's dark ({{ states('sensor.conservatory_motion_light_level') }}
                {{ state_attr('sensor.conservatory_motion_light_level','unit_of_measurement') }} <
                ({{ states('input_number.conservatory_light_level_threshold') }}
                {{ state_attr('input_number.bathroom_light_level_threshold','unit_of_measurement') }}).
                Turning :bulb: :high_brightness: light on.
              title: "Conservatory"
          - service: scene.turn_on
            target:
              entity_id: scene.conservatory_turn_on_light
            data:
              transition: 2
    mode: single
  - id: "1610234794461"
    alias: "^Conservatory: No Motion Detected Dim Lights"
    description: ""
    trigger:
      - platform: state
        to: "off"
        for: 00:01:00
        entity_id: binary_sensor.conservatory_area_motion
        from: "on"
    condition:
      - condition: state
        entity_id: light.conservatory
        state: "on"
      - condition: state
        entity_id: input_boolean.enable_conservatory_motion_trigger
        state: "on"
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message:
                ":no_pedestrians: No motion. :bulb: :low_brightness: Dimming lights."
              title: "Conservatory"
          - service: scene.turn_on
            target:
              entity_id: scene.conservatory_dim_light
            data:
              transition: 2
    mode: single
  - id: "1610238960657"
    alias: "^Conservatory: No Motion Turning Turn Lights Off"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.conservatory_area_motion
        to: "off"
        for: 00:01:30
    condition:
      - condition: state
        entity_id: light.conservatory
        state: "on"
      - condition: state
        entity_id: input_boolean.enable_conservatory_motion_trigger
        state: "on"
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: ":no_pedestrians: No motion. Turning lights off."
              title: "Conservatory"
          - service: scene.turn_on
            target:
              entity_id: scene.conservatory_turn_off_light
            data:
              transition: 2
    mode: single
  # Camera
  - id: "1629146628067"
    alias: "^Conservatory: Person Detected"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.conservatory_person_motion
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: switch.conservatory_detect
        state: "on"
    action:
      - service: camera.snapshot
        data_template:
          filename:
            "{{ states('input_text.latest_frigate_conservatory_person_file_path')
            }}"
        target:
          entity_id: camera.conservatory_person
      - service: script.send_home_log_with_local_attachments
        data_template:
          title: Person detected in conservatory
          message: Frigate detected a person in the conservatory.
          filePath: "{{ states('input_text.latest_frigate_conservatory_person_file_path') }}"
    mode: queued
    max: 10
  # Door
  - id: "1628985027639"
    alias: "^Conservatory: Door Open"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.conservatory_door
        to: "on"
    condition: []
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: ":door: Door opened."
              title: "Conservatory"
          - service: script.send_to_home_log
            data:
              message: "Turning conservatory camera :camera_with_flash: on."
          - service: script.conservatory_turn_on_camera
          - if:
              - condition: not
                conditions:
                  - condition: state
                    entity_id: climate.thermostat
                    state: "off"
            then:
              - service: script.send_to_home_log
                data:
                  message: "Turning off the heating."
                  title: "Conservatory"
              - service: climate.set_hvac_mode
                data:
                  hvac_mode: "off"
                target:
                  entity_id: climate.thermostat
    mode: single
  - id: "1628985156167"
    alias: "Conservatory: Door Closed"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.conservatory_door
        to: "off"
        from: "on"
    condition: []
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: ":door: Conservatory door closed."
          - service: script.conservatory_turn_off_camera
          - if:
              - condition: state
                entity_id: climate.thermostat
                state: "off"
            then:
              - service: script.send_to_home_log
                data:
                  message: "Setting heating to schedule (auto) mode."
                  title: "Conservatory"
              - service: climate.set_hvac_mode
                data:
                  hvac_mode: "auto"
                target:
                  entity_id: climate.thermostat
    mode: single

scene:
  - id: "1610234583738"
    name: "Conservatory: Turn On Light"
    entities:
      light.conservatory:
        min_mireds: 153
        max_mireds: 500
        effect_list:
          - colorloop
          - random
        supported_color_modes:
          - color_temp
          - hs
        color_mode: color_temp
        brightness: 255
        color_temp: 282
        effect: none
        friendly_name: Conservatory
        supported_features: 63
        state: "on"
  - id: "1610238837322"
    name: "Conservatory: Dim Light"
    entities:
      light.conservatory:
        min_mireds: 153
        max_mireds: 500
        effect_list:
          - colorloop
          - random
        supported_color_modes:
          - color_temp
          - hs
        color_mode: color_temp
        brightness: 128
        color_temp: 282
        effect: none
        friendly_name: Conservatory
        supported_features: 63
        state: "on"
  - id: "1610238855789"
    name: "Conservatory: Turn Off Light"
    entities:
      light.conservatory:
        min_mireds: 153
        max_mireds: 500
        effect_list:
          - colorloop
          - random
        supported_color_modes:
          - color_temp
          - hs
        friendly_name: Conservatory
        supported_features: 63
        state: "off"

script:
  conservatory_turn_off_camera:
    alias: Conservatory Turn Off Camera
    fields:
      override:
        name: override
        description: override any other factors that may prevent the camera from turning off.
        required: false
        default: false
        selector:
          boolean:
    sequence:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ override }}"
            sequence:
              - service: script.send_to_home_log
                data:
                  message: "Overriding conditions. Turning conservatory :camera: camera detection off."
              - service: switch.turn_off
                target:
                  entity_id:
                    - switch.conservatory_detect
                    - switch.conservatory_snapshots
          - conditions:
              - or:
                  - not:
                      - condition: state
                        entity_id: alarm_control_panel.house_alarm
                        state: disarmed
                  - condition: state
                    entity_id: binary_sensor.conservatory_door
                    state: "on"
                  - condition: state
                    entity_id: binary_sensor.shed_door
                    state: "on"
            sequence:
              - service: script.send_to_home_log
                data:
                  message: "Alarm is on or conservatory or shed door is open. Keeping conservatory :camera_with_flash: camera detection on."
        default:
          - service: script.send_to_home_log
            data:
              message: "Turning conservatory :camera: camera detection off."
          - service: switch.turn_off
            target:
              entity_id:
                - switch.conservatory_detect
                - switch.conservatory_snapshots
    mode: single
    icon: mdi:cctv
  conservatory_turn_on_camera:
    alias: Conservatory Turn On Camera
    sequence:
      - service: switch.turn_on
        target:
          entity_id:
            - switch.conservatory_detect
            - switch.conservatory_snapshots
    mode: single
    icon: mdi:cctv
