# Created by Danny Tsang <danny@tsang.uk>
alert:
  conservatory:
    name: Conservatory Leak
    entity_id: binary_sensor.conservatory_water
    state: "on"
    repeat:
      - 30
      - 60
    can_acknowledge: true
    skip_first: true
    notifiers:
      - mobile_app_dannys_phone
      - mobile_app_terina_s_phone
automation:
  - id: "1617735040678"
    alias: "^Conservatory: Motion Detected And Alarm Armed"
    description: ""
    trigger:
      - platform: state
        entity_id: group.conservatory_area_motion
        from: "off"
        to: "on"
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: group.adult_people
            state: not_home
          - condition: not
            conditions:
              - condition: state
                entity_id: alarm_control_panel.stevenage_alarm
                state: disarmed
      - condition: state
        entity_id: input_boolean.enable_home_presence_detection
        state: "on"
    action:
      - service: script.conservatory_camera_process_image
        data:
          title: Conservatory Snapshot
          message: Motion Detected In Conservatory And Alarm Armed
    mode: single
  - id: "1610234394136"
    alias: "^Conservatory: Motion Detected And It's Dark"
    description: ""
    trigger:
      - platform: state
        to: "on"
        entity_id: group.conservatory_area_motion
        from: "off"
    condition:
      - condition: numeric_state
        entity_id: sensor.conservatory_motion_light_level
        below: "250"
      - condition: state
        entity_id: input_boolean.enable_conservatory_motion_trigger
        state: "on"
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: light.conservatory
            attribute: brightness
            below: "9"
          - condition: template
            value_template: "{{ state_attr('light.conservatory', 'brightness') == none }}"
    action:
      - service: script.post_to_home_log
        data:
          message: ":paw_prints: :bulb: :high_brightness: Motion detected in conservatory and it's dark ({{ states('sensor.conservatory_motion_light_level') }} lux < 25 lux). Turning on Lights."
      - service: scene.turn_on
        target:
          entity_id: scene.conservatory_turn_on_light
        data:
          transition: 2
    mode: single
  - id: "1610234794461"
    alias: "^Conservatory: No Motion Detected Dim Lights"
    description: ""
    trigger:
      - platform: state
        to: "off"
        for: 00:01:00
        entity_id: group.conservatory_area_motion
        from: "on"
    condition:
      - condition: state
        entity_id: light.conservatory
        state: "on"
      - condition: state
        entity_id: input_boolean.enable_conservatory_motion_trigger
        state: "on"
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":no_pedestrians: :bulb: :low_brightness: No motion detected. Dimming
            conservatory lights."
      - service: scene.turn_on
        target:
          entity_id: scene.conservatory_dim_light
        data:
          transition: 2
    mode: single
  - id: "1610238960657"
    alias: "^Conservatory: No Motion Turning Turn Lights Off"
    description: ""
    trigger:
      - platform: state
        entity_id: group.conservatory_area_motion
        to: "off"
        for: 00:01:30
    condition:
      - condition: state
        entity_id: light.conservatory
        state: "on"
      - condition: state
        entity_id: input_boolean.enable_conservatory_motion_trigger
        state: "on"
    action:
      - service: script.post_to_home_log
        data:
          message: ":no_pedestrians: No motion in conservatory. Turning lights off."
      - service: scene.turn_on
        target:
          entity_id: scene.conservatory_turn_off_light
        data:
          transition: 2
    mode: single
  # Camera
  - id: "1629146628067"
    alias: "^Conservatory: Person Detected"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.conservatory_camera_person_motion
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: switch.conservatory_detect
        state: "on"
    action:
      - service: camera.snapshot
        data_template:
          filename:
            "{{ states('input_text.latest_frigate_conservatory_person_file_path')
            }}"
        target:
          entity_id: camera.conservatory_camera_person
      - service: script.post_to_home_log_with_local_attachments
        data_template:
          title: Person detected in conservatory
          message: Frigate detected a person in the conservatory.
          filePath: "{{ states('input_text.latest_frigate_conservatory_person_file_path') }}"
    mode: queued
    max: 10
  # Door
  - id: "1628985027639"
    alias: "^Conservatory: Door Open"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.conservatory_door
        to: "on"
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":door: Conservatory door opened. Enabling conservatory camera :camera_with_flash:"
      - service: script.conservatory_turn_on_camera
    mode: single
  - id: "1628985156167"
    alias: "Conservatory: Door Closed"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.conservatory_door
        to: "off"
        from: "on"
    condition: []
    action:
      choose:
        - conditions:
            - condition: not
              conditions:
                - condition: state
                  entity_id: alarm_control_panel.stevenage_alarm
                  state: disarmed
            - condition: state
              entity_id: binary_sensor.shed_door
              state: "on"
          sequence:
            - choose:
                - conditions:
                    - condition: state
                      state: "on"
                      entity_id: input_boolean.enable_slack_notifications
                  sequence:
                    - service: script.post_to_home_log
                      data:
                        message: ":door: :hut: :bell: Conservatory door closed. Keeping conservatory
                        camera on because alarm is armed and shed door is open."
              default: []
        - conditions:
            - condition: not
              conditions:
                - condition: state
                  entity_id: alarm_control_panel.stevenage_alarm
                  state: "disarmed"
            - condition: state
              entity_id: binary_sensor.shed_door
              state: "off"
          sequence:
            - choose:
                - conditions:
                    - condition: state
                      state: "on"
                      entity_id: input_boolean.enable_slack_notifications
                  sequence:
                    - service: script.post_to_home_log
                      data:
                        message: ":door: :hut: :bell: Conservatory door closed. Keeping conservatory
                        camera on because alarm is armed."
              default: []
        - conditions:
          - condition: state
            entity_id: binary_sensor.shed_door
            state: "on"
          sequence:
            - choose:
              - conditions:
                - condition: state
                  state: "on"
                  entity_id: input_boolean.enable_slack_notifications
                sequence:
                  - service: script.post_to_home_log
                    data:
                      message: ":door: :hut: :bell: Conservatory door closed. Keeping conservatory
                      camera on because shed door is open."
              default: []
    mode: single
group:
  conservatory_area_motion:
    name: Conservatory Motion
    icon: mdi:walk
    entities:
      - binary_sensor.conservatory_motion
      - binary_sensor.conservatory_motion_2
  conservatory_area_temperature:
    name: Conservatory Area Temperature
    icon: mdi:thermometer
    entities:
      - sensor.conservatory_motion_temperature
      - sensor.conservatory_bucket_temperature
      - sensor.conservatory_temperature
input_boolean:
  enable_conservatory_motion_trigger:
    name: Enable motion trigger for conservatory
    icon: mdi:motion-sensor
scene:
  - id: "1610234583738"
    name: "Conservatory: Turn On Light"
    entities:
      light.conservatory:
        min_mireds: 153
        max_mireds: 500
        effect_list:
          - colorloop
          - random
        supported_color_modes:
          - color_temp
          - hs
        color_mode: color_temp
        brightness: 255
        color_temp: 282
        effect: none
        friendly_name: Conservatory
        supported_features: 63
        state: "on"
  - id: "1610238837322"
    name: "Conservatory: Dim Light"
    entities:
      light.conservatory:
        min_mireds: 153
        max_mireds: 500
        effect_list:
          - colorloop
          - random
        supported_color_modes:
          - color_temp
          - hs
        color_mode: color_temp
        brightness: 128
        color_temp: 282
        effect: none
        friendly_name: Conservatory
        supported_features: 63
        state: "on"
  - id: "1610238855789"
    name: "Conservatory: Turn Off Light"
    entities:
      light.conservatory:
        min_mireds: 153
        max_mireds: 500
        effect_list:
          - colorloop
          - random
        supported_color_modes:
          - color_temp
          - hs
        friendly_name: Conservatory
        supported_features: 63
        state: "off"
script:
  conservatory_turn_off_camera:
    alias: Conservatory Turn Off Camera
    sequence:
      - service: switch.turn_off
        target:
          entity_id:
            - switch.conservatory_detect
    mode: single
    icon: mdi:cctv
  conservatory_turn_on_camera:
    alias: Conservatory Turn On Camera
    sequence:
      - service: switch.turn_on
        target:
          entity_id:
            - switch.conservatory_detect
            - switch.conservatory_snapshots
    mode: single
    icon: mdi:cctv
