# Created by Danny Tsang <danny@tsang.uk>
automation:
  # Doorbell
  - id: "1694521590171"
    alias: "Porch: Doorbell Pressed"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.front_door_ding_2
        to: "on"
    condition: []
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: "Some pressed the door bell."
              title: "Porch"
          - service: script.alexa_announce
            data:
              message: "Ding dong."
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.wait_for_doorbell_camera_update
          - if:
              - condition: state
                entity_id: group.adult_people
                state: "not_home"
            then:
              - service: todo.add_item
                data:
                  item: ":door: :bell: Someone rung the door bell."
                target:
                  entity_id: todo.shared_notifications
    mode: single
  - id: "1621070004545"
    alias: "Front Garden: Doorbell Camera Updated"
    description: ""
    trigger:
      - platform: state
        entity_id: camera.front_door
    condition:
      - condition: template
        value_template:
          "{{ state_attr('camera.front_door', 'last_video_id') | string
          != states('input_text.doorbell_last_video_id') | string}}"
    action:
      # Bug: https://github.com/home-assistant/home-assistant.io/issues/21599
      - service: downloader.download_file
        data:
          url: "{{ state_attr('camera.front_door', 'video_url') }}"
          subdir: "front_door"
          filename: "latest.mp4"
          overwrite: true
      # - service: shell_command.copy_doorbell_footage
      #   data: {}
    mode: queued
    max: 10
  # Light
  - id: "1660894232444"
    alias: "Front Garden: Below Direct Sun Light"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.front_garden_motion_illuminance_lux
        for:
          hours: 0
          minutes: 10
          seconds: 0
        below: input_number.close_blinds_brightness_threshold
    condition:
      - condition: state
        entity_id: sensor.season
        state: "summer"
    action:
      - service: script.send_to_home_log
        data:
          message:
            Sun light has fallen below {{ states('input_number.close_blinds_brightness_threshold')
            }} ({{ states('sensor.front_garden_motion_illuminance_lux', with_unit=True)
            }}). Opening office blinds/curtains.
          title: Front Garden
          log_level: "Normal"
      - service: cover.set_cover_position
        data:
          position: 25
        target:
          entity_id: cover.office_blinds
      - if:
          - condition: numeric_state
            entity_id: cover.bedroom_blinds
            attribute: current_position
            below: input_number.blind_closed_position_threshold
          - condition: sun
            before: sunset
          - condition: state
            entity_id: binary_sensor.bedroom_tv_powered_on
            state: "off"
        then:
          - service: cover.open_cover
            target:
              entity_id: cover.bedroom_blinds
      - if:
          - condition: numeric_state
            entity_id: cover.ashlees_bedroom_blinds
            attribute: current_position
            below: input_number.blind_closed_position_threshold
          - condition: time
            before: input_datetime.childrens_bed_time
        then:
          - service: cover.open_cover
            target:
              entity_id: cover.ashlees_bedroom_blinds
    mode: single
  - id: "1714914120928"
    alias: "Front Garden: Lock Box State Changed"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.outdoor_lock_box_contact
    condition: []
    action:
      - service: script.send_direct_notification
        metadata: {}
        data:
          title: Lock Box
          message: Was {{ states('binary_sensor.outdoor_lock_box_contact') }}
          people:
            - person.danny
            - person.terina
    mode: single
  - id: "1718364408150"
    alias: "Front Garden: Lockbox Sensor Disconnected"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.outdoor_lock_box_contact
        to: unavailable
        for:
          hours: 0
          minutes: 5
          seconds: 0
    condition: []
    action:
      - service: script.send_direct_notification
        metadata: {}
        data:
          message: Lockbox sensor has disconnected.
          people:
            entity_id: person.danny
    mode: single

script:
  front_garden_motion_notification:
    alias: Front Garden Motion Notification
    sequence:
      - repeat:
          count: "4"
          sequence:
            - service: scene.turn_on
              target:
                entity_id: scene.office_front_garden_motion_notification
            - delay:
                hours: 0
                minutes: 0
                seconds: 1
                milliseconds: 0
            - service: scene.turn_on
              target:
                entity_id: scene.office_turn_off_light_notification
    mode: single
  front_garden_turn_off_camera:
    alias: Front Garden Turn Off Camera
    sequence:
      - service: switch.turn_off
        target:
          entity_id:
            - switch.driveway_detect
            - switch.driveway_snapshots
    mode: single
    icon: mdi:cctv
  front_garden_turn_on_camera:
    alias: Front Garden Turn On Camera
    sequence:
      - service: switch.turn_on
        target:
          entity_id:
            - switch.driveway_detect
            - switch.driveway_snapshots
    mode: single
    icon: mdi:cctv

shell_command:
  copy_doorbell_footage: >-
    cp {{ states('input_text.camera_internal_folder_path') }}'/front_door/latest.mp4'
    {{ states('input_text.camera_internal_folder_path') }}'/front_door/'{{ state_attr('camera.front_door', 'friendly_name') }}_{{ as_timestamp(now())|timestamp_custom('%Y-%m-%d_%H%M%S') }}'.mp4'
