# Created by Danny Tsang <danny@tsang.uk>
automation:
  # region Doorbell
  - id: "1694521590171"
    alias: "Front Garden: Doorbell Pressed"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - event.front_door_ding
    conditions: []
    actions:
      - parallel:
          - action: script.send_direct_notification
            data:
              message: "Someone pressed the door bell."
              title: "Porch"
              people:
                entity_id:
                  - person.danny
                  - person.terina
          - action: script.alexa_announce
            data:
              message: "Ding dong."
              suppress_if_quiet: false
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.wait_for_doorbell_camera_update
          - alias: Delayed notification
            sequence:
              - action: todo.get_items
                target:
                  entity_id:
                    - todo.shared_notifications
                data:
                  status: needs_action
                response_variable: todo_list
              - if:
                  - condition: state
                    entity_id: group.tracked_people
                    state: "not_home"
                  - alias: Does not already exist
                    condition: template
                    value_template: >-
                      {%- for t in todo_list['todo.shared_notifications']['items'] -%}
                      {%- if t.summary == '🚪 🔔 Someone rung the door bell.' -%}
                      {{ false }}
                      {%- break -%}
                      {%- endif-%}
                      {%- endfor -%}
                then:
                  - action: todo.add_item
                    data:
                      item: "🚪 🔔 Someone rung the door bell."
                    target:
                      entity_id: todo.shared_notifications
          - alias: Take picture
            sequence:
              - wait_for_trigger:
                  - trigger: state
                    entity_id:
                      - camera.front_door
                timeout:
                  minutes: 1
                continue_on_timeout: false
              - action: script.send_direct_notification_with_url
                data:
                  message: Door bell pressed
                  title: Front Door
                  people:
                    entity_id:
                      - person.danny
                  url: "{{ state_attr('camera.front_door', 'entity_picture') }}"
                  url_type: image
              - action: script.send_direct_notification_with_url
                data:
                  message: Door bell pressed
                  title: Front Door
                  people:
                    entity_id:
                      - person.danny
                  url: "{{ state_attr('camera.front_door', 'video_url') }}"
                  url_type: video
    mode: single
  - id: "1621070004545"
    alias: "Front Garden: Doorbell Camera Updated"
    description: ""
    triggers:
      - trigger: state
        entity_id: camera.front_door
        not_to: "unavailable"
    conditions:
      - condition: template
        value_template:
          "{{ state_attr('camera.front_door', 'last_video_id') | string
          != states('input_text.doorbell_last_video_id') | string}}"
    actions:
      # Bug: https://github.com/home-assistant/home-assistant.io/issues/21599
      - action: downloader.download_file
        data:
          url: "{{ state_attr('camera.front_door', 'video_url') }}"
          subdir: "front_door"
          filename: "latest.mp4"
          overwrite: true
      # - action: shell_command.copy_doorbell_footage
      #   data: {}
    mode: queued
    max: 10
  # region Camera
  - id: "1720276673719"
    alias: "Front Garden: Vehicle Detected On Driveway"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.driveway_vehicle_detected
        from: "off"
        to: "on"
    conditions: []
    actions:
      - action: camera.snapshot
        metadata: {}
        data:
          filename: "{{ states('input_text.driveway_vehicle_latest_image_path') }}/vehicle_latest.jpg"
        target:
          entity_id: camera.driveway_high_resolution_channel
      - action: gpt4vision.image_analyzer
        data:
          provider: Ollama
          max_tokens: 100
          target_width: 3840
          model: llava
          detail: high
          temperature: 0.1
          include_filename: false
          message: Is there a Tesco van Ignoring all other vehicles found. Answer with yes or no.
          image_file: "{{ states('input_text.driveway_vehicle_latest_image_path') }}/vehicle_latest.jpg"
        response_variable: ai
      - action: script.send_home_log_with_local_attachments
        data:
          message: "{{ ai.response_text }}"
          title: Vehicle Detected
          filePath: "{{ states('input_text.driveway_vehicle_latest_image_path') }}/vehicle_latest.jpg"
          people:
            entity_id:
              - person.danny
    mode: single
  # region Light
  - id: "1660894232444"
    alias: "Front Garden: Below Direct Sun Light"
    description: ""
    triggers:
      - trigger: numeric_state
        entity_id: sensor.front_garden_motion_illuminance
        for:
          hours: 0
          minutes: 10
          seconds: 0
        below: input_number.close_blinds_brightness_threshold
    conditions:
      - condition: state
        entity_id: sensor.season
        state: "summer"
    actions:
      - action: script.send_to_home_log
        data:
          message:
            Sun light has fallen below {{ states('input_number.close_blinds_brightness_threshold')
            }} ({{ states('sensor.front_garden_motion_illuminance', with_unit=True)
            }}). Opening office blinds/curtains.
          title: 🌳Front Garden
          log_level: "Normal"
      - action: cover.set_cover_position
        data:
          position: 25
        target:
          entity_id: cover.office_blinds
      - if:
          - condition: numeric_state
            entity_id: cover.bedroom_blinds
            attribute: current_position
            below: input_number.blind_closed_position_threshold
          - condition: sun
            before: sunset
          - condition: state
            entity_id: binary_sensor.bedroom_tv_powered_on
            state: "off"
        then:
          - action: cover.open_cover
            target:
              entity_id: cover.bedroom_blinds
      - if:
          - condition: numeric_state
            entity_id: cover.ashlees_bedroom_blinds
            attribute: current_position
            below: input_number.blind_closed_position_threshold
          - condition: time
            before: input_datetime.childrens_bed_time
        then:
          - action: cover.open_cover
            target:
              entity_id: cover.ashlees_bedroom_blinds
    mode: single
  # region Lockbox
  - id: "1714914120928"
    alias: "Front Garden: Lock Box State Changed"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.outdoor_lock_box_contact
        not_from:
          - "unknown"
          - "unavailable"
        not_to:
          - "unknown"
          - "unavailable"
      - trigger: state
        entity_id:
          - binary_sensor.outdoor_lock_box_contact
        not_from:
          - "unknown"
          - "unavailable"
        to:
          - "unknown"
          - "unavailable"
        for:
          hours: 0
          minutes: 1
          seconds: 0
    conditions: []
    actions:
      - action: script.send_direct_notification
        metadata: {}
        data:
          title: Lock Box
          message: Was {{ states('binary_sensor.outdoor_lock_box_contact') }}
          people:
            entity_id:
              - person.danny
              - person.terina
    mode: single
  - id: "1718364408150"
    alias: "Front Garden: Lockbox Sensor Disconnected"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.outdoor_lock_box_contact
        to: unavailable
        for:
          hours: 0
          minutes: 5
          seconds: 0
    conditions: []
    actions:
      - action: script.send_direct_notification
        metadata: {}
        data:
          message: Lockbox sensor has disconnected.
          people:
            entity_id:
              - person.danny
    mode: single
  - id: "1761115884229"
    alias: "Front Garden: Electricity Meter Door Opened"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.electricity_meter_door_contact
        to: "on"
    conditions: []
    actions:
      - action: script.send_direct_notification
        metadata: {}
        data:
          suppress_if_quiet: true
          message: Electricity meter door open
          title: Front Garden
          people:
            entity_id:
              - person.danny
              - person.terina
          priority: normal
    mode: single

shell_command:
  copy_doorbell_footage: >-
    cp {{ states('input_text.camera_internal_folder_path') }}'/front_door/latest.mp4'
    {{ states('input_text.camera_internal_folder_path') }}'/front_door/'{{ state_attr('camera.front_door', 'friendly_name') }}_{{ as_timestamp(now())|timestamp_custom('%Y-%m-%d_%H%M%S') }}'.mp4'
