# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1613924044189"
    alias: "^Front Garden: Doorbell Pressed"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door_ding
        from: "off"
        to: "on"
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          title: Ding Dong
          message: ":door: :bell: Someone is has rung the door bell."
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.wait_for_doorbell_camera_update
    mode: single
  - id: "1621070004545"
    alias: "^Front Garden: Doorbell Camera Updated"
    description: ""
    trigger:
      - platform: state
        entity_id: camera.front_door
    condition:
      - condition: template
        value_template:
          "{{ state_attr('camera.front_door', 'last_video_id') | string
          != states('input_text.doorbell_last_video_id') | string}}"
    action:
      - service: script.front_garden_door_bell_camera_process_image
        data:
          title: Doorbell Picture updated
          message: ":door: :bell: Doorbell photo updated"
    mode: queued
    max: 10
  - id: "1584089698583"
    alias: "^Front Garden: Doorbell Battery Low"
    description: ""
    trigger:
      - entity_id: sensor.front_doorbell_battery
        platform: state
        to: "10"
    condition: []
    action:
      - data:
          message: ":warning: :battery: Conservatory motion sensor is low on battery"
        service: script.post_to_home_log
    mode: single
  - id: "1584089831265"
    alias: "^Front Garden: Doorbell Battery Critically Low"
    description: ""
    trigger:
      - entity_id: sensor.front_doorbell_battery
        platform: state
        to: "5"
    condition: []
    action:
      - data:
          message:
            ":warning: :battery: Conservatory motion sensor is critically low on
            battery"
        service: script.post_to_home_log
    mode: single
  # Motion
  - id: "1613482098461"
    alias: "^Front Garden: Motion Detected"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.front_garden_motion
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.enable_front_garden_motion_trigger
        state: "on"
    action:
      - service: script.driveway_camera_process_objects
        data:
          title: Front Door Bell Snapshot
          message: Motion Detected In Front Garden
    mode: queued
    max: 10
input_boolean:
  enable_front_door_trigger:
    name: Enable front door sensor
    icon: mdi:door-open
  enable_front_garden_motion_trigger:
    name: Enable motion trigger for front garden
    icon: mdi:motion-sensor
