# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1613924044189"
    alias: "Front Garden: Doorbell Pressed"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door_ding
        from: "off"
        to: "on"
    condition: []
    action:
      - parallel:
          - service: script.send_direct_notification
            data:
              title: Ding Dong
              message: ":door: :bell: Someone is has rung the door bell."
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.wait_for_doorbell_camera_update
    mode: single
  - id: "1621070004545"
    alias: "Front Garden: Doorbell Camera Updated"
    description: ""
    trigger:
      - platform: state
        entity_id: camera.front_door
    condition:
      - condition: template
        value_template:
          "{{ state_attr('camera.front_door', 'last_video_id') | string
          != states('input_text.doorbell_last_video_id') | string}}"
    action:
      # Bug: https://github.com/home-assistant/home-assistant.io/issues/21599
      - service: downloader.download_file
        data:
          url: "{{ state_attr('camera.front_door', 'video_url') }}"
          subdir: "front_door"
          filename: "{{state_attr('camera.front_door', 'friendly_name')}}.mp4"
    mode: queued
    max: 10
  - id: "1584089698583"
    alias: "Front Garden: Doorbell Battery Low"
    description: ""
    trigger:
      - entity_id: sensor.front_doorbell_battery
        platform: state
        to: "10"
    condition: []
    action:
      - data:
          message: ":warning: :battery: Conservatory motion sensor is low on battery"
        service: script.send_to_home_log
    mode: single
  - id: "1584089831265"
    alias: "Front Garden: Doorbell Battery Critically Low"
    description: ""
    trigger:
      - entity_id: sensor.front_doorbell_battery
        platform: state
        to: "5"
    condition: []
    action:
      - data:
          message:
            ":warning: :battery: Conservatory motion sensor is critically low on
            battery"
        service: script.send_to_home_log
    mode: single
  # Motion
  - id: "1629147974029"
    alias: "Front Garden: Person Detected"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.road_person_motion
        from: "off"
        to: "on"
        id: road
      - platform: state
        entity_id: binary_sensor.shared_driveway_person_motion
        id: shared_driveway
        from: "off"
        to: "on"
      - platform: state
        entity_id: binary_sensor.front_garden_person_motion
        id: front_garden
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: switch.driveway_detect
        state: "on"
    action:
      - service: camera.snapshot
        data_template:
          filename:
            "{{ states('input_text.latest_frigate_driveway_person_file_path')
            }}"
        target:
          entity_id: camera.driveway_person
      - choose:
          - conditions:
              - condition: trigger
                id: front_garden
            sequence:
              - service: script.send_home_log_with_local_attachments
                data_template:
                  title: Person detected in the front garden
                  message: Frigate detected a person in the front garden.
                  filePath:
                    "{{ states('input_text.latest_frigate_driveway_person_file_path')
                    }}"
          - conditions:
              - condition: trigger
                id: shared_driveway
            sequence:
              - service: script.send_home_log_with_local_attachments
                data_template:
                  title: Person detected in the shared driveway
                  message: Frigate detected a person in the shared driveway.
                  filePath:
                    "{{ states('input_text.latest_frigate_driveway_person_file_path')
                    }}"
          - conditions:
              - condition: trigger
                id: general
            sequence:
              - service: script.send_home_log_with_local_attachments
                data_template:
                  title: Person detected in the road
                  message: Frigate detected a person in the road.
                  filePath:
                    "{{ states('input_text.latest_frigate_driveway_person_file_path')
                    }}"
        default: []
    mode: queued
    max: 10
  # Light levels
  - id: "1678300398735"
    alias: "Front Garden: Bright Outside"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.front_garden_motion_illuminance_lux
        above: input_number.blind_low_brightness_threshold
        for: "00:01:00"
    condition:
      - condition: sun
        after: sunrise
      - condition: time
        after: "08:00:30"
      - condition: sun
        before: sunset
      - condition: numeric_state
        entity_id: sensor.front_garden_motion_illuminance_lux
        below: input_number.blind_high_brightness_threshold
    action:
      - parallel:
          - alias: "Lounge blinds"
            choose:
              - conditions:
                  - condition: state
                    entity_id: input_boolean.enable_lounge_blind_automations
                    state: "on"
                  - condition: numeric_state
                    entity_id: sun.sun
                    attribute: azimuth
                    above: input_number.office_blinds_afternoon_sun_azimuth_threshold
                  - condition: numeric_state
                    entity_id: sun.sun
                    attribute: elevation
                    above: input_number.office_blinds_sun_elevation_threshold
                sequence:
                  - service: script.send_to_home_log
                    data:
                      message: >-
                        Skipping closing blinds because afternoon :sun: sun is out of the way.

                        Azimuth: {{ state_attr('sun.sun', 'azimuth') }} ({{ states('input_number.lounge_blinds_afternoon_sun_azimuth_threshold')}}).

                        Elevation: {{ state_attr('sun.sun', 'elevation') }} ({{ states('input_number.lounge_blinds_sun_elevation_threshold')}}).
                      title: ":couch_and_lamp: Lounge"
              - conditions:
                  - condition: state
                    entity_id: input_boolean.enable_lounge_blind_automations
                    state: "on"
                  - condition: state
                    entity_id: binary_sensor.lounge_windows
                    state: "off"
                  - or:
                      - not:
                          - condition: state
                            entity_id: cover.lounge_blinds_middle
                            attribute: current_tilt_position
                            state: "25"
                      - not:
                          - condition: state
                            entity_id: cover.lounge_blinds_right
                            attribute: current_tilt_position
                            state: "25"
                  - or:
                      - condition: state
                        entity_id: group.family_computer
                        state: "home"
                      - alias: Only account for laptop during weekdays
                        and:
                          - condition: time
                            weekday:
                              - mon
                              - tue
                              - wed
                              - thu
                              - fri
                          - condition: state
                            entity_id: group.terinas_work_computer
                            state: "home"
                sequence:
                  - parallel:
                      - service: script.send_to_home_log
                        data:
                          message: >-
                            It's bright outside ({{ states('sensor.front_garden_motion_illuminance_lux', with_unit=True) }}).
                            Partially closing middle and right blinds.
                          title: ":couch_and_lamp: Lounge"
                      - service: cover.set_cover_tilt_position
                        data:
                          tilt_position: 25
                        target:
                          entity_id:
                            - cover.lounge_blinds_middle
                            - cover.lounge_blinds_right
            default: []
    mode: single
  - id: "1678300398734"
    alias: "Front Garden: Really Bright Outside"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.front_garden_motion_illuminance_lux
        above: input_number.blind_high_brightness_threshold
        for: "00:01:00"
    condition:
      - condition: sun
        after: sunrise
      - condition: time
        after: "08:00:30"
      - condition: sun
        before: sunset
    action:
      - parallel:
          - alias: "Lounge blinds"
            choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: sun.sun
                    attribute: azimuth
                    above: input_number.office_blinds_afternoon_sun_azimuth_threshold
                  - condition: numeric_state
                    entity_id: sun.sun
                    attribute: elevation
                    above: input_number.office_blinds_sun_elevation_threshold
                sequence:
                  - service: script.send_to_home_log
                    data:
                      message: >-
                        Skipping closing blinds because afternoon :sun: sun is out of the way.

                        Azimuth: {{ state_attr('sun.sun', 'azimuth') }} > {{ states('input_number.lounge_blinds_afternoon_sun_azimuth_threshold') }}

                        Elevation: {{ state_attr('sun.sun', 'elevation') }} > {{ states('input_number.lounge_blinds_sun_elevation_threshold') }}
                      title: ":couch_and_lamp: Lounge"
              - conditions:
                  - condition: state
                    entity_id: input_boolean.enable_lounge_blind_automations
                    state: "on"
                  - condition: state
                    entity_id: binary_sensor.lounge_windows
                    state: "off"
                  - or:
                      - condition: numeric_state
                        entity_id: cover.lounge_blinds_middle
                        attribute: current_tilt_position
                        above: 0
                      - condition: numeric_state
                        entity_id: cover.lounge_blinds_right
                        attribute: current_tilt_position
                        above: 0
                  - or:
                      - condition: state
                        entity_id: group.family_computer
                        state: "home"
                      - alias: Only account for laptop during weekdays
                        and:
                          - condition: time
                            weekday:
                              - mon
                              - tue
                              - wed
                              - thu
                              - fri
                          - condition: state
                            entity_id: group.terinas_work_computer
                            state: "home"
                sequence:
                  - parallel:
                      - service: script.send_to_home_log
                        data:
                          message: >-
                            It's really bright outside ({{ states('sensor.front_garden_motion_illuminance_lux', with_unit=True) }}).
                            Closing blinds.
                          title: ":couch_and_lamp: Lounge"
                      - service: cover.set_cover_tilt_position
                        data:
                          tilt_position: 0
                        target:
                          entity_id:
                            - cover.lounge_blinds_middle
                            - cover.lounge_blinds_right
            default: []
    mode: single
  - id: "1678637987423"
    alias: "Front Garden: Outside Went Darker"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.front_garden_motion_illuminance_lux
        for:
          hours: 0
          minutes: 5
          seconds: 0
        below: input_number.blind_low_brightness_threshold
    condition:
      - condition: sun
        after: sunrise
      - condition: time
        after: "08:00:30"
      - condition: sun
        before: sunset
    action:
      - parallel:
          - alias: "Lounge blinds"
            choose:
              - conditions:
                  - condition: state
                    entity_id: input_boolean.enable_lounge_blind_automations
                    state: "on"
                  - condition: state
                    entity_id: binary_sensor.lounge_windows
                    state: "off"
                  - or:
                      - condition: numeric_state
                        entity_id: cover.lounge_blinds_left
                        attribute: current_tilt_position
                        below: 50
                      - condition: numeric_state
                        entity_id: cover.lounge_blinds_right
                        attribute: current_tilt_position
                        below: 50
                      - condition: numeric_state
                        entity_id: cover.lounge_blinds_middle
                        attribute: current_tilt_position
                        below: 50
                sequence:
                  - parallel:
                      - service: script.send_to_home_log
                        data:
                          message: >-
                            It is not as bright outside ({{ states('sensor.front_garden_motion_illuminance_lux', with_unit=True) }}).
                            Opening Blinds
                          title: ":couch_and_lamp: Lounge"
                      - service: cover.set_cover_tilt_position
                        data:
                          tilt_position: 50
                        target:
                          entity_id:
                            - cover.lounge_blinds_left
                            - cover.lounge_blinds_middle
                            - cover.lounge_blinds_right
            default: []
    mode: single

script:
  front_garden_motion_notification:
    alias: Front Garden Motion Notification
    sequence:
      - repeat:
          count: "4"
          sequence:
            - service: scene.turn_on
              target:
                entity_id: scene.office_front_garden_motion_notification
            - delay:
                hours: 0
                minutes: 0
                seconds: 1
                milliseconds: 0
            - service: scene.turn_on
              target:
                entity_id: scene.office_turn_off_light_notification
    mode: single
  front_garden_turn_off_camera:
    alias: Front Garden Turn Off Camera
    sequence:
      - service: switch.turn_off
        target:
          entity_id:
            - switch.driveway_detect
            - switch.driveway_snapshots
    mode: single
    icon: mdi:cctv
  front_garden_turn_on_camera:
    alias: Front Garden Turn On Camera
    sequence:
      - service: switch.turn_on
        target:
          entity_id:
            - switch.driveway_detect
            - switch.driveway_snapshots
    mode: single
    icon: mdi:cctv
