# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1583797341647"
    alias: "^Kitchen: Turn Off Lights At Night"
    description: ""
    trigger:
      - at: "23:30:00"
        platform: time
    condition:
      - condition: state
        entity_id: group.kitchen_lights
        state: "on"
    action:
      - service: script.post_to_home_log
        data:
          message: ":clock{{ now().strftime('%I') | int }}{% if now().minute | int > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :bulb: Turning off kitchen lights"
      - scene: scene.kitchen_lights_on_3
    mode: single
  - id: "1606652871369"
    alias: "^Kitchen: No Motion During"
    description: ""
    trigger:
      - platform: state
        to: "off"
        for: 00:05:00
        entity_id: group.kitchen_motion
        id: first_no_motion
      - platform: state
        to: "off"
        for: 00:10:00
        entity_id: group.kitchen_motion
        id: second_no_motion
    condition: []
    action:
      - choose:
          - conditions:
              - condition: time
                after: "00:00:00"
              - condition: sun
                before: sunset
            sequence:
              - service: script.post_to_home_log
                data:
                  message: >-
                    :no_pedestrians: No motion detected after :city_sunrise: and before
                    :city_sunset: Turning kitchen all lights off.
              - scene: scene.kitchen_lights_on_3
          - conditions:
              - condition: and
                conditions:
                  - condition: sun
                    before: sunset
                  - condition: time
                    after: "23:30:00"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":no_pedestrians: No motion detected after :city_sunrise: and before
                    :city_sunset: Turning kitchen lights off (1)."
              - scene: scene.kitchen_lights_on_3
        default: []
      - choose:
          - conditions:
              - condition: time
                after: "00:00:00"
              - condition: sun
                before: sunset
              - condition: trigger
                id: first_no_motion
            sequence:
              - service: script.post_to_home_log
                data:
                  message: >-
                    :no_pedestrians: No motion detected after :city_sunrise: and before
                    :city_sunset: Turning main kitchen lights off.
              - scene: scene.kitchen_main_lights_off
          - conditions:
              - condition: and
                conditions:
                  - condition: sun
                    after: sunset
                  - condition: time
                    before: "23:59:59"
                  - condition: trigger
                    id: first_no_motion
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":no_pedestrians: No motion detected after :city_sunset: and before
                    :city_sunrise: Dimming kitchen main lights."
              - scene: scene.kitchen_main_lights_dim
          - conditions:
              - condition: and
                conditions:
                  - condition: sun
                    after: sunset
                  - condition: time
                    before: "23:59:59"
                  - condition: trigger
                    id: second_no_motion
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":no_pedestrians: No motion detected after :city_sunset: and before
                    :city_sunrise: Turning kitchen main lights off."
              - scene: scene.kitchen_main_lights_off
        default: []
    mode: single
  - id: "1606294735952"
    alias: "^Kitchen: Turn Off Lights In The Morning"
    description: ""
    trigger:
      - platform: time
        at: 09:00:00
        id: weekend
      - platform: time
        at: 08:50:00
        id: weekday
    condition:
      - condition: time
        weekday:
          - sat
          - sun
      - condition: state
        entity_id: group.kitchen_lights
        state: "on"
    action:
      - choose:
          - conditions:
              - condition: time
                weekday:
                  - mon
                  - tue
                  - wed
                  - thu
                  - fri
              - condition: trigger
                id: weekday
            sequence:
              - service: script.post_to_home_log
                data:
                  message: ':clock{{ now().strftime("%I") | int }}{% if now().minute | int > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :bulb: Turning off kitchen lights'

              - scene: scene.kitchen_lights_on_3
          - conditions:
              - condition: time
                weekday:
                  - sat
                  - sun
              - condition: trigger
                id: weekend
            sequence:
              - service: script.post_to_home_log
                data:
                  message: ':clock{{ now().strftime("%H")}}: :bulb: Turning off kitchen lights'
              - scene: scene.kitchen_lights_on_3
        default: []
    mode: single
  - id: "1588197104336"
    alias: "^Kitchen: Timed Turn On Lights (Dim)"
    description: ""
    trigger:
      - event: sunset
        platform: sun
      - platform: time
        at: 06:45:00
    condition:
      - condition: and
        conditions:
          - condition: not
            conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: Guest
          - condition: state
            entity_id: group.all_people
            state: home
    action:
      - scene: scene.kitchen_dim_kitchen_lights
      - data:
          message: ":bulb: :low_brightness: At least one person is home. Turning on kitchen lights on dim setting."
        service: script.post_to_home_log
    mode: single
  - id: "1606158191302"
    alias: "^Kitchen: Motion Detected"
    description: ""
    trigger:
      - platform: state
        entity_id: group.kitchen_motion
        to: "on"
    condition: []
    action:
      - choose:
          - conditions:
              - condition: or
                conditions:
                  - condition: numeric_state
                    entity_id: sensor.kitchen_motion_light_level
                    below: "25"
                  - condition: numeric_state
                    entity_id: sensor.kitchen_motion_2_light_level
                    below: "50"
              - condition: or
                conditions:
                  - condition: numeric_state
                    entity_id: light.kitchen_left
                    attribute: brightness
                    below: "100"
                  - condition: numeric_state
                    entity_id: light.kitchen_left_2
                    attribute: brightness
                    below: "100"
                  - condition: numeric_state
                    entity_id: light.kitchen_middle
                    attribute: brightness
                    below: "100"
                  - condition: numeric_state
                    entity_id: light.kitchen_middle_2
                    attribute: brightness
                    below: "100"
                  - condition: numeric_state
                    entity_id: light.kitchen_right
                    attribute: brightness
                    below: "100"
                  - condition: numeric_state
                    entity_id: light.kitchen_right_2
                    attribute: brightness
                    below: "100"
                  - condition: template
                    value_template: "{{ state_attr('light.kitchen_left', 'brightness') == none }}"
                  - condition: template
                    value_template: "{{ state_attr('light.kitchen_left_2', 'brightness') == none }}"
                  - condition: template
                    value_template: "{{ state_attr('light.kitchen_middle', 'brightness') == none }}"
                  - condition: template
                    value_template: "{{ state_attr('light.kitchen_middle_2', 'brightness') == none }}"
                  - condition: template
                    value_template: "{{ state_attr('light.kitchen_right', 'brightness') == none }}"
                  - condition: template
                    value_template: "{{ state_attr('light.kitchen_right_2', 'brightness') == none }}"
            sequence:
              - service: script.post_to_home_log
                data:
                  data:
                    message: >-
                      :paw_prints: :bulb: :high_brightness: Motion detected in the
                      kitchen and it's dark ({{ states('sensor.kitchen_motion_light_level') }} & {{
                      states('sensor.kitchen_motion_2_light_level') }} lux < 25 & 50). Turning
                      main lights on to full brightness.
              - scene: scene.kitchen_main_lights_on
        default: []
      - choose:
          - conditions:
              - condition: or
                conditions:
                  - condition: numeric_state
                    entity_id: light.kitchen_cabinet_light
                    attribute: brightness
                    below: "100"
                  - condition: numeric_state
                    entity_id: light.kitchen_down_light
                    attribute: brightness
                    below: "100"
                  - condition: numeric_state
                    entity_id: light.kitchen_drawers
                    attribute: brightness
                    below: "100"
                  - condition: template
                    value_template: "{{ state_attr('light.kitchen_cabinet_light', 'brightness') == none }}"
                  - condition: template
                    value_template: "{{ state_attr('light.kitchen_down_light', 'brightness') == none }}"
                  - condition: template
                    value_template: "{{ state_attr('light.kitchen_drawers', 'brightness') == none }}"
            sequence:
              - service: script.post_to_home_log
                data:
                  data:
                    message: >-
                      :paw_prints: :bulb: :high_brightness: Motion detected in the
                      kitchen. Turning side lights on to full brightness.
              - scene: scene.kitchen_lights_on_2
        default: []
    mode: single
  - id: "1606158459561"
    alias: "^Kitchen: No Motion In The Evening After 5 Minutes"
    description: ""
    trigger:
      - platform: state
        to: "off"
        for: 00:05:00
        entity_id: group.kitchen_motion
    condition:
      - condition: sun
        after: sunset
      - condition: time
        before: "23:30:00"
    action:
      - service: script.post_to_home_log
        data:
          message: ":no_pedestrians: :bulb: :low_brightness: No motion detected after :city_sunset: and before :clock1130: Dimming kitchen lights."
      - scene: scene.kitchen_dim_kitchen_lights
      - scene: scene.kitchen_main_lights_off
    mode: single
  - id: "1606158610314"
    alias: "^Kitchen: Turn Off Lights"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_motion
        to: "off"
        for: 00:05:00
    condition:
      - condition: time
        after: "23:30"
      - condition: sun
        before: sunset
    action:
      - scene: scene.kitchen_lights_on_3
      - service: script.post_to_home_log
        data:
          message: ':no_pedestrians: :clock{{ now().strftime("%I") | int }}{% if now().minute | int > 25 and now().minute | int < 35 %} 30 {% else %} {% endif %}: No motion in the kitchen after 23:30. Turning lights off.'
    mode: single
  - id: "1619356833117"
    alias: "^Kitchen: Turn Off Coffee Machine"
    description: ""
    trigger:
      - platform: state
        entity_id: switch.coffee_machine
        from: "off"
        to: "on"
        for: 00:30:00
    condition:
      - condition: state
        entity_id: input_boolean.enable_coffee_machine_automations
        state: "on"
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":coffee: Coffee machine has been on for 30 minutes. Turning off coffee
            machine."
      - service: switch.turn_off
        target:
          entity_id: switch.coffee_machine
    mode: single
group:
  kitchen_lights:
    name: Kitchen Lights
    icon: mdi:string-lights
    entities:
      - light.kitchen_down_light
      - light.kitchen_cabinet_light
      - light.kitchen_drawers
      - light.kitchen_left
      - light.kitchen_left_2
      - light.kitchen_middle
      - light.kitchen_middle_2
      - light.kitchen_right
      - light.kitchen_right_2
  kitchen_main_lights:
    name: Kitchen Main Lights
    icon: mdi:string-lights
    entities:
      - light.kitchen_left
      - light.kitchen_left_2
      - light.kitchen_middle
      - light.kitchen_middle_2
      - light.kitchen_right
      - light.kitchen_right_2
  kitchen_motion:
    name: Kitchen Motion
    icon: mdi:walk
    entities:
      - binary_sensor.kitchen_motion
      - binary_sensor.kitchen_motion_2
  kitchen_side_lights:
    name: Kitchen Side Lights
    icon: mdi:string-lights
    entities:
      - light.kitchen_down_light
      - light.kitchen_cabinet_light
      - light.kitchen_drawers
input_boolean:
  enable_coffee_machine_automations:
    name: Enable coffee machine automations
    icon: mdi:coffee-maker
  enable_kitchen_motion_trigger:
    name: Enable motion trigger for kitchen
    icon: mdi:motion-sensor
sensor:
  # Aggregated stats
  - platform: min_max
    name: Kitchen Area Light Level
    entity_ids:
      - sensor.kitchen_motion_light_level
      - sensor.kitchen_motion_2_light_level
    type: mean
  - platform: min_max
    name: Kitchen Area Temperature
    entity_ids:
      - sensor.kitchen_motion_temperature
      - sensor.kitchen_motion_2_temperature
    type: mean
