# Created by Danny Tsang <danny@tsang.uk>
automation:
  # Lights related automation.
  - id: "1583956425622"
    alias: "^Lounge: Dark And Motion Detected"
    description: Added a second delay https://community.home-assistant.io/t/hue-motion-sensor-with-illuminance-condition/128290
    trigger:
      - entity_id: group.lounge_motion
        platform: state
        to: "on"
        from: "off"
      - platform: state
        entity_id: binary_sensor.lounge_motion
        to: "on"
      - platform: state
        entity_id: binary_sensor.lounge_motion_2
        to: "on"
      - platform: state
        entity_id: binary_sensor.lounge_motion_3
        to: "on"
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.enable_lounge_motion_trigger
            state: "on"
          - condition: or
            conditions:
              - below: "30"
                condition: numeric_state
                entity_id: sensor.lounge_motion_2_light_level
              - below: "25"
                condition: numeric_state
                entity_id: sensor.lounge_motion_3_light_level
          - condition: or
            conditions:
              - condition: numeric_state
                entity_id: light.lounge_left_lamp
                attribute: brightness
                below: "190"
              - condition: numeric_state
                entity_id: light.lounge_right_lamp
                attribute: brightness
                below: "190"
              - condition: template
                value_template:
                  "{{ state_attr('light.lounge_left_lamp', 'brightness')
                  == none }}"
              - condition: template
                value_template:
                  "{{ state_attr('light.lounge_right_lamp', 'brightness')
                  == none }}"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: device_tracker.lap_ctc0501
                state: home
              - condition: or
                conditions:
                  - below: "81"
                    condition: numeric_state
                    entity_id: sensor.lounge_motion_2_light_level
                  - below: "65"
                    condition: numeric_state
                    entity_id: sensor.lounge_motion_3_light_level
            sequence:
              - data:
                  message:
                    ":paw_prints: :computer: :bulb: :high_brightness: Motion detected
                    in the lounge, it's dark ({{ states('sensor.lounge_motion_2_light_level')
                    }} & {{ states('sensor.lounge_motion_3_light_level') }} lux < 20-25
                    lux) and Terina''s work computer is on. Turning lounge lights on."
                service: script.post_to_home_log
              - service: scene.turn_on
                target:
                  entity_id: scene.lounge_lights
          - conditions:
              - condition: or
                conditions:
                  - below: "25"
                    condition: numeric_state
                    entity_id: sensor.lounge_motion_2_light_level
                  - below: "30"
                    condition: numeric_state
                    entity_id: sensor.lounge_motion_3_light_level
            sequence:
              - data:
                  message:
                    ":paw_prints: :bulb: :high_brightness: Motion detected in the lounge
                    and it's dark ({{ states('sensor.lounge_motion_2_light_level') }} &
                    {{ states('sensor.lounge_motion_3_light_level') }} lux < 20-25 lux).
                    Turning lounge lights on."
                service: script.post_to_home_log
              - service: scene.turn_on
                target:
                  entity_id: scene.lounge_lights
        default: []
    mode: queued
    max: 10
  - id: "1606170045630"
    alias: "^Lounge: No Motion After 5 Minutes And TV Is Off Dim Lights"
    description: ""
    trigger:
      - platform: state
        entity_id: group.lounge_motion
        to: "off"
        for: 00:05:00
    condition:
      - condition: state
        entity_id: input_boolean.enable_lounge_motion_trigger
        state: "on"
      - condition: numeric_state
        entity_id: sensor.tv_plug_power_meter
        below: "10"
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":no_pedestrians: :bulb: :low_brightness: No motion detected and :tv:TV
            is turned off in the lounge for 5 minutes. Dimming lights"
      - service: scene.turn_on
        target:
          entity_id: scene.lounge_dim_lights
        data:
          transition: 2
    mode: single
  - id: "1605567425876"
    alias: "^Lounge: No Motion After 10 Minutes"
    description: ""
    trigger:
      - platform: state
        entity_id: group.lounge_motion
        from: "on"
        to: "off"
        for: 00:10:00
    condition:
      - condition: state
        entity_id: input_boolean.enable_lounge_motion_trigger
        state: "on"
      - condition: numeric_state
        entity_id: sensor.tv_plug_power_meter
        below: "10"
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":no_pedestrians: No motion detected in the lounge for 10 minutes and
            :tv:TV is turned off. Turning lounge :bulb: lights off."
      - service: scene.turn_on
        target:
          entity_id: scene.lounge_lights_off
        data:
          transition: 2
    mode: single
  - id: "1588859622571"
    alias: "^Lounge: Motion Detected In The Morning"
    description: ""
    trigger:
      - entity_id: binary_sensor.lounge_motion
        platform: state
        to: "on"
      - entity_id: binary_sensor.stairs_motion
        platform: state
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.enable_morning_routine
        state: "on"
      - condition: state
        entity_id: group.adult_people
        state: home
      - condition: state
        entity_id: alarm_control_panel.stevenage_alarm
        state: armed_home
    action:
      - data: {}
        service: script.morning_script
    mode: single
  - id: "1610918759041"
    alias: "^Lounge: Restart Harmony Hub"
    description: ""
    trigger:
      - platform: time
        at: 03:00:00
    condition:
      - condition: time
        weekday:
          - mon
      - condition: state
        entity_id: binary_sensor.tv_powered_on
        state: "off"
    action:
      - service: script.post_to_home_log
        data:
          message: ":TV: Restarting Harmony hub."
      - service: switch.turn_off
        target:
          entity_id: switch.harmony_hub_plug
      - delay:
          hours: 0
          minutes: 1
          seconds: 0
          milliseconds: 0
      - service: switch.turn_on
        target:
          entity_id: switch.harmony_hub_plug
    mode: single
  - id: "1610388245160"
    alias: "^Lounge: TV Turned Off"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.tv_plug_power_meter
        below: "35"
        for: 00:05:00
    condition:
      - condition: state
        entity_id: group.lounge_lights
        state: "on"
      - condition: state
        entity_id: group.lounge_motion
        state: "off"
      - condition: template
        value_template:
          " {{ (as_timestamp(now())-as_timestamp(states.group.lounge_motion.last_updated))
          > 300 }}"
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":bulb: :low_brightness: TV turned off for 5 minutes. Dimming lounge
            lights."
      - service: scene.turn_on
        target:
          entity_id: scene.lounge_dim_lights
        data:
          transition: 2
    mode: single
  - id: "1610409803685"
    alias: "^Lounge: TV Turned Off"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.tv_plug_power_meter
        for: 00:10:00
        below: "35"
    condition:
      - condition: state
        entity_id: group.lounge_lights
        state: "on"
      - condition: state
        entity_id: group.lounge_motion
        state: "off"
      - condition: template
        value_template:
          " {{ (as_timestamp(now())-as_timestamp(states.group.lounge_motion.last_updated))
          > 300 }}"
    action:
      - service: script.post_to_home_log
        data:
          message: TV turned off for 10 minutes. Turning lounge lights off.
      - service: scene.turn_on
        target:
          entity_id: scene.lounge_lights_off
        data:
          transition: 2
    mode: single
  # Bay Window
  - id: "1608493783373"
    alias: "^Lounge: Bay Window High Temperature"
    description: ""
    trigger:
      - platform: event
        event_type: ifttt_webhook_received
        event_data:
          action: bay_window_high_temp
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":warning: :thermometer: Bay window is above 35c. Turning server fan
            on."
      - service: switch.turn_on
        target:
          entity_id: switch.server_fan
    mode: single
  - id: "1608493853210"
    alias: "^Lounge: Bay Window Below High Temperature"
    description: ""
    trigger:
      - platform: event
        event_type: ifttt_webhook_received
        event_data:
          action: bay_window_low_temp
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":thermometer: :snowflake: Bay window below high temperature. Turning
            server fan off."
      - service: switch.turn_off
        target:
          entity_id: switch.server_fan

    mode: single
  - id: "1611063957341"
    alias: "^Lounge: Server Fan Running Longer Than 1 Hour"
    description: ""
    trigger:
      - platform: state
        entity_id: switch.server_fan
        to: "on"
        for: 01:00:00
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message:
            Server fan has been running for more than 1 hour. Consider turning
            Fan off.
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.enable_mobile_direct_notifications
                state: "on"
            sequence:
              - service: notify.mobile_app_dannys_phone
                data:
                  message: Turn off server fan?
                  data:
                    actions:
                      - title: "Yes"
                        action: server_fan_off
                      - title: "No"
                        action: ignore
                  title: Server fan on for over 1 hour
        default: []
    mode: single
  # Camera
  - id: "1630015457540"
    alias: "^Lounge: Person Detected"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.lounge_camera_person_motion
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: switch.lounge_camera_detect
        state: "on"
    action:
      - service: camera.snapshot
        data_template:
          filename:
            "{{ states('input_text.latest_frigate_lounge_person_file_path')
            }}"
        target:
          entity_id: camera.lounge_camera_person
      - service: script.post_to_home_log_with_local_attachments
        data_template:
          title: Person detected in lounge
          message: Frigate detected a person in the lounge.
          filePath:
            "{{ states('input_text.latest_frigate_lounge_person_file_path')
            }}"
    mode: queued
    max: 10
  - id: "1631454174806"
    alias: "^Lounge: Door or Window Open"
    description: ""
    trigger:
      - platform: state
        entity_id: group.lounge_door_windows
        from: "off"
        to: "on"
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":door: :window: Lounge door/window opened. Turning on :carmera_with_flash:
            camera."
      - service: switch.turn_on
        target:
          entity_id:
            - switch.lounge_camera_detect
            - switch.lounge_camera_snapshots
    mode: single
  - id: "1631454249839"
    alias: "^Lounge: Door Or Windows Closed"
    description: ""
    trigger:
      - platform: state
        entity_id: group.lounge_door_windows
        from: "on"
        to: "off"
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":door: :window: All doors/windows closed in the lounge. 
          Turning :camera: camera off."
      - service: switch.turn_off
        target:
          entity_id:
            - switch.lounge_camera_detect
            - switch.lounge_camera_snapshots
    mode: single
binary_sensor:
  - platform: template
    sensors:
      tv_powered_on:
        value_template: "{{ states('sensor.tv_plug_power_meter') | float > 45 }}"
        friendly_name: "TV Powered On"
        device_class: "power"
        icon_template: "mdi:television-classic{{ '' if states('sensor.tv_plug_power_meter') | float > 45 else '-off' }}"
      sky_powered_on:
        value_template: "{{ states('sensor.sky_power_meter') | float > 15 }}"
        friendly_name: "Sky Powered On"
        device_class: "power"
        icon_template: "mdi:television-classic{{ '' if states('sensor.sky_power_meter') | float > 15 else '-off' }}"
group:
  lounge_lights:
    name: Lounge Lights
    icon: mdi:floor-lamp
    entities:
      - light.lounge_left_lamp
      - light.lounge_right_lamp
  lounge_motion:
    name: Lounge Motion
    icon: mdi:walk
    entities:
      - binary_sensor.lounge_motion
      - binary_sensor.lounge_motion_2
      - binary_sensor.lounge_motion_3
  lounge_windows:
    name: Lounge Windows
    icon: mdi:window-closed
    entities:
      - binary_sensor.lounge_left_window
      - binary_sensor.lounge_middle_window
      - binary_sensor.lounge_right_window
  lounge_door_windows:
    name: Lounge Door and Windows
    icon: mdi:door
    entities:
      - binary_sensor.front_door
      - binary_sensor.lounge_left_window
      - binary_sensor.lounge_middle_window
      - binary_sensor.lounge_right_window
input_boolean:
  enable_lounge_motion_trigger:
    name: Enable motion trigger for lounge
    icon: mdi:motion-sensor
scene:
  - id: "1582387315374"
    name: Lounge Lights On
    entities:
      light.lounge_left_lamp:
        min_mireds: 111
        max_mireds: 400
        effect_list:
          - effect_colorloop
          - effect_pulse
          - effect_stop
        brightness: 240
        color_temp: 310
        friendly_name: Lounge Left Lamp
        icon: mdi:floor-lamp
        supported_features: 55
        state: "on"
      light.lounge_right_lamp:
        min_mireds: 111
        max_mireds: 400
        effect_list:
          - effect_colorloop
          - effect_pulse
          - effect_stop
        brightness: 240
        color_temp: 310
        friendly_name: Lounge Right Lamp
        icon: mdi:floor-lamp
        supported_features: 55
        state: "on"
  - id: "1606169827098"
    name: Lounge Dim Lights
    entities:
      light.lounge_left_lamp:
        min_mireds: 111
        max_mireds: 400
        effect_list:
          - effect_colorloop
          - effect_pulse
          - effect_stop
        brightness: 76
        color_temp: 285
        friendly_name: Lounge Left Lamp
        icon: mdi:floor-lamp
        supported_features: 55
        state: "on"
      light.lounge_right_lamp:
        min_mireds: 111
        max_mireds: 400
        effect_list:
          - effect_colorloop
          - effect_pulse
          - effect_stop
        brightness: 76
        color_temp: 285
        friendly_name: Lounge Right Lamp
        icon: mdi:floor-lamp
        supported_features: 55
        state: "on"
  - id: "1582455234238"
    name: Lounge Lights Off
    entities:
      light.lounge_right_lamp:
        min_mireds: 111
        max_mireds: 400
        effect_list:
          - effect_colorloop
          - effect_pulse
          - effect_stop
        friendly_name: Lounge Right Lamp
        icon: mdi:floor-lamp
        supported_features: 55
        state: "off"
      light.lounge_left_lamp:
        min_mireds: 111
        max_mireds: 400
        effect_list:
          - effect_colorloop
          - effect_pulse
          - effect_stop
        friendly_name: Lounge Left Lamp
        icon: mdi:floor-lamp
        supported_features: 55
        state: "off"
script:
  lounge_turn_off_camera:
    alias: Lounge Turn Off Camera
    sequence:
      - service: switch.turn_off
        target:
          entity_id:
            - switch.lounge_camera_detect
    mode: single
    icon: mdi:cctv
  lounge_turn_on_camera:
    alias: Lounge Turn On Camera
    sequence:
      - service: switch.turn_on
        target:
          entity_id:
            - switch.lounge_camera_detect
            - switch.lounge_camera_snapshots
    mode: single
    icon: mdi:cctv
sensor:
  # Aggregated stats
  - platform: min_max
    name: Lounge Area Light Level
    entity_ids:
      - sensor.lounge_motion_light_level
      - sensor.lounge_motion_2_light_level
    type: mean
  - platform: min_max
    name: Lounge Area Temperature
    entity_ids:
      - sensor.lounge_motion_temperature
      - sensor.lounge_motion_2_temperature
    type: mean
