# Created by Danny Tsang <danny@tsang.uk>
automation:
  # Lights related automation.
  - id: "1583956425622"
    alias: "^Lounge: Dark And Motion Detected"
    description: Added a second delay https://community.home-assistant.io/t/hue-motion-sensor-with-illuminance-condition/128290
    trigger:
      - entity_id: group.lounge_motion
        platform: state
        to: "on"
        from: "off"
      - platform: state
        entity_id: binary_sensor.lounge_motion
        to: "on"
      - platform: state
        entity_id: binary_sensor.lounge_motion_2
        to: "on"
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.enable_lounge_motion_trigger
            state: "on"
          - condition: or
            conditions:
              - below: "25"
                condition: numeric_state
                entity_id: sensor.lounge_motion_light_level
              - below: "20"
                condition: numeric_state
                entity_id: sensor.lounge_motion_2_light_level
          - condition: or
            conditions:
              - condition: numeric_state
                entity_id: light.lounge_left_lamp
                attribute: brightness
                below: "190"
              - condition: numeric_state
                entity_id: light.lounge_right_lamp
                attribute: brightness
                below: "190"
              - condition: template
                value_template: "{{ state_attr('light.lounge_left_lamp', 'brightness') == none }}"
              - condition: template
                value_template: "{{ state_attr('light.lounge_right_lamp', 'brightness') == none }}"
    action:
      - data:
          message:
            ":feet: :bulb: :high_brightness: Motion detected in the lounge and it's dark ({{ states('sensor.lounge_motion_light_level')
            }} & {{ states('sensor.lounge_motion_2_light_level') }} lux < 20-25 lux). Turning lounge
            lights on."
        service: script.post_to_home_log
      - scene: scene.lounge_lights
    mode: queued
    max: 10
  - id: "1606170045630"
    alias: "^Lounge: No Motion After 5 Minutes And TV Is Off Dim Lights"
    description: ""
    trigger:
      - platform: state
        entity_id: group.lounge_motion
        to: "off"
        for: 00:05:00
    condition:
      - condition: state
        entity_id: input_boolean.enable_lounge_motion_trigger
        state: "on"
      - condition: numeric_state
        entity_id: switch.tv_plug
        attribute: current_power_w
        below: "10"
    action:
      - scene: scene.lounge_dim_lights
      - service: script.post_to_home_log
        data:
          message:
            ":no_pedestrians: :bulb: :low_brightness: No motion detected and :tv:TV
            is turned off in the lounge for 5 minutes. Dimming lights"
    mode: single
  - id: "1605567425876"
    alias: "^Lounge: No Motion After 10 Minutes"
    description: ""
    trigger:
      - platform: state
        entity_id: group.lounge_motion
        to: "off"
        for: 00:10:00
    condition:
      - condition: state
        entity_id: input_boolean.enable_lounge_motion_trigger
        state: "on"
      - condition: numeric_state
        entity_id: switch.tv_plug
        attribute: current_power_w
        below: "10"
    action:
      - scene: scene.lounge_lights_off
      - service: script.post_to_home_log
        data:
          message:
            ":no_pedestrians: No motion detected in the lounge for 10 minutes and
            :tv:TV is turned off. Turning lounge :bulb: lights off."
    mode: single
  - id: "1588859622571"
    alias: "^Lounge: Motion Detected In The Morning"
    description: ""
    trigger:
      - entity_id: binary_sensor.lounge_motion
        platform: state
        to: "on"
      - entity_id: binary_sensor.stairs_motion
        platform: state
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.enable_morning_routine
        state: "on"
      - condition: state
        entity_id: group.all_people
        state: home
      - condition: state
        entity_id: alarm_control_panel.stevenage_alarm
        state: armed_home
    action:
      - data: {}
        service: script.1588857720303
    mode: single
  - id: "1610388245160"
    alias: "^Lounge: TV Turned Off"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: switch.tv_plug
        below: "35"
        attribute: current_power_w
        for: 00:05:00
    condition:
      - condition: state
        entity_id: group.lounge_lights
        state: "on"
      - condition: state
        entity_id: group.lounge_motion
        state: "off"
      - condition: template
        value_template:
          " {{ (as_timestamp(now())-as_timestamp(states.group.lounge_motion.last_updated))
          > 300 }}"
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":bulb: :low_brightness: TV turned off for 5 minutes. Dimming lounge
            lights."
      - scene: scene.lounge_dim_lights
    mode: single
  # Bay Window
  - id: "1608493783373"
    alias: "^Lounge: Bay Window High Temperature"
    description: ""
    trigger:
      - platform: event
        event_type: ifttt_webhook_received
        event_data:
          action: bay_window_high_temp
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":warning: :thermometer: Bay window is above 35c. Turning server fan
            on."
      - type: turn_on
        device_id: 15217f2c122d11eba01aa91aa4fd493d
        entity_id: switch.server_fan
        domain: switch
    mode: single
  - id: "1608493853210"
    alias: "^Lounge: Bay Window Below High Temperature"
    description: ""
    trigger:
      - platform: event
        event_type: ifttt_webhook_received
        event_data:
          action: bay_window_low_temp
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":thermometer: :snowflake: Bay window below high temperature. Turning
            server fan off."
      - type: turn_off
        device_id: 15217f2c122d11eba01aa91aa4fd493d
        entity_id: switch.server_fan
        domain: switch
    mode: single
binary_sensor:
  - platform: template
    sensors:
      tv_powered_on:
        value_template: "{{ state_attr('switch.tv_plug','current_power_w') | float > 45 }}"
        friendly_name: "TV Powered On"
        device_class: "power"
        icon_template: "mdi:television-classic{{ '' if state_attr('switch.tv_plug','current_power_w') | float > 45 else '-off' }}"
      sky_powered_on:
        value_template: "{{ state_attr('switch.sky_plug','current_power_w') | float > 15 }}"
        friendly_name: "Sky Powered On"
        device_class: "power"
        icon_template: "mdi:television-classic{{ '' if state_attr('switch.sky_plug','current_power_w') | float > 15 else '-off' }}"
group:
  lounge_windows:
    name: Lounge Windows
    icon: mdi:window-closed
    entities:
      - binary_sensor.lounge_left_window
      - binary_sensor.lounge_middle_window
      - binary_sensor.lounge_right_window
sensor:
  # Plug sensors to tell if it's turned on or not
  - platform: template
    sensors:
      tv_plug_current_w:
        value_template: "{{ state_attr('switch.tv_plug','current_power_w') | float }}"
        friendly_name: "TV current power"
        unit_of_measurement: "Wh"
        icon_template: mdi:flash
      sky_plug_current_w:
        value_template: "{{ state_attr('switch.sky_plug','current_power_w') | float }}"
        friendly_name: "Sky current power"
        unit_of_measurement: "Wh"
        icon_template: mdi:flash
  # Aggregated stats
  - platform: min_max
    name: Lounge Area Light Level
    entity_ids:
      - sensor.lounge_motion_light_level
      - sensor.lounge_motion_2_light_level
    type: mean
  - platform: min_max
    name: Lounge Area Temperature
    entity_ids:
      - sensor.lounge_motion_temperature
      - sensor.lounge_motion_2_temperature
    type: mean
