# Created by Danny Tsang <danny@tsang.uk>
automation:
  # Motion
  - id: "1606428361967"
    alias: "^Office: Motion Detected"
    description: ""
    trigger:
      - platform: state
        entity_id: group.office_motion
        to: "on"
    condition:
      - condition: and
        conditions:
          - condition: numeric_state
            entity_id: sensor.office_motion_light_level
            below: "100"
          - condition: numeric_state
            entity_id: sensor.office_motion_2_light_level
            below: "110"
          - condition: state
            entity_id: input_boolean.enable_office_motion_trigger
            state: "on"
          - condition: or
            conditions:
              - condition: numeric_state
                entity_id: light.office_light_2
                attribute: brightness
                below: "200"
              - condition: numeric_state
                entity_id: light.office_light_3
                attribute: brightness
                below: "200"
              - condition: template
                value_template: "{{ state_attr('light.office_light', 'brightness') == none }}"
              - condition: template
                value_template: "{{ state_attr('light.office_light_2', 'brightness') == none }}"
    action:
      - scene: scene.office_turn_on_light
      - data:
          title: Office Motion Detected
          message:
            ":feet: :bulb: :high_brightness: Motion detected in the office and it's dark ({{ states('sensor.office_motion_light_level')
            }} & {{ states('sensor.office_motion_2_light_level') }} lux < 100-110 lux). Turning office lights
            on"
        service: script.post_to_home_log
    mode: single
  - id: "1606170234725"
    alias: "^Office: No Motion After 5 Minutes"
    description: ""
    trigger:
      - platform: state
        entity_id: group.office_motion
        to: "off"
        for: 00:05:00
        from: "on"
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":no_pedestrians: No motion detected in the office after 5 minutes.
            Dimming lights."
      - scene: scene.office_dim_main_lights
    mode: single
  # Plugs / switches
  - id: "1596190251094"
    alias: "^Office: Turn Fan Off After 1 Hour"
    description: ""
    trigger:
      - entity_id: switch.office_fan
        for: 01:00:00
        from: "off"
        platform: state
        to: "on"
    condition: []
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.office_fan
      - data:
          message: Turned off office Fan after 1 hour.
        service: script.post_to_home_log
    mode: single
group:
  office_windows:
    name: Office Windows
    icon: mdi:window-closed
    entities:
      - binary_sensor.office_window_left
      - binary_sensor.office_window_right
sensor:
  - platform: min_max
    name: Office Area Light Level
    entity_ids:
      - sensor.office_motion_light_level
      - sensor.office_motion_2_light_level
    type: mean
  - platform: min_max
    name: Office Area Temperature
    entity_ids:
      - sensor.office_motion_temperature
      - sensor.office_motion_2_temperature
    type: mean
