# Created by Danny Tsang <danny@tsang.uk>
automation:
  # Motion
  - id: "1606428361967"
    alias: "^Office: Motion Detected"
    description: ""
    trigger:
      - platform: state
        entity_id: group.office_motion
        to: "on"
    condition: []
    action:
      - choose:
          - conditions:
              - condition: and
                conditions:
                  - condition: or
                    conditions:
                      - condition: numeric_state
                        entity_id: sensor.office_motion_light_level
                        below: "105"
                      - condition: numeric_state
                        entity_id: sensor.office_motion_2_light_level
                        below: "110"
                  - condition: or
                    conditions:
                      - condition: numeric_state
                        entity_id: light.office_light_2
                        attribute: brightness
                        below: "200"
                      - condition: numeric_state
                        entity_id: light.office_light_3
                        attribute: brightness
                        below: "200"
                      - condition: template
                        value_template: "{{ state_attr('light.office_light_2', 'brightness') == none }}"
                      - condition: template
                        value_template: "{{ state_attr('light.office_light_3', 'brightness') == none }}"
            sequence:
              - scene: scene.office_turn_on_light
              - service: script.post_to_home_log
                data:
                  title: Office Motion Detected
                  message: >-
                    :paw_prints: :bulb: :high_brightness: Motion detected in the office
                    and it's dark ({{ states('sensor.office_motion_light_level') }} & {{
                    states('sensor.office_motion_2_light_level') }} lux < 105 & 110
                    lux). Turning office lights on.
          - conditions:
              - condition: and
                conditions:
                  - condition: numeric_state
                    entity_id: sensor.office_motion_light_level
                    above: "105"
                  - condition: numeric_state
                    entity_id: sensor.office_motion_2_light_level
                    above: "110"
                  - condition: or
                    conditions:
                      - condition: numeric_state
                        entity_id: light.office_light_2
                        attribute: brightness
                        below: "200"
                      - condition: numeric_state
                        entity_id: light.office_light_3
                        attribute: brightness
                        below: "200"
            sequence:
              - scene: scene.office_main_light_off
              - service: script.post_to_home_log
                data:
                  title: Office Motion Detected
                  message: >-
                    :paw_prints: :bulb: :high_brightness: Motion detected in the office
                    and bright ({{ states('sensor.office_motion_light_level') }} & {{
                    states('sensor.office_motion_2_light_level') }} lux > 105 & 110
                    lux). Turning office lights off.
        default: []
    mode: single
  - id: "1606170234725"
    alias: "^Office: No Motion After 5 Minutes"
    description: ""
    trigger:
      - platform: state
        entity_id: group.office_motion
        to: "off"
        for: 00:05:00
        from: "on"
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":no_pedestrians: No motion detected in the office after 5 minutes.
            Dimming lights."
      - scene: scene.office_dim_main_lights
    mode: single
  - id: "1584277767373"
    alias: "^Office: No Motion Detected And Computer Is Off"
    description: ""
    trigger:
      - entity_id: group.office_motion
        for: 00:06:00
        platform: state
        to: "off"
      - platform: state
        entity_id: input_boolean.enable_office_motion_trigger
        to: "on"
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: group.jd_computer
            state: not_home
    action:
      - data:
          message:
            ":no_pedestrians: :bulb: No motion detected in the office for 6 minutes
            and :computer: is not connected. Turning office and desk lights off."
        service: script.post_to_home_log
      - scene: scene.office_turn_off_all_lights
    mode: single
  - id: "1587044886886"
    alias: "^Office: No Motion Detected And Computer Is On"
    description: ""
    trigger:
      - entity_id: group.office_motion
        for: 00:10:00
        platform: state
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.enable_office_motion_trigger
        state: "on"
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":no_pedestrians: No motion detected in the office for 10 minutes and
            :computer: is connected. Turning office light off."
      - scene: scene.office_main_light_off
    mode: single
  # Plugs / switches
  - id: "1622584959878"
    alias: "^Office: High Temperature"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.office_area_temperature
        above: "26"
      - platform: numeric_state
        entity_id: sensor.office_area_temperature
        above: "29"
        for: 00:01:00
      - platform: numeric_state
        entity_id: sensor.office_area_temperature
        for: 00:01:00
        above: "31"
    condition:
      - condition: state
        entity_id: switch.office_fan
        state: "off"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: group.adult_people
                state: home
              - condition: time
                before: "22:00:00"
              - condition: time
                after: "08:30:00"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":hotsprings: :people_holding_hands: Office temperature is high
                    ({{states('sensor.office_area_temperature') }}c) and someone is home.
                    Turning on fan."
              - service: switch.turn_on
                target:
                  entity_id: switch.office_fan
          - conditions:
              - condition: numeric_state
                entity_id: sensor.office_area_temperature
                above: "29"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":warning: :hotsprings: Office temperature is above 29c ({{states('sensor.office_area_temperature')
                    }}c)."
              - service: notify.mobile_app_dannys_phone
                data:
                  message: Turn on office fan?
                  data:
                    actions:
                      - title: "Yes"
                        action: switch_on_office_fan
                      - title: "No"
                        action: ignore
                  title: â™¨ï¸ðŸ¢Office temperature is 29c+
          - conditions:
              - condition: numeric_state
                entity_id: sensor.office_area_temperature
                above: "31"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":warning: :hotsprings: Office temperature is above 31c. Turning
                    fan on."
              - service: switch.turn_on
                target:
                  entity_id: switch.office_fan
        default: []
    mode: single
  - id: "1596190251094"
    alias: "^Office: Turn Fan Off After 1 Hour"
    description: ""
    trigger:
      - entity_id: switch.office_fan
        for: 01:00:00
        platform: state
        to: "on"
        id: 1h
        from: "off"
      - entity_id: switch.office_fan
        for: 02:00:00
        platform: state
        to: "on"
        id: 2h
        from: "off"
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: 1h
            sequence:
              - service: script.post_to_home_log
                data:
                  message: Turned off office Fan after 1 hour.
          - conditions:
              - condition: trigger
                id: 2h
            sequence:
              - service: script.post_to_home_log
                data:
                  message: Turned off office Fan after 2 hours.
        default: []
      - service: switch.turn_off
        target:
          entity_id: switch.office_fan
    mode: single
  - id: "1622666920056"
    alias: "^Office: Window Closed At Night"
    description: ""
    trigger:
      - platform: state
        entity_id: group.office_windows
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.enable_office_curtain_automations
        state: "on"
      - condition: or
        conditions:
          - condition: sun
            after: sunset
            after_offset: -01:00:00
          - condition: sun
            before: sunrise
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":window: :city_sunset: Office window closed and it's dark. Closing
            curtains."
      - service: script.office_close_curtains
    mode: single
  # Computer related automations
  - id: "1619865008647"
    alias: "^Office: Computer Turned On"
    description: ""
    trigger:
      - platform: state
        entity_id: group.jd_computer
        from: not_home
        to: home
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":tv: Computer turned on."
      - service: switch.turn_on
        target:
          entity_id: switch.goxlr
      - service: script.post_to_home_log
        data:
          message: ":level_slider: Turned on GoXLR."
      - service: script.office_turn_on_external_hard_drive
    mode: single
  - id: "1606256309890"
    alias: "^Office: Computer Turned Off"
    description: ""
    trigger:
      - platform: state
        entity_id: group.jd_computer
        for: 00:10:00
        to: not_home
        from: home
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: device_tracker.unifi_security_gateway
            state: unavailable
    action:
      - service: script.post_to_home_log
        data:
          message: ":computer: :tv: Computer turned off for more than 10 minutes."
      - scene: scene.office_turn_off_desk_light
      - service: script.post_to_home_log
        data:
          messsage: Turned off desk lights.
      - service: switch.turn_off
        target:
          entity_id: switch.goxlr
      - service: script.post_to_home_log
        data:
          message:
            ":computer: :tv: Computer turned off for more than 10 minutes. Turned
            off :level_slider: goXLR"
      - service: script.office_turn_off_backup_drive
    mode: single
  # Curtains
  - id: "1622374444832"
    alias: "^Office: Open Curtains In The Morning"
    description: ""
    trigger:
      - platform: time
        at: 08:00:00
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":clock{{ now().strftime('%I') | int }}{% if now().minute | int > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: Opening office curtains."
      - service: script.office_open_curtains
    mode: single
  - id: "1622374233310"
    alias: "^Office: Close Office Curtains At Night"
    description: ""
    trigger:
      - platform: sun
        event: sunset
        offset: -01:00:00
    condition:
      - condition: state
        entity_id: input_boolean.enable_office_curtain_automations
        state: "on"
    action:
      - service: script.post_to_home_log
        data:
          message: ":city_sunset: :window: It's getting dark, closing office blinds."
      - choose:
          - conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: binary_sensor.office_window_right
                    state: "on"
                  - condition: state
                    entity_id: binary_sensor.office_window_left
                    state: "on"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":warning: :window: Office window is still open so not closing
                    curtains. before closing curtains. :warning:"
        default:
          - service: script.office_close_curtains
    mode: single
group:
  jd_computer:
    name: JD Computer
    icon: mdi:laptop
    entities:
      - device_tracker.jd
  office_ceiling_lights:
    name: Office Ceiling Lights
    icon: mdi:lightbulb
    entities:
      - light.office_light
      - light.office_light_2
      - light.office_light_3
      - light.office_light_4
  office_computers:
    name: Office Computers
    icon: mdi:laptop
    entities:
      - device_tracker.janitor
      - device_tracker.jd
      - device_tracker.gt18_5110
      - device_tracker.gt18_5110_2
      - device_tracker.sam
  office_key_lights:
    name: Office Key Lights
    icon: mdi:spotlight
    entities:
      - light.elgato_key_light_left
      - light.elgato_key_light_right
  office_lights:
    name: Office Lights
    icon: mdi:lightbulb
    entities:
      - light.office_desk_left
      - light.office_desk_right
      - light.office_desk_top
      - light.office_light
      - light.office_light_2
      - light.office_light_3
      - light.office_light_4
      - light.elgato_key_light_left
      - light.elgato_key_light_right
  office_motion:
    name: Office Motion
    icon: mdi:walk
    entities:
      - binary_sensor.office_motion
      - binary_sensor.office_motion_2
  office_windows:
    name: Office Windows
    icon: mdi:window-closed
    entities:
      - binary_sensor.office_window_left
      - binary_sensor.office_window_right
  work_computers:
    name: Office Computers
    icon: mdi:laptop
    entities:
      - device_tracker.gt18_5110
      - device_tracker.gt18_5110_2
input_boolean:
  arm_office_door:
    name: Alarm office door
    icon: mdi:alarm-light-outline
  enable_office_curtain_automations:
    name: Enable office curtain automations
    icon: mdi:window-open
  enable_office_motion_trigger:
    name: Enable motion trigger for office
    icon: mdi:motion-sensor
script:
  office_close_curtains:
    alias: Office Close Curtains
    sequence:
      - service: ifttt.trigger
        data:
          event: close_office_left_curtain
      - service: ifttt.trigger
        data:
          event: close_office_right_curtain
    mode: single
    icon: mdi:blinds
  office_open_curtains:
    alias: Office Open Curtains
    sequence:
      - service: ifttt.trigger
        data:
          event: open_office_right_curtain
      - service: ifttt.trigger
        data:
          event: open_office_left_curtain
    mode: single
sensor:
  - platform: min_max
    name: Office Area Light Level
    entity_ids:
      - sensor.office_motion_light_level
      - sensor.office_motion_2_light_level
    type: mean
  - platform: min_max
    name: Office Area Temperature
    entity_ids:
      - sensor.office_motion_temperature
      - sensor.office_motion_2_temperature
    type: mean
