# Created by Danny Tsang <danny@tsang.uk>
automation:
  # Motion
  - id: "1606428361967"
    alias: "^Office: Motion Detected"
    description: ""
    trigger:
      - platform: state
        entity_id: group.office_motion
        to: "on"
    condition:
      - condition: and
        conditions:
          - condition: numeric_state
            entity_id: sensor.office_motion_light_level
            below: "100"
          - condition: numeric_state
            entity_id: sensor.office_motion_2_light_level
            below: "110"
          - condition: state
            entity_id: input_boolean.enable_office_motion_trigger
            state: "on"
          - condition: or
            conditions:
              - condition: numeric_state
                entity_id: light.office_light_2
                attribute: brightness
                below: "200"
              - condition: numeric_state
                entity_id: light.office_light_3
                attribute: brightness
                below: "200"
              - condition: template
                value_template: "{{ state_attr('light.office_light', 'brightness') == none }}"
              - condition: template
                value_template: "{{ state_attr('light.office_light_2', 'brightness') == none }}"
    action:
      - scene: scene.office_turn_on_light
      - data:
          title: Office Motion Detected
          message:
            ":paw_prints: :bulb: :high_brightness: Motion detected in the office and it's dark ({{ states('sensor.office_motion_light_level')
            }} & {{ states('sensor.office_motion_2_light_level') }} lux < 100-110 lux). Turning office lights
            on"
        service: script.post_to_home_log
    mode: single
  - id: "1606170234725"
    alias: "^Office: No Motion After 5 Minutes"
    description: ""
    trigger:
      - platform: state
        entity_id: group.office_motion
        to: "off"
        for: 00:05:00
        from: "on"
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":no_pedestrians: No motion detected in the office after 5 minutes.
            Dimming lights."
      - scene: scene.office_dim_main_lights
    mode: single
  # Plugs / switches
  - id: "1596190251094"
    alias: "^Office: Turn Fan Off After 1 Hour"
    description: ""
    trigger:
      - entity_id: switch.office_fan
        for: 01:00:00
        from: "off"
        platform: state
        to: "on"
    condition: []
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.office_fan
      - data:
          message: Turned off office Fan after 1 hour.
        service: script.post_to_home_log
    mode: single
  - id: "1622666920056"
    alias: "^Office: Window Closed At Night"
    description: ""
    trigger:
      - platform: state
        entity_id: group.office_windows
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.enable_office_curtain_automations
        state: "on"
      - condition: or
        conditions:
          - condition: sun
            after: sunset
            after_offset: -01:00:00
          - condition: sun
            before: sunrise
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":window: :city_sunset: Office window closed and it's dark. Closing
            curtains."
      - service: script.office_close_curtains
    mode: single
group:
  jd_computer:
    name: JD Computer
    icon: mdi:laptop
    entities:
      - device_tracker.jd
  office_ceiling_lights:
    name: Office Ceiling Lights
    icon: mdi:lightbulb
    entities:
      - light.office_light
      - light.office_light_2
      - light.office_light_3
      - light.office_light_4
  office_computers:
    name: Office Computers
    icon: mdi:laptop
    entities:
      - device_tracker.janitor
      - device_tracker.jd
      - device_tracker.gt18_5110
      - device_tracker.sam
  office_lights:
    name: Office Lights
    icon: mdi:lightbulb
    entities:
      - light.office_desk_left
      - light.office_desk_right
      - light.office_desk_top
      - light.office_light
      - light.office_light_2
      - light.office_light_3
      - light.office_light_4
      - light.elgato_key_light_left
  office_motion:
    name: Office Motion
    icon: mdi:walk
    entities:
      - binary_sensor.office_motion
      - binary_sensor.office_motion_2
  office_windows:
    name: Office Windows
    icon: mdi:window-closed
    entities:
      - binary_sensor.office_window_left
      - binary_sensor.office_window_right
input_boolean:
  arm_office_door:
    name: Alarm office door
    icon: mdi:alarm-light-outline
  enable_office_curtain_automations:
    name: Enable office curtain automations
    icon: mdi:window-open
  enable_office_motion_trigger:
    name: Enable motion trigger for office
    icon: mdi:motion-sensor
script:
  office_close_curtains:
    alias: Office Close Curtains
    sequence:
      - service: ifttt.trigger
        data:
          event: close_office_left_curtain
      - service: ifttt.trigger
        data:
          event: close_office_right_curtain
    mode: single
    icon: mdi:blinds
  office_open_curtains:
    alias: Office Open Curtains
    sequence:
      - service: ifttt.trigger
        data:
          event: open_office_right_curtain
      - service: ifttt.trigger
        data:
          event: open_office_left_curtain
    mode: single
sensor:
  - platform: min_max
    name: Office Area Light Level
    entity_ids:
      - sensor.office_motion_light_level
      - sensor.office_motion_2_light_level
    type: mean
  - platform: min_max
    name: Office Area Temperature
    entity_ids:
      - sensor.office_motion_temperature
      - sensor.office_motion_2_temperature
    type: mean
