# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1606157753577"
    alias: "^Porch: Front Door Open Turn Light On"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: "on"
    condition: []
    action:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: sensor.porch_motion_light_level
                below: "100"
            sequence:
              - service: script.post_to_home_log
                data:
                  message: ":door: :bulb: :high_brightness: Door opened and it's dark 
                  ({{ states('sensor.porch_motion_light_level') }} < 100). Turning on light."
              - service: scene.turn_on
                target:
                  entity_id: scene.porch_light_on
        default: []
      - service: script.post_to_home_log
        data:
          message:
            ':door: Incrementing front door counter :abacus:
            from {{ states("counter.front_door") }} to {{ states("counter.front_door")
            | int + state_attr("counter.front_door", "step") | int }}.'
      - service: counter.increment
        data: {}
        entity_id: counter.front_door
    mode: single
  - id: "1614033445487"
    alias: "^Porch: Front Door Opened Once For More than 20 seconds"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: "on"
        from: "off"
        for: 00:00:20
    condition:
      - condition: numeric_state
        entity_id: counter.front_door
        below: "2"
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":door: :abacus: Front door has been opened for more than 20 secs.
            Resetting counter  from {{ states('counter.front_door') }} to 0."
      - service: counter.reset
        data: {}
        entity_id: counter.front_door
  - id: "1615224190495"
    alias: "^Porch: Front Door Closed For More than 20 seconds"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: "off"
        from: "on"
        for: 00:00:20
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":door: :abacus: Front  door has been closed for more than 20 secs.
            Resetting counter  from {{ states('counter.front_door') }} to 0"
      - service: counter.reset
        target:
          entity_id: counter.front_door
    mode: single
  - id: "1611931640441"
    alias: "^Porch: Front Door Closed"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        from: "on"
        to: "off"
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":door: Front door closed."
      - service: script.front_door_closed_notification
        data: {}
    mode: single
  - id: "1606157835544"
    alias: "^Porch: Front Door Closed Turn Off Porch Light"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        from: "on"
        to: "off"
        for: 00:01:00
    condition: []
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.porch_lights_off
      - service: script.post_to_home_log
        data:
          message: ":door: Front door closed for 1 minute. Turning off porch light."
      - choose:
        - conditions:
            - condition: state
              entity_id: light.stairs
              state: "on"
          sequence:
            - service: script.post_to_home_log
              data:
                message: "Front door closed. Turning stairs light off as fall back."
            - service: scene.turn_on
              target:
                entity_id:
                  - scene.stairs_light_off
        default: []
      - choose:
        - conditions:
            - condition: state
              entity_id: light.office_light
              state: "on"
          sequence:
            - service: script.post_to_home_log
              data:
                message: "Front door closed. Turning office light off as fall back."
            - service: scene.turn_on
              target:
                entity_id:
                  - scene.office_turn_off_light_notification
        default: []
    mode: single
input_boolean:
  enable_porch_light_override:
    name: Enable Bathroom Override Feature
    icon: mdi:door
  porch_light_override:
    name: Bathroom Light Override
    icon: mdi:lightbulb
scene:
  - id: "1606157607021"
    name: Porch Lights Off
    entities:
      light.porch:
        min_mireds: 111
        max_mireds: 400
        effect_list:
          - effect_colorloop
          - effect_pulse
          - effect_stop
        friendly_name: Porch
        supported_features: 55
        state: "off"
  - id: "1606157646144"
    name: Porch Light On
    entities:
      light.porch:
        min_mireds: 111
        max_mireds: 400
        effect_list:
          - effect_colorloop
          - effect_pulse
          - effect_stop
        brightness: 178
        color_temp: 285
        friendly_name: Porch
        supported_features: 55
        state: "on"
script:
  front_door_closed_notification:
    alias: Front Door Closed Notification
    sequence:
      - service: scene.turn_on
        target:
          entity_id:
            - scene.current_office_light_1
            - scene.current_stairs_light
            - scene.current_stairs_light2
    mode: single
    icon: mdi:door
  nfc_front_door:
    alias: NFC Front Door
    sequence:
      - choose:
          - conditions:
              - condition: not
                conditions:
                  - condition: state
                    entity_id: alarm_control_panel.stevenage_alarm
                    state: disarmed
            sequence:
              - service: script.post_to_home_log
                data:
                  message: ":no_bell: Turning off alarm."
              - service: alarm_control_panel.alarm_disarm
                target:
                  entity_id: alarm_control_panel.stevenage_alarm
              - service: script.lounge_flash_lounge_lights_green
        default:
          - service: script.post_to_home_log
            data:
              message: ":no_bell: Alarm is not on so nothing to do."
          - service: script.lounge_flash_lounge_lights_red
    mode: single
    icon: mdi:nfc
template:
  # Replicate Switchbot contact sensor to know if someone is entering or leaving. Thanks to @damieng5
  # https://www.switch-bot.com/products/contact-sensor
  - trigger:
    - platform: state
      entity_id: binary_sensor.front_door
    sensor:
    - name: Door Entry Direction
      icon: >-
        mdi:{% if states('binary_sensor.porch_motion') == 'on' %}location-exit
        {% elif states('binary_sensor.porch_motion') == 'on' %}location-enter
        {% else %}alert-circle-outline{% endif %}
      state: >-
        {% if states('binary_sensor.porch_motion') == 'on' %}leaving
        {% elif states('binary_sensor.porch_motion') == 'off' %}entering
        {% else %}unknown{% endif %}
