# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1606157753577"
    alias: "Porch: Front Door Open Turn Light On"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: "on"
    condition: []
    action:
      - parallel:
          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: sensor.porch_motion_illuminance_lux
                    below: "100"
                sequence:
                  - service: script.send_to_home_log
                    data:
                      message: >-
                        Front :door: door opened it's dark
                        ({{ states('sensor.porch_motion_illuminance_lux') }} < 100).
                        Turning on :bulb: :high_brightness: light.
                      title: "Porch"
                      log_level: "Debug"
                  - service: scene.turn_on
                    target:
                      entity_id: scene.porch_light_on
            default: []
      - service: script.send_to_home_log
        data:
          message: >-
            Front :door: door opened. Incrementing counter :abacus:
            from {{ states('counter.front_door_opened_closed') }} to {{ states('counter.front_door_opened_closed')
            | int + state_attr('counter.front_door_opened_closed', 'step') | int }}.
          title: "Porch"
          log_level: "Debug"
      - service: counter.increment
        data: {}
        entity_id: counter.front_door_opened_closed
      - alias: Add delay otherwise the picture is too quick to capture someone walking through the door
        delay:
          seconds: 2
      - service: script.send_to_computers
        data:
          message: Opened
          title: "🚪🛎 Front Door"
          filePath: /api/camera_proxy/camera.lounge
          duration: 10
    mode: single
  - id: "1614033445487"
    alias: "Porch: Front Door Opened Once For More than 20 seconds"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: "on"
        from: "off"
        for: 00:00:20
    condition:
      - condition: numeric_state
        entity_id: counter.front_door_opened_closed
        below: "2"
    action:
      - service: script.send_to_home_log
        data:
          message: >-
            Front door has been opened for more than 20 secs.
            Resetting :abacus: counter from {{ states('counter.front_door_opened_closed') }} to 0.
          title: "Porch"
          log_level: "Debug"
      - service: counter.reset
        data: {}
        entity_id: counter.front_door_opened_closed
  - id: "1611931052908"
    alias: "Porch: Front Door Open Indicator"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: group.adult_people
        state: "home"
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: >-
                front :door: door is open and:people_holding_hands: someone is home.
                Turning on notification :bulb: :high_brightness: light.
              title: "Porch"
              log_level: "Debug"
          - service: script.front_door_open_notification
            data: {}
    mode: single
  - id: "1615224190495"
    alias: "Porch: Front Door Closed For More than 20 seconds"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: "off"
        from: "on"
        for: 00:00:20
    condition: []
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: >-
                Front door closed for more than 20 secs.
                Resetting :abacus: counter from {{ states('counter.front_door_opened_closed') }} to 0.
              title: "Porch"
              log_level: "Debug"
          - service: counter.reset
            target:
              entity_id: counter.front_door_opened_closed
    mode: single
  - id: "1611931640441"
    alias: "Porch: Front Door Closed"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        from: "on"
        to: "off"
    condition: []
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: "Front :door: door closed."
              title: "Porch"
              log_level: "Debug"
          - service: script.front_door_closed_notification
            data: {}
          - service: script.send_to_computers
            data:
              message: Closed.
              title: "🚪🛎 Front Door"
              filePath: /api/camera_proxy/camera.lounge
              duration: 10
    mode: single
  - id: "1606157835544"
    alias: "Porch: Front Door Closed Turn Off Porch Light"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        from: "on"
        to: "off"
        for: 00:01:00
    condition: []
    action:
      - parallel:
          - service: scene.turn_on
            target:
              entity_id: scene.porch_lights_off
          - service: script.send_to_home_log
            data:
              message: >-
                Front :door: door closed for 1 minute.
                Turning off light.
              title: "Porch"
              log_level: "Debug"
          - choose:
              - conditions:
                  - condition: state
                    entity_id: light.stairs
                    state: "on"
                sequence:
                  - service: script.send_to_home_log
                    data:
                      message: "Front door closed. Turning stairs light off as fall back."
                      title: "Porch"
                      log_level: "Debug"
                  - service: scene.turn_on
                    target:
                      entity_id:
                        - scene.stairs_light_off
            default: []
          - choose:
              - conditions:
                  - condition: state
                    entity_id: light.office_light
                    state: "on"
                sequence:
                  - service: script.send_to_home_log
                    data:
                      message: "Front door closed. Turning office light off as fall back."
                      title: "Porch"
                      log_level: "Debug"
                  - service: scene.turn_on
                    target:
                      entity_id:
                        - scene.office_turn_off_light_notification
            default: []
    mode: single

scene:
  - id: "1606157607021"
    name: Porch Lights Off
    entities:
      light.porch:
        min_mireds: 111
        max_mireds: 400
        effect_list:
          - effect_colorloop
          - effect_pulse
          - effect_stop
        friendly_name: Porch
        supported_features: 55
        state: "off"
  - id: "1606157646144"
    name: Porch Light On
    entities:
      light.porch:
        min_mireds: 111
        max_mireds: 400
        effect_list:
          - effect_colorloop
          - effect_pulse
          - effect_stop
        brightness: 178
        color_temp: 285
        friendly_name: Porch
        supported_features: 55
        state: "on"

script:
  front_door_closed_notification:
    alias: Front Door Closed Notification
    sequence:
      - service: scene.turn_on
        target:
          entity_id:
            - scene.current_office_light_1
            - scene.current_stairs_light
            - scene.current_stairs_light2
    mode: single
    icon: mdi:door
  nfc_front_door:
    alias: NFC Front Door
    sequence:
      - choose:
          - conditions:
              - not:
                  - condition: state
                    entity_id: alarm_control_panel.house_alarm
                    state: "disarmed"
            sequence:
              - service: script.send_to_home_log
                data:
                  message: ":no_bell: Turning off alarm."
                  title: ":bell: Alarm"
                  log_level: "Debug"
              - service: script.set_alarm_to_disarmed_mode
              - service: script.lounge_flash_lounge_lights_green
        default:
          - service: script.send_to_home_log
            data:
              message: ":no_bell: Alarm is not on so nothing to do."
              title: ":bell: Alarm"
              log_level: "Debug"
          - service: script.lounge_flash_lounge_lights_red
    mode: single
    icon: mdi:nfc
  front_door_open_notification:
    alias: Front Door Open Notification
    sequence:
      - service: scene.create
        data:
          scene_id: current_stairs_light
          snapshot_entities:
            - light.stairs
      - service: scene.create
        data:
          scene_id: current_stairs_light2
          snapshot_entities:
            - light.stairs_2
      - service: scene.create
        data:
          scene_id: current_office_light_1
          snapshot_entities:
            - light.office_light
      - service: scene.turn_on
        target:
          entity_id:
            - scene.front_door_open_notification
    mode: single
    icon: mdi:door-open
  porch_override_notification:
    alias: Porch Override Notification
    sequence:
      - repeat:
          count: "2"
          sequence:
            - service: light.turn_on
              data:
                brightness: 255
                color_name: blue
              entity_id: light.porch
            - service: light.turn_on
              data:
                brightness: 178
                color_name: white
              entity_id: light.porch
      - service: scene.turn_on
        target:
          entity_id: scene.porch_light_on
    mode: single

template:
  # Replicate Switchbot contact sensor to know if someone is entering or leaving. Thanks to @damieng5
  # https://www.switch-bot.com/products/contact-sensor
  - trigger:
      - platform: state
        entity_id: binary_sensor.front_door
    sensor:
      - name: Door Entry Direction
        unique_id: 97c1df2b-dcde-4aba-884c-acfc59c140aa
        icon: >-
          mdi:{% if states('binary_sensor.porch_motion_occupancy') == 'on' %}location-exit
          {% elif states('binary_sensor.porch_motion_occupancy') == 'on' %}location-enter
          {% else %}alert-circle-outline{% endif %}
        state: >-
          {% if states('binary_sensor.porch_motion_occupancy') == 'on' %}leaving
          {% elif states('binary_sensor.porch_motion_occupancy') == 'off' %}entering
          {% else %}unknown{% endif %}
