# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1606157753577"
    alias: "^Porch: Front Door Open Turn Light On"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: "on"
    condition: []
    action:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: sensor.porch_motion_light_level
                below: "100"
            sequence:
              - service: script.post_to_home_log
                data:
                  message: ":door: :bulb: :high_brightness: Door opened and it's dark 
                  ({{ states('sensor.porch_motion_light_level') }} < 100). Turning on light."
              - service: scene.turn_on
                target:
                  entity_id: scene.porch_light_on
        default: []
      - service: script.post_to_home_log
        data:
          message:
            ':door: Incrementing front door counter :abacus:
            from {{ states("counter.front_door") }} to {{ states("counter.front_door")
            | int + state_attr("counter.front_door", "step") | int }}.'
      - service: counter.increment
        data: {}
        entity_id: counter.front_door
    mode: single
  - id: "1611931640441"
    alias: "^Porch: Front Door Closed"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        from: "on"
        to: "off"
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":door: Front door closed."
      - service: script.front_door_closed_notification
        data: {}
    mode: single
  - id: "1606157835544"
    alias: "^Porch: Front Door Closed Turn Off Porch Light"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        from: "on"
        to: "off"
        for: 00:01:00
    condition: []
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.porch_lights_off
      - service: script.post_to_home_log
        data:
          message: ":door: Front door closed for 1 minute. Turning off porch light."
      - choose:
        - conditions:
            - condition: state
              entity_id: light.stairs
              state: 'on'
          sequence:
            - service: script.post_to_home_log
              data:
                message: "Front door closed. Turning stairs light off as fall back."
            - service: scene.turn_on
              target:
                entity_id:
                  - scene.stairs_light_off
        default: []
      - choose:
        - conditions:
            - condition: state
              entity_id: light.office_light
              state: 'on'
          sequence:
            - service: script.post_to_home_log
              data:
                message: "Front door closed. Turning office light off as fall back."
            - service: scene.turn_on
              target:
                entity_id:
                  - scene.office_turn_off_light_notification
        default: []
    mode: single
input_boolean:
  enable_porch_light_override:
    name: Enable Bathroom Override Feature
    icon: mdi:door
  porch_light_override:
    name: Bathroom Light Override
    icon: mdi:lightbulb
