# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1606157753577"
    alias: "Porch: Front Door Open Turn Light On"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: "on"
    condition: []
    action:
      - parallel:
          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: sensor.porch_motion_illuminance_lux
                    below: "100"
                sequence:
                  - service: script.send_to_home_log
                    data:
                      message: >-
                        Front :door: door opened it's dark
                        ({{ states('sensor.porch_motion_illuminance_lux') }} < 100).
                        Turning on :bulb: :high_brightness: light.
                      title: "Porch"
                      log_level: "Debug"
                  - service: scene.turn_on
                    target:
                      entity_id: scene.porch_light_on
            default: []
      - service: script.send_to_home_log
        data:
          message: >-
            Front :door: door opened. Incrementing counter :abacus:
            from {{ states('counter.front_door_opened_closed') }} to {{ states('counter.front_door_opened_closed')
            | int + state_attr('counter.front_door_opened_closed', 'step') | int }}.
          title: "Porch"
          log_level: "Debug"
      - service: counter.increment
        data: {}
        entity_id: counter.front_door_opened_closed
      - alias: Add delay otherwise the picture is too quick to capture someone walking through the door
        delay:
          seconds: 2
      - service: script.send_to_computers
        data:
          message: Opened
          title: "🚪🛎 Front Door"
          filePath: /api/camera_proxy/camera.lounge
          duration: 10
    mode: single
  - id: "1614033445487"
    alias: "Porch: Front Door Opened Once For More than 20 seconds"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: "on"
        from: "off"
        for: 00:00:20
    condition:
      - condition: numeric_state
        entity_id: counter.front_door_opened_closed
        below: "2"
    action:
      - service: script.send_to_home_log
        data:
          message: >-
            Front door has been opened for more than 20 secs.
            Resetting :abacus: counter from {{ states('counter.front_door_opened_closed') }} to 0.
          title: "Porch"
          log_level: "Debug"
      - service: counter.reset
        data: {}
        entity_id: counter.front_door_opened_closed
  - id: "1611931052908"
    alias: "Porch: Front Door Open Indicator"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: group.adult_people
        state: "home"
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: >-
                front :door: door is open and:people_holding_hands: someone is home.
                Turning on notification :bulb: :high_brightness: light.
              title: "Porch"
              log_level: "Debug"
          - service: script.front_door_open_notification
            data: {}
    mode: single
  - id: "1615224190495"
    alias: "Porch: Front Door Closed For More than 20 seconds"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: "off"
        from: "on"
        for: 00:00:20
    condition: []
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: >-
                Front door closed for more than 20 secs.
                Resetting :abacus: counter from {{ states('counter.front_door_opened_closed') }} to 0.
              title: "Porch"
              log_level: "Debug"
          - service: counter.reset
            target:
              entity_id: counter.front_door_opened_closed
    mode: single
  - id: "1611931640441"
    alias: "Porch: Front Door Closed"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        from: "on"
        to: "off"
    condition: []
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: "Front :door: door closed."
              title: "Porch"
              log_level: "Debug"
          - service: script.front_door_closed_notification
            data: {}
          - service: script.send_to_computers
            data:
              message: Closed.
              title: "🚪🛎 Front Door"
              filePath: /api/camera_proxy/camera.lounge
              duration: 10
    mode: single
  - id: "1606157835544"
    alias: "Porch: Front Door Closed Turn Off Porch Light"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        from: "on"
        to: "off"
        for: 00:01:00
    condition: []
    action:
      - parallel:
          - service: scene.turn_on
            target:
              entity_id: scene.porch_lights_off
          - service: script.send_to_home_log
            data:
              message: >-
                Front :door: door closed for 1 minute.
                Turning off light.
              title: "Porch"
              log_level: "Debug"
          - choose:
              - conditions:
                  - condition: state
                    entity_id: light.stairs
                    state: "on"
                sequence:
                  - service: script.send_to_home_log
                    data:
                      message: "Front door closed. Turning stairs light off as fall back."
                      title: "Porch"
                      log_level: "Debug"
                  - service: scene.turn_on
                    target:
                      entity_id:
                        - scene.stairs_light_off
            default: []
          - choose:
              - conditions:
                  - condition: state
                    entity_id: light.office_light
                    state: "on"
                sequence:
                  - service: script.send_to_home_log
                    data:
                      message: "Front door closed. Turning office light off as fall back."
                      title: "Porch"
                      log_level: "Debug"
                  - service: scene.turn_on
                    target:
                      entity_id:
                        - scene.office_turn_off_light_notification
            default: []
    mode: single
  - id: "1708895092115"
    alias: "Porch: Light On And Door Is Shut"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - light.porch
        to: "on"
        for:
          minutes: 5
    condition:
      - condition: state
        entity_id: binary_sensor.front_door
        state: "off"
    action:
      - parallel:
          - service: script.send_to_home_log
            metadata: {}
            data:
              log_level: Debug
              title: Porch
              message:
                "Light has been on for 5 minutes and :door: is closed. Turning light
                off."
          - service: light.turn_off
            metadata: {}
            data:
              transition: 2
            target:
              entity_id: light.porch
    mode: single
  - id: "1700940016581"
    alias: "Porch: Light Switch"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.porch_main_light_input
        not_from:
          - "unknown"
          - "unavailable"
        not_to:
          - "unknown"
          - "unavailable"
    condition: []
    action:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.porch
      - service: script.send_to_home_log
        data:
          log_level: Debug
          title: Porch
          message: Light switch changed
    mode: single

scene:
  - id: "1606157607021"
    name: Porch Lights Off
    entities:
      light.porch:
        min_mireds: 111
        max_mireds: 400
        effect_list:
          - effect_colorloop
          - effect_pulse
          - effect_stop
        friendly_name: Porch
        supported_features: 55
        state: "off"
  - id: "1606157646144"
    name: Porch Light On
    entities:
      light.porch:
        min_mireds: 111
        max_mireds: 400
        effect_list:
          - effect_colorloop
          - effect_pulse
          - effect_stop
        brightness: 178
        color_temp: 285
        friendly_name: Porch
        supported_features: 55
        state: "on"
  - id: "1696367037290"
    name: Porch Green Light
    entities:
      light.porch:
        min_color_temp_kelvin: 2000
        max_color_temp_kelvin: 6535
        min_mireds: 153
        max_mireds: 500
        effect_list:
          - blink
          - breathe
          - okay
          - channel_change
          - candle
          - fireplace
          - colorloop
          - finish_effect
          - stop_effect
          - stop_hue_effect
        supported_color_modes:
          - color_temp
          - xy
        icon: phu:bulb-sultan-v2
        friendly_name: Porch
        supported_features: 44
        color_mode: xy
        brightness: 255
        hs_color:
          - 127.895
          - 89.412
        rgb_color:
          - 27
          - 255
          - 57
        xy_color:
          - 0.176
          - 0.707
        state: "on"
    metadata:
      light.porch:
        entity_only: true
  - id: "1701031703306"
    name: Porch Red Light
    entities:
      light.porch:
        min_color_temp_kelvin: 2000
        max_color_temp_kelvin: 6535
        min_mireds: 153
        max_mireds: 500
        effect_list:
          - blink
          - breathe
          - okay
          - channel_change
          - candle
          - fireplace
          - colorloop
          - finish_effect
          - stop_effect
          - stop_hue_effect
        supported_color_modes:
          - color_temp
          - xy
        color_mode: xy
        brightness: 255
        color_temp_kelvin:
        color_temp:
        hs_color:
          - 358.745
          - 93.725
        rgb_color:
          - 255
          - 16
          - 21
        xy_color:
          - 0.695
          - 0.299
        effect:
        icon: phu:bulb-sultan-v2
        friendly_name: Porch
        supported_features: 44
        state: "on"
    metadata:
      light.porch:
        entity_only: true
  - id: "1701032346965"
    name: Porch Blue Light
    entities:
      light.porch:
        min_color_temp_kelvin: 2000
        max_color_temp_kelvin: 6535
        min_mireds: 153
        max_mireds: 500
        effect_list:
          - blink
          - breathe
          - okay
          - channel_change
          - candle
          - fireplace
          - colorloop
          - finish_effect
          - stop_effect
          - stop_hue_effect
        supported_color_modes:
          - color_temp
          - xy
        color_mode: xy
        brightness: 255
        color_temp_kelvin:
        color_temp:
        hs_color:
          - 242.683
          - 96.471
        rgb_color:
          - 20
          - 9
          - 255
        xy_color:
          - 0.137
          - 0.041
        effect:
        icon: phu:bulb-sultan-v2
        friendly_name: Porch
        supported_features: 44
        state: "on"
    metadata:
      light.porch:
        entity_only: true
  - id: "1611931150080"
    name: Front Door Open Notification
    entities:
      light.office_light:
        min_mireds: 111
        max_mireds: 400
        effect_list:
          - effect_colorloop
          - effect_pulse
          - effect_stop
        brightness: 255
        hs_color:
          - 254.997
          - 100
        rgb_color:
          - 63
          - 0
          - 255
        xy_color:
          - 0.157
          - 0.05
        friendly_name: Office Light
        supported_features: 55
        state: "on"
      light.stairs_ambient:
        min_color_temp_kelvin: 2702
        max_color_temp_kelvin: 6535
        min_mireds: 153
        max_mireds: 370
        supported_color_modes:
          - color_temp
          - xy
        color_mode: xy
        brightness: 255
        color_temp_kelvin:
        color_temp:
        hs_color:
          - 237.073
          - 96.471
        rgb_color:
          - 9
          - 21
          - 255
        xy_color:
          - 0.136
          - 0.042
        friendly_name: Stairs Ambient
        supported_features: 40
        state: "on"
    metadata:
      light.stairs_ambient:
        entity_only: true

script:
  front_door_closed_notification:
    alias: Front Door Closed Notification
    sequence:
      - service: scene.turn_on
        target:
          entity_id:
            - scene.current_office_light_1
      - service: light.turn_off
        data: {}
        target:
          entity_id:
            - light.stairs_ambient
            - scene.kitchen_cooker_ambient_light_to_blue
            - scene.kitchen_table_ambient_light_to_blue
    mode: single
    icon: mdi:door
  nfc_front_door:
    alias: NFC Front Door
    sequence:
      - choose:
          - conditions:
              - not:
                  - condition: state
                    entity_id: alarm_control_panel.house_alarm
                    state: "disarmed"
            sequence:
              - service: script.send_to_home_log
                data:
                  message: ":no_bell: Turning off alarm."
                  title: ":bell: Alarm"
                  log_level: "Debug"
              - service: script.set_alarm_to_disarmed_mode
              - service: script.living_room_flash_lounge_lights_green
        default:
          - service: script.send_to_home_log
            data:
              message: ":no_bell: Alarm is not on so nothing to do."
              title: ":bell: Alarm"
              log_level: "Debug"
          - service: script.living_room_flash_lounge_lights_red
    mode: single
    icon: mdi:nfc
  front_door_open_notification:
    alias: Front Door Open Notification
    sequence:
      - service: scene.create
        data:
          scene_id: current_office_light_1
          snapshot_entities:
            - light.office_light
      - service: scene.turn_on
        target:
          entity_id:
            - scene.front_door_open_notification
            - scene.kitchen_cooker_ambient_light_to_blue
            - scene.kitchen_table_ambient_light_to_blue
    mode: single
    icon: mdi:door-open
  porch_override_notification:
    alias: Porch Override Notification
    sequence:
      - repeat:
          count: "2"
          sequence:
            - service: light.turn_on
              data:
                brightness: 255
                color_name: blue
              entity_id: light.porch
            - service: light.turn_on
              data:
                brightness: 178
                color_name: white
              entity_id: light.porch
      - service: scene.turn_on
        target:
          entity_id: scene.porch_light_on
    mode: single
  stop_lock_status_light:
    alias: Stop Lock Status Light
    sequence:
      - service: script.turn_off
        data: {}
        target:
          entity_id: script.front_door_lock_status
      - service: light.turn_off
        target:
          entity_id: light.porch
        data: {}
    mode: single
    icon: mdi:lock-off

template:
  # Replicate Switchbot contact sensor to know if someone is entering or leaving. Thanks to @damieng5
  # https://www.switch-bot.com/products/contact-sensor
  - trigger:
      - platform: state
        entity_id: binary_sensor.front_door
    sensor:
      - name: Door Entry Direction
        unique_id: 97c1df2b-dcde-4aba-884c-acfc59c140aa
        icon: >-
          mdi:{% if states('binary_sensor.porch_motion_occupancy') == 'on' %}location-exit
          {% elif states('binary_sensor.porch_motion_occupancy') == 'on' %}location-enter
          {% else %}alert-circle-outline{% endif %}
        state: >-
          {% if states('binary_sensor.porch_motion_occupancy') == 'on' %}leaving
          {% elif states('binary_sensor.porch_motion_occupancy') == 'off' %}entering
          {% else %}unknown{% endif %}
