# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1606157753577"
    alias: "^Porch: Front Door Open Turn Light On"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: "on"
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message:
            ':door: :bulb: :high_brightness: Door opened. Turning porch light on. Incrementing counter :abacus:
            from {{ states("counter.front_door") }} to {{ states("counter.front_door")
            | int + state_attr("counter.front_door", "step") | int }}.'
      - scene: scene.porch_light_on
      - service: counter.increment
        data: {}
        entity_id: counter.front_door
    mode: single
  - id: "1606157835544"
    alias: "^Porch: Front Door Closed Turn Off Porch Light"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        from: "on"
        to: "off"
        for: 00:01:00
    condition: []
    action:
      - scene: scene.porch_lights_off
      - service: script.post_to_home_log
        data:
          message: ":door: Front door closed for 1 minute. Turning off porch light."
    mode: single
input_boolean:
  enable_porch_light_override:
    name: Enable Bathroom Override Feature
    icon: mdi:door
  porch_light_override:
    name: Bathroom Light Override
    icon: mdi:lightbulb
