# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1595678795894"
    alias: "Utility: Freezer Door Open"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.utility_freezer_door
        from: "off"
        to: "on"
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: ":door: :snowflake: Freezer door is open."
          title: ":fountain: Utility Room"
          log_level: "Debug"
    mode: single
  - id: "1595678900777"
    alias: "Utility: Freezer Door Closed"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.utility_freezer_door
        from: "on"
        to: "off"
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: ":door: :snowflake: Freezer door closed"
          title: ":fountain: Utility Room"
          log_level: "Debug"
    mode: single
  - id: "1595679010792"
    alias: "Utility: Freezer Open For A Long Period Of Time"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.utility_freezer_door
        from: "off"
        to: "on"
        for: 00:04:00
      - platform: state
        entity_id: binary_sensor.utility_freezer_door
        to: "on"
        for: 00:30:00
      - platform: state
        entity_id: binary_sensor.utility_freezer_door
        to: "on"
        for: 00:45:00
      - platform: state
        entity_id: binary_sensor.utility_freezer_door
        to: "on"
        for: 01:00:00
    condition: []
    action:
      - parallel:
          - service: script.send_direct_notification
            data:
              message: >-
                :warning: :door: :snowflake: Freezer door has been open for more than
                {{ relative_time(states.binary_sensor.utility_freezer_door.last_changed) }}!
              title: ":fountain: Utility Room"
          - service: script.alexa_announce
            data:
              message: >-
                Utility Room â„ Freezer door has been open for more than
                {{ relative_time(states.binary_sensor.utility_freezer_door.last_changed) }}!
    mode: single
  - id: "1657801925106"
    alias: "Utility: Freezer Plug Turned Off"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - switch.freezer
        to: "off"
        for:
          hours: 0
          minutes: 1
          seconds: 0
    condition: []
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: Freezer plug is turned off.
              title: ":fountain: Utility Room"
              log_level: "Normal"
          - service: script.send_actionable_notification_with_2_buttons
            data:
              message: Freezer plug is turned off. Turn on?
              title: ":fountain: Utility Room"
              log_level: "Normal"
              people:
                - person.danny
              action1_title: "Yes"
              action1_name: switch_on_freezer
              action2_title: "No"
              action2_name: ignore
    mode: single
  # Washing Machine
  - id: "1595679010794"
    alias: "Utility: Washing Machine Started"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine_powered_on
        to: "on"
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: ":shirt: :soap: Washing Machine :arrow_forward: Started."
          title: "Utility Room"
          log_level: "Debug"
    mode: single
  - id: "1595679010795"
    alias: "Utility: Washing Machine Finished"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine_powered_on
        from: "on"
        to: "off"
    condition: []
    action:
      - parallel:
          - service: script.washing_complete_notification
            data:
              message: ":shirt: :soap: Washing Machine :checkered_flag: Finished."
              title: "Utility Room"
    mode: single

script:
  washing_complete_notification:
    alias: Washing Complete Notification
    fields:
      message:
        description: Message to post
        required: true
        selector:
          text:
            multiline: true
      title:
        description: (optional)Title to the message posted.
        selector:
          text:
    variables:
      people_home: "{% set people = namespace(home=[]) %}
        {% for p in state_attr('group.adult_people', 'entity_id')|default([]) %}
        {% if states(p) == 'home' %}
        {% set people.home = people.home + [p] %}
        {% endif %}
        {% endfor %}
        {{ people.home }}"
    sequence:
      - if:
          - condition: template
            value_template: "{{ (people_home|default([]))|length > 0 }}"
          - condition: time
            before: "22:00:00"
            after: "09:00:00"
        then:
          - parallel:
              - service: script.send_direct_notification
                data:
                  message: "{{ message }}"
                  title: "{{ title }}"
                  people: "{{ people_home }}"
              - service: script.alexa_announce
                data:
                  message: "{{ message|replace(':shirt:', '')|replace(':soap:', '')|replace(':checkered_flag: ', '') }}"
                  title: "{{ title }}"
        else:
          - service: script.send_to_home_log
            data:
              message: "{{ message }}"
              title: "{{ title }}"
              log_level: "Debug"
    mode: single
    icon: mdi:washing-machine

sensor:
  # Washing Machine
  - platform: history_stats
    name: Washing Machine Running Time Today
    unique_id: 8e7b3f2e-d65b-4b73-929d-7425bf08e610
    entity_id: binary_sensor.washing_machine_powered_on
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Washing Machine Running Time Last 24 Hours
    unique_id: 9bd7e07f-91bf-46a6-bc5d-c3f418874633
    entity_id: binary_sensor.washing_machine_powered_on
    state: "on"
    type: time
    end: "{{ now() }}"
    duration:
      hours: 24
  - platform: history_stats
    name: Washing Machine Running Time Yesterday
    unique_id: a6729412-5121-49b8-b4fc-d6cd4e9f836e
    entity_id: binary_sensor.washing_machine_powered_on
    state: "on"
    type: time
    end: "{{ now().replace(hour=0, minute=0, second=0) }}"
    duration:
      hours: 24
  - platform: history_stats
    name: Washing Machine Running Time This Week
    unique_id: 2f44e30c-a022-47a2-8c76-bc6561687b4b
    entity_id: binary_sensor.washing_machine_powered_on
    state: "on"
    type: time
    start: "{{ as_timestamp( now().replace(hour=0, minute=0, second=0) ) - now().weekday() * 86400 }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Washing Machine Running Time Last 30 Days
    unique_id: 3e744fc4-6631-4aed-ad62-8464b3ae24db
    entity_id: binary_sensor.washing_machine_powered_on
    state: "on"
    type: time
    end: "{{ now().replace(hour=0, minute=0, second=0) }}"
    duration:
      days: 30

template:
  - trigger:
      - platform: numeric_state
        entity_id: sensor.washing_machine_current_consumption
        for:
          hours: 0
          minutes: 1
          seconds: 0
        above: "9"
      - platform: numeric_state
        entity_id: sensor.washing_machine_current_consumption
        for:
          hours: 0
          minutes: 1
          seconds: 30
        below: "10"
      - platform: homeassistant
        event: start
    binary_sensor:
      - name: "Washing Machine Powered On"
        unique_id: ac5bc0d6-2199-4a2a-8d23-c2f81e8fe0dd
        device_class: "running"
        icon: "mdi:washing-machine{{ '' if states('sensor.washing_machine_current_consumption') | float(0) > 9 else '-off' }}"
        state: "{{ states('sensor.washing_machine_current_consumption') | float(0) > 9 }}"
