# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1595678795894"
    alias: "Utility: Freezer Door Open"
    description: ""
    trigger:
      - entity_id: binary_sensor.freezer_2_door
        from: "off"
        platform: state
        to: "on"
    condition: []
    action:
      - data:
          message: ":door: :snowflake: Freezer door is open"
        service: script.send_to_home_log
    mode: single
  - id: "1595678900777"
    alias: "Utility: Freezer Door Closed"
    description: ""
    trigger:
      - entity_id: binary_sensor.freezer_2_door
        from: "on"
        platform: state
        to: "off"
    condition: []
    action:
      - data:
          message: ":door: :snowflake: Freezer door closed"
        service: script.send_to_home_log
    mode: single
  - id: "1595679010792"
    alias: "Utility: Freezer Open For A Long Period Of Time"
    description: ""
    trigger:
      - entity_id: binary_sensor.freezer_2_door
        for: 00:04:00
        from: "off"
        platform: state
        to: "on"
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: "Reloading Smartthings integration to see if the sensor lagged out."
          title: "Utility freezer door is open"
      - service: rest_command.reload_smartthings
        data: {}
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - if:
          - condition: state
            entity_id: binary_sensor.freezer_2_door
            state: "on"
        then:
          - service: script.send_direct_notification
            data:
              message:
                ":warning: :door: :snowflake: Freezer door has been open for more than
                4 minutes!"
              title: "Utility Room"
    mode: single
  # Washing Machine
  - id: "1595679010794"
    alias: "Utility: Washing Machine Started"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine_powered_on
        to: "on"
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: ":arrow_forward: Started."
          title: ":shirt: :soap: Washing Machine"
    mode: single
  - id: "1595679010795"
    alias: "Utility: Washing Machine Finished"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine_powered_on
        to: "off"
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: ":checkered_flag: Finished."
          title: ":shirt: :soap: Washing Machine"
    mode: single

template:
  - trigger:
      - platform: numeric_state
        entity_id: sensor.washing_machine_current_consumption
        for:
          hours: 0
          minutes: 1
          seconds: 0
        above: "9"
      - platform: numeric_state
        entity_id: sensor.washing_machine_current_consumption
        for:
          hours: 0
          minutes: 1
          seconds: 0
        below: "10"
      - platform: homeassistant
        event: start
    binary_sensor:
      - name: "Washing Machine Powered On"
        unique_id: ac5bc0d6-2199-4a2a-8d23-c2f81e8fe0dd
        device_class: "running"
        icon: "mdi:washing-machine{{ '' if states('sensor.washing_machine_current_consumption') | float(0) > 9 else '-off' }}"
        state: "{{ states('sensor.washing_machine_current_consumption') | float(0) > 9 }}"
