# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1595678795894"
    alias: "^Utility: Freezer Door Open"
    description: ""
    trigger:
      - entity_id: binary_sensor.freezer_contact
        from: "off"
        platform: state
        to: "on"
    condition: []
    action:
      - data:
          message: ":door: :snowflake: Freezer door is open"
        service: script.post_to_home_log
    mode: single
