# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1595678795894"
    alias: "Utility: Freezer Door Open"
    description: ""
    trigger:
      - entity_id: binary_sensor.utility_freezer_door
        from: "off"
        platform: state
        to: "on"
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: ":door: :snowflake: Freezer door is open"
          log_level: "Debug"
    mode: single
  - id: "1595678900777"
    alias: "Utility: Freezer Door Closed"
    description: ""
    trigger:
      - entity_id: binary_sensor.utility_freezer_door
        from: "on"
        platform: state
        to: "off"
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: ":door: :snowflake: Freezer door closed"
          log_level: "Debug"
    mode: single
  - id: "1595679010792"
    alias: "Utility: Freezer Open For A Long Period Of Time"
    description: ""
    trigger:
      - entity_id: binary_sensor.utility_freezer_door
        for: 00:04:00
        from: "off"
        platform: state
        to: "on"
    condition: []
    action:
      - service: script.send_direct_notification
        data:
          message:
            ":warning: :door: :snowflake: Freezer door has been open for more than
            4 minutes!"
          title: "Utility Room"
    mode: single
  - id: "1657801925106"
    alias: "Utility: Freezer Plug Turned Off"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - switch.freezer
        to: "off"
        for:
          hours: 0
          minutes: 1
          seconds: 0
    condition: []
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message: Freezer plug is turned off.
              title: Utility Room
              log_level: "Normal"
          - service: script.send_actionable_notification_with_2_buttons
            data:
              message: Freezer plug is turned off. Turn on?
              title: Utility Room
              log_level: "Normal"
              people:
                - person.danny
              action1_title: "Yes"
              action1_name: switch_on_freezer
              action2_title: "No"
              action2_name: ignore
    mode: single
  # Washing Machine
  - id: "1595679010794"
    alias: "Utility: Washing Machine Started"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine_powered_on
        to: "on"
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: ":arrow_forward: Started."
          title: ":shirt: :soap: Washing Machine"
          log_level: "Debug"
    mode: single
  - id: "1595679010795"
    alias: "Utility: Washing Machine Finished"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine_powered_on
        to: "off"
    condition: []
    action:
      - service: script.washing_complete_notification
        data:
          message: ":checkered_flag: Finished."
          title: ":shirt: :soap: Washing Machine"
    mode: single

script:
  washing_complete_notification:
    alias: Washing Complete Notification
    fields:
      message:
        description: Message to post
        required: true
      title:
        description: (optional)Title to the message posted.
    variables:
      people_home: "{% set people = namespace(home=[]) %}
        {% for p in state_attr('group.adult_people', 'entity_id')|default([]) %}
        {% if states(p) == 'home' %}
        {% set people.home = people.home + [p] %}
        {% endif %}
        {% endfor %}
        {{ people.home }}"
    sequence:
      - if:
          - condition: template
            value_template: "{{ (people_home|default([]))|length > 0 }}"
          - condition: time
            before: "22:00:00"
            after: "09:00:00"
        then:
          - service: script.send_direct_notification
            data:
              message: "{{ message }}"
              title: "{{ title }}"
              people: "{{ people_home }}"
        else:
          - service: script.send_to_home_log
            data:
              message: "{{ message }}"
              title: "{{ title }}"
              log_level: "Debug"
    mode: single
    icon: mdi:washing-machine

template:
  - trigger:
      - platform: numeric_state
        entity_id: sensor.washing_machine_current_consumption
        for:
          hours: 0
          minutes: 1
          seconds: 0
        above: "9"
      - platform: numeric_state
        entity_id: sensor.washing_machine_current_consumption
        for:
          hours: 0
          minutes: 1
          seconds: 30
        below: "10"
      - platform: homeassistant
        event: start
    binary_sensor:
      - name: "Washing Machine Powered On"
        unique_id: ac5bc0d6-2199-4a2a-8d23-c2f81e8fe0dd
        device_class: "running"
        icon: "mdi:washing-machine{{ '' if states('sensor.washing_machine_current_consumption') | float(0) > 9 else '-off' }}"
        state: "{{ states('sensor.washing_machine_current_consumption') | float(0) > 9 }}"
