# Created by Danny Tsang <danny@tsang.uk>
automation:
  #region Light
  - id: "1741438466512"
    alias: "Utility Room: Motion Detected"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.utility
          - binary_sensor.utility_room_motion_occupancy
          - binary_sensor.utility_room_light_trigger
        to: "on"
    conditions: []
    actions:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: ":paw_prints: Motion detected. Turning :bulb: light off."
              title: ":fountain: Utility Room"
              log_level: "Debug"
          - action: switch.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: switch.utility_room_light_switch_0
    mode: single
  - id: "1741438515604"
    alias: "Utility Room: No Motion Detected"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.utility_room_light_trigger
        to: "off"
        for:
          hours: 0
          minutes: 2
          seconds: 0
    conditions: []
    actions:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: ":no_pedestrians: No motion detected. Turning light off."
              title: ":fountain: Utility Room"
              log_level: "Debug"
          - action: switch.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: switch.utility_room_light_switch_0
    mode: single
  #endRegion
  #region Freezer
  - id: "1595678795894"
    alias: "Utility: Freezer Door Open"
    description: ""
    triggers:
      - trigger: state
        entity_id: binary_sensor.utility_freezer_door_contact
        from: "off"
        to: "on"
    conditions: []
    actions:
      - action: script.send_to_home_log
        data:
          message: ":door: :snowflake: Freezer door is open."
          title: ":fountain: Utility Room"
          log_level: "Debug"
    mode: single
  - id: "1595678900777"
    alias: "Utility: Freezer Door Closed"
    description: ""
    triggers:
      - trigger: state
        entity_id: binary_sensor.utility_freezer_door_contact
        from: "on"
        to: "off"
    conditions: []
    actions:
      - action: script.send_to_home_log
        data:
          message: ":door: :snowflake: Freezer door closed"
          title: ":fountain: Utility Room"
          log_level: "Debug"
    mode: single
  - id: "1595679010792"
    alias: "Utility: Freezer Open For A Long Period Of Time"
    description: ""
    triggers:
      - trigger: state
        entity_id: binary_sensor.utility_freezer_door_contact
        from: "off"
        to: "on"
        for: 00:04:00
      - trigger: state
        entity_id: binary_sensor.utility_freezer_door_contact
        to: "on"
        for: 00:30:00
      - trigger: state
        entity_id: binary_sensor.utility_freezer_door_contact
        to: "on"
        for: 00:45:00
      - trigger: state
        entity_id: binary_sensor.utility_freezer_door_contact
        to: "on"
        for: 01:00:00
    conditions: []
    actions:
      - parallel:
          - action: script.send_direct_notification
            data:
              message: >-
                :warning: :door: :snowflake: Freezer door has been open for more than
                {{ relative_time(states.binary_sensor.utility_freezer_door_contact.last_changed) }}!
              title: ":fountain: Utility Room"
          - action: script.alexa_announce
            data:
              message: >-
                Utility Room â„ Freezer door has been open for more than
                {{ relative_time(states.binary_sensor.utility_freezer_door_contact.last_changed) }}!
    mode: single
  - id: "1657801925106"
    alias: "Utility: Freezer Plug Turned Off"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - switch.freezer
        to: "off"
        for:
          hours: 0
          minutes: 1
          seconds: 0
    conditions: []
    actions:
      - parallel:
          - action: script.send_to_home_log
            data:
              message: Freezer plug is turned off.
              title: ":fountain: Utility Room"
              log_level: "Normal"
          - action: script.send_actionable_notification_with_2_buttons
            data:
              message: Freezer plug is turned off. Turn on?
              title: ":fountain: Utility Room"
              log_level: "Normal"
              people:
                entity_id:
                  - person.danny
              action1_title: "Yes"
              action1_name: switch_on_freezer
              action2_title: "No"
              action2_name: ignore
    mode: single
  #endRegion
  #region Washing Machine
  - id: "1595679010794"
    alias: "Utility: Washing Machine Started"
    description: ""
    triggers:
      - trigger: state
        entity_id: binary_sensor.washing_machine_powered_on
        to: "on"
    conditions: []
    actions:
      - action: script.send_to_home_log
        data:
          message: ":shirt: :soap: Washing Machine :arrow_forward: Started."
          title: "Utility Room"
          log_level: "Debug"
    mode: single
  - id: "1595679010795"
    alias: "Utility: Washing Machine Finished"
    description: ""
    triggers:
      - trigger: state
        entity_id: binary_sensor.washing_machine_powered_on
        from: "on"
        to: "off"
    conditions: []
    actions:
      - action: script.washing_complete_notification
        data:
          message: ":shirt: :soap: Washing Machine :checkered_flag: Finished."
          title: "Utility Room"
    mode: single
  #endRegion

script:
  washing_complete_notification:
    alias: Washing Complete Notification
    description: "TODO: refactor this with dishwashing complete notification."
    fields:
      message:
        description: Message to post
        required: true
        selector:
          text:
            multiline: true
      title:
        description: (optional)Title to the message posted.
        selector:
          text:
    variables:
      people_home: "{% set people = namespace(home=[]) %}
        {% for p in state_attr('group.tracked_people', 'entity_id')|default([]) %}
        {% if states(p) == 'home' %}
        {% set people.home = people.home + [p] %}
        {% endif %}
        {% endfor %}
        {{ people.home }}"
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: group.tracked_people
                state: "home"
              - condition: time
                before: "22:00:00"
                after: "09:00:00"
            sequence:
              - parallel:
                  - action: script.send_direct_notification
                    data:
                      message: "{{ message }}"
                      title: "{{ title }}"
                      people:
                        entity_id: "{{ people_home }}"
                  - action: script.alexa_announce
                    data:
                      message: "{{ message|replace(':shirt:', '')|replace(':soap:', '')|replace(':checkered_flag: ', '') }}"
                      title: "{{ title }}"
        default:
          - parallel:
              - action: script.send_to_home_log
                data:
                  message: "{{ message }}"
                  title: "{{ title }}"
                  log_level: "Debug"
              - action: todo.add_item
                data:
                  item: "{{ message }}"
                target:
                  entity_id: todo.dannys_notifications
    mode: single
    icon: mdi:washing-machine
  utility_room_turn_off_camera:
    alias: Utility_room Turn Off Camera
    icon: mdi:cctv-off
    sequence:
      - action: script.send_to_home_log
        data:
          message: "Turning utility_room :camera: camera detection off."
      - action: switch.turn_off
        target:
          entity_id:
            - switch.utility_room_detect
            - switch.utility_room_motion
    mode: single
  utility_room_turn_on_camera:
    alias: Utility_room Turn On Camera
    icon: mdi:cctv
    sequence:
      - action: switch.turn_on
        target:
          entity_id:
            - switch.utility_room_detect
            - switch.utility_room_motion
    mode: single

sensor:
  # Washing Machine
  - platform: history_stats
    name: Washing Machine Running Time Today
    unique_id: 8e7b3f2e-d65b-4b73-929d-7425bf08e610
    entity_id: binary_sensor.washing_machine_powered_on
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Washing Machine Running Time Last 24 Hours
    unique_id: 9bd7e07f-91bf-46a6-bc5d-c3f418874633
    entity_id: binary_sensor.washing_machine_powered_on
    state: "on"
    type: time
    end: "{{ now() }}"
    duration:
      hours: 24
  - platform: history_stats
    name: Washing Machine Running Time Yesterday
    unique_id: a6729412-5121-49b8-b4fc-d6cd4e9f836e
    entity_id: binary_sensor.washing_machine_powered_on
    state: "on"
    type: time
    end: "{{ now().replace(hour=0, minute=0, second=0) }}"
    duration:
      hours: 24
  - platform: history_stats
    name: Washing Machine Running Time This Week
    unique_id: 2f44e30c-a022-47a2-8c76-bc6561687b4b
    entity_id: binary_sensor.washing_machine_powered_on
    state: "on"
    type: time
    start: "{{ as_timestamp( now().replace(hour=0, minute=0, second=0) ) - now().weekday() * 86400 }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Washing Machine Running Time Last 30 Days
    unique_id: 3e744fc4-6631-4aed-ad62-8464b3ae24db
    entity_id: binary_sensor.washing_machine_powered_on
    state: "on"
    type: time
    end: "{{ now().replace(hour=0, minute=0, second=0) }}"
    duration:
      days: 30

template:
  - trigger:
      - trigger: numeric_state
        entity_id: sensor.washing_machine_current_consumption
        for:
          hours: 0
          minutes: 0
          seconds: 45
        above: "2.4"
      - trigger: numeric_state
        entity_id: sensor.washing_machine_current_consumption
        for:
          hours: 0
          minutes: 1
          seconds: 45
        below: "2.5"
      - trigger: homeassistant
        event: start
    binary_sensor:
      - name: "Washing Machine Powered On"
        unique_id: ac5bc0d6-2199-4a2a-8d23-c2f81e8fe0dd
        device_class: "running"
        icon: "mdi:washing-machine{{ '' if states('sensor.washing_machine_current_consumption') | float(0) > 9 else '-off' }}"
        state: "{{ states('sensor.washing_machine_current_consumption') | float(0) > 9 }}"
