substitutions:
  name: apollo-r-pro-1-eth-ef755c
  friendly_name: living_room-motion-3
packages:
  ApolloAutomation.R-PRO-1-ETH: github://ApolloAutomation/R_PRO-1/Integrations/ESPHome/R_PRO-1_ETH.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret living_room_motion_3_api_encryption_key
