esphome:
  name: attic
  platform: ESP32
  board: esp32dev

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

# esp32_ble_tracker:

# Enable logging
logger:

sensor:
  # Analogue
  - platform: adc
    pin: 36
    name: "Water Tank Level"
    update_interval: 60s
  # BME680
  - platform: bme680
    address: 0x77
    temperature:
      name: "Attic Temperature"
      oversampling: 16x
    pressure:
      name: "Attic Air Pressure"
    humidity:
      name: "Attic Humidity"
      id: hum
    gas_resistance:
      name: "Attic Gas Resistance"
      id: g_res
    update_interval: 60s
  # https://community.home-assistant.io/t/bme680-gas-resistance-values/140719/15
  - platform: template
    name: "Attic IAQ"
    id: Attic_IAQ
    unit_of_measurement: IAQ
    lambda: "return log(id(g_res).state) + 0.04 * id(hum).state;"
  # Platform sensors
  - platform: uptime
    name: Attic Uptime Sensor

# Enable Home Assistant API
api:

ota:
  password: !secret test_ota_password

wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: !secret test_fallback_password

captive_portal:
