esphome:
  name: bed
  platform: ESP32
  board: esp32dev

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

ads1115:
  - address: 0x48
    continuous_mode: true

#esp32_ble_tracker:

sensor:
  # ADS1115
  - platform: ads1115
    multiplexer: 'A0_GND'
    gain: 4.096
    name: "Bed Top Left"
  - platform: ads1115
    multiplexer: 'A1_GND'
    gain: 4.096
    name: "Bed Top Right"
  - platform: ads1115
    multiplexer: 'A2_GND'
    gain: 4.096
    name: "Bed Bottom Left"
  - platform: ads1115
    multiplexer: 'A3_GND'
    gain: 4.096
    name: "Bed Bottom Right"
  # BME680
  - platform: bme680
    address: 0x77
    temperature:
      name: "Bedroom Temperature"
      oversampling: 16x
    pressure:
      name: "Bedroom Air Pressure"
    humidity:
      name: "Bedroom Humidity"
      id: hum
    gas_resistance:
      name: "Bedroom Gas Resistance"
      id: g_res
    update_interval: 60s
  # https://community.home-assistant.io/t/bme680-gas-resistance-values/140719/15
  - platform: template
    name: "Bed IAQ"
    id: Bed_IAQ
    unit_of_measurement: IAQ
    lambda: "return log(id(g_res).state) + 0.04 * id(hum).state;"
  # Platform sensors
  - platform: uptime
    name: Uptime Sensor

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret bed_ota_password

wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bed Fallback Hotspot"
    password: !secret bed_fallback_password

captive_portal:
