esphome:
  name: esp8266-test

esp8266:
  board: d1_mini  # IMPORTANT: use the actual board from your original config
  framework:
    version: 3.1.1

logger:
  level: DEBUG

wifi:
  output_power: 20dB

  ap:
    ssid: "ESP8266-Test"
    channel: 6