substitutions:
  name: "conservatory-motion"
packages:
  Everything_Smart_Technology.Everything_Presence_One: github://everythingsmarthome/presence-one/everything-presence-one.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  #  https://community.home-assistant.io/t/compilation-fails-xtensa-lx106-elf-g-fatal-error-killed-signal-terminated-program-cc1plus/463184/14
  compile_process_limit: 1
esp32:
  board: esp32dev
  framework:
    type: esp-idf

esp32_ble_tracker:
  scan_parameters:
    active: true  # Whether to send scan-request packets to devices to gather more info (like devicename)
    interval: 211ms  # suggested 211ms # default 320ms
    window: 120ms  # suggested 120ms # default 30ms

bluetooth_proxy:
  active: true

switch:
  - platform: restart
    name: "Conservatory Motion Restart"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
