substitutions:
  name: everything-presence-lite-0480c4
  friendly_name: kitchen-motion

packages:
  EverythingSmartTechnology.Everything Presence Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha-co2.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: !secret kitchen_motion_api_encryption_key


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
