substitutions:
  name: everything-presence-one-26eb54
  friendly_name: conservatory-motion-3
packages:
  Everything Smart Technology.Everything Presence One: github://everythingsmarthome/everything-presence-one/everything-presence-one-sen0609-ble.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret conservatory_motion_3_api_encryption_key


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
