substitutions:
  name: "kitchen-motion"
packages:
  Everything_Smart_Technology.Everything_Presence_One: github://everythingsmarthome/presence-one/everything-presence-one.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: !secret kitchen_api_encryption_key

esp32_ble_tracker:

bluetooth_proxy:
  active: true

switch:
  - platform: restart
    name: "Kitchen Motion Restart"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kitchen Fallback Hotspot"
    password: !secret kitchen_fallback_password
