substitutions:
  name: "kitchen-motion"

packages:
  Everything_Smart_Technology.Everything_Presence_One: github://everythingsmarthome/presence-one/everything-presence-one-ble.yaml@main
  bluetooth_base: !include common/bluetooth-base.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false
  #  https://community.home-assistant.io/t/compilation-fails-xtensa-lx106-elf-g-fatal-error-killed-signal-terminated-program-cc1plus/463184/14
  compile_process_limit: 1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
