esphome:
  name: kitchen

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

esp32_ble_tracker:

sensor:
  - platform: xiaomi_hhccjcy01
    mac_address: !secret chlorophytum_comosum_ble_mac
    temperature:
      name: "Chlorophytum Comosum Temperature"
    moisture:
      name: "Chlorophytum Comosum Moisture"
    illuminance:
      name: "Chlorophytum Comosum Illuminance"
    conductivity:
      name: "Chlorophytum Comosum Soil Conductivity"
    battery_level:
      name: "Chlorophytum Comosum Battery Level"
  - platform: xiaomi_hhccjcy01
    mac_address: !secret sansevieria_trifasciata_ble_mac
    temperature:
      name: "Sansevieria Trifasciata Temperature"
    moisture:
      name: "Sansevieria Trifasciata Moisture"
    illuminance:
      name: "Sansevieria Trifasciata Illuminance"
    conductivity:
      name: "Sansevieria Trifasciata Soil Conductivity"
    battery_level:
      name: "Sansevieria Trifasciata Battery Level"

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret kitchen_api_encryption_key

ota:
  password: !secret kitchen_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kitchen Fallback Hotspot"
    password: !secret kitchen_fallback_password

captive_portal:
  
