substitutions:
  name: "living_room-motion"
packages:
  Everything_Smart_Technology.Everything_Presence_One: github://everythingsmarthome/presence-one/everything-presence-one.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
esp32:
  board: esp32dev
  framework:
    type: esp-idf

esp32_ble_tracker:
  scan_parameters:
    active: true  # Whether to send scan-request packets to devices to gather more info (like devicename)
    interval: 320ms  # suggested 211ms # default 320ms
    window: 300ms  # suggested 120ms # default 30ms

bluetooth_proxy:
  active: true

switch:
  - platform: restart
    name: "Living Room Motion Restart"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
