esphome:
  name: lounge
  friendly_name: lounge

esp32:
  board: esp32dev
  framework:
    type: arduino

esp32_ble_tracker:

bluetooth_proxy:
  active: true

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret lounge_api_encryption_key

ota:
  password: !secret lounge_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lounge Fallback Hotspot"
    password: !secret lounge_fallback_password

captive_portal:
