substitutions:
  name: "office-motion"
packages:
  Everything_Smart_Technology.Everything_Presence_One: github://everythingsmarthome/presence-one/everything-presence-one.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
esp32:
  board: esp32dev
  framework:
    type: esp-idf
api:
  encryption:
    key: !secret office_api_encryption_key

esp32_ble_tracker:

bluetooth_proxy:
  active: true

switch:
  - platform: restart
    name: "Office Motion Restart"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
