substitutions:
  name: "office-motion"
packages:
  Everything_Smart_Technology.Everything_Presence_One: github://everythingsmarthome/presence-one/everything-presence-one.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: !secret office_api_encryption_key

esp32_ble_tracker:

bluetooth_proxy:
  active: true

switch:
  - platform: restart
    name: "Leo's Bed Restart"

web_server:
  port: 80
  auth:
    username: !secret office_motion_webserver_username
    password: !secret office_motion_webserver_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Office Fallback Hotspot"
    password: !secret office_fallback_password
