esphome:
  name: test
  platform: ESP32
  board: esp32dev

esp32_ble_tracker:

# Enable logging
logger:

sensor:
  # Platform sensors
  - platform: uptime
    name: Uptime Sensor

# Enable Home Assistant API
api:

ota:
  password: !secret test_ota_password

wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: !secret test_fallback_password

captive_portal:
