esphome:
  name: water-softener
  friendly_name: water-softener

packages:
  bluetooth_base: !include common/bluetooth-base.yaml
  esp32_base: !include common/esp32-base.yaml

esp32:
  board: esp32dev
  framework:
    type: arduino

sensor:
  - platform: ultrasonic
    trigger_pin: GPIO13
    echo_pin: GPIO12
    name: "Salt Level"

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret water_softener_api_encryption_key

ota:
  platform: esphome
  password: !secret water_softener_ota_password
