# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1587680439011"
    alias: "^Alarm: Arm Overnight Home Mode"
    description: ""
    trigger:
      - at: 00:00:00
        platform: time
      - at: 02:00:00
        platform: time
      - at: 05:00:00
        platform: time
    condition:
      - condition: state
        entity_id: group.all_people
        state: home
      - condition: state
        entity_id: group.alarmed_doors_and_windows
        state: "off"
    action:
      - service: alarm_control_panel.alarm_arm_home
        data: {}
        target:
          entity_id: alarm_control_panel.stevenage_alarm
      - data:
          message:
            ":couple: home. Turning alarm on in home mode (door sensors only) :bell:
            :house:"
        service: script.post_to_home_log
    mode: single
  - id: "1614197981954"
    alias: "^Alarm: Disconnected"
    description: ""
    trigger:
      - platform: state
        entity_id: sensor.stevenage_alarm_info
        to: unavailable
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          title: Alarm Offline
          message: ":warning: :no_bell: Alarm has disconnected from @home_assistant :warning:"
    mode: single
group:
  alarmed_doors_and_windows:
    name: Alarmed Doors and Windows
    entities:
      - binary_sensor.conservatory_door
      - binary_sensor.front_door
      - binary_sensor.lounge_left_window
      - binary_sensor.lounge_middle_window
      - binary_sensor.lounge_right_window
      - binary_sensor.office_window_left
      - binary_sensor.office_window_right
      - binary_sensor.shed_door
