# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1614197981954"
    alias: "^Alarm: Disconnected"
    description: ""
    trigger:
      - platform: state
        entity_id: sensor.stevenage_alarm_info
        to: unavailable
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          title: Alarm Offline
          message: ":warning: :no_bell: Alarm has disconnected from @home_assistant :warning:"
    mode: single
