# Created by Danny Tsang <danny@tsang.uk>
# https://github.com/alphasixtyfive/HomeAssistantConfigs/blob/main/octopus_energy_go.yaml
input_text:
  electricity_mpan:
    initial: !secret electricity_mpan
  electricity_serial:
    initial: !secret electricity_serial
  gas_mprn:
    initial: !secret gas_mprn
  gas_serial:
    initial: !secret gas_serial
sensor:
  - platform: rest
    name: Gas consumption yesterday
    resource_template: >-
      {% set mprn = states('input_text.gas_mprn') %}
      {% set serial = states('input_text.gas_serial') %}
      {% set date = as_timestamp(now() - timedelta(days = 1))|timestamp_custom('%Y-%m-%d') %}
      https://api.octopus.energy/v1/gas-meter-points/{{ mprn }}/meters/{{ serial }}/consumption/?period_from={{ date + 'T00:00:00' }}&period_to={{ date + 'T23:59:59' }}
    headers:
      Authorization: !secret octopus_key
    value_template: "{{ value_json.results|sum(attribute='consumption')|round(3) }}"
    unit_of_measurement: "m3"
    json_attributes:
      - "results"

  - platform: template
    sensors:
      gas_cost_yesterday:
        friendly_name: Gas cost yesterday
        icon_template: mdi:cash-multiple
        value_template: >-
          {% set unit_price = 2.86 %}
          {% set standing_charge = 26.06 %}
          {% set calorific_value = 39.1 %}
          {% set usage = state_attr('sensor.gas_consumption_yesterday', 'results') %}
          {% if usage is defined and usage|count == 48 %}
            {{ ((states('sensor.gas_consumption_yesterday') | float * 1.02264 * calorific_value / 3.6) * unit_price / 100 + standing_charge / 100)|round(2) }}
          {% else %}
            Unknown
          {% endif %}
        unit_of_measurement: "£"

  - platform: rest
    name: Electricity consumption yesterday
    resource_template: >-
      {% set mpan = states('input_text.electricity_mpan') %}
      {% set serial = states('input_text.electricity_serial') %}
      {% set date = as_timestamp(now() - timedelta(days = 1))|timestamp_custom('%Y-%m-%d') %}
      https://api.octopus.energy/v1/electricity-meter-points/{{ mpan }}/meters/{{ serial }}/consumption/?period_from={{ date + 'T00:00:00' }}&period_to={{ date + 'T23:59:59' }}
    headers:
      Authorization: !secret octopus_key
    value_template: "{{ value_json.results|sum(attribute='consumption')|round(3) }}"
    unit_of_measurement: "kWh"
    json_attributes:
      - "results"

  - platform: template
    sensors:
      electricity_cost_yesterday:
        friendly_name: Electricity cost yesterday
        icon_template: mdi:cash-multiple
        value_template: >-
          {% set standing_charge = 25 %}
          {% set usage = state_attr('sensor.electricity_consumption_yesterday', 'results') %}
          {% if usage is defined and usage|count == 48 %}
            {% set ns = namespace(total=0) %}
            {% for p in range(0, 48) %}
              {% set time = as_timestamp(usage[p].interval_start)|timestamp_custom('%H:%M:%S') %}
              {% set unit_price = 15.96 %}
              {% if '00:30:00' <= time < '04:30:00' %}
                {% set unit_price = 5 %}
              {% endif %}
              {% set ns.total = ns.total + (usage[p].consumption * unit_price / 100) %}
            {% endfor %}
            {{ (ns.total + standing_charge / 100)|round(2) }}
          {% else %}
            Unknown
          {% endif %}
        unit_of_measurement: "£"

  - platform: template
    sensors:
      current_electriity_unit_cost:
        value_template: "{% if [now().hour, now().minute]|join()|int <= 430  %} 0.05 {% else %} 0.1596 {% endif %}"
        friendly_name: "Current Electricity Unit Cost"
        unit_of_measurement: "£"
        icon_template: mdi:cash-multiple
  # Total energy usage using energy@home <https://github.com/dannytsang/energyathome>
  - platform: sql
    db_url: !secret energyathome
    queries:
      - name: House Power Meter
        query: "SELECT id,date_time,channel_id,data FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 18 LIMIT 1) LIMIT 1) AND unit = 'W' AND date_time >= NOW() - INTERVAL 30 MINUTE ORDER BY date_time DESC LIMIT 1;"
        column: "data"
        unit_of_measurement: W
  # Computer A
  - platform: sql
    db_url: !secret energyathome
    queries:
      - name: JD Power Meter
        query: "SELECT id,date_time,channel_id,data FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 19 LIMIT 1) AND date_time >= NOW() - INTERVAL 30 MINUTE ORDER BY date_time DESC LIMIT 1;"
        column: "data"
        unit_of_measurement: W
  # Computer B
  - platform: sql
    db_url: !secret energyathome
    queries:
      - name: Server Power Meter
        query: "SELECT id,date_time,channel_id,data FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 37 LIMIT 1) AND date_time >= NOW() - INTERVAL 30 MINUTE ORDER BY date_time DESC LIMIT 1;"
        column: "data"
        unit_of_measurement: W
  # Telephony
  - platform: sql
    db_url: !secret energyathome
    queries:
      - name: Telephony Power Meter
        query: "SELECT id,date_time,channel_id,data FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 26 LIMIT 1) AND date_time >= NOW() - INTERVAL 30 MINUTE ORDER BY date_time DESC LIMIT 1;"
        column: "data"
        unit_of_measurement: W
  # Fridge Freezer
  - platform: sql
    db_url: !secret energyathome
    queries:
      - name: Fridge Freezer Power Meter
        query: "SELECT id,date_time,channel_id,data/1000 as data FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 20 LIMIT 1) AND date_time >= NOW() - INTERVAL 30 MINUTE ORDER BY date_time DESC LIMIT 1;"
        column: "data"
        unit_of_measurement: W
  # Freezer
  - platform: sql
    db_url: !secret energyathome
    queries:
      - name: Freezer Power Meter
        query: "SELECT id,date_time,channel_id,data as data FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 28 LIMIT 1) AND date_time >= NOW() - INTERVAL 30 MINUTE ORDER BY date_time DESC LIMIT 1;"
        column: "data"
        unit_of_measurement: W
  # Home Entertainment
  - platform: sql
    db_url: !secret energyathome
    queries:
      - name: Home Entertainment Power Meter
        query: "SELECT id,date_time,channel_id,data/1000 as data FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 21 LIMIT 1) AND date_time >= NOW() - INTERVAL 30 MINUTE ORDER BY date_time DESC LIMIT 1;"
        column: "data"
        unit_of_measurement: W
  # Surround Sound
  - platform: sql
    db_url: !secret energyathome
    queries:
      - name: Surround Sound Power Meter
        query: "SELECT id,date_time,channel_id,data as data FROM energyathome.historical_data WHERE channel_id = (SELECT channel_id FROM channel WHERE device_id = 29 LIMIT 1) AND date_time >= NOW() - INTERVAL 30 MINUTE ORDER BY date_time DESC LIMIT 1;"
        column: "data"
        unit_of_measurement: W
  # Convert power to energy (e.g. W to Wh)
  - platform: integration
    source: sensor.house_power_meter
    name: House Energy Meter
    unit_prefix: k
    round: 2
  - platform: integration
    source: sensor.jd_power_meter
    name: JD Energy Meter
    unit_prefix: k
    round: 2
  - platform: integration
    source: sensor.server_power_meter
    name: House Energy Meter
    unit_prefix: k
    round: 2
  - platform: integration
    source: sensor.telephony_power_meter
    name: JD Energy Meter
    unit_prefix: k
    round: 2
  - platform: integration
    source: sensor.fridge_freezer_power_meter
    name: House Energy Meter
    unit_prefix: k
    round: 2
  - platform: integration
    source: sensor.freezer_power_meter
    name: JD Energy Meter
    unit_prefix: k
    round: 2
  - platform: integration
    source: sensor.home_entertainment_power_meter
    name: House Energy Meter
    unit_prefix: k
    round: 2
  - platform: integration
    source: sensor.surround_sound_power_meter
    name: JD Energy Meter
    unit_prefix: k
    round: 2
