# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1613937312554"
    alias: "^Home Assistant CI"
    description: "https://community.home-assistant.io/t/guide-to-setting-up-a-fully-automated-ci-for-hassio/51576"
    trigger:
      - platform: state
        entity_id: sensor.travis_ci_build_status
        from: started
        to: passed
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":construction_worker: :hammer_and_wrench:  Travis CI
            build passed :white_check_mark:. Pulling changes."
      - service: hassio.addon_start
        data:
          addon: core_git_pull
    mode: single
input_boolean:
  enable_git_automations:
    name: Enable git integration
    icon: mdi:github
sensor:
  # Travis CI build status
  - platform: rest
    resource: !secret travis_ci_url
    headers:
      Accept: application/vnd.travis-ci.2+json
      Authorization: !secret travis_ci_token
      Travis-API-Version: 3
    value_template: "{{ value_json.builds[0].state }}"
    name: "Travis CI Build Status"
