# Created by Danny Tsang <danny@tsang.uk>
automation:
  # Change modes
  - id: "1649891307330"
    alias: "^Mode: Check If Scheduled Mode"
    description: Check if the schedule mode is set for the same day as today.
    trigger:
      - platform: time
        at: input_datetime.start_of_next_mode
    condition:
      - condition: state
        entity_id: input_boolean.enable_scheduled_mode
        state: "on"
    action:
      - choose:
          - conditions:
              - not:
                  - condition: state
                    entity_id: input_select.home_mode
                    state: input_select.next_scheduled_home_mode
            sequence:
              - service: script.send_to_home_log
                data:
                  message:
                    Scheduled mode change to {{ states('input_select.next_scheduled_home_mode')
                    }}
              - service: input_select.select_option
                data:
                  option: "{{ states('input_select.next_scheduled_home_mode') }}"
                target:
                  entity_id: input_select.home_mode
        default:
          - service: script.send_to_home_log
            data:
              message: Current mode and scheduled mode are the same.
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.enable_scheduled_mode
    mode: single
  - id: "1658594276643"
    alias: "^Home Mode: Set Scheduled Home Mode"
    description: ""
    trigger:
      - platform: time
        at: 00:00:01
    condition:
      - condition: state
        entity_id: input_boolean.enable_scheduled_mode
        state: "off"
    action:
      - service: script.send_to_home_log
        data:
          message: Updating Scheduled Home Mode to current date and time.
          title: Home Mode
      - service: input_datetime.set_datetime
        data:
          # https://community.home-assistant.io/t/assign-current-date-and-time-to-my-input-datetime/214493/10
          datetime: "{{ now().timestamp() | timestamp_local }}"
        entity_id: input_datetime.start_of_next_mode
    mode: single
  # Handle mode changes
  - id: "1631138390675"
    alias: "^Home Mode: Changed"
    description: ""
    trigger:
      - platform: state
        entity_id: input_select.home_mode
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: ":repeat: Entering {{ states('input_select.home_mode') }} mode."
          title: "Home Mode"
      - choose:
          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: "Holiday"
            sequence:
              - service: script.home_mode_turn_on_holiday_mode
                data: {}
          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: "Normal"
            sequence:
              - service: script.home_mode_turn_on_normal_mode
                data: {}
        default: []
    mode: single
  # Privacy Mode
  - id: "1646257483770"
    alias: "^Home: Privacy Mode Turned On"
    description: ""
    trigger:
      - platform: state
        entity_id: input_boolean.privacy_mode
        to: "on"
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: ":detective: Privacy mode enabled."
      - service: script.send_to_home_log
        data:
          message: ":camera: Turning conservatory camera recording and detction off."
      - service: script.conservatory_turn_off_camera
        data: {}
      - service: script.send_to_home_log
        data:
          message: ":camera: Turning lounge camera recording and detction off."
      - service: script.lounge_turn_off_camera
        data: {}
    mode: single

script:
  home_mode_turn_on_holiday_mode:
    alias: Home Mode Turn On Holiday Mode
    icon: mdi:airplane
    sequence:
      - service: script.set_central_heating_to_away_mode
        data: {}
      - service: script.set_how_water_to_away_mode
        data: {}
      - service: script.send_to_home_log
        data:
          message: "Finished setting up :airplane: holiday mode"
          title: Home Mode
    mode: single
  home_mode_turn_on_normal_mode:
    alias: Home Mode Turn On Normal Mode
    icon: mdi:home
    sequence:
      - service: script.set_central_heating_to_home_mode
        data: {}
      - service: script.set_how_water_to_home_mode
        data: {}
      - service: script.send_to_home_log
        data:
          message: "Finished setting up normal mode"
          title: Home Mode
    mode: single
