# Created by Danny Tsang <danny@tsang.uk>
automation:
  # Handle mode changes
  - id: "1631138390675"
    alias: "Home Mode: Changed"
    description: ""
    trigger:
      - platform: state
        entity_id: input_select.home_mode
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: ":repeat: Entering {{ states('input_select.home_mode') }} mode."
          title: "Home Mode"
      - choose:
          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: "Holiday"
            sequence:
              - service: script.home_mode_turn_on_holiday_mode
                data: {}
          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: "Normal"
            sequence:
              - service: script.home_mode_turn_on_normal_mode
                data: {}
        default: []
    mode: single
  # Privacy Mode
  - id: "1646257483770"
    alias: "Home: Privacy Mode Turned On"
    description: ""
    trigger:
      - platform: state
        entity_id: input_boolean.privacy_mode
        to: "on"
    condition: []
    action:
      - service: script.send_to_home_log
        data:
          message: ":detective: Privacy mode enabled."
      - service: script.send_to_home_log
        data:
          message: ":camera: Turning conservatory camera recording and detction off."
      - service: script.conservatory_turn_off_camera
        data: {}
      - service: script.send_to_home_log
        data:
          message: ":camera: Turning lounge camera recording and detction off."
      - service: script.lounge_turn_off_camera
        data: {}
    mode: single

script:
  home_mode_turn_on_holiday_mode:
    alias: Home Mode Turn On Holiday Mode
    icon: mdi:airplane
    sequence:
      - parallel:
          - service: script.set_central_heating_to_away_mode
            data: {}
          - service: script.set_how_water_to_away_mode
            data: {}
          - service: script.send_to_home_log
            data:
              message: "Finished setting up :airplane: holiday mode"
              title: Home Mode
    mode: single
  home_mode_turn_on_normal_mode:
    alias: Home Mode Turn On Normal Mode
    icon: mdi:home
    sequence:
      - parallel:
          - service: script.set_central_heating_to_home_mode
            data: {}
          - service: script.set_how_water_to_home_mode
            data: {}
          - service: script.send_to_home_log
            data:
              message: "Finished setting up normal mode"
              title: Home Mode
          - service: script.normal_mode_swtich_on
            data: {}
    mode: single
  # Mode scripts
  holiday_mode_swtich_off:
    alias: Holiday Mode Switch Off
    icon: mdi:power-plug-off
    sequence:
      - service: script.send_to_home_log
        data:
          message: "Turning off Kitchen"
          title: Home Mode
      - service: switch.turn_off
        data: {}
        target:
          entity_id:
            - switch.coffee_machine
            - switch.kettle
      - service: script.send_to_home_log
        data:
          message: "Turning off Lounge"
          title: Home Mode
      - service: switch.turn_off
        data: {}
        target:
          entity_id:
            - switch.harmony_hub_plug
            - switch.playstation_plug
      - service: script.send_to_home_log
        data:
          message: "Turning off Office"
          title: Home Mode
      - service: switch.turn_off
        data: {}
        target:
          entity_id:
            - switch.pc_accessories_plug
  normal_mode_swtich_on:
    alias: Normal Mode Switch On
    icon: mdi:power-plug
    sequence:
      - service: script.send_to_home_log
        data:
          message: "Turning on Kitchen"
          title: Home Mode
      - service: switch.turn_on
        data: {}
        target:
          entity_id:
            - switch.kettle
      - service: script.send_to_home_log
        data:
          message: "Turning on Lounge"
          title: Home Mode
      - service: switch.turn_on
        data: {}
        target:
          entity_id:
            - switch.harmony_hub_plug
            - switch.playstation_plug
      - service: script.send_to_home_log
        data:
          message: "Turning on Office"
          title: Home Mode
      - service: switch.turn_on
        data: {}
        target:
          entity_id:
            - switch.pc_accessories_plug
