# Created by Danny Tsang <danny@tsang.uk>
octoprint:
  host: !secret octoprint
  api_key: !secret octoprint_api
  bed: true
  number_of_tools: 1
automation:
  - id: "1608655560832"
    alias: "^3D Printer: Print Started"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.octoprint_printing
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.enable_3d_printer_automations
        state: "on"
    action:
      - wait_for_trigger:
          - platform: numeric_state
            entity_id: sensor.octoprint_time_remaining
            above: "0"
        timeout: "60"
      - service: script.post_to_home_log
        data:
          message:
            ':printer: 3D printer has started. Estimated time to completion: {{((now().strftime("%s")
            | int + (states("sensor.octoprint_time_remaining") | int)) | timestamp_custom("%H:%M:%S"))}}
            ({{ ((((states("sensor.octoprint_time_remaining") | int) / 60) | float) /
            60) | round(2) }} hours).'
      - service: switch.turn_on
        target:
          entity_id: switch.prusa_fan
    mode: single
  - id: "1609349959402"
    alias: "^3D Printer: Print Finished And Hot End Cooled"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.octoprint_actual_tool0_temp
        below: "50"
    condition:
      - condition: state
        entity_id: input_boolean.enable_3d_printer_automations
        state: "on"
    action:
      - service: script.post_to_home_log
      - service: switch.turn_off
        target:
          entity_id: switch.prusa_fan
    mode: single
input_boolean:
  enable_3d_printer_automations:
    name: Enable 3D printer automations
    icon: mdi:printer-3d
  enable_octoprint_automations:
    name: Enable Octoprint automations
    icon: mdi:printer-3d
