# Created by Danny Tsang <danny@tsang.uk>
octoprint:
  host: !secret octoprint
  api_key: !secret octoprint_api
  bed: true
  number_of_tools: 1
automation:
  - id: "1613321560216"
    alias: "^3D Printer: Finished Printing"
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.octoprint_printing
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.enable_3d_printer_automations
        state: "on"
    action:
      - service: script.post_to_home_log
        data:
          message:
            ':printer: :white_check_mark: Completed 3D printing. Total time: {{
            (((states("sensor.octoprint_time_elapsed") | int) / 60) | float) / 60 }} hours.'
    mode: single
input_boolean:
  enable_3d_printer_automations:
    name: Enable 3D printer automations
    icon: mdi:printer-3d
  enable_octoprint_automations:
    name: Enable Octoprint automations
    icon: mdi:printer-3d
