octopusagile:
  region_code: "A"
  mpan: !secret octopus_mpan
  serial: !secret octopus_serial
  auth: !secret octopus_key
  startdate: "2020-05-08"
  run_devices:
    - energy_time: 2
      entity_id: dishwasher
      run_before: "07:00:00"
      run_time: 2.5
    - energy_time: 2
      entity_id: washing_machine
      run_before: "07:00:00"
      run_time: 2
sensor:
  # Octopus Energy
  - platform: "octopusagile"
