# Created by Danny Tsang <danny@tsang.uk>
proximity:
  danny_dannys_parents:
    ignored_zones:
      - Home
      - Danny's Work
      - School
      - Terina's Parents
      - Terina's Work
    devices:
      - device_tracker.dannys_phone
      - device_tracker.oneplus8pro
    tolerance: 25
    unit_of_measurement: mi
  danny_home:
    ignored_zones:
      - Danny's Parents
      - Danny's Work
      - School
      - Terina's Parents
      - Terina's Work
    devices:
      - device_tracker.dannys_phone
      - device_tracker.oneplus8pro
    tolerance: 25
    unit_of_measurement: mi
  danny_school:
    ignored_zones:
      - Danny's Parents
      - Danny's Work
      - Home
      - Terina's Parents
      - Terina's Work
    devices:
      - device_tracker.dannys_phone
      - device_tracker.oneplus8pro
    tolerance: 25
    unit_of_measurement: mi
  terina_home:
    ignored_zones:
      - Danny's Parents
      - Danny's Work
      - School
      - Terina's Parents
      - Terina's Work
    devices:
      - device_tracker.oneplus6t
    tolerance: 25
    unit_of_measurement: mi
  terina_school:
    ignored_zones:
      - Danny's Parents
      - Danny's Work
      - Home
      - Terina's Parents
      - Terina's Work
    devices:
      - device_tracker.oneplus6t
    tolerance: 25
    unit_of_measurement: mi
  terina_terinas_parents:
    ignored_zones:
      - Danny's Parents
      - Danny's Work
      - Home
      - School
      - Terina's Work
    devices:
      - device_tracker.oneplus6t
    tolerance: 25
    unit_of_measurement: mi
  terina_work:
    ignored_zones:
      - Danny's Parents
      - Danny's Work
      - Home
      - School
      - Terina's Parents
    devices:
      - device_tracker.oneplus6t
    tolerance: 25
    unit_of_measurement: mi
automation:
  - id: "1588609147280"
    alias: "^People: Someone Arrives Home"
    description: ""
    trigger:
      - entity_id: group.all_people
        from: not_home
        platform: state
        to: home
    condition:
      - condition: state
        entity_id: alarm_control_panel.stevenage_alarm
        state: armed_away
    action:
      - data: {}
        entity_id: alarm_control_panel.stevenage_alarm
        service: script.1589652888991
  - id: "1613333442249"
    alias: "^People: No One Home And 3D Printing"
    description: ""
    trigger:
      - platform: state
        entity_id: group.adult_people
        to: not_home
        for: 00:01:00
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.octoprint_time_remaining
            state: unknown
    action:
      - service: script.post_to_direct_notification
        data:
          title: 3D Printing
          message: 3D printer is printing and no one is home.
    mode: single
input_boolean:
  enable_home_presence_detection:
    name: Enable home presence detection
    icon: mdi:home-account