# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1588609147280"
    alias: "^People: Someone Arrives Home"
    description: ""
    trigger:
      - entity_id: group.adult_people
        from: not_home
        platform: state
        to: home
    condition:
      - condition: state
        entity_id: alarm_control_panel.house_alarm
        state: armed_away
      - condition: state
        entity_id: input_boolean.enable_home_presence_detection
        state: "on"
    action:
      - parallel:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: alarm_control_panel.house_alarm
                    state: armed_away
                  - condition: state
                    entity_id: input_boolean.enable_morning_routine
                    state: "off"
                sequence:
                  - service: script.send_to_home_log
                    data:
                      message: ":house: :running: Someone arrived home."
                  - service: script.set_alarm_to_disarmed_mode
                  - service: script.conservatory_turn_off_camera
                  - service: script.lounge_turn_off_camera
                  - service: script.upstairs_turn_off_camera
              - conditions:
                  - condition: state
                    entity_id: input_boolean.enable_morning_routine
                    state: "on"
                sequence:
                  - service: script.send_to_home_log
                    data:
                      message: ":house: :running: Someone arrived home before :city_sunrise: sunrise."
                  - service: script.set_alarm_to_disarmed_mode
                  - service: script.send_to_home_log
                    data:
                      message: "Turning on downstairs :camera_with_flash: cameras."
                  - service: script.conservatory_turn_on_camera
                  - service: script.lounge_turn_on_camera
                  - service: script.front_garden_turn_on_camera
            default: []
          - choose:
              - conditions:
                  - condition: state
                    entity_id: climate.thermostat
                    state: "off"
                sequence:
                  - service: script.send_to_home_log
                    data:
                      message: Heating is off.
                  - service: script.set_central_heating_to_home_mode
            default: []
    mode: single
  - id: "1595524992208"
    alias: "^People: No One Home And Locked"
    description: ""
    trigger:
      - entity_id: group.adult_people
        for: 00:02:00
        platform: state
        to: not_home
    condition:
      - condition: state
        entity_id: input_boolean.enable_home_presence_detection
        state: "on"
      - condition: state
        entity_id: binary_sensor.alarmed_doors_and_windows
        state: "off"
      - not:
          - condition: state
            entity_id: device_tracker.udmpro
            state: unavailable
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: Guest
              - condition: state
                entity_id: input_boolean.enable_direct_notifications
                state: "on"
            sequence:
              - parallel:
                  - service: script.send_to_home_log
                    data:
                      message: ":warning: Guest mode is active and no one is home."
                  - service: notify.mobile_app_dannys_phone
                    data:
                      message: Guest mode is on. Do you want to turn on the alarm?
                      title: No One Home In Guest Mode
                      data:
                        actions:
                          - title: Alarm On & Turn Off Devices
                            action: guest_mode_arm_alarm_and_turn_off_devices
                          - title: Alarm On Only
                            action: guest_mode_arm_alarm_away
                          - title: Turn Off Devices Only
                            action: guest_mode_turn_off_devices
        default:
          - service: script.set_alarm_to_away_mode
          - choose:
              - conditions:
                  - condition: state
                    entity_id: binary_sensor.external_doors_and_windows
                    state: "on"
                sequence:
                  - service: script.send_direct_notification
                    data:
                      message:
                        ":information_source: :door: :window: :bell: Alarm was turned on.
                        The following entrances are still open:\n {% for entity in state_attr('binary_sensor.external_doors_and_windows','entity_id')
                        %}{% if states(entity) == 'on' %}{{ '* ' ~ state_attr(entity, 'friendly_name')
                        }} {% endif %}{% endfor %}\n"
            default:
              - choose:
                  - conditions:
                      - condition: state
                        entity_id: input_boolean.enable_direct_notifications
                        state: "on"
                    sequence:
                      - service: script.send_actionable_notification_with_3_buttons
                        data:
                          message: Turn on office fan?
                          title: ♨️🏢Office temperature is 29c+
                          people: person.danny
                          action1_title: "Disarm"
                          action1_name: disarm
                          action2_title: "Devices On"
                          action2_name: leave_on
                          action3_title: "Disarm & Leave On"
                          action3_name: disarm_leave_on
                      - service: notify.mobile_app_terina_s_phone
                        data:
                          title: No One Home
                          message: Alarm armed and turning off devices.
                          data:
                            actions:
                              - title: Disarm
                                action: disarm
                              - title: Leave On
                                action: leave_on
                              - title: Disarm & Leave On
                                action: disarm_leave_on
                      - wait_for_trigger:
                          - platform: event
                            event_type: mobile_app_notification_action
                        timeout: "300"
                        continue_on_timeout: true
                      - choose:
                          - conditions:
                              - condition: template
                                value_template: "{{ wait.trigger.event.data.action == 'disarm' }}"
                            sequence:
                              - service: script.set_alarm_to_disarmed_mode
                          - conditions:
                              - condition: template
                                value_template:
                                  "{{ wait.trigger.event.data.action == 'leave_on'
                                  }}"
                            sequence:
                              - service: script.send_to_home_log
                                data:
                                  message: Leaving devices on.
                          - conditions:
                              - condition: template
                                value_template:
                                  "{{ wait.trigger.event.data.action == 'disarm_leave_on'
                                  }}"
                            sequence:
                              - parallel:
                                  - service: script.set_alarm_to_disarmed_mode
                                  - service: script.send_to_home_log
                                    data:
                                      message: Skipping turning off devices.
                        default:
                          - service: script.everybody_leave_home
                default:
                  - service: script.everybody_leave_home
      - service: script.3d_printer_left_unattended
    mode: single
  - id: "1594554327310"
    alias: "^People: No One Home And House Is Not Locked"
    description: ""
    trigger:
      - entity_id: group.adult_people
        for: 00:02:00
        platform: state
        to: not_home
    condition:
      - not:
          - condition: state
            entity_id: device_tracker.udmpro
            state: unavailable
      - condition: state
        entity_id: binary_sensor.alarmed_doors_and_windows
        state: "on"
      - condition: state
        entity_id: input_boolean.enable_home_presence_detection
        state: "on"
    action:
      - parallel:
          - choose:
              - conditions:
                  - not:
                      - condition: state
                        entity_id: input_select.home_mode
                        state: Guest
                sequence:
                  - service: script.send_direct_notification
                    data:
                      message:
                        ":warning: :door: :window: The following entrances are still open:
                        {% for entity in state_attr('binary_sensor.alarmed_doors_and_windows','entity_id')
                        %}{% if states(entity) == 'on' %}{{ '\n* ' ~ state_attr(entity, 'friendly_name')
                        }} {% endif %}{% endfor %}"
                      title: No one is home and couldn't turn on the alarm
            default: []
          - choose:
              - conditions:
                  - not:
                      - condition: state
                        entity_id: input_select.home_mode
                        state: Guest
                sequence:
                  - service: script.send_to_home_log
                    data:
                      message:
                        ":warning: :door: :window: The following entrances are still open:
                        {% for entity in state_attr('binary_sensor.alarmed_doors_and_windows','entity_id')
                        %}{% if states(entity) == 'on' %}{{ '\n* ' ~ state_attr(entity, 'friendly_name')
                        }} {% endif %}{% endfor %}"
                      title: No one is home and couldn't turn on the alarm
            default: []
      - service: script.3d_printer_left_unattended
    mode: single
  # Danny
  - id: "1581867286886"
    alias: "^People: Danny Arrives Home"
    description: ""
    trigger:
      - entity_id: person.danny
        from: not_home
        platform: state
        to: home
    condition:
      - condition: state
        entity_id: input_boolean.enable_home_presence_detection
        state: "on"
    action:
      - service: scene.turn_on
        target:
          entity_id:
            - scene.lounge_lights
            - scene.kitchen_side_lights_on
      - data:
          message: ":house: :running: Arrived home."
          title: ":man: Danny"
        service: script.send_to_home_log
    mode: single
  - id: "1582456019025"
    alias: "^People: Danny Leaves Home"
    description: ""
    trigger:
      - entity_id: person.danny
        from: home
        platform: state
        to: not_home
    condition:
      - condition: state
        entity_id: person.terina
        state: not_home
    action:
      - service: scene.turn_on
        target:
          entity_id:
            - scene.turn_off_downstairs_lights
            - scene.office_all_lights_off
      - data:
          message:
            ":running: :house: Danny has left the house and no one is home. Turning
            off lights."
          title: ":man: Danny"
        service: script.send_to_home_log
      - service: script.car_update_location
  # Terina
  - id: "1582754128581"
    alias: "^People: Terina Arrives Home"
    description: ""
    trigger:
      - entity_id: person.terina
        from: not_home
        platform: state
        to: home
    condition:
      - condition: numeric_state
        entity_id: sensor.lounge_motion_2_light_level
        below: "55"
    action:
      - service: scene.turn_on
        target:
          entity_id:
            - scene.lounge_lights
            - scene.kitchen_side_lights_on
      - data:
          message: ":dancer: :house: :bulb: Arrived home."
          title: ":woman: Terina"
        service: script.send_to_home_log
  - id: "1582456025977"
    alias: "^People: Terina Leaves Home"
    description: ""
    trigger:
      - entity_id: person.terina
        from: home
        platform: state
        to: not_home
    condition:
      - condition: state
        entity_id: person.danny
        state: not_home
    action:
      - service: scene.turn_on
        target:
          entity_id:
            - scene.turn_off_downstairs_lights
            - scene.office_all_lights_off
      - data:
          message: ":house: :dancer: Left the house and no one is home."
          title: ":woman: Terina"
        service: script.send_to_home_log

proximity:
  danny_dannys_parents:
    ignored_zones:
      - Home
      - Danny's Work
      - School
      - Terina's Parents
      - Terina's Work
    devices:
      - device_tracker.dannys_phone
      - device_tracker.oneplus8pro
    tolerance: 25
    unit_of_measurement: mi
  danny_home:
    ignored_zones:
      - Danny's Parents
      - Danny's Work
      - School
      - Terina's Parents
      - Terina's Work
    devices:
      - device_tracker.dannys_phone
      - device_tracker.oneplus8pro
    tolerance: 25
    unit_of_measurement: mi
  danny_school:
    ignored_zones:
      - Danny's Parents
      - Danny's Work
      - Home
      - Terina's Parents
      - Terina's Work
    devices:
      - device_tracker.dannys_phone
      - device_tracker.oneplus8pro
    tolerance: 25
    unit_of_measurement: mi
  terina_home:
    ignored_zones:
      - Danny's Parents
      - Danny's Work
      - School
      - Terina's Parents
      - Terina's Work
    devices:
      - device_tracker.terinas_phone
      - device_tracker.oneplus_10_pro_5g
    tolerance: 25
    unit_of_measurement: mi
  terina_school:
    ignored_zones:
      - Danny's Parents
      - Danny's Work
      - Home
      - Terina's Parents
      - Terina's Work
    devices:
      - device_tracker.terinas_phone
      - device_tracker.oneplus_10_pro_5g
    tolerance: 25
    unit_of_measurement: mi
  terina_terinas_parents:
    ignored_zones:
      - Danny's Parents
      - Danny's Work
      - Home
      - School
      - Terina's Work
    devices:
      - device_tracker.terinas_phone
      - device_tracker.oneplus_10_pro_5g
    tolerance: 25
    unit_of_measurement: mi
  terina_work:
    ignored_zones:
      - Danny's Parents
      - Danny's Work
      - Home
      - School
      - Terina's Parents
    devices:
      - device_tracker.terinas_phone
      - device_tracker.oneplus_10_pro_5g
    tolerance: 25
    unit_of_measurement: mi

group:
  adult_people:
    name: Adults
    icon: mdi:account-multiple
    entities:
      - person.danny
      - person.terina
  all_people:
    name: Anyone Home
    icon: mdi:account-group
    entities:
      - person.danny
      - person.terina
      - person.leo
      - person.ashlee
  children_people:
    name: Children
    icon: mdi:account-multiple
    entities:
      - person.leo
      - person.ashlee

script:
  everybody_leave_home:
    alias: Everybody Leave Home
    sequence:
      - data:
          message:
            ":running: :house: :dancer: Everyone has left the house. Running the
            following:"
        service: script.send_to_home_log
      - service: script.turn_everything_off
    mode: single
