# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1588609147280"
    alias: "^People: Someone Arrives Home"
    description: ""
    trigger:
      - entity_id: group.adult_people
        from: not_home
        platform: state
        to: home
    condition:
      - condition: state
        entity_id: alarm_control_panel.house_alarm
        state: armed_away
      - condition: state
        entity_id: input_boolean.enable_home_presence_detection
        state: "on"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: alarm_control_panel.house_alarm
                state: armed_away
              - condition: state
                entity_id: input_boolean.enable_morning_routine
                state: "off"
            sequence:
              - service: script.send_to_home_log
                data:
                  message: ":house: :running: Someone arrived home."
              - service: script.set_alarm_to_disarmed_mode
              - service: script.conservatory_turn_off_camera
              - service: script.lounge_turn_off_camera
              - service: script.upstairs_turn_off_camera
          - conditions:
              - condition: state
                entity_id: input_boolean.enable_morning_routine
                state: "on"
            sequence:
              - service: script.send_to_home_log
                data:
                  message: ":house: :running: Someone arrived home before :city_sunrise: sunrise."
              - service: script.set_alarm_to_disarmed_mode
              - service: script.send_to_home_log
                data:
                  message: "Turning on downstairs :camera_with_flash: cameras."
              - service: script.conservatory_turn_on_camera
              - service: script.lounge_turn_on_camera
              - service: script.front_garden_turn_on_camera
        default: []
      - choose:
          - conditions:
              - condition: state
                entity_id: climate.thermostat
                state: "off"
            sequence:
              - service: script.send_to_home_log
                data:
                  message: Heating is off.
              - service: script.set_central_heating_to_home_mode
        default: []
    mode: single
  - id: "1613333442249"
    alias: "^People: No One Home And 3D Printing"
    description: ""
    trigger:
      - platform: state
        entity_id: group.adult_people
        to: not_home
        for: 00:01:00
    condition:
      - not:
          - condition: state
            entity_id: sensor.octoprint_estimated_finish_time
            state: unknown
      - condition: state
        entity_id: binary_sensor.octoprint_printing
        state: "on"
    action:
      - service: script.send_direct_notification
        data:
          title: 3D Printing
          message: ":printer: 3D printer is printing and no one is :house_with_garden: home."
    mode: single
  - id: "1595524992208"
    alias: "^People: No One Home And Locked"
    description: ""
    trigger:
      - entity_id: group.adult_people
        for: 00:02:00
        platform: state
        to: not_home
    condition:
      - condition: state
        entity_id: input_boolean.enable_home_presence_detection
        state: "on"
      - condition: state
        entity_id: group.alarmed_doors_and_windows
        state: "off"
      - not:
          - condition: state
            entity_id: device_tracker.udmpro
            state: unavailable
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_select.home_mode
                state: Guest
              - condition: state
                entity_id: input_boolean.enable_direct_notifications
                state: "on"
            sequence:
              - parallel:
                  - service: script.send_to_home_log
                    data:
                      message: ":warning: Guest mode is active and no one is home."
                  - service: notify.mobile_app_dannys_phone
                    data:
                      message: Guest mode is on. Do you want to turn on the alarm?
                      title: No One Home In Guest Mode
                      data:
                        actions:
                          - title: Alarm On & Turn Off Devices
                            action: guest_mode_arm_alarm_and_turn_off_devices
                          - title: Alarm On Only
                            action: guest_mode_arm_alarm_away
                          - title: Turn Off Devices Only
                            action: guest_mode_turn_off_devices
        default:
          - service: script.set_alarm_to_away_mode
          - choose:
              - conditions:
                  - condition: state
                    entity_id: group.external_doors_and_windows
                    state: "on"
                sequence:
                  - service: script.send_direct_notification
                    data:
                      message:
                        ":information_source: :door: :window: :bell: Alarm was turned on.
                        The following entrances are still open:\n {% for entity in state_attr('group.external_doors_and_windows','entity_id')
                        %}{% if states(entity) == 'on' %}{{ '* ' ~ state_attr(entity, 'friendly_name')
                        }} {% endif %}{% endfor %}\n"
            default:
              - choose:
                  - conditions:
                      - condition: state
                        entity_id: input_boolean.enable_direct_notifications
                        state: "on"
                    sequence:
                      - service: notify.mobile_app_dannys_phone
                        data:
                          message: Alarm armed and turning off devices.
                          title: No One Home
                          data:
                            actions:
                              - title: Disarm
                                action: disarm
                              - title: Devices On
                                action: leave_on
                              - title: Disarm & Leave On
                                action: disarm_leave_on
                      - service: notify.mobile_app_terina_s_phone
                        data:
                          title: No One Home
                          message: Alarm armed and turning off devices.
                          data:
                            actions:
                              - title: Disarm
                                action: disarm
                              - title: Leave On
                                action: leave_on
                              - title: Disarm & Leave On
                                action: disarm_leave_on
                      - wait_for_trigger:
                          - platform: event
                            event_type: mobile_app_notification_action
                        timeout: "300"
                        continue_on_timeout: true
                      - choose:
                          - conditions:
                              - condition: template
                                value_template: "{{ wait.trigger.event.data.action == 'disarm' }}"
                            sequence:
                              - service: script.set_alarm_to_disarmed_mode
                          - conditions:
                              - condition: template
                                value_template:
                                  "{{ wait.trigger.event.data.action == 'leave_on'
                                  }}"
                            sequence:
                              - service: script.send_to_home_log
                                data:
                                  message: Leaving devices on.
                          - conditions:
                              - condition: template
                                value_template:
                                  "{{ wait.trigger.event.data.action == 'disarm_leave_on'
                                  }}"
                            sequence:
                              - parallel:
                                  - service: script.set_alarm_to_disarmed_mode
                                  - service: script.send_to_home_log
                                    data:
                                      message: Skipping turning off devices.
                        default:
                          - service: script.everybody_leave_home
                default:
                  - service: script.everybody_leave_home
    mode: single
  - id: "1594554327310"
    alias: "^People: No One Home And House Is Not Locked"
    description: ""
    trigger:
      - entity_id: group.adult_people
        for: 00:02:00
        platform: state
        to: not_home
    condition:
      - not:
          - condition: state
            entity_id: device_tracker.udmpro
            state: unavailable
      - condition: state
        entity_id: group.alarmed_doors_and_windows
        state: "on"
      - condition: state
        entity_id: input_boolean.enable_home_presence_detection
        state: "on"
    action:
      - choose:
          - conditions:
              - not:
                  - condition: state
                    entity_id: input_select.home_mode
                    state: Guest
            sequence:
              - service: script.send_direct_notification
                data:
                  message:
                    ":warning: :door: :window: The following entrances are still open:
                    {% for entity in state_attr('group.alarmed_doors_and_windows','entity_id')
                    %}{% if states(entity) == 'on' %}{{ '\n* ' ~ state_attr(entity, 'friendly_name')
                    }} {% endif %}{% endfor %}"
                  title: No one is home and couldn't turn on the alarm
        default: []
      - choose:
          - conditions:
              - not:
                  - condition: state
                    entity_id: input_select.home_mode
                    state: Guest
            sequence:
              - service: script.send_to_home_log
                data:
                  message:
                    ":warning: :door: :window: The following entrances are still open:
                    {% for entity in state_attr('group.alarmed_doors_and_windows','entity_id')
                    %}{% if states(entity) == 'on' %}{{ '\n* ' ~ state_attr(entity, 'friendly_name')
                    }} {% endif %}{% endfor %}"
                  title: No one is home and couldn't turn on the alarm
        default: []
    mode: single
proximity:
  danny_dannys_parents:
    ignored_zones:
      - Home
      - Danny's Work
      - School
      - Terina's Parents
      - Terina's Work
    devices:
      - device_tracker.dannys_phone
      - device_tracker.oneplus8pro
    tolerance: 25
    unit_of_measurement: mi
  danny_home:
    ignored_zones:
      - Danny's Parents
      - Danny's Work
      - School
      - Terina's Parents
      - Terina's Work
    devices:
      - device_tracker.dannys_phone
      - device_tracker.oneplus8pro
    tolerance: 25
    unit_of_measurement: mi
  danny_school:
    ignored_zones:
      - Danny's Parents
      - Danny's Work
      - Home
      - Terina's Parents
      - Terina's Work
    devices:
      - device_tracker.dannys_phone
      - device_tracker.oneplus8pro
    tolerance: 25
    unit_of_measurement: mi
  terina_home:
    ignored_zones:
      - Danny's Parents
      - Danny's Work
      - School
      - Terina's Parents
      - Terina's Work
    devices:
      - device_tracker.oneplus_6t
      - device_tracker.oneplus_6t_2
    tolerance: 25
    unit_of_measurement: mi
  terina_school:
    ignored_zones:
      - Danny's Parents
      - Danny's Work
      - Home
      - Terina's Parents
      - Terina's Work
    devices:
      - device_tracker.oneplus_6t
      - device_tracker.oneplus_6t_2
    tolerance: 25
    unit_of_measurement: mi
  terina_terinas_parents:
    ignored_zones:
      - Danny's Parents
      - Danny's Work
      - Home
      - School
      - Terina's Work
    devices:
      - device_tracker.oneplus_6t
      - device_tracker.oneplus_6t_2
    tolerance: 25
    unit_of_measurement: mi
  terina_work:
    ignored_zones:
      - Danny's Parents
      - Danny's Work
      - Home
      - School
      - Terina's Parents
    devices:
      - device_tracker.oneplus_6t
      - device_tracker.oneplus_6t_2
    tolerance: 25
    unit_of_measurement: mi
input_boolean:
  enable_home_presence_detection:
    name: Enable home presence detection
    icon: mdi:home-account
group:
  adult_people:
    name: Adults
    icon: mdi:account-multiple
    entities:
      - person.danny
      - person.terina
  all_people:
    name: Anyone Home
    icon: mdi:account-group
    entities:
      - person.danny
      - person.terina
      - person.leo
      - person.ashlee
  children_people:
    name: Children
    icon: mdi:account-multiple
    entities:
      - person.leo
      - person.ashlee
script:
  everybody_leave_home:
    alias: Everybody Leave Home
    sequence:
      - data:
          message:
            ":running: :house: :dancer: Everyone has left the house. Running the
            following:"
        service: script.send_to_home_log
      - service: script.turn_everything_off
    mode: single
