# Created by Danny Tsang <danny@tsang.uk>
sensor:
  - platform: template
    sensors:
      # Pi Hole totals from different entities
      pi_hole_total_ads_blocked_today:
        value_template: "{{ states('sensor.pi_hole_ads_blocked_today') | int + states('sensor.pi_hole_2_ads_blocked_today') | int }}"
        friendly_name: "Pi-Hole Total Ads Blocked Today"
        unit_of_measurement: "ads"
      pi_hole_total_ads_percentage_blocked_today:
        value_template: "{{ states('sensor.pi_hole_ads_percentage_blocked_today') | int + states('sensor.pi_hole_2_ads_percentage_blocked_today') | int / 2 | float }}"
        friendly_name: "Pi-Hole Total Ads Percentage Blocked Today"
        unit_of_measurement: "%"
      pi_hole_total_dns_queries_cached:
        value_template: "{{ states('sensor.pi_hole_dns_queries_cached') | int + states('sensor.pi_hole_2_dns_queries_cached') | int }}"
        friendly_name: "Pi-Hole Total DNS Queries Cached"
        unit_of_measurement: "queries"
      pi_hole_total_dns_queries_forwarded:
        value_template: "{{ states('sensor.pi_hole_dns_queries_forwarded') | int + states('sensor.pi_hole_2_dns_queries_forwarded') | int }}"
        friendly_name: "Pi-Hole Total DNS Queries Forwarded"
        unit_of_measurement: "queries"
      pi_hole_total_dns_queries_today:
        value_template: "{{ states('sensor.pi_hole_dns_queries_today') | int + states('sensor.pi_hole_2_dns_queries_today') | int }}"
        friendly_name: "Pi-Hole Total DNS Queries Today"
        unit_of_measurement: "queries"
      pi_hole_total_dns_unique_clients:
        value_template: "{{ states('sensor.pi_hole_dns_unique_clients') | int + states('sensor.pi_hole_2_dns_unique_clients') | int }}"
        friendly_name: "Pi-Hole Total DNS Unique Clients"
        unit_of_measurement: "clients"
      pi_hole_total_dns_unique_domains:
        value_template: "{{ states('sensor.pi_hole_dns_unique_domains') | int + states('sensor.pi_hole_2_dns_unique_domains') | int }}"
        friendly_name: "Pi-Hole Total DNS Unique Domains"
        unit_of_measurement: "domains"
      pi_hole_total_domains_blocked:
        value_template: "{{ states('sensor.pi_hole_domains_blocked') | int + states('sensor.pi_hole_2_domains_blocked') | int }}"
        friendly_name: "Pi-Hole Total Domains Blocked"
        unit_of_measurement: "domains"
      pi_hole_total_seen_clients:
        value_template: "{{ states('sensor.pi_hole_seen_clients') | int + states('sensor.pi_hole_2_seen_clients') | int }}"
        friendly_name: "Pi-Hole Total Seen Clients"
        unit_of_measurement: "clients"
