# Created by Danny Tsang <danny@tsang.uk>
automation:
  # NowTV
  - id: "1612998070590"
    alias: "^Bedroom: NowTv Turned Off"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.nowtv_stick
        to: standby
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":tv: NowTv turned off."
    mode: queued
    max: 10
  - id: "1612997966835"
    alias: "^Bedroom: NowTv Playing"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.nowtv_stick
        to: playing
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":tv: NowTv is playing {{ state_attr('media_player.nowtv_stick',
            'app_name') }}"
    mode: queued
    max: 10
  - id: "1613051036668"
    alias: "^Bedroom: NowTv On Standby"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.nowtv_stick
        to: "on"
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":tv: NowTv turned on"
    mode: queued
    max: 10
  - id: "1613052205966"
    alias: "^Bedroom: NowTv Paused"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.nowtv_stick
        to: paused
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":tv: NowTv paused."
    mode: queued
    max: 10
  # Roku
  - id: "1612998168526"
    alias: "^Lounge: Roku Stick Playing"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.roku_streaming_stick
        to: playing
    condition: []
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: >-
                  {{ state_attr('media_player.roku_streaming_stick','media_position') !=
                  none and
                  state_attr('media_player.roku_streaming_stick','media_duration') !=
                  none}}
            sequence:
              - service: camera.snapshot
                target:
                  entity_id: camera.lounge_tv
                data:
                  filename: "{{ states('input_text.latest_hyperion_lounge_tv_file_path') }}"
              - delay:
                  seconds: 2
              - service: script.post_to_home_log_with_local_attachments
                data:
                  title: "Roku started playing"
                  message:
                    ":tv: Roku playing {{ state_attr('media_player.roku_streaming_stick',
                    'app_name') }} and is at {{ state_attr('media_player.roku_streaming_stick','media_position') |
                    int | timestamp_custom('%H:%M:%S') }}/{{ state_attr('media_player.roku_streaming_stick','media_duration') |
                    int | timestamp_custom('%H:%M:%S') }} ({{ ((state_attr('media_player.roku_streaming_stick',
                    'media_position') | int / state_attr('media_player.roku_streaming_stick',
                    'media_duration') | int) * 100) | round(2, 'common') }}%) way through."
                  filePath: "{{ states('input_text.latest_hyperion_lounge_tv_file_path') }}"
        default:
          - service: camera.snapshot
            target:
              entity_id: camera.lounge_tv
            data:
              filename: "{{ states('input_text.latest_hyperion_lounge_tv_file_path') }}"
          - delay:
              seconds: 2
          - service: script.post_to_home_log_with_local_attachments
            data:
              title: "Roku started playing"
              message:
                ":tv: Roku playing {{ state_attr('media_player.roku_streaming_stick',
                'app_name') }}"
              filePath: "{{ states('input_text.latest_hyperion_lounge_tv_file_path') }}"
    mode: queued
    max: 10
  - id: "1612998400190"
    alias: "^Lounge: Roku Stick Turned Off"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.roku_streaming_stick
        to: idle
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":tv: Roku turned off."
    mode: queued
    max: 10
  - id: "1617813522257"
    alias: "^Lounge: Roku Paused"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.roku_streaming_stick
        to: paused
    condition: []
    action:
      - service: camera.snapshot
        target:
          entity_id: camera.lounge_tv
        data:
          filename: "{{ states('input_text.latest_hyperion_lounge_tv_file_path') }}"
      - delay:
          seconds: 2
      - service: script.post_to_home_log_with_local_attachments
        data:
          title: "Roku paused"
          message: ":tv: Roku paused."
          filePath: "{{ states('input_text.latest_hyperion_lounge_tv_file_path') }}"
    mode: queued
    max: 10
  - id: "1613051229066"
    alias: "^Lounge: Roku Turned On"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.roku_streaming_stick
        to: "on"
    condition: []
    action:
      - service: camera.snapshot
        target:
          entity_id: camera.lounge_tv
        data:
          filename: "{{ states('input_text.latest_hyperion_lounge_tv_file_path') }}"
      - delay:
          seconds: 2
      - service: script.post_to_home_log_with_local_attachments
        data:
          title: "Roku turned on"
          message: ":tv: Roku turned on."
          filePath: "{{ states('input_text.latest_hyperion_lounge_tv_file_path') }}"
    mode: queued
    max: 10
  # Office Chromecast
  - id: "1617795487661"
    alias: "^Office: Chromecast Start Playing"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.office_chromecast
        attribute: media_title
        to: playing
    condition: []
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ state_attr('media_player.office_chromecast', 'media_title') != none }}"
              - condition: template
                value_template: "{{ state_attr('media_player.office_chromecast', 'app_name') != none }}"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":tv: Chromecast office is playing {{ state_attr('media_player.office_chromecast',
                    'media_title') }} on {{ state_attr('media_player.office_chromecast',
                    'app_name') }}."
          - conditions:
              - condition: template
                value_template: "{{ state_attr('media_player.office_chromecast', 'app_name') != none }}"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":tv: Chromecast office is playing {{ state_attr('media_player.office_chromecast',
                    'app_name') }}."
        default:
          - service: script.post_to_home_log
            data:
              message: ":tv: Chromecast office is playing."
    mode: queued
    max: 10
  - id: "1617795505115"
    alias: "^Office: Chromecast Start Paused"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.office_chromecast
        to: paused
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":tv: Chromecast office paused"
    mode: queued
    max: 10
  - id: "1617795302933"
    alias: "^Office: Chromecast Turned On"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.office_chromecast
        to: "on"
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":tv: Chromecast office turned on."
    mode: queued
    max: 10
  - id: "1617795318685"
    alias: "^Office: Chromecast Turned Off"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.office_chromecast
        to: "off"
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":tv: Chromecast office turned off."
    mode: queued
    max: 10
  - id: "1617796469498"
    alias: "^Office: Chromecast Media Changes"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.office_chromecast
        attribute: media_title
    condition: []
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ state_attr('media_player.office_chromecast', 'media_title') != none }}"
              - condition: template
                value_template: "{{ state_attr('media_player.office_chromecast', 'app_name') != none }}"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":tv: Chromecast office is playing {{ state_attr('media_player.office_chromecast',
                    'media_title') }} on {{ state_attr('media_player.office_chromecast',
                    'app_name') }}."
          - conditions:
              - condition: template
                value_template: "{{ state_attr('media_player.office_chromecast', 'app_name') != none }}"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":tv: Chromecast office is playing {{ state_attr('media_player.office_chromecast',
                    'app_name') }}."
        default:
          - service: script.post_to_home_log
            data:
              message: ":tv: Chromecast office is playing."
    mode: queued
    max: 10
  # Office TV
  - id: "1617814309728"
    alias: "^Office: TV On"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.office_tv
        from: "off"
        to: "on"
    condition: []
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ state_attr('media_player.office_tv', 'source') != none }}"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":tv: Office TV turned on and playing {{ state_attr('media_player.office_tv',
                    'source') }}."
        default:
          - service: script.post_to_home_log
            data:
              message: ":tv: Office TV turned on."
    mode: queued
    max: 10
  - id: "1617814349289"
    alias: "^Office: TV Off"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.office_tv
        from: "on"
        to: "off"
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":tv: Office TV turned off."
    mode: queued
    max: 10
  - id: "1617814753264"
    alias: "^Office: TV Source Changes"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.office_tv
        attribute: source
    condition: []
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ state_attr('media_player.office_tv', 'source') != none }}"
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":tv: Office TV turned on and playing {{ state_attr('media_player.office_tv',
                    'source') }}."
        default:
          - service: script.post_to_home_log
            data:
              message: ":tv: Office TV media changed."
    mode: queued
    max: 10
