# Created by Danny Tsang <danny@tsang.uk>
automation:
  # Roku: Bedroom
  - id: "1612998168527"
    alias: "^Bedroom: Roku Stick Playing"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.bedroom_roku_streaming_stick
        to: playing
    condition: []
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: >-
                  {{ state_attr('media_player.bedroom_roku_streaming_stick','media_position') !=
                  none and
                  state_attr('media_player.bedroom_roku_streaming_stick','media_duration') !=
                  none}}
            sequence:
              - service: script.post_to_home_log
                data:
                  message:
                    ":tv: Roku playing {{ state_attr('media_player.bedroom_roku_streaming_stick',
                    'app_name') }} and is at {{ state_attr('media_player.bedroom_roku_streaming_stick','media_position') |
                    int | timestamp_custom('%H:%M:%S') }}/{{ state_attr('media_player.bedroom_roku_streaming_stick','media_duration') |
                    int | timestamp_custom('%H:%M:%S') }} ({{ ((state_attr('media_player.bedroom_roku_streaming_stick',
                    'media_position') | int / state_attr('media_player.bedroom_roku_streaming_stick',
                    'media_duration') | int) * 100) | round(2, 'common') }}%) way through."
        default:
          - service: script.post_to_home_log
            data:
              message:
                ":tv: Roku playing {{ state_attr('media_player.bedroom_roku_streaming_stick',
                'app_name') }}"
    mode: queued
    max: 10
  - id: "1612998400191"
    alias: "^Bedroom: Roku Stick Turned Off"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.bedroom_roku_streaming_stick
        to: idle
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":tv: Roku turned off."
    mode: queued
    max: 10
  - id: "1617813522258"
    alias: "^Bedroom: Roku Paused"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.bedroom_roku_streaming_stick
        to: paused
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":tv: Bedroom Roku paused."
    mode: queued
    max: 10
  - id: "1613051229067"
    alias: "^Bedroom: Roku Turned On"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.bedroom_roku_streaming_stick
        to: "on"
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":tv: Bedroom Roku turned on."
    mode: queued
    max: 10
  # Roku: Lounge
  - id: "1612998168526"
    alias: "^Lounge: Roku Stick Playing"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.lounge_roku_streaming_stick
        to: playing
    condition: []
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: >-
                  {{ state_attr('media_player.lounge_roku_streaming_stick','media_position') !=
                  none and
                  state_attr('media_player.lounge_roku_streaming_stick','media_duration') !=
                  none}}
            sequence:
              - service: camera.snapshot
                target:
                  entity_id: camera.lounge_tv
                data:
                  filename: "{{ states('input_text.latest_hyperion_lounge_tv_file_path') }}"
              - delay:
                  seconds: 2
              - service: script.post_to_home_log_with_local_attachments
                data:
                  title: "Lounge Roku started playing"
                  message:
                    ":tv: Lounge Roku playing {{ state_attr('media_player.lounge_roku_streaming_stick',
                    'app_name') }} and is at {{ state_attr('media_player.lounge_roku_streaming_stick','media_position') |
                    int | timestamp_custom('%H:%M:%S') }}/{{ state_attr('media_player.lounge_roku_streaming_stick','media_duration') |
                    int | timestamp_custom('%H:%M:%S') }} ({{ ((state_attr('media_player.lounge_roku_streaming_stick',
                    'media_position') | int / state_attr('media_player.lounge_roku_streaming_stick',
                    'media_duration') | int) * 100) | round(2, 'common') }}%) way through."
                  filePath: "{{ states('input_text.latest_hyperion_lounge_tv_file_path') }}"
        default:
          - service: camera.snapshot
            target:
              entity_id: camera.lounge_tv
            data:
              filename: "{{ states('input_text.latest_hyperion_lounge_tv_file_path') }}"
          - delay:
              seconds: 2
          - service: script.post_to_home_log_with_local_attachments
            data:
              title: "Lounge Roku started playing"
              message:
                ":tv: Lounge Roku playing {{ state_attr('media_player.lounge_roku_streaming_stick',
                'app_name') }}"
              filePath: "{{ states('input_text.latest_hyperion_lounge_tv_file_path') }}"
    mode: queued
    max: 10
  - id: "1612998400190"
    alias: "^Lounge: Roku Stick Turned Off"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.lounge_roku_streaming_stick
        to: idle
    condition: []
    action:
      - service: script.post_to_home_log
        data:
          message: ":tv: Lounge Roku turned off."
    mode: queued
    max: 10
  - id: "1617813522257"
    alias: "^Lounge: Roku Paused"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.lounge_roku_streaming_stick
        to: paused
    condition: []
    action:
      - service: camera.snapshot
        target:
          entity_id: camera.lounge_tv
        data:
          filename: "{{ states('input_text.latest_hyperion_lounge_tv_file_path') }}"
      - delay:
          seconds: 2
      - service: script.post_to_home_log_with_local_attachments
        data:
          title: "Roku paused"
          message: ":tv: Lounge Roku paused."
          filePath: "{{ states('input_text.latest_hyperion_lounge_tv_file_path') }}"
    mode: queued
    max: 10
  - id: "1613051229066"
    alias: "^Lounge: Roku Turned On"
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.lounge_roku_streaming_stick
        to: "on"
    condition: []
    action:
      - service: camera.snapshot
        target:
          entity_id: camera.lounge_tv
        data:
          filename: "{{ states('input_text.latest_hyperion_lounge_tv_file_path') }}"
      - delay:
          seconds: 2
      - service: script.post_to_home_log_with_local_attachments
        data:
          title: "Lounge Roku turned on"
          message: ":tv: Lounge Roku turned on."
          filePath: "{{ states('input_text.latest_hyperion_lounge_tv_file_path') }}"
    mode: queued
    max: 10
