# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1622667704047"
    alias: "Time: Warn Doors or Windows Still Open At Night"
    description: ""
    triggers:
      - trigger: time
        at: "22:00:00"
    conditions:
      - condition: state
        entity_id: binary_sensor.alarmed_doors_and_windows
        state: "on"
    actions:
      - action: script.send_to_home_log
        data:
          message:
            "⚠️ :clock{{ now().strftime('%I') | int }}{% if now().minute | int > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: 🚪 🪟
            The following entrances are still open:
            {% for entity in state_attr('binary_sensor.alarmed_doors_and_windows','entity_id')
            %}{% if states(entity) == 'on' %}{{ '\n* ' ~ state_attr(entity, 'friendly_name')
            }} {% endif %}{% endfor %}"
          log_level: "Debug"
    mode: single
  - id: "1619466600288"
    alias: "Time: Delete Old Camera Files"
    description: ""
    triggers:
      - trigger: time_pattern
        hours: "/2"
    conditions: []
    actions:
      parallel:
        - action: script.send_to_home_log
          data:
            message:
              ":clock{{ now().strftime('%I') | int }}{% if now().minute | int > 25 and now().minute | int < 35 %}30{% else %}{% endif %}:
              Deleting 📸 files"
            log_level: "Debug"
        - action: delete.files_in_folder
          data:
            folder: /config/camera/
            scan_subfolders: true
            remove_subfolders: false
            time: 14400
            except_files:
              - .gitignore
              - deepstack_object_conservatory_latest.png
              - deepstack_object_conservatory_none.png
              - deepstack_object_driveway_latest.png
              - deepstack_object_driveway_none.png
              - deepstack_object_front_door_latest.png
              - deepstack_object_front_door_None.png
              - deepstack_object_kitchen_latest.png
              - deepstack_object_kitchen_none.png
              - deepstack_object_lounge_latest.png
              - deepstack_object_lounge_none.png
              - deepstack_object_upstairs_latest.png
              - deepstack_object_upstairs_none.png
              - README.md
    mode: single
  - id: "1588859384208"
    alias: "Time: Reset Morning Run"
    description: ""
    triggers:
      - trigger: time
        at: "04:59:00"
    conditions: []
    actions:
      - parallel:
          - action: input_boolean.turn_on
            entity_id: input_boolean.enable_morning_routine
            data: {}
          - action: script.send_to_home_log
            data:
              message: ":clock{{ now().strftime('%I') | int }}{% if now().minute | int > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :sunny: Reset morning routine run flag"
              log_level: "Debug"
    mode: single
  - id: "1582406380123"
    alias: "Timed: Turn Off Downstairs Lights at 2am"
    description: "Fall back to turn off all lights should there be any connectivity issues etc."
    triggers:
      - trigger: time
        at: "02:00:00"
        id: 2am
      - trigger: time
        at: "03:00:00"
      - trigger: time
        at: "04:00:00"
    conditions:
      - not:
          - condition: time
            weekday:
              - sun
          - condition: trigger
            id:
              - 2am
    actions:
      - parallel:
          - action: script.send_to_home_log
            data:
              message:
                ":clock{{ now().strftime('%I') | int }}{% if now().minute | int >
                25 and now().minute | int < 35 %}30{% else %}{% endif %}: Turning downstairs
                light off."
              log_level: "Debug"
          - action: scene.turn_on
            target:
              entity_id: scene.turn_off_downstairs_lights
    mode: single
  - id: "1745396436913"
    alias: "Time: Announce Bed Time"
    description: ""
    triggers:
      - trigger: time
        at:
          entity_id: input_datetime.childrens_bed_time
          offset: "-1:15:00"
        id: 1h
      - trigger: time
        at:
          entity_id: input_datetime.childrens_bed_time
          offset: "-0:15:00"
        id: 0h
    conditions:
      - condition: or
        conditions:
          - condition: state
            entity_id: person.leo
            state: home
          - condition: state
            entity_id: person.ashlee
            state: home
      - condition: not
        conditions:
          - condition: state
            entity_id: input_select.home_mode
            state: No Children
      - condition: time
        weekday:
          - thu
          - wed
          - tue
          - mon
          - sun
    actions:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - 1h
            sequence:
              - parallel:
                  - action: script.send_to_home_log
                    metadata: {}
                    data:
                      log_level: Debug
                      message: Sending bed time notification
                  - action: script.alexa_announce
                    metadata: {}
                    data:
                      method: speak
                      message: It's one hour before bedtime.
          - conditions:
              - condition: trigger
                id:
                  - 0h
            sequence:
              - parallel:
                  - action: script.send_to_home_log
                    metadata: {}
                    data:
                      log_level: Debug
                      message: Sending bed time notification
                  - action: script.alexa_announce
                    metadata: {}
                    data:
                      method: speak
                      message: It's bed time. Don't forget your reading book.
    mode: single

script:
  morning_script:
    alias: Morning Script
    sequence:
      - action: input_boolean.turn_off
        entity_id: input_boolean.enable_morning_routine
        data: {}
      - parallel:
          - action: script.send_to_home_log
            data:
              message: "🐾 🌅 Motion detected in the Lounge in the morning.
                Running morning routine."
              log_level: "Normal"
          - action: script.set_alarm_to_disarmed_mode
          - action: script.send_to_home_log
            data:
              message: ":clock9: 🌅 Morning routine complete."
              log_level: "Normal"
          - action: script.announce_delayed_notifications
    mode: single
