# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1622667704047"
    alias: "Time: Warn Doors or Windows Still Open At Night"
    description: ""
    trigger:
      - platform: time
        at: "22:00:00"
    condition:
      - condition: state
        entity_id: binary_sensor.alarmed_doors_and_windows
        state: "on"
    action:
      - service: script.send_to_home_log
        data:
          message:
            ":warning: :clock{{ now().strftime('%I') | int }}{% if now().minute | int > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :door: :window:
            The following entrances are still open:
            {% for entity in state_attr('binary_sensor.alarmed_doors_and_windows','entity_id')
            %}{% if states(entity) == 'on' %}{{ '\n* ' ~ state_attr(entity, 'friendly_name')
            }} {% endif %}{% endfor %}"
          log_level: "Debug"
    mode: single
  - id: "1622933176882"
    alias: "Time: Alert Doors or Windows Still Open At Night"
    description: ""
    trigger:
      - platform: state
        entity_id: schedule.alarm_scheduled_home_mode
        to: "on"
      - platform: time
        at: "23:00:00"
    condition:
      - condition: state
        entity_id: binary_sensor.alarmed_doors_and_windows
        state: "on"
    action:
      - service: script.send_direct_notification
        data:
          message:
            ":warning: :clock{{ now().strftime('%I') | int }}{% if now().minute | int > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :door: :window: The following entrances are still open:
            {% for entity in state_attr('binary_sensor.alarmed_doors_and_windows','entity_id')
            %}{% if states(entity) == 'on' %}{{ '\n* ' ~ state_attr(entity, 'friendly_name')
            }} {% endif %}{% endfor %}"
          title: ":bell: Alarm"
          people:
            entity_id:
              - person.danny
              - person.terina
    mode: single
  - id: "1619466600288"
    alias: "Time: Delete Old Camera Files"
    description: ""
    trigger:
      - platform: time_pattern
        hours: "/2"
    condition: []
    action:
      parallel:
        - service: script.send_to_home_log
          data:
            message:
              ":clock{{ now().strftime('%I') | int }}{% if now().minute | int > 25 and now().minute | int < 35 %}30{% else %}{% endif %}:
              Deleting :camera: files"
            log_level: "Debug"
        - service: delete.files_in_folder
          data:
            folder: /config/camera/
            scan_subfolders: true
            remove_subfolders: false
            time: 14400
            except_files:
              - .gitignore
              - deepstack_object_conservatory_latest.png
              - deepstack_object_conservatory_none.png
              - deepstack_object_driveway_latest.png
              - deepstack_object_driveway_none.png
              - deepstack_object_front_door_latest.png
              - deepstack_object_front_door_None.png
              - deepstack_object_kitchen_latest.png
              - deepstack_object_kitchen_none.png
              - deepstack_object_lounge_latest.png
              - deepstack_object_lounge_none.png
              - deepstack_object_upstairs_latest.png
              - deepstack_object_upstairs_none.png
              - README.md
    mode: single
  - id: "1588859384208"
    alias: "Time: Reset Morning Run"
    description: ""
    trigger:
      - at: "04:59:00"
        platform: time
    condition: []
    action:
      - parallel:
          - data: {}
            entity_id: input_boolean.enable_morning_routine
            service: input_boolean.turn_on
          - service: script.send_to_home_log
            data:
              message: ":clock{{ now().strftime('%I') | int }}{% if now().minute | int > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :sunny: Reset morning routine run flag"
              log_level: "Debug"
    mode: single
  - id: "1582406380123"
    alias: "Timed: Turn Off Downstairs Lights at 2am"
    description: "Fall back to turn off all lights should there be any connectivity issues etc."
    trigger:
      - at: "02:00:00"
        platform: time
      - at: "03:00:00"
        platform: time
      - at: "04:00:00"
        platform: time
    condition: []
    action:
      - parallel:
          - service: script.send_to_home_log
            data:
              message:
                ":clock{{ now().strftime('%I') | int }}{% if now().minute | int >
                25 and now().minute | int < 35 %}30{% else %}{% endif %}: Turning downstairs
                light off."
              log_level: "Debug"
          - service: scene.turn_on
            target:
              entity_id: scene.turn_off_downstairs_lights
    mode: single

script:
  morning_script:
    alias: Morning Script
    sequence:
      - data: {}
        entity_id: input_boolean.enable_morning_routine
        service: input_boolean.turn_off
      - service: script.send_to_home_log
        data:
          message:
            ":paw_prints: :sunrise: Motion detected in the Lounge in the morning.
            Running morning routine."
          log_level: "Normal"
      - service: script.set_alarm_to_disarmed_mode
      - service: script.send_to_home_log
        data:
          message: ":no_bell: Turning alarm off."
          log_level: "Normal"
      - service: switch.turn_off
        target:
          entity_id: switch.indoor_cameras
      - service: script.send_to_home_log
        data:
          message: ":clock9: :sunrise: Morning routine complete."
          log_level: "Normal"
    mode: single
