# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1622667704047"
    alias: "^Time: Warn Doors or Windows Still Open At Night"
    description: ""
    trigger:
      - platform: time
        at: "22:00:00"
    condition:
      - condition: state
        entity_id: group.alarmed_doors_and_windows
        state: "on"
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":warning: :clock{{ now().strftime('%I') | int }}{% if now().minute | int > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :door: :window: The following entrances are still open:
            {% for entity in state_attr('group.alarmed_doors_and_windows','entity_id')
            %}{% if states(entity) == 'on' %}{{ '\n* ' ~ state_attr(entity, 'friendly_name')
            }} {% endif %}{% endfor %}"
    mode: single
  - id: "1622933176882"
    alias: "^Time: Alert Doors or Windows Still Open At Night"
    description: ""
    trigger:
      - platform: time
        at: "00:00:00"
      - platform: time
        at: "23:00:00"
      - platform: time
        at: 00:00:00
    condition:
      - condition: state
        entity_id: group.alarmed_doors_and_windows
        state: "on"
    action:
      - service: script.post_to_direct_notification
        data:
          message:
            ":warning: :clock{{ now().strftime('%I') | int }}{% if now().minute | int > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :door: :window: The following entrances are still open:
            {% for entity in state_attr('group.alarmed_doors_and_windows','entity_id')
            %}{% if states(entity) == 'on' %}{{ '\n* ' ~ state_attr(entity, 'friendly_name')
            }} {% endif %}{% endfor %}"
      - service: script.post_to_home_log
        data:
          message:
            ":warning: :clock{{ now().strftime('%I') | int }}{% if now().minute | int > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :door: :window: The following entrances are still open:
            {% for entity in state_attr('group.alarmed_doors_and_windows','entity_id')
            %}{% if states(entity) == 'on' %}{{ '\n* ' ~ state_attr(entity, 'friendly_name')
            }} {% endif %}{% endfor %}"
    mode: single
  - id: "1619466600288"
    alias: "^Time: Delete Old Camera Files"
    description: ""
    trigger:
      - platform: time
        at: 03:00:00
    condition: []
    action:
      - service: delete.files_in_folder
        data:
          folder: /config/camera/
          scan_subfolders: true
          remove_subfolders: false
          time: 172800
          except_files:
            - .gitignore
            - deepstack_object_conservatory_latest.png
            - deepstack_object_conservatory_none.png
            - deepstack_object_front_door_latest.png
            - deepstack_object_front_door_None.png
            - deepstack_object_lounge_latest.png
            - deepstack_object_lounge_none.png
            - deepstack_object_upstairs_latest.png
            - deepstack_object_upstairs_none.png
    mode: single
  - id: "1588859384208"
    alias: "^Time: Reset Morning Run"
    description: ""
    trigger:
      - at: 04:59:00
        platform: time
    condition: []
    action:
      - data: {}
        entity_id: input_boolean.enable_morning_routine
        service: input_boolean.turn_on
      - data:
          message: ":clock{{ now().strftime('%I') | int }}{% if now().minute | int > 25 and now().minute | int < 35 %}30{% else %}{% endif %}: :sunny: Reset morning routine run flag"
        service: script.post_to_home_log
    mode: single
