# Created by Danny Tsang <danny@tsang.uk>
automation:
  - id: "1622667704047"
    alias: "^Time: Warn Doors or Windows Still Open At Night"
    description: ""
    trigger:
      - platform: time
        at: "22:00:00"
    condition:
      - condition: state
        entity_id: group.alarmed_doors_and_windows
        state: "on"
    action:
      - service: script.post_to_home_log
        data:
          message:
            ":warning: :door: :window: The following entrances are still open:
            {% for entity in state_attr('group.alarmed_doors_and_windows','entity_id')
            %}{% if states(entity) == 'on' %}{{ '\n* ' ~ state_attr(entity, 'friendly_name')
            }} {% endif %}{% endfor %}"
    mode: single
  - id: "1622933176882"
    alias: "^Time: Alert Doors or Windows Still Open At Night"
    description: ""
    trigger:
      - platform: time
        at: "00:00:00"
      - platform: time
        at: "23:00:00"
      - platform: time
        at: 00:00:00
    condition:
      - condition: state
        entity_id: group.alarmed_doors_and_windows
        state: "on"
    action:
      - service: script.post_to_direct_notification
        data:
          message:
            ":warning: :door: :window: The following entrances are still open:
            {% for entity in state_attr('group.alarmed_doors_and_windows','entity_id')
            %}{% if states(entity) == 'on' %}{{ '\n* ' ~ state_attr(entity, 'friendly_name')
            }} {% endif %}{% endfor %}"
      - service: script.post_to_home_log
        data:
          message:
            ":warning: :door: :window: The following entrances are still open:
            {% for entity in state_attr('group.alarmed_doors_and_windows','entity_id')
            %}{% if states(entity) == 'on' %}{{ '\n* ' ~ state_attr(entity, 'friendly_name')
            }} {% endif %}{% endfor %}"
    mode: single
