call:
  name: Call Service
  description: Retry a service call on failure.
  fields:
    service:
      name: Retrying Service
      description: The service to retry on failure.
      example: homeassistant.turn_on
      required: true
      selector:
        text:
    retries:
      name: Retries
      description: Max amount of calls (defualt is 7).
      advanced: true
      example: 5
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: retries
          mode: box
    expected_state:
      name: Expected State
      description: The expected state of the entities after the service call.
      advanced: true
      example: "on"
      selector:
        text:
    individually:
      name: Individually
      description: Make a separate call per entity.
      default: true
      advanced: true
      example: false
      selector:
        boolean:
